### ISSUE TITLE
incorrect keywords 1.2.1

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#100]
Please use correct help keywords see screens
![keyword1](https://cloud.githubusercontent.com/assets/2631910/6389908/9765cf14-bdda-11e4-8e1e-87becf33acba.png)
![keyword2](https://cloud.githubusercontent.com/assets/2631910/6389909/9766412e-bdda-11e4-8b38-474fe33e5b97.png)
![keyword3](https://cloud.githubusercontent.com/assets/2631910/6389911/97a07e98-bdda-11e4-92ca-14638f31a6ec.png)
![keyword4](https://cloud.githubusercontent.com/assets/2631910/6389910/979bef9a-bdda-11e4-853d-37f3f077b7ac.png)

**Comment by abolabo** [comment]
fixed
