### ISSUE TITLE
Admin section loads http template

### ISSUE THREAD

**Issue by Loggan08** [abantecart/abantecart-src#1002]
I get a ton of these in developers chrome-console:

![abante bug](https://user-images.githubusercontent.com/7104301/30610321-1a5414fa-9d7e-11e7-9010-4a4ef7fc480b.png)

> this request has been blocked; the content must be served over HTTPS.

**Comment by abantecart** [comment]
How is this a bug? Please provide details to confirm the bug.

**Comment by Loggan08** [comment]
I get alot of mixed content errors, (Should be served over https)

I did install it for https.

![abante bug](https://user-images.githubusercontent.com/7104301/30632069-125d505e-9de7-11e7-8092-3005c5a3271f.png)

**Comment by abolabo** [comment]
Please try to re-save store urls on admin->settings->store details page and let us know

**Comment by Loggan08** [comment]
Looks like this and saved it, no luck.

![untitled](https://user-images.githubusercontent.com/7104301/30639219-48b7828e-9dfe-11e7-9163-7bd2ea3876f9.png)

**Comment by abolabo** [comment]
what about cache? You can delete all subdirectories of folder /shop/system/cache manually, via cpanel filemanager or ftp. 
Also check table "settings" via phpMyAdmin. You should to check setting key config_ssl. In your case it must be have value "2"

**Comment by Loggan08** [comment]
I still get these, deleted cache folder.

Storefront is displaying normal (No errors like these below)

![untitled](https://user-images.githubusercontent.com/7104301/30639592-d102e9b6-9dff-11e7-87fd-7ee010d96094.png)

**Comment by abolabo** [comment]
hmmm.. try one more thing..
You should to delete session cookies.
Go to Application tab of Chrome devtools and find cookies for your domain.
It have name like this AC_CP_******. Delete it and try to login

**Comment by Loggan08** [comment]
After doing that I could load "insecure scripts" , that makes the admin panel load normal, however I still think this should be fixed. :)

**Comment by abolabo** [comment]
glad to hear) 
p.s. please delete your screenshots with url to your secret admin side ;-)
