### ISSUE TITLE
category search improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1003]
1. issue if search with 2 keywords. For example if you search for category "_Soft Baits_" nothing found, but with just _Soft_ it finds Soft Baits category.

2. Need to make input wider

![screen shot 2017-09-28 at 10 35 33 pm](https://user-images.githubusercontent.com/2631910/31002060-7461f7c8-a512-11e7-8762-66d87cda879e.png)
![screen shot 2017-09-28 at 10 35 41 pm](https://user-images.githubusercontent.com/2631910/31002059-74611c7c-a512-11e7-9a44-8cb1434d566f.png)

**Comment by abolabo** [comment]
Need more details. Tried to search "Fragrance Sets" in demo data. Looks works correctly.
