### ISSUE TITLE
Site balance bug, being added twice randomly

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1009]
when im trying to give a customer sitebalance it adds the amount twice completely random, mostly 1 out of 30 or something, sometimes more sometimes less. tried to find out the reason but the error log show nothing, seems like something being called twice.

**Comment by abantecart** [comment]
What is site balance? Please provide more details to the problem. Use screenshots or examples to demonstrate the problem.

**Comment by kolynet** [comment]
sorry, i meant customer transaction!

**Comment by kolynet** [comment]
<img width="1301" alt="x" src="https://user-images.githubusercontent.com/22685076/31630527-1ec65d92-b2b7-11e7-8da2-c6e0dddf683c.png">
I also received 2 of the green success popup on the left! Now i had it after 4th transaction add.

**Comment by abantecart** [comment]
Thank you for details. Marked for dev to check this issue

**Comment by BasaraABC** [comment]
What is your browser?

**Comment by kolynet** [comment]
chrome. if needed i can try reproducing it on a completely clean new abc installation

**Comment by BasaraABC** [comment]
How do you add transaction with mouse click or with keyboard's enter hint? 
I am trying to replicate in my Chrome 61 with no luck (as well Firefox 56)

**Comment by kolynet** [comment]
mouse click, but it might be a problem with only my setup, i would try it out on a clean new installation as well first.

**Comment by kolynet** [comment]
did you add like 40-50 transaction to the  same customer following each other? use different amounts, so you will easily notice if it get doubled.

**Comment by BasaraABC** [comment]
We have an idea how to prevent this. We will update this thread
Thank you for reporting a problem

**Comment by kolynet** [comment]
can you link me to changes on source, so i can test as well!

**Comment by abantecart** [comment]
One more update to JavaScript.

**Comment by BasaraABC** [comment]
Transaction add button works fine but others buttons in admin stop working. For example Add new product. After click nothing happen and no errors in browser console
