### ISSUE TITLE
PayPal express create 2 orders

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#101]
Minor issue If checkout with PayPal Express with logged in customer -after checkout  created 2 orders one with Incomplete status and one more with Processing status
(Note:use normal checkout process Cart->default Checkout button->select Shipping->select PayPal->pay on paypal side-> confirm order) 
checked in 1.2.1

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
thank you. Closed
