### ISSUE TITLE
shipping: Flat rate and locations

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1010]
Please add option to disable/enable delivery method in some location.
<img width="798" alt="2017-10-18_16-56-06" src="https://user-images.githubusercontent.com/2631910/31712523-8ac38456-b425-11e7-8005-0f3bd918623f.png">

**Comment by AVSthe** [comment]
Please do the needful at the earliest and let the location restriction work in Flat rate Shipping extension. It is definitely a fundamental need in shopping cart.

**Comment by AVSthe** [comment]
Nice to see that the issue is fixed, need QA. Please let me know when QA is done. 
Thanks

**Comment by BasaraABC** [comment]
It doesnot work. 
![2017-11-22_17-19-47](https://user-images.githubusercontent.com/2631910/33122385-a55dd7a4-cfa9-11e7-8551-879bd170986d.png)

**Comment by BasaraABC** [comment]
thank you.
