### ISSUE TITLE
Should Line 37 have a closing tag?

### ISSUE THREAD

**Issue by DSinOR** [abantecart/abantecart-src#1011]
No closing </form> tag for line 37?

**Comment by DSinOR** [comment]
Sorry.  

file - public_html/storefront/view/default/template/pages/checkout/confirm.tpl
line - 37 has no closing </form> tag.

learning...

**Comment by abantecart** [comment]
I think you refer to this line
https://github.com/abantecart/abantecart-src/blob/master/public_html/storefront/view/default/template/pages/checkout/confirm.tpl#L37

There is no tag to be closed here. Is this a correct line?

**Comment by DSinOR** [comment]
Hi, I'm new to this, and maybe it's nothing, but while I was looking at various AC files, I noticed a possible missing close tag: </form> 

[https://github.com/abantecart/abantecart-src/blob/master/public_html/storefront/view/default/template/pages/checkout/confirm.tpl]

Line 37: <?php echo $form['form_open']; ?>

Should this file contain an associated </form> tag for line 37?

I asked on the forum.  The forum response suggests that there should probably be a closing tag for that line, but I don't see it.  

Again, maybe this is nothing.  Hope I'm not wasting anyone's time.  Thx.

**Comment by abantecart** [comment]
Can you please share forum post

**Comment by DSinOR** [comment]
http://forum.abantecart.com/index.php/topic,6030.0/

**Comment by abolabo** [comment]
form_open not needed there. removed

**Comment by DSinOR** [comment]
How do I get the fix?

I looked in the pp-express extension files on GitHub, none are updated.  

Thx,

DS



----- Original Message -----
