### ISSUE TITLE
Worldpay not working

### ISSUE THREAD

**Issue by featurespoon** [abantecart/abantecart-src#1012]
The payment extension default_worldpay was not working in earlier versions of Abantecart and has been removed from version 1.2.11.  As a user of Worldpay, I would like to see it back and I know how to make it work. One of the reasons it could not work as it existed in version 1.2.9 was because the code referred to non-existent templates. It also did not reference the correct Worldpay URLs, among other deficiencies.

**Comment by abantecart** [comment]
Thank you. We will address this issue. 

Related post on the forum:
http://forum.abantecart.com/index.php/topic,5906.0/topicseen.html

**Comment by BasaraABC** [comment]
Thank you for contribution. Wordpay will be included in 1.2.12
