### ISSUE TITLE
coupon search issue

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1013]
latest source seem to be returning incorrect values of coupons. completely messed up, i filtered the results for one of the coupon name, in the example 1%-> after pressing enter, all of the coupons under different name shows the same value, however in db everything is ok.

**Comment by kolynet** [comment]
<img width="241" alt="c" src="https://user-images.githubusercontent.com/22685076/32026882-506cc9cc-b9e6-11e7-8d47-96133e72993d.png">

**Comment by abantecart** [comment]
I just checked this and get correct result. Are you sure you do not have coupons with 1% ?

**Comment by kolynet** [comment]
of course not. could it be a problem that im on the latest github sources? since i updated my older admin to github, its happening (it seems)

**Comment by BasaraABC** [comment]
Issue is confirmed. Thank you @kolynet 
See screenshot after refine incorrect results shown in grid and all coupons duplicated
![2017-10-26_13-31-01](https://user-images.githubusercontent.com/2631910/32037990-1ef19b86-ba52-11e7-9feb-b90389042d7f.png)

**Comment by kolynet** [comment]
your very welcome. you can also reproduce bug by using code field. keep me updated with the results!

**Comment by kolynet** [comment]
any update?

**Comment by abantecart** [comment]
This issue is in the queue. We should get to it soon.

**Comment by BasaraABC** [comment]
thank you fixed

**Comment by kolynet** [comment]
@BasaraABC can you link me the source update, so I can test? thanks Basa

**Comment by BasaraABC** [comment]
Link is above with commit.
https://github.com/abantecart/abantecart-src/commit/039a4b911e1df341c8832eea0c23493c7720140c
