### ISSUE TITLE
PayPal express invalid csrf token

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1016]
once i try to pay via paypal it redirects back to blank page with invalid csrf token.

**Comment by BasaraABC** [comment]
Do you have latest AbanteCart and PayPal express ?

**Comment by kolynet** [comment]
of course, used the latest sources. as soon as i update the old extension/pp_express sources it starts working. you must pay via paypal express to reproduce issue, because after paying it redirect to store with this csrf error, and the order remains in incomplete status.

**Comment by BasaraABC** [comment]
So "it starts working" mean no bug after update? Could you please clarify these?

**Comment by kolynet** [comment]
no, i mean if i revert back to the old " storefront / controller / responses / extension / default_pp PHP source" then it starts working. with the updated latest files the bug occurs.
