### ISSUE TITLE
Storefront: Flat Shipping Rate is getting disappeared from top cart and Order Summary

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#1017]
Flat Shipping Rate is getting disappeared from top cart and Order Summary

Steps to reproduce
1.	Visit http://demo.abantecart.com/
2.	Click on "Add to Cart" icon on BeneFit Girl Meets Pearl
![2](https://user-images.githubusercontent.com/22338790/32177721-02acf9d6-bdb1-11e7-8017-9906de7ae700.png)

3.	Top cart will show Flat shipping Rate $2.00 and Total as $22.62
![3](https://user-images.githubusercontent.com/22338790/32177731-09790228-bdb1-11e7-8586-353f9291ac2e.png)

4.	Now click on view cart icon from the top cart
![4](https://user-images.githubusercontent.com/22338790/32177747-0f5d0e78-bdb1-11e7-86fc-1d242cafeeb4.png)

5.	Click on Update button from Shopping Cart screen
![5](https://user-images.githubusercontent.com/22338790/32177757-13379b76-bdb1-11e7-8009-0e4063d28610.png)

6.	Flat Shipping Rate will get disappeared from top cart and total will displayed as $20.62
![6](https://user-images.githubusercontent.com/22338790/32177766-18ddffa2-bdb1-11e7-8015-2b027ffd3254.png)

7.	Click on Checkout from Shopping Cart screen
8.	Choose option as Guest Checkout and click on Continue
9.	You will be navigated to Guest Checkout – Step 1 screen. Here as well Flat Rate Shipping will get disappeared from Order Summary
![9](https://user-images.githubusercontent.com/22338790/32177774-1c23cec6-bdb1-11e7-8f60-a7521c017321.png)

It’s a random behavior. Sometime it works. Try above steps 4-5 times. It will reproduce.

**Comment by BasaraABC** [comment]
Confirmed. Related to "Estimate Shipping & Taxes" apply to the basket

**Comment by BasaraABC** [comment]
Problem more detailed.
Quick basket do not show actual shipping applied to cart. Sometimes it show, sometimes no.
For example you can replicate on shopping cart page (rt=checkout/cart)
If click UPDATE button - after page reloaded on the page will be two different order summaries. See screenshot
![2017-12-12_13-52-01](https://user-images.githubusercontent.com/2631910/33871363-ceeefc4c-df44-11e7-8742-5a733ad276ef.png)

**Comment by BasaraABC** [comment]
Still issue here. Total in quick basket different from total at the bottom of page (index.php?rt=checkout/cart).

**Comment by BasaraABC** [comment]
Delivery method in checkout now separated so Estimate calculator and Order checkout delivery methods are different things.

**Comment by hb007006** [comment]
Tested on dated 10/07/2019. Still issue persist. Total in quick basket different from total at the bottom of page (http://demo.abantecart.com/index.php?rt=checkout/cart)

![1017](https://user-images.githubusercontent.com/22338790/60991743-bf204480-a368-11e9-807f-6206ec23de19.png)

**Comment by BasaraABC** [comment]
demo do not use latest version for now. Estimate is just for the information only.

**Comment by hb007006** [comment]
Top cart is showing **FREE SHIPPING: $0.00**. Shopping Cart page is showing **Flat Shipping Rate: $2.00**. As a customer point of view its very confusing. IMO, Flat Shipping Rate OR Free Shipping whichever is applicable after adding / removing a product should reflect in Top Cart and in Order Summary. Also Total should be recalculated. Top Cart and Order Summary should always display updated Total based on applicable Flat Shipping Rate / Free Shipping charges.

Which version is having the fix?

**Comment by hb007006** [comment]
I have installed 1.2.12 on my local and issue is reproducible. Which version is having the fix?
![1 2 12](https://user-images.githubusercontent.com/22338790/61060809-c2730900-a418-11e9-889c-81995ffe8299.png)

**Comment by abantecart** [comment]
Is this issue present on 1.2.15?

**Comment by hb007006** [comment]
Let me test on 1.2.15

**Comment by hb007006** [comment]
I need to upgrade my PHP version. Getting below error...
5.6.0+ Required for AbanteCart to work properly! Please contact your system administrator or host service provider.

**Comment by hb007006** [comment]
I can confirm that issue still presents on AbanteCart Version 1.2.14

**Comment by abantecart** [comment]
Unfortunately, PHP 5.6.x has reached EOL. We will not support it. https://www.php.net/eol.php

**Comment by hb007006** [comment]
Today, I have upgraded PHP version on my local system and installed AbanteCart Version 1.2.15.
Issue is reproducible on AbanteCart Version 1.2.15.

**Comment by abantecart** [comment]
Thank you. We will investigate

**Comment by BasaraABC** [comment]
Please read comments
https://github.com/abantecart/abantecart-src/issues/1017#issuecomment-351997995
https://github.com/abantecart/abantecart-src/issues/1017#issuecomment-510324615
Estimate on shopping cart page is not the tool for delivery selection for checkout. It is just for the info before checkout.
