### ISSUE TITLE
Quantity Column Missing in mobile view

### ISSUE THREAD

**Issue by AVSthe** [abantecart/abantecart-src#1018]
Please see that after adding to cart the page goes to www.example.com/store/index.php?rt=checkout/cart. 
In this page, it is showing Product name, Unit price, Total and Remove columns. **Quantity column is missing in mobile phone.** Customers will not be able to change quantity and update it in view cart page. To cross check if my files on my server are corrupted, I logged into Abantecat DEMO version after activating personal demo account. DEMO website also not showing quantity column in mobile.  It shows properly in Computer desktop.  Please check. I request you to kindly resolve it soon, and let customers don't face any issues. Thanks.

**Comment by abantecart** [comment]
I think quantity column was hidden on portrait mobile view due to spacing issue. Did you try to scroll right and left? Can you please attach a screenshot?

**Comment by AVSthe** [comment]
I have attached screenshot of mobile phone for your kind reference. Rotating the phone either way top or side wise and also scrolling left to right also, does not show quantitybox. Please check. 
![view cart_mobile_view_screenshot](https://user-images.githubusercontent.com/33345282/32402688-e1845694-c14f-11e7-9fc3-979449426b17.png)
Thanks

**Comment by BasaraABC** [comment]
Please check this post with solution from community user http://forum.abantecart.com/index.php/topic,6066.msg26000.html#msg26000

**Comment by AVSthe** [comment]
Thank you. It was I who posted that in AC forum also. The issue is solved. The solution given there helped me and now quantity box column in Cart page shows in small screen perfectly.

**Comment by abantecart** [comment]
If we hide thumbnail of the product, there will be a place for quantity. Any thoughts?

**Comment by AVSthe** [comment]
Instead of hiding thumbnail of product , we can hide "total" in the table, because, anyways 'Total' is visible and shown at the bottom in the cart page. Instead of 'total', **quantity** **can be shown in the table** and allow customers to update  quantity it if they need.  Customers may visually be interest to see picture of product and to keep them attached to the site till they checkout and and make payment. The solution in AC forum about this topic worked for me and quantity column shows in mobile phone.
