### ISSUE TITLE
PayPal Express Bug

### ISSUE THREAD

**Issue by DSinOR** [abantecart/abantecart-src#1019]
When customer chooses PayPal Express Checkout, they are redirected to PP page for login etc.

The PP API transmits the customer name and address data back to AbanteCart for order confirm.  

While the customer is on their PP page, they can choose a different shipping address, like for a gift.

When this happens, the PP API transmits the wrong data back to AC:  it sends customer (billing) name + gift (shipping) address.  That is the first problem, and it is the biggest problem.  

You can see it yourself by going to my site and adding something to the cart, then choosing PP Express, then logging in to your PP account, then choosing a different shipping address on the PP page, then clicking Continue on the PP page, which will take you back to the Confirm page on my site where you will see the bug (wrong combination of billing name + gift address).  As long as you don't click the Confirm button, the transaction will not complete, so you don't have to actually buy something to do this test.  FYI - there is a 50 cent Test Product in the Reduced category.  

There are other related problems:

2 - For the AC storeowner, there is no indication that there is a problem with addresses.  This type of transaction looks like any other PP transaction: you get a name and address just like normal, but you have no way of knowing that the address is a gift address with a wrong (billing) name attached to it.  

3 - For the Customer who is buying someone a gift in your store: the customer will see the wrong name with gift address when they are returned to your confirm page, and they will try to fix the problem by using the Back button on the confirm page.  This will restart the PP Express routine, ultimately leaving the customer in an infinite loop of "wrong address-go back-do paypal again-get wrong address-go back-do paypal again" etc.  Obviously, the customer will abandon the transaction, and you lose a sale because AbanteCart does not work.  

3 - AC has fields for Billing address and Shipping address.  These fields are displayed on the Confirm page.  When a PP Express customer chooses a "gift" address on PP, AC is populating BOTH the billing and shipping address fields with the incorrect combination of billing name + gift shipping address.  

3a - At a bare minimum, AC should be showing Gift Shipping [b]name[/b] with Gift Shipping [b]address[/b] in the fields.  At least then you have a better chance that the customer will click confirm to complete the transaction because the correct shipping address is being shown; BUT, they still might not click confirm because they don't like the fact that the gift recipient's NAME and ADDRESS are now showing in both the BILLING and SHIPPING address fields on the AC confirm page.  Because they might worry that the gift reciepient is going to receive some kind of invoice or receipt for the transaction, which gift givers do not want.  The reason they might think this is because ABANTECART IS SAYING THAT THE BILLING AND SHIPPING ADDRESS ARE BOTH THE GIFT RECIPIENT'S ADDRESS.

3b - The best solution would be if AbanteCart worked properly with PayPal, meaning that whenever a PayPal customer chose a different shipping address on their PP page, the PP API would transmit correct billing and shipping data back to AC, and AC would show that data correctly on the Confirm page.  

3c - If AbanteCart cannot work properly with Paypal to distinguish between and properly display billing vs shipping address data for PP transactions where the customer selects a different shipping address, then the least that AbanteCart should be able to do is NOT SHOW a Billing address on the Confirm page at the conclusion of a PayPal transaction.

Thx.

**Comment by BasaraABC** [comment]
Hi, team. We need to discuss before any changes.
Here is important notes and use cases
1. Guest checkout
2. Registered customer checkout with PP Express banner in the basket (skip payment selection)
3. Registered customer checkout with normal checkout process (select payment)

Worst case is Guest checkout - see screenshots.
After paypal return data we have new email (paypal email), new name (paypal registered, note the shipping name selected in paypal side also ignored), new shipping and billing addresses. But company name is from what customer enter in AbanteCart side
![2017-11-10_16-34-50](https://user-images.githubusercontent.com/2631910/32652232-3447ebc6-c636-11e7-9312-c3771ed5562f.png)

**Comment by abolabo** [comment]
Their API gives only one address. Only shipping address from their UI. 
Also this data does not contains "Company name"

**Comment by goatlady102** [comment]
Let me add a thought to this, at least in regards to Guest.  IMO this is the wrong approach to a solution.  As this is an issue with all forms of payment when a guest.  So solution should address a global resolution.

My suggestion is to add a Is this a gift? Or a Add additional address select button in the Guest CheckOut -Step 2 that allows the guest customer to add an additional shipping address for the gift but leaves the original purchaser address intact.  Currently there is not an easy way for Guest to return to the separate shipping address on the guest_step_1.    And the Edit shipping button only returns to Shipping method.

This is also important if the payment is authorize.net  as the account address and the address on file for the card must match.

**Comment by DSinOR** [comment]
If it is correct that PP API will only return 1 address back to AC, 
and the API cannot be modified to accommodate 2-address transaction,
then the only way to avoid customer confusion on AC Confirm page is to not 
display Billing address on Confirm page after PP transaction.  

That's my 2 cents.  


----- Original Message -----

**Comment by DSinOR** [comment]
I understand that AC has many payment extensions.

I only use two: PP Express and Stripe.

My site only uses Guest checkout.    

On my site, a Stripe guest checkout where the customer enters a different shipping address DOES work properly.  
@goatlady102 - perhaps it is not entirely correct to say that "this is an issue with all forms of payment when a guest."

Also, I think it is important to remember the spirit of PP Express, which is "speed".
The PP Express button is on the AC Cart page.  
From my Cart page, a PP gift-buying customer is five clicks from completion:  
1 - click the PP Express button.
2 - on PP page, click "different address" button. 
3 - on PP page, choose different address from PP address book.
4 - on PP page, click continue.
5 - on AC Confirm page, click Confirm.  
(GS2 has been removed from the checkout routine on my site.)

The goatlady recommendation to add "Is this a Gift?" element to GS2 is a good idea, but I think it will be a redundant experience for the PP Express customer who chooses a gift address on their PP page, and then is required to hand-enter the gift address _again_ when they are returned to GS2.  
In this scenario, the PP Express checkout has been made slower than a standard credit card checkout.

The AC billing address value is integral to AC credit card checkout extensions (for authorization), but AC billing address is not needed by PayPal or by PayPal customer for success:
1 - If PP needs a billing address for a PP Credit Card, PP will get the billing address from the customer on the PP page.
2 - The customer who pays with their PayPal account already knows that PP has their correct address data, so It's not important for AC to display billing and shipping address data for PP customers.
By this assessment (if it is correct), there is no need to **ask for** or **display** a "billing" address on the AC Confirm page for PayPal customers.  The first part is already done: AC does not ask for a billing address from a PayPal customer.  However, the 2nd part is a problem: AC currently _does_ display both a "billing" and "shipping" address on the Confirm page at the end of a PayPal transaction.  If the API only passes one address back to AC, then this will always be a problem for gift-buying customers because they will always see the gift address in _both_ the billing and shipping fields, which will cause worry and concern for the customer.  

Possible intermediate solution: fix the primary "name" problem that occurs when a PP user chooses a gift address, then hide the billing address element on the AC Confirm page after PP transactions.  The customer will then only see the corect shipping address on the Confirm page.  

If that works, then only one problem remains with a guest checkout PP Express gift purchase: the store-owner does not know who the customer is.  
In fact, the store-owner will think that the gift recipient is the customer.  

Hope this helps in some way.  If my assessment includes mistakes, my apologies in advance.  

Well, good luck!  🤐  

Dave

**Comment by DSinOR** [comment]
Hi, I talked to PP today.

I succeeded in making a PP employee understand the following:

1 - It is counter-intuitive to drop the First name and Last name values from the address data that is passed back to the vendor site by PP Express when the PP account holder selects the Change Address function on PP.  

2 - If random customer Joe uses the Change Address feature of PP Express checkout, Joe does not expect PP to combine HIS name with DIFFERENT address, because that is not how the "different shipping address" feature works on **any other e-commerce platform**.  

3 - PP suggested a solution:  add a blurb to the PP page to explain that the Change Address feature is NOT for a gift purchase, but rather for choosing a different address for the account holder.  I helped the PP employee see that this solution is suboptimal compared to the better idea of coding the PP API to pass 2 unique addresses whenever a PP customer uses the Change Address function on the PP page.  In particular: pass the changed shipping address ver batim.  The billing address can just be the account holder's primary address.

4 - PP suggested another solution: change the vendor site to add a provision for selecting a "gift address" only for a PP Express purchase.  I explained that random people are not going to understand this non-Express plan of action for an Express checkout, and also that no other e-commerce checkout flows function in this manner (because it is counter-intuitive), and also that this proposed solution violates the spirit of express checkout.  Finally, I explained that the much simpler solution would be to pass back to the vendor site whatever address data that a PP user chooses on the PP page.  IOW, to do the predictable thing, instead of some other counter-intuitive thing.  

At the end of the phone call, the PP employee said that they would send the recording of the call to the magic PP coder fortress.

Maybe something good will happen!

**Comment by BasaraABC** [comment]
thank you, @DSinOR 
We will review and update PP express. I think main idea of pp express is paypal account data should override any AbanteCart data and do not combine anything. Also we will improve paypal's ship to name and address support as well

**Comment by DSinOR** [comment]
This is as far as I can get:

_"Thank you for the information. Since you are using a 3rd Party  Shopping cart, and have not custom coded your site, the best course of action is  to speak with your 3rd Party Cart AbanteCart about how the address is being  captured and relayed to your cart.   Sincerely,JenniferGlobal Technical  SupportPayPal, Inc."_

The default location for the PP Express button is the Cart page, before GS1.  
For unregistered guests, there is no data for PP to override.

Thx.

**Comment by BasaraABC** [comment]
Issue is fixed only partly. Please pay more attention to details.
For example issues found in Guest Checkout.
1. Add products to cart and start guest checkout
<img width="702" alt="1a" src="https://user-images.githubusercontent.com/2631910/34038138-cf40afd0-e1bd-11e7-88cd-3a112a4dd6cf.png">

2. Select PP Express and continue
![2](https://user-images.githubusercontent.com/2631910/34038114-b9612e92-e1bd-11e7-9ac8-b0e781e5e6f5.png)


3. On paypal side select SHIP TO with different name and address
![3](https://user-images.githubusercontent.com/2631910/34037841-d43911fe-e1bc-11e7-90d4-96ad4e3c265c.png)

4. Take a note: paypal account holder name and billing address
![4](https://user-images.githubusercontent.com/2631910/34037862-e1469efc-e1bc-11e7-831b-75a19ccf2bf5.png)

5. Place the order and see invoice
![5a](https://user-images.githubusercontent.com/2631910/34038260-617ec544-e1be-11e7-8fab-f695916cd2b0.png)



I see problems here:
A: Why Payment address are taken from Ship to?
B: Why Payment data contain Company name taken from guest form. We discuss this before. This is incorrect.

**Comment by BasaraABC** [comment]
More issues with Registered Account. All data from paypal ignored.
1. register account
![11](https://user-images.githubusercontent.com/2631910/34040794-ee17498c-e1c7-11e7-91ea-4f1bf994a756.png)

2. Select different SHIP TO 
![22](https://user-images.githubusercontent.com/2631910/34040795-ee4fdd1a-e1c7-11e7-89c5-fedef21f6df8.png)

3. In result all paypal data are wrong: Shipping name and address, payment name and address
![33](https://user-images.githubusercontent.com/2631910/34040796-ee89f4f0-e1c7-11e7-8ec0-8e78e53707b8.png)

**Comment by BasaraABC** [comment]
SHIP TO address and name fixed. For both guest and registered users the Shipping address and Shipping Name are taken from PayPal. 
However question about billing address. With latest fix customer's paypal name and billing address do Not go into invoice. For both guest and registered customers billing data from the AbanteCart forms. Is it correct?

**Comment by abolabo** [comment]
yes. Paypal DO NOT gives billing address to us. Only delivery(shipping) address.

**Comment by DSinOR** [comment]
Hi, I think I replied to the wrong email a couple minutes ago.  Sorry.

How do I get the fix for the "paypal express bug" referenced below. 

I checked GitHub, none of the extension files had been updated.  

It seems like you fixed the extension so that it now passes the correct name 
with address when user selects "different address" on paypal.

How do I update my cart to get this fix?

Thx.

DS





----- Original Message -----

**Comment by BasaraABC** [comment]
Download 1.2.12 branch https://github.com/abantecart/abantecart-src/archive/1.2.12.zip
unarchive and go to /extension/ directory find **default_pp_express** folder and uplaud it to your server

**Comment by DSinOR** [comment]
Ok, thanks, I'll give it a try.


----- Original Message -----

**Comment by DSinOR** [comment]
Hello.  

Issue #1019.

Branch 1.2.12

/extensions/default_pp_express/storefront/controller/responses/extension/default_pp_express.php

L335 & L339 = new property: $new_shipping_address.  It applies correct Ship 
Name to Ship Address data passed back to AC when PP User chooses 
"Different Ship Address" on the PP page.

However, there is still a problem.  

The GS3 page now shows this:

Shipping Address:
Ship Name
Ship Address

Billing Address:
Billing Name
Ship Address

This will confuse customer.  If customer uses "Back" functions to attempt to 
fix problem, it gets bad.  Lost sale.  

I understand that PayPal will only pass one address back to AC.  

If PP user chooses default PP address while on PP page, 
PP passes default PP address to AC.  
GS3 will show correct (same) Shipping and Billing address.

If PP user chooses Different Shipping address while on PP page, 
PP passes new_shipping_address back to AC.  
GS3 will show pp-user-name + new_shipping_address in the Billing Address field.  
See attached screenshot:  Uncle Bill on Ruxton is a 
"Different Shipping Address" entered on the PP page.  I am David, and my 
address is in Oregon.  On AC GS3, my name was combined with Texas address and 
displayed in Billing Address fields.  

Solution: 
If $new_shipping_address = true; pass null data for Billing Address to AC, and 
populate GS3 Billing Address fields with blank data.  This will be better than 
wrong data, and this will be viable for customer and store owner.  

Or...

If payment-method = pp_express && if $new_shipping_address = true, GS3 Billing 
Address Fields = display: none, or clear:something + echo:empty_ fields.  
Something like that.  

Comments:
After pp_express, it is better for GS3 to show nothing for Billing Address, 
than for GS3 to show wrong name+address for Billing Address.  

After pp_express, Storeowner does not need "Billing Address" on GS3 to have 
successful experience, because Storeowner will receive email from paypal that 
contains Customer name and Customer email address.  

After pp_express, Customer does not need to see "Billing Address" data on GS3 
because Customer knows that paypal delivers Customer info to Storeowner via 
email, and Customer only needs to see proper new Shipping Address data on GS3 
to trust the transaction and click Confirm.  

Thanks!

Dave





----- Original Message -----

**Comment by BasaraABC** [comment]
Blank Billing address is not good approach. Even if this suit your business model. 

Anyway are you sure your update all paypal express files correctly? Please also clear browser cache to clean your Guest checkout session. In my setup for the Guest customer + PP Express the Billing name and Address go from what guest enter on step 1
![pp](https://user-images.githubusercontent.com/2631910/34334750-c94ff8ea-e97b-11e7-9b32-61511f607c66.png)

**Comment by DSinOR** [comment]
Hello!  Merry Christmas!

Paypal will only return one address.  
You fixed the wrong shipping address problem, but your fix caused a new wrong 
billing address problem.

On GS3, customer and store owner do not need Billing Address displayed after PP 
Express.  
So the choice is:
1 - display a wrong billing address to cause a problem even though a billing 
address is not needed, or...
2 - not display billing address. 


I have a PP Express button on the Cart page and at the top of GS1.  
The PP Express customer does not complete any name or address fields on GS1.

The purpose of PP EXPRESS on all websites is to bypass the address-fields step 
of the checkout process.

Customers who see a PP Express button will click the button, not fill in the 
address fields and then click the button.  

DS





----- Original Message -----

**Comment by BasaraABC** [comment]
@abolabo can you please check and confirm that PayPal API return only one address? 
If PayPal return ship-to AND billing addresses maybe we have a bug.

**Comment by BasaraABC** [comment]
According to technical support PayPal do not return in this case a billing address. Order and invoice can not be without any billing data so if you start checkout from basket the only one address data go to billing section - from what Paypal return.  You can force guest customer to enter a billing data by disabling Paypal express banners in settings.

**Comment by DSinOR** [comment]
I 
don't think this issue will ever reach a functional resolution.  "Functional resolution" is a big word.  "Good enough resolution" is what we settle for when we don't 
want to think or work enough to achieve functional resolution.  

PP is the largest, most trusted, most commonly-used 3rd party payment system on 
the planet.  

There are 2 reasons for an e-commerce customer to use PP Express:  they trust 
it and it is fast/convenient.

********************

The most important design goal for e-commerce code is to permit and encourage 
successful transactions.  Not semantic satisfaction of benchmarks.  

********************

Since you are not going to take my word for any of this, you should go 
interview 50 PP users.  Ask them what they expect to happen when they click a 
PP Express button to pay for an online purchase.  Ask them what they expect to 
happen when they choose a different shipping address on the PP page.    

Compare their answers to what actually happens when they click a PP Express 
button and enter a different shipping address on an Abantecart site.  
Compare their answers to the idea of requiring customers to complete address 
fields before clicking a PP Express button.  
Ask them what they think of that idea.  

*******************

The rest of this entire discourse is just people flapping their mouths.  

You guys are either going to address the obvious problem, or not.  

Your hands are not tied.  This all comes down to whether you want AC to work 
intuitively to achieve trusted and successful transactions, or to have stupid 
parts coded into it.  

BTW - 
don't feel bad.  I spent 5 hours explaining this entire problem to PayPal employees, and at the end of that effort, they were faced with a decision of whether to pass 2 address sets back to cms's 
when PP-users choose "diferent address", or stay stupid.
They happily chose "stupid".  
This was not a surprise because PP has been stupid for 18 years.  
The only reason they are #1 is that they were first with pay by email, and they 
got in bed with ebay.  
Their code and practices have always been stupid, counter-intuitive, and not 
customer-centric.  
They have never not had a bad reputation for screwing people over and ignoring 
their customers-users.  

Not a good role model to follow.  

Anyway.  

Happy Holidays.    

DS





----- Original Message -----

**Comment by BasaraABC** [comment]
Hello @DSinOR . If billing address is so critical for your business why not modify paypal express extension or even AbanteCart code? AbanteCart is open source, feel free to create new paypal extension designed for this case. You can share it with community or even sale in marketplace.

**Comment by DSinOR** [comment]
Thanks for the reply.

I only have general comments:

1 - I'm not a coder.  I'm a non-tech AC user who pushed the boundary of non-
coder AC capabilities to its maximum limit during a 6 month development of an 
AC site.  The outcome is a simple site suitable for small business.  Of 
particular note: my site has several features that are both non-typical to AC 
sites and widely accepted in the development world as being optimal features 
for e-commerce.
Namely: uncluttered interface with fewer distracting non-essential features, 
streamlined checkout with fewer pages and clicks required, improved seo profile 
without multiple urls for identical content (the duplicate content issue 
described by google), improved control over which images are indexed by search 
engines, simple and unique incorporation of social media buttons without loss 
of easy-zoom feature, improved pageload speed, etc.  

2 - My AC customizations can be construed as either a series of personal style 
or 
'business model" preferences, or as a series of changes to the platform that improve the degree to which AC conforms to widely accepted "best practices for e-commerce".  If the latter is accepted, then I have done as much as any person to contribute to the ongoing development of AC, which IMO is notable given my lack of coding ability.  

3 - I paid you folks $300 to customize your platform to my preferences for faster checkout with less clicks, and for elimination of multiple urls to identical content.  Arguably, those customizations of the code were for personal preference, not repair of flawed code.  

The PP Express problem is different.  It is an actual flaw in the checkout process  

In the context of best practices, a developer must know that visitors arrive at any website with pre-conceptions of how e-commerce works.  
When a website does not work in the same way that nearly every other website works, visitors do not tolerate counter-intuitive outcomes.
Rather, they just leave without buying anything.  They leave for 2 reasons: frustration, and lack of trust of the site.  

"Express checkout" is a very common feature of e-commerce sites.  It comes in many different flavors: Amazon, eBay, PayPal, browser autofill functions that even autofill credit card fields, etc.
All of the flavors work the same way.  
They are all the same in how they handle the tasks of online checkout.  
Therefore their processes have become intuitive to online shoppers.  

PP Express has a major flaw.  We have described the flaw in this Issue 1019.  
Your team has attempted to fix the flaw by changing how AC interacts with PP so that AC GS3 will now populate the shipping name field with accurate data.  
That is certainly progress.  
One fatal flaw still remains: after your initial repair, the AC GS3 page still displays inaccurate 'address' data in the billing address fields after a PP Express customer uses the Different Shipping Address function on the PP page to accomplish a common checkout task: changing the shipping address for a gift or whatever.  

From the customer's 
perspective: 
PP allowed them to change the shipping address and it was an intuitive 
experience.  
However, when PP returned them to the online store, the store displayed 
incorrect billing address data after the PP success.
Therefore this online store does not work intuitively, therefore I will leave 
instead of clicking confirm because I am worried that my gift purchase will be 
accompanied by a purchase receipt being mailed to my gift recipient under my 
name because that is what GS3 says is going to happen.  
The shopper may try to fix the problem with the back button, which results in 
an infinite loop of the same error, which is arguably worse than if they just 
left immediately.  

When you buy someone a gift, do you mail them a receipt so that they know the 
price of the gift?  NO!  Nobody does that.  

Is this PP issue your fault?  NO!  It's PayPal's fault.  They suck!  

But, they are the largest such payment entity on the planet, and millions of 
online shoppers trust the PP process and use it everyday, so we have to 
tolerate the low-quality PP process because 
A - we want the PP capability on our site
B - PP will not fix this problem in their system because they suck.  

There is only one remaining option for AC:  choose the lesser of two evils.  
Choose to display inaccurate data on GS3 that will cause lost sales, 
or choose to modify how AC interacts with PP, namely do not display Billing 
data on GS3 after PP Express.  This will not cause lost sales.  

The latter option is viable because both the customer and the storeowner can 
survive it.
The Customer will see the correct Shipping address and will therefore click 
Confirm on GS3 because everything "looked right and felt normal".
The storeowner will receive a correct shipping name & address from AC, and also 
the name and the email address of the buyer in an email from PP.  

I hope you will make this fix to the AC code.  
This issue is not a Dave (Geoffrey) problem.  
This problem will occur for every AC user who uses PP Express.  
I cannot speak to other PP extensions.  
I have not tested them.  
Have you?  

To address your latest questions directly:
Accurate name & address data displayed on GS3 is not critical for 
"my business".  It is critical for any business.  

I am 52.  I have expertise in GAAP accounting, controlled deviation and survey 
of offshore deepwater wells, bison management, external ballistics, motorcycle 
racing, medical device manufacture and regulatory affairs, and sewing machine 
repair.  I am a bad welder.  My welds are ugly.  I will no sooner learn php 
than take up dentistry.  Are you going to learn federal transport requirements 
and safe handling and emergency recovery techniques for lost-in-hole cesium137 
sources used in realtime formation evaluation?  I learned all that stuff 25 
years ago, before the internet existed.  I'm not suggesting you need to learn it.   But "feel free" to learn it if you want.  Then you can sell your new expertise in the drilling industry.  

Thanks.  

Happy New Year!

Dave


----- Original Message -----

**Comment by abantecart** [comment]
Originally, this integration was certified by PayPal back 3 years ago.  This does not make it bulletproof to serve all the cases. 

We try to build an e-commerce application to cover most common cases, but we can not cover all possible scenarios. 

I think we need to make this discussion shorter and straight to the point.
We can list short use cases that you suggest and see what we can do. 

The longer the discussion the more difficult to navigate it. Reading all these am not very clear on the problem at this point.

**Comment by DSinOR** [comment]
Do a guest checkout with PP Express.
While on PP page, use the "Different Shipping Address" function, then click 
Continue.
GS3 will display a correct Shipping Name+Address but incorrect Billing Address.  

This is a bug that will cause lost sales.  

Since it is not possible to make PP pass 2 distinct addresses back to AC, 
the easiest solution is to not display Billing address on GS3 after PP Express 
transaction.  
Outcome: Shipping address will always be correct.  Storeowner will always have 
correct buyer name and email provided by PP email after transaction.  

This bug probably also affects other PP extensions, and should be checked.  

If registered customer uses Different Shipping Address function on PP page 
during checkout, the same bug may also affect address data.

*******************

I have requested fix for 7 weeks.  

My long posts only happen after illogical replies or denial of repair from AC 
devs.  

I apologize for wall of text, but what else can I do?  

Is wall of text an effective strategy?  Did lead developer just re-engage issue?  

Thx.

DS





----- Original Message -----

**Comment by BasaraABC** [comment]
@abolabo  can you please check this https://stackoverflow.com/questions/16469369/getting-billing-info-express-checkout/26775941#26775941
see if we can make optional setting in extension (default off) if merchant contact paypal and have enabled billing return? Or this solution for customers only?

**Comment by DSinOR** [comment]
Any resolution?

**Comment by BasaraABC** [comment]
PayPal express deprecated in 1.3.3
