### ISSUE TITLE
Bank Transfer mail issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#102]
Bank transfer instructions are not visible in customer's order email 
(note: tested in 1.2.1 with 2 languages installed)
![bankissue](https://cloud.githubusercontent.com/assets/2631910/6571617/ef241fb0-c73c-11e4-9ac6-578a1c18cf99.png)

**Comment by BasaraABC** [comment]
same problems in order history
![bankissue2](https://cloud.githubusercontent.com/assets/2631910/6571671/86d801a0-c73d-11e4-86d3-a5926ad53729.png)

**Comment by abolabo** [comment]
fixed

**Comment by Lucan86** [comment]
Good day same problem here can someone help there, the invoice appear without banking details

**Comment by BasaraABC** [comment]
Hi, Lican86 you need to update this file https://github.com/abantecart/abantecart-src/blob/0d3a288a678b0ac987157ab894254b576a371efb/public_html/extensions/default_banktransfer/storefront/controller/responses/extension/default_banktransfer.php

**Comment by Lucan86** [comment]
Hi BasaraABC

thank you for the mail, but how do i update this file or where do i go to update it.

**Comment by BasaraABC** [comment]
Lucan86, issue is closed. If you have additional questions please use abantecart forum http://forum.abantecart.com/
