### ISSUE TITLE
default_stripe_ssl_off_error

### ISSUE THREAD

**Issue by barry819** [abantecart/abantecart-src#1021]
Abantecart is not showing the form to enter credit card information, It is showing the error default_stripe_ssl_off_error. How do I fix this?

**Comment by BasaraABC** [comment]
What is your stipe extension and AbanteCart versions?

**Comment by BasaraABC** [comment]
This error mean "Secure connection cannot be established!" If your cart version 1.2.11 Make sure you have latest stripe extension and SSL is setup correctly
