### ISSUE TITLE
editing block or custom content issue

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1023]
when you try to insert a '%' mark anywhere, after saving it will insert a backslash '\' before the '%' which makes it \%.

**Comment by BasaraABC** [comment]
Hi. Can you send a screenshot? In what field you insert % ?

**Comment by kolynet** [comment]
found out you have an str_replace \% in core database amysqli.php... fixed myself by removing. latest github source

**Comment by BasaraABC** [comment]
what is line number?

**Comment by kolynet** [comment]
i think its been edited. i downloaded the source couple days ago i think. we can close this issue down.

**Comment by kolynet** [comment]
https://media.discordapp.net/attachments/217982362317881344/381065180886335488/unknown.png?width=1083&height=956
