### ISSUE TITLE
broken url in message

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1028]
<img width="841" alt="2017-11-21_19-42-20" src="https://user-images.githubusercontent.com/2631910/33073192-aeb25362-cef4-11e7-943e-dc6d89b7511c.png">

**Comment by BasaraABC** [comment]
Looks like this issue anywhere. For example after order confirm if customer click invoice link it also broken. Looks like not related to browser (visible in chrome, ff)
```
http://dev06.store.net/http://dev06.store.net/abc1212_m11d22/index.php?rt=account/invoice&order_id=1223
The requested URL  was not found on this server.
```

**Comment by abolabo** [comment]
need more details how to replicate. Tried to reproduce on dev-server - works fine.:/
