### ISSUE TITLE
Download attributes issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#103]
Few issues with Download attributes

issue 1: Can not save Checkbox download attribute value see screenshot
-----------------------------------------------
![options-issue8](https://cloud.githubusercontent.com/assets/2631910/6597223/93aa9578-c82d-11e4-975f-04dbe89830ad.png)

issue 2: No way to remove download attribute (Selectbox and Radio types) from file download
-----------------------------------------------
![options-issue10](https://cloud.githubusercontent.com/assets/2631910/6597226/97a8fed0-c82d-11e4-9060-3c37024e953d.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issues fixed few minor found.
Issue 1: minor issue. Please add 'create download attribute' link in case no attributes created yet. We have this in AbanteCart 1.1.9
-----------------------------------
![downlattrib1](https://cloud.githubusercontent.com/assets/2631910/6842594/abd372a0-d3cc-11e4-8c60-630521b4e636.png)
-----------------------------------
-----------------------------------
-----------------------------------
Issue 2: incorrect cursor on remove button mouseover
---------------------------------------------------------------
![dowatribcursor](https://cloud.githubusercontent.com/assets/2631910/6842704/a57657f0-d3cd-11e4-8263-151d07606945.png)

**Comment by abolabo** [comment]
fixed
