### ISSUE TITLE
Error "F2 17" on add to cart sometimes when using AbanteCart

### ISSUE THREAD

**Issue by Xavron** [abantecart/abantecart-src#1033]
Error code "F2 17" shows up. Currently, I've tracked it to the following:

Shows up on first browsing to store. Fixed by going to product or re-freshing home by using home button, etc.

NOT resolved by refreshing page from browser (Firefox 57)

Error log:
method not exist: AbanteCart core v.1.2.11 Error: controller method not exist Controllerresponsesproductproduct::addToCart'! in .../core/engine/dispatcher.php on line 313

`if (is_callable(array ($controller, $this->method))){ <-------- false`

```
	//event for adding product to cart by ajax
	$(document).on('click', 'a.productcart', function() {
        var item = $(this);
        //check if href provided for product details access
        if ( item.attr('href') && item.attr('href') != '#') {
        	return true;
        }
        if(item.attr('data-id')){
	        if( update_cart(item.attr('data-id')) == true ) { <------- false
		        var alert_msg = '<div class="quick_basket">'
				        + '<a href="https://REMOVED.com/store/index.php?rt=checkout/cart" title="Added to cart">'
				        + '<i class="fa fa-shopping-cart fa-fw"></i></a></div>';
				item.closest('.thumbnail .pricetag').addClass('added_to_cart').prepend(alert_msg);
	        }
        }
    return false; <-----------
```

```
	function update_cart(product_id){

		var senddata = {},
			result = false;
		if(product_id){
			senddata['product_id'] = product_id;
		}
		$.ajax({
                url:'https://REMOVED.com/store/index.php?rt=r/product/product/addToCart',
                type:'GET',
                dataType:'json',
                data: senddata,
				async: false,
                success:function (data) { <------- false
					//top cart
					$('.nav.topcart .dropdown-toggle span').first().html(data.item_count);
					$('.nav.topcart .dropdown-toggle .cart_total').html(data.total);
					if($('#top_cart_product_list')){
						$('#top_cart_product_list').html(data.cart_details);
					};
	                result = true;
                }
        });
		return result; <------- false
```

![screenshot from 2017-11-28 13-48-57](https://user-images.githubusercontent.com/6201844/33519493-adc5ccc0-d775-11e7-918e-848d4980989e.png)

**Comment by abolabo** [comment]
hi. Did you checked file /public_html/storefront/controller/responses/product/product.php ?
Can you compare yours with file in repo?

**Comment by Xavron** [comment]
$ diff git_product.php product.php
340c340
< }
---
> }
\ No newline at end of file

Nothing meaningful.

(I've been a bit busy with other things so haven't looked into it further yet.)

**Comment by BasaraABC** [comment]
Just to clarify do you have clean installation of AbanteCart 1.2.11 or upgrade from 1.2.10?

**Comment by Xavron** [comment]
Clean install of 1.2.11 from cPanel (first time using AbanteCart). 

Additional info:
Firefox 57 sees the problem immediately on first browsing to AbanteCart home - every time I open in a clean browser window this is what happens. I.E. If you are a first time customer then this is what you will see upon first using the store.

Chrome 62.0.3202.94 does not appear to see this problem.

Since you pointed out a php file, tried switching server PHP to 7.1 but that doesn't appear to affect it either).

Including 2 images of 2 other areas affected.

Looks like maybe from the major changes of Firefox 57?

**Comment by abolabo** [comment]
Why your font icons are broken? Do you have some errors in browser console with CORS etc?
Looks like you have wrong configuration of ssl URL in admin. 
Can you check the same issue on our demo http://demo.abantecart.com/ ?

**Comment by Xavron** [comment]
http://demo.abantecart.com/ doesn't seem to have the problem =)

Ah, so will check the SSL url...

Thanks, this is a weird problem to me.

**Comment by Xavron** [comment]
So changing ssl url to non-www fixes it in Firefox but causes it in Chrome.

I think this is an issue on my side? Though I'm not aware of differentiating between browsers.

Thanks much! That's awesome =)

**Comment by BasaraABC** [comment]
Please check what is the url value you have in Admin > System > Settings > Store
And please clean AbanteCart cache

**Comment by Xavron** [comment]
Brilliant 👍

Forgot to clean Chrome cache. Cleaned AbanteCart cache as well. Now both are working great.

Sorry, that it wasn't a core problem. I didn't expect www to be a problem in the url and don't remember seeing anything like this.

**Comment by Xavron** [comment]
For reference: Use www.domain.com then go to store with www causes this as well. So setting up AbanteCart url seems to be a bit tricky here to avoid problems.

**Comment by BasaraABC** [comment]
If you store url without www. you should set redirects from all www trafic to non-www version.
And vise versa.
For your reference google think www and non-www are two different sites

**Comment by Xavron** [comment]
Thanks much =)
