### ISSUE TITLE
font-awesome and ssl

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1043]
Browser block font-awesome. Do not forget to fix this in embed too
![2017-12-20_13-24-55](https://user-images.githubusercontent.com/2631910/34194048-5d7eb3f4-e589-11e7-9268-51d84fe1ef33.png)

**Comment by abolabo** [comment]
it's just a message about blocked font from browser-cache. As you see on screenshot all font icons presents. That means browser sends another request to font via https and get font anyway.

**Comment by abantecart** [comment]
Please check that we do not have hardcoded inclusion of assets with HTTP

**Comment by BasaraABC** [comment]
Please also check this
![2017-12-20_20-41-57](https://user-images.githubusercontent.com/2631910/34209866-6e839768-e5c6-11e7-9522-6bf2b9c1bc13.png)

**Comment by abolabo** [comment]
@abantecart, i already checked before posting.  we have no hardcode for css. 
all web-fonts asks by relative urls.
@BasaraABC , missed web-fonts added
