### ISSUE TITLE
HTML cache: total price recalculation and quanity discount

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1044]
Total price ignore quantity discounts
<img width="402" alt="2017-12-20_14-23-06" src="https://user-images.githubusercontent.com/2631910/34195730-a0daac4a-e591-11e7-8ac3-b5c700e8d53f.png">

**Comment by abolabo** [comment]
need more details. Try to replicate on your testcase abc1212_m12d20 (product ID 51) 
It works fine for me. :/

**Comment by BasaraABC** [comment]
I think problem in the HTML cache. If promotions are set for different customer groups total may show incorrect values.

To replicate issue add few promotions specials/quantity to different Customer Groups. Then login and logout you will see unexpected results like on the screenshot
<img width="474" alt="screen shot 2017-12-21 at 1 55 54 pm" src="https://user-images.githubusercontent.com/2631910/34244179-bcc9f72e-e656-11e7-9f15-f1aa8edfe7b3.png">
