### ISSUE TITLE
dev: warning in log

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1048]
warning: AbanteCart core v.1.2.12 session_start(): Cannot send session cache limiter - headers already sent (output started at //abc1212_m12d22/core/lib/response.php:150) in <b>/abc1212_m12d22/core/lib/session.php</b> on line <b>114</b>

warning: AbanteCart core v.1.2.12 Cannot modify header information - headers already sent by (output started at abc1212_m12d22/core/lib/response.php:150) in <b>/abc1212_m12d22/core/lib/session.php</b> on line <b>113</b>

**Comment by abolabo** [comment]
it's too common error. Needs steps how to replicate

**Comment by BasaraABC** [comment]
I will try to catch again
