### ISSUE TITLE
Admin front language selection issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#105]
Install new language, enable it and Load missing data then change to new language in admin. The blank screeen appear in Chrome browser only. 
Note: in FireFox issue Not visible, in IE no blank screen, but the backend jump to storefront (abc 1.2.1)
http://forum.abantecart.com/index.php/topic,3333.msg14276.html#msg14276
![aban-bug01](https://cloud.githubusercontent.com/assets/2631910/6613142/0962e77e-c8bb-11e4-819f-96c9dedd38bd.jpg)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
White screen issue fixed but another one appear: incorrect page loaded when change admin language see screenshot
![languages](https://cloud.githubusercontent.com/assets/2631910/6843147/8a3f5acc-d3d2-11e4-9c85-8737342b6c89.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
thank you. closed
