### ISSUE TITLE
Issue "No shipping options"

### ISSUE THREAD

**Issue by sultanali87** [abantecart/abantecart-src#1052]
Hello @abantecart and @BasaraABC 

@BasaraABC as you told me to upgrade to the latest version AbanteCart Version 1.2.12,  i did it, a strange error came in, when i try to place dummy order it says 
Error: No Shipping options are available. Please contact us for assistance! 
even though "default free shipping", and " default flat rate shipping" is ON. and the payment is set to COD. 
error log has a long list, i have attached it  
Please help and resolve it as soon as possible,
Thanks
 
[error log.txt](https://github.com/abantecart/abantecart-src/files/1587305/error.log.txt)
![error1](https://user-images.githubusercontent.com/34834164/34356745-6cccc2f0-ea62-11e7-99c9-4eeea200921d.jpg)

**Comment by BasaraABC** [comment]
Go to every shipping extension enabled and re-save all setting

**Comment by sultanali87** [comment]
actually only two's are installed! 
and the other's are not installed! 
should i have to install all of them ?

**Comment by BasaraABC** [comment]
No, go to Installed only open and click save

**Comment by sultanali87** [comment]
i did, still error is there!

**Comment by BasaraABC** [comment]
Ok, there are few reasons 
* something was not updated during upgrade
* cache problem - try to clear AbanteCart and browser caches to make sure session is clean.
* make sure your customer address within Locations set in your shipping method (Flat rate for example)

**Comment by BasaraABC** [comment]
Forgot to mention if you have Flat rate shipping. In 1.2.11+ you need to set cost for each location.

**Comment by sultanali87** [comment]
Thank you for quick reply, issue is resolved! 
i have to set the cost in the shipping method Flat rate, i set it to "0" now its working fine! 

i have another questing not related to this issue but related to shipping, please tell me how i can set different shipping cost for the different products ? not for the regions " worldwide or us " 

 
![flat rate](https://user-images.githubusercontent.com/34834164/34357524-adde0fe0-ea69-11e7-9bd3-a8b0a2d15c3e.jpg)

**Comment by BasaraABC** [comment]
I am kindly ask you again to communicate in forum http://forum.abantecart.com/
Bug tracker is not a place for questions- only bug reports
