### ISSUE TITLE
upgrade: critical error - content pages

### ISSUE THREAD

**Issue by sultanali87** [abantecart/abantecart-src#1053]
Hello @abantecart @BasaraABC 
today i was trying to put some information to the return policy for the web, when i hit save all the settings, a critical error occurred! 
i have attached the screen shot and the report 

AbanteCart
There has been a critical error processing your req
![error](https://user-images.githubusercontent.com/34834164/34554953-29544c3c-f151-11e7-8b6a-9609a798fc4e.jpg)
uest
SQL Error: Unknown column 'meta_keywords' in 'field list'
Error No: 1054
SQL: UPDATE abjm_content_descriptions SET title = 'Return Policy', description = 'Terms & Conditions', meta_keywords = '', meta_description = '', content = '\r\nWe accept returns on UN-used products within 7 days. Any problems with orders should be reported within 24 hours after receiving product.\r\n\r\nWe try to make returns as easy as possible. If there is a defect with a product or we made a mistake with the order, we will pay for the return shipping.\r\n\r\nShipping charges will not be refunded unless there is a defect on the product or a mistake in the order. Any damaged product must be received by us or a digital image e-mailed to us before any credits or product reshipment.\r\n\r\nSend all returns to:\r\n\r\nSSQUARE INTL Motorcycle Wears | Championship Belts\r\n\r\nAttn: Returns Department\r\n \r\nIt is recommended that you send all returns back via USPS US MAIL International Air Mail Register. Send your package insured and postage paid. There will be no credits or refunds for return shipping charges. If you request that we replace or exchange an item you will be responsible for paying the re-shipping charges. Please call or email us if you have any questions regarding returns.\r\n\r\nDisclaimer - Equipment Warning\r\n\r\nThe items sold on this website are manufactured with care and craftsmanship to provide the best quality products, degree of protection to help reduce the risks of injury. These products are not warranted to prevent injury. The user, therefore, assumes full responsibility for all risk of injuries. With time and use the materials used in these products will lose some of their effectiveness and require replacement.\r\n\r\nDisclaimer - Website Pricing\r\n\r\nWe make every effort to insure that all information is correct. We reserve the right to change listed prices without prior notice and invoice at the corrected price.' WHERE content_id = '3' AND language_id = '1' in /home/ssquarei/public_html/core/database/amysqli.php on line 109	

Report this problem to AbanteCart team (do not change email subject)

Check AbanteCart Troubleshooting Guide

Need help? Contact for support

Go to main page
Project Homepage|Documentation|Support Forums|Marketplace

================================================================

Log file tail: 
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an object that implements Countable in <b>/home/ssquarei/public_html/core/engine/view.php</b> on line <b>373</b>
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an object that implements Countable in <b>/home/ssquarei/public_html/core/engine/view.php</b> on line <b>569</b>
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an object that implements Countable in <b>/home/ssquarei/public_html/core/engine/view.php</b> on line <b>571</b>
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an object that implements Countable in <b>/home/ssquarei/public_html/core/engine/view.php</b> on line <b>371</b>
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an object that implements Countable in <b>/home/ssquarei/public_html/core/engine/view.php</b> on line <b>373</b>
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an object that implements Countable in <b>/home/ssquarei/public_html/core/engine/view.php</b> on line <b>569</b>
2018-01-04 2:37:26 - warning:  AbanteCart core v.1.2.12 count(): Parameter must be an array or an 

![error](https://user-images.githubusercontent.com/34834164/34554977-4415618c-f151-11e7-8701-c3afe3ac1aad.jpg)

**Comment by BasaraABC** [comment]
Do you have clean 1.2.12 installation or upgraded from 1.2.11 to 1.2.12?

**Comment by sultanali87** [comment]
upgrade from AbanteCart version 1.2.10, to 1.2.11 and then 1.2.12

**Comment by BasaraABC** [comment]
Looks like your database was not updated correctly 1.2.11 > 1.2.12 do you autoupdate or run manually all stuff?

**Comment by sultanali87** [comment]
there were no option to auto update it, i received a message in the Abantecart message box, i click on the link from there... and then update it.

**Comment by sultanali87** [comment]
What to do now ? Please urgent help is needed!

**Comment by BasaraABC** [comment]
When you upgrade do you have any upgrade related errors in log?

**Comment by sultanali87** [comment]
yes there is a long list of it. i will send it here!

**Comment by sultanali87** [comment]
it's a long list.. i can't paste here directly, i have attached it. Please find it
[error log.txt](https://github.com/abantecart/abantecart-src/files/1602805/error.log.txt)

**Comment by BasaraABC** [comment]
these is error after upgrade. Maybe you clean the cache and upgrade errors are gone. Restore backup and after each upgrade check the log for upgrade errors like (Cant replace file )

**Comment by sultanali87** [comment]
i do clean the cache and then clear the log as page refreshed, right away this error came in, also i try to update the other fields like privacy policy, about us, ect .. page crashed! 

2018-01-04 3:46:38 - warning: AbanteCart core v.1.2.12 Use of undefined constant INSTALL - assumed 'INSTALL' (this will throw an Error in a future version of PHP) in <b>/home/ssquarei/public_html/core/engine/language.php</b> on line <b>66</b>

**Comment by sultanali87** [comment]
actually i didn't upgrade it, i asked my hosting provider to do that, 
also how i can restore backup ? and if i do this all the products i have updated and my new clients data will be gone ? 

isn't there any other solution ?  to resolve this ?

**Comment by sultanali87** [comment]
**Brother i'm in big trouble..."as you can imagine"  please find a quick and flexible solution of it!**  other than restore it! it feels so scary! 
:(

**Comment by sultanali87** [comment]
which one is stable version ? 1.2.11 or 1.2.12 ?

**Comment by BasaraABC** [comment]
you can try solution for similar issue http://forum.abantecart.com/index.php/topic,6190.msg26473.html#msg26473
make sure to change ac_ to your table prefix

**Comment by sultanali87** [comment]
thanks for help! i have forwarded the information to the hosting provider! as soon as i get any update on it, i'll update here .

**Comment by sultanali87** [comment]
Thanks for the help! error resolved! :+1:
