### ISSUE TITLE
Order edit page - Downloads minor issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#106]
two issues on order edit page Files section:
issue 1: download attributes not aligned see screen
issue 2: missed download status
Note: checked on 1.2.2
![downloads1](https://cloud.githubusercontent.com/assets/2631910/6615363/c32e82ca-c8d5-11e4-874f-ead9bfdd0a3d.png)

**Comment by BasaraABC** [comment]
Note: when download is available for downloading ON/Off button appear in status column but it doesn't work

**Comment by abolabo** [comment]
fixed
