### ISSUE TITLE
dev: php 7.2 warnings - count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1073]
warning "count(): Parameter must be an array or an object that implements Countable"

htdocs/admin/view/default/template/pages/tool/error_log.tpl</b> on line <b>14</b>
htdocs/core/engine/view.php</b> on line <b>371</b>
htdocs/core/engine/view.php</b> on line <b>373</b>
htdocs/storefront/view/default/template/responses/checkout/cart_details.tpl</b> on line <b>2</b>

**Comment by BasaraABC** [comment]
Issue 1 and 4 not fixed.

**Comment by BasaraABC** [comment]
Issue 4 still not fixed.
Try to add and **remove** products from basket. I see issue after removing all products

**Comment by BasaraABC** [comment]
and new issue
**5.** warning: AbanteCart core v.1.2.13 count(): Parameter must be an array or an object that implements Countable in /htdocs/core/lib/layout_manager.php</b> on line <b>142</b>

**Comment by BasaraABC** [comment]
**6.**  count(): Parameter must be an array or an object that implements Countable in /storefront/view/default/template/pages/checkout/guest_step_2.tpl</b> on line <b>53</b>

**7.** warning: AbanteCart core v.1.2.13 count(): Parameter must be an array or an object that implements Countable in <b> storefront/view/default/template/pages/checkout/guest_step_2.tpl</b> on line <b>105</b>

**Comment by BasaraABC** [comment]
8. warning: AbanteCart core v.1.2.13 count(): Parameter must be an array or an object that implements Countable in /core/lib/layout_manager.php</b> on line <b>142</b>

**Comment by abolabo** [comment]
count() replaced with sizeof() in all tpl files and files inside core/engine directory

**Comment by BasaraABC** [comment]
Issue 4 again not fixed.  Same with others.

**Comment by BasaraABC** [comment]
More warnings found **count(): Parameter must be an array or an object that implements Countable**

* warning: AbanteCart core v.1.2.13 count(): Parameter must be an array or an object that implements Countable in <b>/admin/model/localisation/country.php</b> on line <b>66</b>

* warning: AbanteCart core v.1.2.13 count(): Parameter must be an array or an object that implements Countable in <b>/admin/model/localisation/zone.php</b> on line <b>64</b>
