### ISSUE TITLE
feature: resend activation link

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1075]
Settings case:
Approve New Customers: OFF (all approved by default)
**Email Activation for New Customers: ON**

We need to add a feature to resend activation link if a customer with Non-activated account tries to login.
Now if customer is too rush to login without activation or in case of mail issues - he will get "Error: Incorrect login name or password." I suggest to check if account was activated and if not show message with link
"Please Activate Your Account. Before you can login, you must activate your account with the link sent to your email address. **Resend activation link**?"

Note: we need **do not allow resend** for blocked users.

**Comment by abantecart** [comment]
This is correct. We should add this.

**Comment by abolabo** [comment]
it was a bug. fixed
