### ISSUE TITLE
Contact us form improve: email subject

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1077]
The subject in email is too common and inquiries from different customers combined to one thread in most of the email apps.
I suggest adding name to email subject or add a new subject field to form. Please also apply changes to MP.
![d2018-02-22_13-09-03](https://user-images.githubusercontent.com/2631910/36523072-6a7b210c-17d2-11e8-9e60-eccb0b341ae9.png)

**Comment by abantecart** [comment]
We need to add site name customer name. 

**[site name] enquiry from [customer name]** 

**Make sure you validate input to prevent injections with the name entered by user!**
