### ISSUE TITLE
User transaction / balance issue

### ISSUE THREAD

**Issue by bossthe** [abantecart/abantecart-src#1079]
There is something wrong with the currency exchange when balance is used. It happens when for example customer wants to pay using CAD, instead the default USD, and use balance. 

I dont know how, but it deducted more than the customer actually had, and put him in minus -$10.

I think it only checked the amount of the CAD but in USD if he got enough, but then when it deducts, it didnt exchange back to his currency, which put him in negative balance.

If you need a particular order or more info or screenshot, lmk.

**Comment by BasaraABC** [comment]
Hi. Please answer on this list:
1. AbanteCart version
2. make a screenshot of your currencies grid (Admin > System > Localizations > Currencies)
3. what is store default currency? (Admin > System > Settings > Store)

**Comment by bossthe** [comment]
1. Latest version from github sources

2. 
<img width="994" alt="currencies" src="https://user-images.githubusercontent.com/35280717/36585412-1443bc16-187e-11e8-8e01-b9d1c065175f.png">

3. Default is USD.

**Comment by BasaraABC** [comment]
Please make a screenshot with order total and available balance

**Comment by bossthe** [comment]
<img width="751" alt="transaction" src="https://user-images.githubusercontent.com/35280717/36596664-b4390a78-18a6-11e8-81ef-b38faac8fa1d.png">

<img width="526" alt="order" src="https://user-images.githubusercontent.com/35280717/36596665-b45d0e5a-18a6-11e8-99a1-17fdd5bebc23.png">

<img width="355" alt="order_details" src="https://user-images.githubusercontent.com/35280717/36596666-b47f0f14-18a6-11e8-972b-5906ca00b7a9.png">

Here you go, sorry for my delay

**Comment by BasaraABC** [comment]
From your screenshots, it is not clear what is wrong.
C$49.92 is approx. 39 USD. Where do you see an issue?

**Comment by BasaraABC** [comment]
So customer's balance is negative?

**Comment by BasaraABC** [comment]
The issue is confirmed. @abolabo  to replicate it please switch to CAD dollar and place an order with total more than customers balance. If pay with balance balance will be negative
