### ISSUE TITLE
'empty directory to extension folder' issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#108]
Pavel: f you add empty directory to extension folder BEFORE Abantecart installation, install will fail.
This is rare case, and low priority, but we need to get to it one day

**Comment by abantecart** [comment]
Thank you. We will get to it at some point

**Comment by abolabo** [comment]
i can't to solve it without functionality loss.

**Comment by abantecart** [comment]
What is the loss? Install of abantecart does not install extensions. When list of extensions is loaded (before saving to DB), need to check if config.xml is present inside of directory. If not present directory is ignored.

**Comment by abantecart** [comment]
Fixed.
