### ISSUE TITLE
currency autoupdate: some currencies set to zero

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1080]
Autoupdate currency set Canadian dollar to 0.
![2018-02-26_15-39-59](https://user-images.githubusercontent.com/2631910/36660765-e3136dcc-1b0b-11e8-8e4a-6ecec0e2526d.png)

**Comment by BasaraABC** [comment]
same with INR currency. Please fix

**Comment by abolabo** [comment]
it's restriction of 3d party service. https://www.alphavantage.co/documentation/#fx They allows only 2 call for new currency rate. But not always:/ I got rate after 5 attempts. Have not ideas except to get official subscription of their API. 
Now i added message into error log: 
`"Currency Auto Updater Info: Thank you for using the CURRENCY_EXCHANGE_RATE API! Please kindly contact support@alphavantage.co if you would like to have a higher API call volume"`

fyi. need to think about changing this calls in 2.0. I think it must be via ajax after login.
