### ISSUE TITLE
HTML Editor improve: improve Add media

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1084]
Now we allow adding only images. 
I think we need to allow to insert at least PDF and Archives links:
1. in HTML Editors
2. in objects media like Categories, Brands (now only products allow all media formats)

![media](https://user-images.githubusercontent.com/2631910/38074217-34dbdf2c-3358-11e8-92ab-f6f928f15b57.png)

**Comment by abantecart** [comment]
Moved to 2.0
