### ISSUE TITLE
admin: Blocked loading mixed active content

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1085]
![2018-03-29_13-55-01](https://user-images.githubusercontent.com/2631910/38074441-f2dcca72-3358-11e8-909c-e1890ea1f183.png)

**Comment by abolabo** [comment]
looks like some ff bug. I opened devtools and see requested URL for this font is under https.
 Chrome does not show this warning.

**Comment by BasaraABC** [comment]
Yes, this is latest Firefox 59.0.1

**Comment by abantecart** [comment]
For some reason font is not loaded with HTTPS. Check if font is loaded with correct protocol

**Comment by BasaraABC** [comment]
Closed. I think it was related to HTTP cache.
