### ISSUE TITLE
Product Option value is converted into numbers

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1087]
Hi core devs, I was able to reproduce the issue posted here: http://forum.abantecart.com/index.php/topic,6404.0/topicseen.html
Based on my debug, it's caused by line 634 in this file: https://github.com/abantecart/abantecart-src/blob/master/public_html/admin/controller/responses/product/product.php

Please fix it as i believe many users will use any kind of text as the value. Thanks

**Comment by handoyo** [comment]
Only use .  on the last text just like the previous poster did. I'm using Windows 7 and 10 btw.

**Comment by abolabo** [comment]
Hi. 
As i see on your first screenshot you operating with selectbox as option value.
Please clarify how do you did that?
Can you inspect your html-code and give us raw html of selected option name and value? Is some hidden signs presents there (such as &#123 etc)?

**Comment by handoyo** [comment]
Hi abolabo, there are no hidden sign presents there. 

![image](https://user-images.githubusercontent.com/225439/38192431-062ad042-3697-11e8-8d53-2ce0032f2b0b.png).

This is the global attribute i create:
![image](https://user-images.githubusercontent.com/225439/38192472-43de6f34-3697-11e8-8e46-dd4a659c9857.png)


Seems to me the html_entity_decode cause the issue here. I removed the html_entity_decode and it's showing correctly.

**Comment by abolabo** [comment]
![image](https://user-images.githubusercontent.com/1264239/38194838-bb3faa30-3682-11e8-9137-a2a29e9706eb.png)
I do not see the way to paste selectboxes without parent attribute.
how do you did that? i see that fields are SELECTBOXES on your screenshot. how?

**Comment by BasaraABC** [comment]
The issue is confirmed. Visible only if you add pre-defined Global Attribute selectbox with values
