### ISSUE TITLE
dev: php 7.2 warnings - create_function() is deprecated 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1088]
DEPRECATED: AbanteCart core v.1.2.13 Function create_function() is deprecated in /htdocs/extensions/default_twilio/core/lib/Services/Twilio/Resource.php</b> on line <b>93

**Comment by abolabo** [comment]
3d party warning. move this to 2.0 ?

**Comment by abantecart** [comment]
default_twilio is included in AbanteCart, we need to fix this. 
Check for updated library in Twilo and update 
https://www.twilio.com/docs/libraries/php

**Comment by BasaraABC** [comment]
1. if you update library please change extension version
2. Looks like the update is not work I get "Twilio error: [HTTP 401] Unable to create record: Authenticate. Error Code:20003"
