### ISSUE TITLE
rare issue: missing extension folder

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1089]
If for some reason extension installation fail we have broken record in the All Extensions Grid.
## Issue: this record cant be removed 

![2018-04-02_13-36-01](https://user-images.githubusercontent.com/2631910/38186088-5925cf3e-367b-11e8-9f9e-c06fb2dc546a.png)

**Comment by abolabo** [comment]
what installation mode?

**Comment by abantecart** [comment]
What do we need to discuss? 

This will happen in config file is removed or folder is not an extension. 

If we cannot delete, we should hide the icon.

**Comment by abantecart** [comment]
Can we ignore items, that are not extensions? 
Error, should only be shown if extension is installed. Otherwise, directory or broken extension, should be ignored.
