### ISSUE TITLE
negative zero balance

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1091]
For the unknown reason, zero balance is shown as **-0**
![2018-04-03_16-25-22](https://user-images.githubusercontent.com/2631910/38241205-d1c749fa-375b-11e8-991a-5ad087357761.png)

**Comment by abantecart** [comment]
This has to be fixed. I noticed that as well.

**Comment by BasaraABC** [comment]
Storefront fixed but the issue is visible in admin (customer account page)
![bug](https://user-images.githubusercontent.com/2631910/38288183-401a51ac-37f9-11e8-9741-ea9ce7dfea06.png)
