### ISSUE TITLE
Add post code into store settings

### ISSUE THREAD

**Issue by abolabo** [abantecart/abantecart-src#1092]
Need to add store post code into Settings -> Store Details. Some extensions will be use it for api-requests etc

**Comment by BasaraABC** [comment]
Also good to add Working Hours, few phone numbers/emails (most stores have few departmens)

**Comment by abantecart** [comment]
Zip code can be a separate field, but the the rest, we should add an HTML editor area for this details. Does not have to be separate field for each data point.

**Comment by BasaraABC** [comment]
resolved in 1.2.16
