### ISSUE TITLE
improve: page not exist

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1097]
If page not exists we need to show valid error (404 not found ) and **do not write anything to error log** or to messages
![2018-04-09_14-44-36df](https://user-images.githubusercontent.com/2631910/38485758-2430a4e0-3c05-11e8-97c7-8c6b27a753a8.png)

**Comment by BasaraABC** [comment]
2.0?

**Comment by abantecart** [comment]
Moved to v2.0
