### ISSUE TITLE
Bug with SAVE button

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#110]
After click on SAVE button in admin - the saving process never completed.
-----------
Please note: issue visible from time to time in all browsers, some users report this problem, I can see this issue in 1 of 15-20 times Chrome (more rare in FireFox) when save product and randomly in any admin section
![saving](https://cloud.githubusercontent.com/assets/2631910/6864583/46bfd640-d496-11e4-9d6a-3218a0adb799.png)

few user reports: 
http://forum.abantecart.com/index.php/topic,3101.msg13112.html#msg13112
http://forum.abantecart.com/index.php/topic,3125.msg13238.html#msg13238
We can not ignore this.

**Comment by BasaraABC** [comment]
One more user confirm issue with Chrome http://forum.abantecart.com/index.php/topic,3449.0/topicseen.html

**Comment by BasaraABC** [comment]
Issue is more critical http://forum.abantecart.com/index.php/topic,3467.0/topicseen.html

**Comment by abantecart** [comment]
This is fixed with commit:
https://github.com/abantecart/abantecart-src/commit/b750dcfce3b5d625c637007d3aad612b1d634923

More about this issue:
https://github.com/twbs/bootstrap/issues/14450
