### ISSUE TITLE
mobile: firefox browser - write review form too large

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1111]
![iss3](https://user-images.githubusercontent.com/2631910/38802103-c8b893a2-4195-11e8-8df3-76c04eb30fec.png)

**Comment by abantecart** [comment]
Is this emulator or real phone. I get no problem in this screen resolution. 
<img width="419" alt="screen shot 2018-05-24 at 9 15 46 pm" src="https://user-images.githubusercontent.com/1239995/40521062-a8269484-5f97-11e8-8827-e6130e74d687.png">

**Comment by abantecart** [comment]
I think the problem is with google recaptcha.

**Comment by BasaraABC** [comment]
Please check live at dev06.*****.net/abc1213_m05d25/ 
Pick any product page. The test was on Browserstack

**Comment by abolabo** [comment]
same for me. all works fine, even on dev06

**Comment by abantecart** [comment]
Biris, can you please recheck this one?
