### ISSUE TITLE
embed and Jquery 3

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1117]
Embed is not work if web site use jQuery 3
`TypeError: a.indexOf is not a function`
Forum post http://forum.abantecart.com/index.php/topic,6516.msg27466.html#msg27466
See if this help you to fix https://stackoverflow.com/questions/38871753/uncaught-typeerror-a-indexof-is-not-a-function-error-when-opening-new-foundat

Also check this guide maybe we can upgrade to 3.0 https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin

**Comment by Luxinbag** [comment]
Hi all,
First, thanks for your work !
When do you think this update 1.2.13 come in ?
Thanks in advance.
Franck

**Comment by abantecart** [comment]
You can check dates in here 
https://github.com/abantecart/abantecart-src/milestones

**Comment by Luxinbag** [comment]
Thanks, and is there a beta version?
I don't have to use it in production since may 1 but it permit to work and test before ;-) and I don't know how to downgrade the jquery version!
thanks
Franck

**Comment by abolabo** [comment]
not an AbanteCart bug. It's jquery compatibility issue.
To solve just place <script src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script> before embed code on your page.
