### ISSUE TITLE
embed: 'SAMEORIGIN;' is not a recognized directive. 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1119]
browser console report an error: Invalid 'X-Frame-Options' header encountered when loading
![2018-04-23_14-51-46](https://user-images.githubusercontent.com/2631910/39113474-fd1a067e-4705-11e8-80d9-d9e27d067038.png)

**Comment by abolabo** [comment]
header removed

**Comment by BasaraABC** [comment]
More warning and errors in console.
error: Refused to execute script from 'http://****/abc1213_m07d05/index.php?rt=r/embed/js/addtocart&product_id=113&quantity=1' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

warning:
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://****/abc1213_m07d05/index.php?rt=r/embed/js/addtocart&product_id=113&quantity=1&ABC_TOKEN=cidh852odr96ce8pqmjgg4rha1 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

![2018-07-05_14-03-25](https://user-images.githubusercontent.com/2631910/42307407-86c45bba-805c-11e8-8560-09029719641f.png)

warning visible here http://embedac.blogspot.com/2018/07/embed-1213-no-header.html
