### ISSUE TITLE
Cart issue with Multi-store

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#112]
1. Create new product available only for Store2.
2. Log in to Store2 and add to cart
3. Logout in Store2
4. then Login to Store1 (default)
5. ISSUE: product added to cart in store2 is visible in shopping cart for Store1 <strong>(please note - this product is not available for Store1)</strong>
http://forum.abantecart.com/index.php/topic,2969.0.html 
issue visible in 1.2.2

**Comment by abolabo** [comment]
cannot to replicate. need details. i don't understand what customer login in store1 (see #4). Abc allows customer per store, but can't find how to register the same customer in both stores.

**Comment by BasaraABC** [comment]
Steps to replicate:
1. Create second store2
2. Create new product available only for store2
3. Visit store2 SF
4. Register new user in store2 and login
5. Add to cart new product (created in step 2)
6. Logout in store2 SF
7. Visit default store (store1) 
8. Login with store2 user account credentials  (created in step4)
9. ISSUE: product available for store2 only will be visible in store1 cart
Note: I do this today on latest 122 installation 
![stores](https://cloud.githubusercontent.com/assets/2631910/7628551/e63e470a-fa4e-11e4-97e8-41c6d15fed1c.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Critical error when I try to login to store1 (steps same as mentioned in previous post)
![nmu](https://cloud.githubusercontent.com/assets/2631910/7648555/70b96832-fb0e-11e4-8d82-11644e1fbaa9.png)

**Comment by BasaraABC** [comment]
Issue fixed but warning is still in log

2015-05-15 5:17:12 - warning: AbanteCart core v.1.2.2 array_keys() expects parameter 1 to be array, boolean given in <b>****/abc122_m05d15fix2/core/lib/customer.php</b> on line <b>531</b>
2015-05-15 5:17:12 - warning: AbanteCart core v.1.2.2 Invalid argument supplied for foreach() in <b>****/mnt/drive1/home/beremenko/htdocs/abc122_m05d15fix2/core/lib/customer.php</b> on line <b>532</b>

**Comment by abantecart** [comment]
Warning is fixed.
