### ISSUE TITLE
admin: read message counter issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1126]
When user click on notifications in the header (admin messages) usually unread messages counter is decresed by 1 but if read few messages it stop decreasing.

To replicate issue you should have 3-4 unread messages. Try to click 2-3 times
<img width="325" alt="2018-05-08_14-47-44" src="https://user-images.githubusercontent.com/2631910/39744547-d61c6150-52ce-11e8-9013-d864ef107efe.png">

**Comment by abolabo** [comment]
needs steps for reproduce.
Note: we have periodical updater for this by ajax.

**Comment by BasaraABC** [comment]
It doesnot work. After first message reading the counter show less messages count correctly, on next message read counter do not changed. I check with 2 unread messaged

**Comment by BasaraABC** [comment]
![2018-07-02_13-58-44](https://user-images.githubusercontent.com/2631910/42149524-a600316a-7e00-11e8-9c9e-51993f9be4d1.gif)

**Comment by BasaraABC** [comment]
Reopened. Counter decrease not work if close modal with click on outside. 
![2018-07-13_13-53-24](https://user-images.githubusercontent.com/2631910/42676973-5ca55db8-86a4-11e8-86d0-7768ee94527c.gif)
