### ISSUE TITLE
CSV import wizard

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1127]
After success task import the product is not added to database and error in log "Missing images data array for products."
To replicate try attached comma separated csv
<img width="864" alt="sdf" src="https://user-images.githubusercontent.com/2631910/40051983-d368c08c-5866-11e8-99a3-d3b87057d126.png">

[comma.csv.zip](https://github.com/abantecart/abantecart-src/files/2004446/comma.csv.zip)

**Comment by abantecart** [comment]
This one is in the queue. I say 2-3 days.

**Comment by abantecart** [comment]
I checked this issue. 
I think import works as it should. 

No images are provided in the import, that is why you see an error with the image. 

Product is still created. 
Because category is not provided, you can not find it.

**Comment by BasaraABC** [comment]
I recheck again. New imported product is not visible in Catalog -> Products so bug here

**Comment by abantecart** [comment]
Fixed.

**Comment by BasaraABC** [comment]
@proteaapteek you need to replace one file to apply fixes.

**Comment by proteaapteek** [comment]
It is creating a new item with every import.
We just want to update prices and quantity and not add new items.
I've run it 2 times and every time I got the item added as new item. I did not delete it after first attempt to see if it is something with the name. We use the SKU to update.

**Comment by BasaraABC** [comment]
You need to set "update" checkbox. 

Or please read documentation how to update with AbanteCart internal csv format https://abantecart.atlassian.net/wiki/spaces/AD/pages/15007876/Import#Import-Example1:Updateproducts

**Comment by proteaapteek** [comment]
![import settings](https://user-images.githubusercontent.com/39330881/40489333-25193624-5f69-11e8-98ad-c1e7a52688c8.jpg)
I've done it like this.

**Comment by abantecart** [comment]
This is fixed in #1128

**Comment by proteaapteek** [comment]
IT is ADDING stock!!!!
2018-05-25 6:21:53 - Warning: Missing images for products.

2018-05-25 6:21:53 - Processing record for product VITAL SELENIUM COMP 200UG 100 1 6001464148592 .
2018-05-25 6:21:53 - Created product 'VITAL SELENIUM COMP 200UG 100 1' with ID 25748
2018-05-25 6:21:53 - Warning: Missing images for products.
2018-05-25 6:21:53 - Processing record for product HUMEX K CAPS 600MG 60 1 6009829050245 .
2018-05-25 6:21:53 - Created product 'HUMEX K CAPS 600MG 60 1' with ID 25749
2018-05-25 6:21:53 - Warning: Missing images for products.

I done it with the update if existing. and nou I have about 4200 items added that i did not want to do.

**Comment by proteaapteek** [comment]
Good day.
I've done the demo file I've given. It updated it. But as our online shop items is only at this stage 181 items and the physical shop have about 4200 items. When i did the price udpate now it added all the stock in the file and dit not update only the ones in tha online database. I have a backup of the site and tried to restore it, but all 4200 items is still there.

www.proteaapteek.co.za/shop
I want to update only items already loaded and not add stock on updates. 
[PROTEA.txt](https://github.com/abantecart/abantecart-src/files/2038279/PROTEA.txt)
There is our complete stock file. I will add stock on a daily basis manualy to get pictures loaded as I must first source it as I'm adding it.
How do I no get rid off all the stock online I do not want?

**Comment by BasaraABC** [comment]
If I understood you correctly, please move discussions to forum.
Bugtracker is for bug reporting only.
