### ISSUE TITLE
API 'latest' issue

### ISSUE THREAD

**Issue by cydh** [abantecart/abantecart-src#1129]
**Version**
a9df918cee40cc7f32e68ee136a683dc30632f5c

**Description**
1. When using API `a/product/latest`, it doesn't give `price` in product list.
2. The cache string is kinda evil, so if using this API, the result are *never* be updated
```php
		$cache_key = 'product.latest.' . $limit
				. '.store_' . (int)$this->config->get('config_store_id') . '_lang_' . $this->config->get('storefront_language_id');
		$cache = $this->cache->pull($cache_key);
```

**Solution**
1. A little this for this
```Diff
 public_html/storefront/model/catalog/product.php | 1 +
 1 file changed, 1 insertion(+)

diff --git a/public_html/storefront/model/catalog/product.php b/public_html/storefront/model/catalog/product.php
index 19bec47..cb5687e 100755
--- a/public_html/storefront/model/catalog/product.php
+++ b/public_html/storefront/model/catalog/product.php
@@ -748,6 +748,7 @@ class ModelCatalogProduct extends Model{
 					m.name AS manufacturer,
 					ss.name AS stock,
 					pd.blurb,
+					" . $this->_sql_final_price_string() . ",
 					" . $this->_sql_avg_rating_string() . ",
 					" . $this->_sql_review_count_string() . "
 					" . $this->_sql_join_string() . "
```

2. In my use, I disable the cache. I used to add datetime string `date("Ymd_H")` so at least the cache will be same every hour, but idk how it'll affect the storage for storing cache.

**Comment by abantecart** [comment]
Thank you for pointing this out. I have pushed a fix. 

There is no issue with the cache itself as it is cleaned on any update to the data in the admin. 
If you do changes directly in the database, you need to clear cache manually. 
This is a normal process.

**Comment by cydh** [comment]
ok, thank you :+1:
