### ISSUE TITLE
admin SSL enabled detection failture

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1130]
If in the store settings SSL url is non-secure (see screenshot) the administrator still get a message to redirect to HTTPS admin (https://)
![2018-06-04_18-29-59](https://user-images.githubusercontent.com/2631910/40915444-50e8905e-6826-11e8-8b17-9df6cfd69976.png)

**Comment by abantecart** [comment]
I think we need have different message in this case.
"Warning" icon and color:
You are not using secure connection. It is recommended to have SSL enabled and configured. Read more (Link to online doc using a doc key.) 
https://abantecart.atlassian.net/wiki/spaces/AD/pages/5832828/Store+URLs+SSL

**Comment by goatlady102** [comment]
I comment -  why is http:  even an option within the Secure Store URL field?

**Comment by abantecart** [comment]
I answer - In case you do not have SSL configured. Mostly locals or development servers
