### ISSUE TITLE
Home page products block and HTML cache issue

### ISSUE THREAD

**Issue by afrianviolet** [abantecart/abantecart-src#1131]
Enabling the "HTML cache", the special price to customer groups will not display properly. Please refer to this topic : http://forum.abantecart.com/index.php?topic=6657.msg28024#msg28024

**Comment by afrianviolet** [comment]
Hi
1. 1.2.12
2. Home page and all the pages displaying product listing.
Thank you!

**Comment by BasaraABC** [comment]
Are you sure you have a 1.2.12 version? Is this a clear installation or upgrade from 1.2.11?

**Comment by afrianviolet** [comment]
It should be 1.2.13 which is download 1 month ago from https://github.com/abantecart/abantecart-src/branches. It is clear installation.
Thank you!

**Comment by BasaraABC** [comment]
1.2.13 is not released. Anyway I cant replicate the issue in 1.2.12 or 1.2.13
Could you provide more screenshots with product regular price, special discounts and listing with bug?

**Comment by afrianviolet** [comment]
Please see the attached picture.
1. I have two customer Ryan and User A. Ryan is VIP member with 8% off, User A is general member with 5%
2. Go to backend admin to enable HTML cache
3. Clear the html-cache (backend admin, System->Cache)
4. Login Ryan and refresh browser (chrome), shows the VIP price. 
5. Login User A and use IE to open first page / home page, still shows the VIP price. (incorrect, should show general member price).

![compare01](https://user-images.githubusercontent.com/28209666/41292061-006241c0-6e84-11e8-943b-bfb82c382d4d.jpg)

**Comment by BasaraABC** [comment]
Thank you. Issue confirmed in home page blocks.

**Comment by afrianviolet** [comment]
This issue also happens for all the product listing pages.

**Comment by BasaraABC** [comment]
Hi, afrianviolet. I have clean 1.2.12 installation and I see issue only in the Home page. Let see what developer find

**Comment by afrianviolet** [comment]
Yes! You are right. I can't replicate it at other pages this time. Once I discover it at other pages, I will inform you.
Thank you!
