### ISSUE TITLE
Edit order in backend has problem for member price.

### ISSUE THREAD

**Issue by afrianviolet** [abantecart/abantecart-src#1132]
I have tried to add a product to customer's order. But abantecart cart doesn't allow to modify the product unit price or return the membership discount price. So that the price is incorrect for this case. Could abantecart modify it to allow to modify the price or get the membership price of the product?
Thank you!
Please refer to this topic :  http://forum.abantecart.com/index.php/topic,6649.0.html

**Comment by BasaraABC** [comment]
Hello. Bug tracker is for bugs only. Features discussions or suggestions post in forum only
