### ISSUE TITLE
RL downloads: show linked products

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1135]
We need to show linked products in case Download file attached/added to several products. 
Discussion http://forum.abantecart.com/index.php/topic,6703.msg28165.html#msg28165
![2018-06-26_18-50-42](https://user-images.githubusercontent.com/2631910/41909755-0ce6ba2c-7972-11e8-88ea-8bc753e724da.png)

**Comment by BasaraABC** [comment]
Resource library view from the product show some checkbox. What does it mean? Is this button to map file or indicator about already mapped state? 
Media library do not show linked correctly please see screenshot

![uplod](https://user-images.githubusercontent.com/2631910/42076268-a530f382-7b9e-11e8-8498-a0f70a366cd9.png)


I think correct view should be like in images
![2018-06-29_13-20-02](https://user-images.githubusercontent.com/2631910/42076461-74c90ca6-7b9f-11e8-9864-81c78e325352.png)

**Comment by abolabo** [comment]
no. downloads of products is not the same downloads from RL. Icon about mapping related to inner resource mapping of RL, not  to product downloads. On this page we use resources of RL as standalone. i think we need to improve it in the 2.0. But it's ok for now

**Comment by abantecart** [comment]
Can we add text fo the icon to clarify the action?

What do we need to discuss here? If there is no bug and only improvement needed, we can do this in next release.

**Comment by BasaraABC** [comment]
> What do we need to discuss here?
To discuss: why we RL window opened from product can not show same data in RL opened from Media Library page?

To @abolabo . Your fix do not work at all. "Download file" attached to two products, but in RL this is not visible.

**Comment by abolabo** [comment]
@BasaraABC  Mapping resource-to-downloads is not the RL-mapping. 
We cannot to define how many standalone resources used yet. 
Let's do it in 2.0

**Comment by BasaraABC** [comment]
moved to internal tracker
