### ISSUE TITLE
Invoice page doesn't show full order history.

### ISSUE THREAD

**Issue by Tishbyte** [abantecart/abantecart-src#1136]
Greetings,
I ran into an issue in which the full order history doesn't show in the invoice page on the storefront.
I included images and it can be seen that on the admin page all of the history is there while on the storefront it only shows the oldest order history.
I have checked in the database and it all shows up there. I also tried manually displaying the info through a loop in the storefront/view/account/invoice.tpl file, but to no avail.
I have also cleared the local cache, the website cache, and tried different system cache configurations, all to no success.
![capture](https://user-images.githubusercontent.com/29070637/42240008-b2e55954-7eba-11e8-984c-70a13432d738.PNG)
![capture1](https://user-images.githubusercontent.com/29070637/42240009-b2fe99aa-7eba-11e8-8d25-459de88a1932.PNG)

**Comment by BasaraABC** [comment]
Check the customer notified column. If set to no this mean record was only for internal use (for admin only). If you want to show it for customer next time when you add comment to order click Notify customer
