### ISSUE TITLE
RL: limit products name chars

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1139]
Please limit products name chars in resource library
<img width="1180" alt="2018-07-13_14-20-43" src="https://user-images.githubusercontent.com/2631910/42678142-3cdad3e2-86a8-11e8-8bbf-8e4550bac3d0.png">

**Comment by abolabo** [comment]
cannot to replicate. Name is already cutted

**Comment by BasaraABC** [comment]
Try to rename your product to "亂數假文產生器Chinese Lorem Ipsum. 我要約 字的假文。 北得庭資頭. 目車沒世好道環小書年地中？等觀那影這夠麼小證前也岸業支相年不生。 "
