### ISSUE TITLE
Issue on Retina Displays

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#114]
Users report issue on retina display - Close button is not visible
see http://forum.abantecart.com/index.php/topic,3406.msg14576.html#msg14576
![how_to_unselect_from_the_list](https://cloud.githubusercontent.com/assets/2631910/6978479/d535c274-d9fd-11e4-93b6-f5dfcce42b13.png)

**Comment by abolabo** [comment]
fixed by replacement of image sprite by content: "X"; css property
