### ISSUE TITLE
quick wizard js warnings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1141]
1. if start wizard in HTTPS page next warning shown for wizard images:
   * Mixed Content: The page at 'https://localhost/index.php?rt=setting/setting/details&store_id=&s=admin' was loaded over HTTPS, but requested an insecure image 'http://www.abantecart.com/images/partners/avatax-trial-750x400.jpg'. This content should also be served over HTTPS.
   * same for cardconnect image

2. After wizard completed and closed I see warning in chrome
    * [DOM] Found 2 elements with non-unique id #settingFrm: 

<img width="1273" alt="2018-07-16_14-34-46" src="https://user-images.githubusercontent.com/2631910/42747248-dbc605bc-8905-11e8-9c59-727381d63f28.png">

**Comment by abantecart** [comment]
Fixed. Warning in Chrome I cannot reproduce.
