### ISSUE TITLE
dev: automatic tax and Tax Exemption

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1142]
1. please remove "w" char from the account edit page
![2018-07-16_14-49-59](https://user-images.githubusercontent.com/2631910/42747744-d0366c62-8907-11e8-8080-ea1a61d4612f.png)

2. When Tax Exemption code entered the tax calculation stop working (no matter is code valid or not approved yet).

**Comment by abolabo** [comment]
can you replicate this and inspect w-letter in browser dev-tools? i can't

**Comment by BasaraABC** [comment]
first issue is fixed the second issue is **Not fixed**.
Enter any tax exemption certificate number and taxes stop working.

<img width="973" alt="2018-08-14_18-28-44" src="https://user-images.githubusercontent.com/2631910/44089326-94ba7cb4-9ff0-11e8-9eb9-8ac494d72a30.png">
