### ISSUE TITLE
sys_temp_dir no value issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1146]
Most of the shared hosting have **sys_temp_dir** without any value. This affect export, extension' installation, upgrade installation, backup...etc 
Also adding it to php.ini is usually prohibited and have no effect.
Solution to discuss: if sys_temp_dir has not any value use **upload_tmp_dir** or some folder in AbanteCart installation. 
<img width="534" alt="2018-07-19_20-44-41" src="https://user-images.githubusercontent.com/2631910/42946381-eb56a6ee-8b94-11e8-8711-52ae75bbeb5d.png">

**Comment by abolabo** [comment]
i cannot find usage of this directive in abc-code. We use http://php.net/manual/en/function.sys-get-temp-dir.php function to get path of that directory and it always returns correct value.

Need more details about affecting of that

**Comment by BasaraABC** [comment]
It is related to "Error: cannot to pack" or cant unpack errors - when we decompress or compress  tar.gz file (for example extension installation)

**Comment by BasaraABC** [comment]
Unfortunately  solution will not work for most shared hostings due to _ini_set() has been disabled_

**Comment by BasaraABC** [comment]
moved to internal tracker
