### ISSUE TITLE
quantity discount & special issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1147]
Customer logged in with in group *New*
HTML cache *OFF*
Display prices with Tax *ON*

Take a note few promotions applied to product: special and quantity discounts
![2018-07-20_15-28-42](https://user-images.githubusercontent.com/2631910/42992182-063b01c4-8c32-11e8-868b-53d6002438ce.png)

**Comment by abolabo** [comment]
i think it's not a bug.
You already set special price at $8 (see screenshot). 
What another discount?
Discount works only non-special products.

**Comment by abantecart** [comment]
Generally, promotion can be applied on special products.

**Comment by BasaraABC** [comment]
At quantity 10 should be price $2.00

**Comment by BasaraABC** [comment]
Looks like was cache problem. Cant replicate any more on 2 installs
