### ISSUE TITLE
Liqpay v1.0.2 - issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#115]
Liqpay v1.0.2 tested on latest AbanteCart 1.2.2
Bug1: After click on checkout confirmation button - error occurred please see screenshots
--------------------------------------
![liqpay-bug1](https://cloud.githubusercontent.com/assets/2631910/7003949/004983be-dc8e-11e4-8aca-ac8492de66a9.png)

-------------------------------------------------------------
-------------------------------------------------------------
Minor issue: Absent help notes for settings
-------------------------------------------------------------
![liqpay-bug2](https://cloud.githubusercontent.com/assets/2631910/7003948/00484cd8-dc8e-11e4-9240-9c46c3497817.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Liqpay work now but Order Status setting is ignored please see screenshot
![liqpay3](https://cloud.githubusercontent.com/assets/2631910/7064502/52c48a6a-ded9-11e4-9ad4-266f02fa0fac.png)
Also I can not check "Test Mode" setting due to my liqpay account limitations.

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
can not create test transaction. Liqpay did not sent SMS.
