### ISSUE TITLE
Add Product To Order doesn't work.

### ISSUE THREAD

**Issue by Tishbyte** [abantecart/abantecart-src#1157]
I ran into an issue in which when I try to add a product to an order, it displays the windows where you can select the options and the quantity, but then it simply redirects to the order list page without making any changes.

AbanteCart 1.2.12 (It wasn't working in 1.2.11 either)
The products are ordinary, they have nothing special about them. There is only one store.
I did modify one core file, but it doesn't work without that change either.
I downloaded the core and admin files from the repository and uploaded them, but that didn't change anything.
My guess is a database issue, but I don't really know how to check for that.
No errors appear with this.

Changing the quantity does work, but if I try adding a new product or changing a product with the little window that appears (center of the screen and the background gets dimmer, kinda like a lightbox) then it doesn't change anything.

I did a little bit of testing and found that it's skipping steps when checking the Network through the Chrome debugging tools.
The working process (the Abantecart demo) shows these steps here:

http://demo.abantecart.com/index.php?rt=sale/order/update&order_id=17&product_id=118&s=demo_admin&token=mVxaFejkCmYO5Npx0o7ffXv9gipMD9HI
http://demo.abantecart.com/index.php?rt=sale/order/recalc&order_id=17&s=demo_admin&token=mVxaFejkCmYO5Npx0o7ffXv9gipMD9HI
http://demo.abantecart.com/index.php?rt=sale/order/details&order_id=17&s=demo_admin&token=mVxaFejkCmYO5Npx0o7ffXv9gipMD9HI

And then it simply goes on through a bunch of JavaScript and CSS requests.
While the results for the not working process:

https://3cdog.net/index.php?rt=sale/order/update&order_id=628&product_id=1490&s=(details removed)
https://3cdog.net/index.php?rt=sale/order&s=(details removed)

And then it does the rest of the CSS and JavaScript requests.
Again, there are no errors in the logs or anywhere else that initiate when this happens.

Based off of this info, are there any files you recommend I look at?
I can get more details/screenshots on request and if access is necessary, then I might be able to arrange something.
Any help is appreciated.

**Comment by BasaraABC** [comment]
Hello. Start from compare your files and source. Download source archive with your version https://github.com/abantecart/abantecart-src/releases
unarchive and use some tools like https://www.scootersoftware.com/download.php to quickly compare the folders with AbanteCart files.

If you are sure it is database related install new fresh installation in subfolder and test order edit.

**Comment by Tishbyte** [comment]
Alright,
I made a fresh install of AbanteCart on a subdomain and there everything worked fine, so it isn't a database issue.
Afterwards I did a directory/file check using the suggested software and tried deleting/changing different files until I got to something. I was very sure that it was some of my own custom files, but it actually turned out that it was a different file altogether.
Turns out that the Enhanced Option Pricing Display With Link Pro extension was to blame. After temporarily deleting it the functionality came back and other things I didn't know were there started working (like clicking on the customer's name from Order Details does things)

In this situation, do I simply contact the maker of the extension to figure out the issue?
Thanks so much for helping me find the issue!

**Comment by goatlady102** [comment]
Hello Tishbyte,

Are you a client of Elijah Bozin ?  He posted on our support board earlier this week something similar.  
The solution was to upload the correct version of the extension for your AbanteCart version.  
AbantecartCart Version(s) 1.2.10-1.2.12 use Enhanced Option Pricing Display With Link - Pro v1.2.2.2

We are the extension writers for Enhanced Option Pricing Display.  There are links within your extension to the support system that we provide for all of our extensions.  As well as to our manuals so you can always check on the versions.

Extension providers in the Market Place are always the ones you should contact about an extension they provide.  We can't help you, if you don't contact us.  We support our extensions even if they were provided to you by a different webmaster -  but we do need to be able to verify that you were a purchaser of the extension or someone purchased it on your behalf -  in other words that you have a legitimate copy of our extension.  We may ask for an invoice number to verify this.

The Support Team
We Hear You 2, Inc.  (WHY2)
