### ISSUE TITLE
html resource as store logo

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1158]
HTML resource added as store logo return error in log
2018-08-15 8:15:00 - App Error:  AbanteCart core v.1.2.13 Error: Cannot get image size of file htdocs/resources/100253. File not found or it's not an image!

To replicate copy svg code from here https://codepen.io/anaisampaio/pen/tGuDo

<img width="575" alt="2018-08-15_13-17-33" src="https://user-images.githubusercontent.com/2631910/44134165-bacecf84-a08d-11e8-913e-c6baf6bbd0ad.png">

**Comment by abolabo** [comment]
![image](https://user-images.githubusercontent.com/1264239/44195416-a9e36b80-a141-11e8-997b-f6641d32267c.png)

??

**Comment by BasaraABC** [comment]
I see issue in Chrome 68 and error in log in any browser after SF visit
