### ISSUE TITLE
smtp improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1162]
SMTP mail require review and improvements with specific conditions.

Some possible workaround:
* Type of Encryption: (TLS/SSL/No Encryption)
* SMTP Authentication: Whether to use SMTP authentication when sending an email (True/False).
* Disable SSL Certificate Verification: Yes/No
* From Email Address: The email address to be used as the From Address when sending an email. Note: we have Default sender setting in the Form manager extension. I thing we should deprecate it and add new setting to System > Settings > Mail

Consider to add some Debug mode to see more detailed info in log if mailer fail

**Comment by abantecart** [comment]
Improvement will be done in a later version.
