### ISSUE TITLE
IM: incorrect message text

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1167]
If IM enabled and customer change phone number or first name the notification received about "Your account login name was changed to testemail@email.com"

To replicate set Require Login Name to **OFF** in System > Settings > Checkout
![2018-10-04_15-14-57](https://user-images.githubusercontent.com/2631910/46461482-f7e32a00-c7e8-11e8-980f-150ceb3d274b.jpg)

**Comment by abolabo** [comment]
fixed. mail will be sent only after login changing

**Comment by BasaraABC** [comment]
It is not a FIX. Please do not remove features.
You should send message "Your account details were changed"
