### ISSUE TITLE
email change validation in admin

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1168]
Do not allow administrator to change customer's account email if it is already registered.
![2018-10-12_20-19-12](https://user-images.githubusercontent.com/2631910/46871715-5a2cd200-ce5c-11e8-8e44-9a79f93d59d0.jpg)

**Comment by abantecart** [comment]
I think email editing should be allowed. In some cases emails can be incorrect, invalid or requested to be changed by customers.
What we need to add is a validation of new email to be unique.

**Comment by abolabo** [comment]
fix added into 2.0
