### ISSUE TITLE
add Product Listing page to layout

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1169]
see 2.0 for details

**Comment by abantecart** [comment]
Added layout for product listing page. NOTE: There is no upgrade SQL only new install

**Comment by BasaraABC** [comment]
A lot of default blocks are missing. See screenshot
<img width="2096" alt="layout" src="https://user-images.githubusercontent.com/2631910/54201751-0274be80-4501-11e9-87b9-907bdaab9ba7.png">
