### ISSUE TITLE
SF Telephone field - missed required mark

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#117]
Please add required mark to the telephone field on account edit section (storefront).
see screen
![telephone](https://cloud.githubusercontent.com/assets/2631910/7046001/11ac2b02-de2d-11e4-847f-e5f4d52f3be8.png)

**Comment by abolabo** [comment]
fixed by https://github.com/abantecart/abantecart-src/commit/c51382b62e3cd603e837b0d9b4a7e603142f8a2d
