### ISSUE TITLE
Parcelforce 48: missing 3 language definitions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1170]
Missing 3 language definitions
http://forum.abantecart.com/index.php/topic,7048.0/topicseen.html

<img width="533" alt="screen shot 2018-11-05 at 15 11 08" src="https://user-images.githubusercontent.com/2631910/47985694-12246680-e10d-11e8-808c-5e529c619169.png">
<img width="400" alt="screen shot 2018-11-05 at 15 11 17" src="https://user-images.githubusercontent.com/2631910/47985695-12246680-e10d-11e8-9f09-b57da0e708b3.png">

**Comment by ashtonm999** [comment]
Has anyone got a fix for this?
