### ISSUE TITLE
Critical error with PayPal payment and site balance

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1175]
To replicate the issue: use any amount of site balance, you can even apply 0$, but to test add some credit transaction on customer. Apply it before checking out, select paypal express as payment method, then click back twice to reach payment selecton site, there will be a confirm button, which if we click it will process the order and mark as pending (like if the payment would be confirmed).

**Comment by kolynet** [comment]
The affected orders will have no_payment_required in the orders under the payment method key column.

**Comment by BasaraABC** [comment]
Hello. What is "click back twice"? Browser`s back button?

**Comment by BasaraABC** [comment]
@abolabo here is the steps to replicate issue:
### 1. Apply customers balance to the cart but make sure not all amount of order paid with balance

### 2. Select PayPal express and click next.
![pp1](https://user-images.githubusercontent.com/2631910/48933308-5e0b4400-ef32-11e8-957a-d89f5a00e953.png)

### 3. You will be redirected to PayPal site. Click BACK button in Browser!

![pp2](https://user-images.githubusercontent.com/2631910/48933325-66fc1580-ef32-11e8-9214-d97759da3e04.png)


### 4. After that you will be redirected to the Confirm order page
![pp3](https://user-images.githubusercontent.com/2631910/48933327-6bc0c980-ef32-11e8-9e33-a0fd77c4e60f.png)

### 5. BUG: customer able to click on CONFIRM button so order placed with Pending status and "No payment required" as payment method. See screenshots
![pp4](https://user-images.githubusercontent.com/2631910/48933333-6fece700-ef32-11e8-8313-05a549d477af.png)

**Comment by kolynet** [comment]
Yes, BasaraABC that's correct! (browser back button, as you replicated)

**Comment by abantecart** [comment]
Once we will fix it you will see changes in the commit history.

**Comment by abolabo** [comment]
hmm..have a trouble with back button. Browser redirects me back to payment page, not confirmation.
I tried to logout from paypal account and click BACK once page open - the same, redirects on checkout/payment 
Also tried to visit paypal side already logged-in. But in this case i got 3 redirects to PP log-in page. See attachment. 

Guys, i need detailed steps and conditions.

P.S. 
![srceen1](https://user-images.githubusercontent.com/1264239/48951732-535ba980-ef48-11e8-932b-93ed2edab354.png)
@BasaraABC i tried on your testcase abc1213_m11d14.

**Comment by BasaraABC** [comment]
@abolabo , did you apply some balance to the order? It is important

**Comment by abolabo** [comment]
yes, sure. tryied to replicate as on your screenshot

**Comment by kolynet** [comment]
I would try google in google chrome, apply balance, be sure that the product you order is more than the balance so paypal payment needed. Be sure that u use paypal express payments, and click 1 or 2 back until you are back on the abante payment select, you should see confirm button. I can reproduce on teamviewer if you need.

**Comment by BasaraABC** [comment]
Issue is not fixed. Replicated with same steps on PHP 7.2.12 latest 1.2.14 code

**Comment by abolabo** [comment]
sorry. typo
