### ISSUE TITLE
Critical error with site balance

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1176]
The issue is related with non-standard (non-default currencies).

To replicate: I have 3-4 currencies set up in the store. Add a product to cart, at the site balance screen before payment let's change the currency from the standard USD to GBP or anything, then apply balance. (be sure that the product that we order is higher than the available balance, so balance not covering the full amount).

If balance applied in GBP done for example, lets switch back to standard USD currency, and you will see a difference from 10-20%. It will deduct 10-30% less than it should, so the customer will have some left in site balance. Using CAD (canadian usd) it will even go into minus, let me attach a screen.

![payment_using_cad](https://user-images.githubusercontent.com/22685076/48918745-ee904880-ee8e-11e8-991c-4a5d6a9be8ae.png)

**Comment by BasaraABC** [comment]
Can you please screenshot a currencies rates page System > Localization > Currencies

**Comment by BasaraABC** [comment]
Please confirm that you have latest AbanteCart 1.2.13 version

**Comment by kolynet** [comment]
![eur](https://user-images.githubusercontent.com/22685076/48934346-ec1c0600-ef03-11e8-8ac3-5683de059d96.png)
![gbp](https://user-images.githubusercontent.com/22685076/48934348-ec1c0600-ef03-11e8-9bcd-eba44a3ba183.png)
![usd](https://user-images.githubusercontent.com/22685076/48934349-ec1c0600-ef03-11e8-89f4-b12e231c37c1.png)
![usdaftergbp](https://user-images.githubusercontent.com/22685076/48934383-14a40000-ef04-11e8-8bf1-f5776ba763be.png)

![currencies](https://user-images.githubusercontent.com/22685076/48934390-1bcb0e00-ef04-11e8-966b-12e24c5decc6.png)

**Comment by BasaraABC** [comment]
Thank you for screenshot. I did not see CAD you mentioned before and please confirm you use latest AbanteCart 1.2.13

**Comment by kolynet** [comment]
I will be able to update you once the latest 1.2.13 installed and i replicated tonight

**Comment by BasaraABC** [comment]
Backup before upgrade and please clear AbanteCart cacher right after upgrade completed

**Comment by kolynet** [comment]
Sorry, its not active in the latest abc. Was probably fixed

**Comment by BasaraABC** [comment]
thank you, @kolynet
