### ISSUE TITLE
getting 500 internal server error when trying to save text that contains "from"

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1177]
Hi admins,

I wonder if you have ever encounter getting 500 error internal server during saving any text that contains "from" within it? Here's the content that i want to post:

[https://pastebin.com/1eeW99f7](https://pastebin.com/1eeW99f7)

![image](https://user-images.githubusercontent.com/225439/48993324-9fd4fe00-f16f-11e8-8e71-eeeff6b663e3.png)

However if i remove the "from", it is saved correctly. 

And we have that happen in a regular cart too, within a text line on sub-category, in the description for the sub-category.

"If you choose the gift bag with cookies here is the list you can choose from"

Is problematic.

changed it to "Gift bag with Cookies list" and that has solved the issue.

I can't post the code on forum due to the unable to post external links. Thanks

**Comment by handoyo** [comment]
Hi Basara, unfortunately there are no error log within AbanteCart nor the server log.

**Comment by BasaraABC** [comment]
Where you save this text?

**Comment by handoyo** [comment]
Can you please send me your email so i can send the urls for you to test?

**Comment by BasaraABC** [comment]
Please describe on what page you got error and what field you saving.

**Comment by BasaraABC** [comment]
I saw a mailchimp mentions in your pastebin. If you have a 3rd party extension please contact extension developer

**Comment by abolabo** [comment]
also try to disable security_mod on your host via CPanel

**Comment by handoyo** [comment]
Hi abolablo , are there other options besides of disabling security_mod?

**Comment by abolabo** [comment]
@handoyo , would you check error log of web-server (not abantecart)? 
500 internal server error means error on server side, but your "pastebin" does not contains server code.
Can you open cPanel and check httpd errors with 500 code? (see servers logs on dash)

**Comment by goatlady102** [comment]
this is an error entry found by our server support  on Sat -  
[Sat Nov 24 04:42:12.135883 2018] [:error] [pid 49685:tid 47656669116160] [client 114.124.214.158:51281] [client 114.124.214.158] ModSecurity: Access denied with code 500 (phase 2). Pattern match "(insert[[:space:]]+into.+values|select.*from.+[a-z|A-Z|0-9]|select.+from|bulk[[:space:]]+insert|union.+select|convert.+\\\\(.*from)" at ARGS:integration_mailchimp_plus_gen_form. [file "/etc/apache2/conf.d/modsec2.liquidweb.conf"] [line "247"] [id "300016"] [rev "2"] [msg "Generic SQL injection protection"] [severity "CRITICAL"] [hostname "abdev7.com"] [uri "/multi/index.php"] [unique_id "W-krA4es7@ouo2HmPAByMAAAAAg"], referer: https://abdev7.com/multi/index.php?rt=extension/extensions/edit&store_id=0&s=usps&token=TxU8fJbmw8ILRYsSp7RtJUQQARRLCopD&extension=integration_mailchimp_plus

**Comment by goatlady102** [comment]
yes,  they can do that and we have looked at that for a solution,  but think that is too convoluted if we offer this extension in the MarketPlace since this is a often encountered issue.  And even if we limit it to ignoring ID 300016 it still weakens the modsec.

We have decided on instruct users if they encounter the issue on their installation,  simply reword the text without using the word "from"

Lee

**Comment by BasaraABC** [comment]
I think you should contact https://github.com/SpiderLabs/ModSecurity project and report problem there

**Comment by goatlady102** [comment]
excellent idea,  we will do that.
Thanks
