### ISSUE TITLE
improve: SEO - URL with subcategories

### ISSUE THREAD

**Issue by ghost** [abantecart/abantecart-src#1178]
I have found a canonical url issue, which is caused by different urls for the same subcategory or items. The problem is that the deep product or category will not have the full url with the subcategories. For example my item under category: 1 should look www.test.com/1/item.

The problem is that it will load at www.test.com/item.

We need to have one fix URL for each product and category ,which includes every subcategory in the URL (e.g: www.test.com/clothes/tshirt/fancycategory/trex-tshirt1). 

And it should be the same easy to follow schema in the breadcrumb area on site.

It will solve various seo and crawling issues.

It could be an optional thing, but i think its very recommended and would have it as a default standard permanent setting. If you have a temporary workaround (solution) for it, please let me know.

**Comment by BasaraABC** [comment]
One product can be assigned to several categories as well as no category at all.
Canonical url should be www.test.com/item in my opinion

**Comment by BasaraABC** [comment]
Check this 3rd party tool https://marketplace.abantecart.com/seo_images

**Comment by kolynet** [comment]
That sound like a good option, however the product should be only reachable with 1 url. Crawler can sometimes find 3 url which work for the same product. And see products with duplicate meta/titles etc, and it confuses google with ranking manipulation, since we have more url of the same pages. So any good fix would be to just limit the pages to 1 seo URL. 

And the breadcrumb should work the same way. If we have multi level subcategory the breadcrumb can only see 1 category, thats also confusing.

**Comment by BasaraABC** [comment]
Canonical urls already included in AbanteCart. Enable SEO Urls in your store and check product pages

**Comment by abantecart** [comment]
Sounds good. Scheduling this update for 1.2.1.4. 

Thank you

**Comment by abantecart** [comment]
I checked SEO URLs. I think we build URLs correctly in all the places. 

I case of one product in 2 different categories, URLs will look as following:
http://localhost/amazon-gift-certificate-update?path=36_38
http://localhost/amazon-gift-certificate-update?path=58_60

Path is necessary to identify the category referenced and should not be treated by google.

**Comment by BasaraABC** [comment]
I did not see any commits. What is changed?
Product assigned to several categories work in old style (which I think is correct)
based on from what category customer visit product

http://localhost/abantecart/eyes/absolue-eye-precious-cells
http://localhost/abantecart/skincare/absolue-eye-precious-cells
http://localhost/abantecart/books/absolue-eye-precious-cells

**Comment by abantecart** [comment]
There was no commit as it worked correctly for me.
