### ISSUE TITLE
improve: SEO - missing alt attribute in category page

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1179]
In category pages, where product listings can be found, the product thumbnail images got a missing <img alt attribute. This attribute is active in the product page, but outside the product, it fails to read product info. The alt could be a default product title or name, similar as in the product itself.

It seemed like a bug for me, it can cause various seo errors and ranking issues in big stores with a lot of products.

**Comment by BasaraABC** [comment]
Images are managed by Resource library so if you add title to your image resource it will appear in alt tag
<img width="1204" alt="alt2" src="https://user-images.githubusercontent.com/2631910/49713400-1814e680-fc7b-11e8-87b6-7f66bcdded63.png">

**Comment by BasaraABC** [comment]
Check this 3rd party tool https://marketplace.abantecart.com/seo_images
