### ISSUE TITLE
Totals recalculation 1.2.2

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#118]
Issue 1: when remove product from order the totals are not recalculated 
------------------------------------------------------------------
![totals-issue1](https://cloud.githubusercontent.com/assets/2631910/7181333/1aaba708-e474-11e4-99a9-1a0f8fa535e2.png)
Issue 2: when add new total to order the totals name is not defined see screen
------------------------------------------------------------------
![totals-issue2](https://cloud.githubusercontent.com/assets/2631910/7181334/1aad8bcc-e474-11e4-9cae-5ed4af85c5f0.png)
Issue 3: when chnage product quantity and save - white screen appear and error in log
------------------------------------------------------------------
![totals-issue3](https://cloud.githubusercontent.com/assets/2631910/7181465/21b838da-e475-11e4-8557-268b823dfa59.png)

Issue 4: when click recalculate low order fee total - white screen appear
------------------------------------------------------------------
![totals-issue4](https://cloud.githubusercontent.com/assets/2631910/7181336/1ab5125c-e474-11e4-8285-ea1e67982694.png)

**Comment by abantecart** [comment]
Issue 1: This is how it will behave. Not all totals will be automatically recalculated. 
Issue 2: This is a total extension key. Nothing needs to be defined. I will check if I can show text.
Issue 3 and 4: I have trouble replicating, but I will check more.

**Comment by abantecart** [comment]
What do you get in a log after #3 and #4? I can not replicate this issue

**Comment by abantecart** [comment]
1 Improved to be more clear. Added "Save & Recalculate" button
2. Is low value and not easy to pull full text
3 and 4, can not replicate, please show log errors

**Comment by BasaraABC** [comment]
About 3 & 4. Log visible in screenshot.
error: AbanteCart core v.1.2.2 Call to a member function convert() on a non-object in <b>..../htdocs/abc122_m04d16/core/lib/cart.php</b> on line <b>494</b>
to replicate visit this page and click recalculate for low_order_fee
dev06.*****.net/abc122_m04d16/index.php?rt=sale/order/details&order_id=16&s=your_admin

**Comment by abantecart** [comment]
I have retested again. I can not get this error. Possibly this is old. If you still get this error, please remember STR.
