### ISSUE TITLE
Abantecart Forum NOT WORKING

### ISSUE THREAD

**Issue by AVSthe** [abantecart/abantecart-src#1181]
Abantecart forum is not working. The page displays error. One could not login.  Also to test i Clicked other menu links like help, register etc... but are not working. Please Fix at the earliest. Thanks

**Comment by BasaraABC** [comment]
Hello. This is Bug Tracker for AbanteCart software..not forum

**Comment by AVSthe** [comment]
Thanks. But I could  find contact  information of Abantecart forum adminitrator to fix the FORUM page loading error. I request you to kindly forward my complaint to fix that issue. Thanks again

**Comment by BasaraABC** [comment]
Screebshot?

**Comment by AVSthe** [comment]
Here is the screenshot

![abantecartforumerror](https://user-images.githubusercontent.com/33345282/49716164-e1d66780-fc78-11e8-896b-cb6ddee3076c.jpg)

**Comment by BasaraABC** [comment]
So your account banned.

**Comment by BasaraABC** [comment]
What is your login name

**Comment by AVSthe** [comment]
I dont think My account is banned. There seems to be some error in login system. Because, I tried to input random username and password to cross check if it says User ID or password is wrong. But whatever one input, it says Error occurred. It says " Sorry Guest your account is banned". Hence, the error seems to unrelated to my account.   Moreover I have not done anything offensive in the forum to get banned. Only thing, I was away from Forum for few months as I busy with other work. Please do the needful. Thanks

**Comment by BasaraABC** [comment]
Try now. Looks like your subnet was banned. Too much spam from your location
