### ISSUE TITLE
Sort Products as default by issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1185]
"Sort Products as default by" setting ignored if search in descriptions  
![2018-12-17_17-12-18](https://user-images.githubusercontent.com/2631910/50081577-6bf67100-0221-11e9-81bf-0ad273992085.jpg)

**Comment by abantecart** [comment]
It works correctly for me. I think confusion is with "default" selection in the dropdown and default set in the settings. These are not the same. 
Default sorting in dropdown is sorting based on sort order set in the products.

**Comment by BasaraABC** [comment]
No, the default "Sort by" for sorting on search page follows admin setting. At least when you search without "Search in product descriptions"
I am agree it should be sorted by relevance but it is not (see #1204 ).
