### ISSUE TITLE
Get Remote IP issue while server behind Cloudflare or proxy

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1186]
core/lib/request.php

The problem will cause the customer IP to be the same as the cloudflare server's. Every user will have identical IP address in the system.

Modify the function to this: (it can cause a lot of troubles if the owner use 3rd party tools for IP checking, or fraud checking while behind proxy or cloudflare)

        public function getRemoteIP()
    {

        if(isset($_SERVER["HTTP_CF_CONNECTING_IP"]))
        {
        $ip = $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
        }else{
            
         if(!empty($this->server['HTTP_CLIENT_IP']))
        {
            $ip = $this->server['HTTP_CLIENT_IP'];
        }elseif(!empty($this->server['HTTP_X_FORWARDED_FOR']))
        {
            $ip = $this->server['HTTP_X_FORWARDED_FOR'];
        }else
        {
            $ip = $this->server['REMOTE_ADDR'];
        }
            
            
        }

        
        return $ip;
    }

**Comment by BasaraABC** [comment]
Are you posting solution or report a bug?

**Comment by kolynet** [comment]
It was a bug, but more likely a suggestion (but yes, its a solution). I have sent the updated function for the request.php.

**Comment by BasaraABC** [comment]
Thank you. We will check. 
 Feel free to create a Pull requests if you want to develop in future https://github.com/abantecart/abantecart-src/pulls

**Comment by BasaraABC** [comment]
@abolabo can you please check solution provided?

**Comment by abolabo** [comment]
@kolynet please help us to check solution. 
just replace your core/lib/request.php with this https://github.com/abantecart/abantecart-src/blob/54041c9aec56a2a2b2e0cf5ce61a5c56a11862b6/public_html/core/lib/request.php
(code a bit different with yours)

**Comment by kolynet** [comment]
> @kolynet please help us to check solution.
> just replace your core/lib/request.php with this https://github.com/abantecart/abantecart-src/blob/54041c9aec56a2a2b2e0cf5ce61a5c56a11862b6/public_html/core/lib/request.php
> (code a bit different with yours)

this was my posted solution :), i have it on my live environment and works like a charm. so confirmed

**Comment by BasaraABC** [comment]
Hi. You have to replace all file to make sure. Anyway thank you for reporting and solution.

**Comment by kolynet** [comment]
how can i find the affected files/changes? I can only see the core/lib/request.

**Comment by abolabo** [comment]
Please check this diff  https://github.com/abantecart/abantecart-src/commit/54041c9aec56a2a2b2e0cf5ce61a5c56a11862b6

**Comment by kolynet** [comment]
> Please check this diff [54041c9](https://github.com/abantecart/abantecart-src/commit/54041c9aec56a2a2b2e0cf5ce61a5c56a11862b6)

syntax error at the last else (double else)

**Comment by abolabo** [comment]
> > Please check this diff [54041c9](https://github.com/abantecart/abantecart-src/commit/54041c9aec56a2a2b2e0cf5ce61a5c56a11862b6)
> 
> syntax error at the last else (double else)
> is there an option so I could edit or make change or requests to the source?

1. there is no syntax error. Do you replaced file or edited?
2. Yes, sure. You can do this via [pull-request mechanism of github](https://help.github.com/articles/creating-a-pull-request/).

**Comment by kolynet** [comment]
Now its fixed yeah. Thanks
