### ISSUE TITLE
feature: Random Order ID and Invoice number

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1187]
Discussion here http://forum.abantecart.com/index.php/topic,7164.0/topicseen.html

**Comment by kolynet** [comment]
+1 interesting feature. I would need it on my live stores as well.

**Comment by abantecart** [comment]
I add correction here. It will be random order number. System ID will be still sequential and hidden from  customers.

**Comment by BasaraABC** [comment]
related #734

**Comment by BasaraABC** [comment]
Now you can set start order id in settings. Random order id will be added in 2.0
