### ISSUE TITLE
Skrill and (complete balance) payment issue

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1188]
Its more likely a confusing / UX issue.

The payment status id wont change or update until customer come back to website after successful payment and click confirm. After payment completion they wont come back to site, its a bit weird UX to confirm it again after payments. So some solution would be probably via the IPN automatically, so it doesnt need confirmations. This could also go for site balance (if paid from user balance and covered) then it could automatically finish UX, because there are an extra confirm button and step to confirm.

For PayPal the experience is smooth. After successful payment, order updates to pending or whatever, and customer can close web tabs :)

**Comment by abolabo** [comment]
Default Skrill payment have a callback method of controller that process requests from skrill api. 
This method should to change order status by parallel process, independently from customer UX.
Do you see some messages inside order history tab?

**Comment by BasaraABC** [comment]
This issue was closed because it has been inactive.
