### ISSUE TITLE
dev: specials page sort order

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1190]
Sort by Price not work correctly
<img width="928" alt="2019-01-03_20-03-26" src="https://user-images.githubusercontent.com/2631910/50639084-b05c6d80-0f92-11e9-95c2-224149ef00ea.png">

**Comment by abantecart** [comment]
Very strange. Works correctly for me. @BasaraABC please try again.

**Comment by BasaraABC** [comment]
I see issue on fresh install. Here is screenshot
<img width="1196" alt="price" src="https://user-images.githubusercontent.com/2631910/54256260-fd118580-458d-11e9-962d-bd2ab8de2704.png">
