### ISSUE TITLE
How to create a menu link for XML feed

### ISSUE THREAD

**Issue by sunnykasera3107** [abantecart/abantecart-src#1191]
I am new to Abantecart. And I am trying to create a menu link for XML feed of orders for some of my other system link ship station, QuickBooks etc.
Could anyone tell me how to create a page for that? Or Is there any documentation available for that?

**Comment by BasaraABC** [comment]
Helo. You post in bugtracker. Please post questions to AbanteCart Community forum http://forum.abantecart.com/
