### ISSUE TITLE
Non-SEO URL for products / categories when you change currency

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1192]
When you have the layout currency selector enabled on product and category pages, SEO urls enabled: if you change currency on the page it will automatically lose seo url and load the parametered version.

It can cause various issues. Maybe an auto redirect to its seo friendly URL would be an easy fix.

**Comment by BasaraABC** [comment]
Hello. What issues in you opinion it may cause?

**Comment by kolynet** [comment]
Maybe something in the request controller, it doesnt get SEO URL. But i havent look at the source yet.

**Comment by abolabo** [comment]
fixed.now URL inside currency block are seo-encoded but with currency parameter
