### ISSUE TITLE
Mcrypt library has been declared DEPRECATED

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1193]
The Mcrypt library has been declared DEPRECATED since PHP 7.1, to use in its OpenSSL

**Comment by BasaraABC** [comment]
@abolabo can you check this commit https://github.com/abantecart/abantecart-src/commit/3846f51ba67e763459b35809509df4ed200beae6
looks like we fix it already?

**Comment by abantecart** [comment]
I thought we already deprecated Mcrypt in 1.2.11. This is based on the release notes and commits.
