### ISSUE TITLE
default template: max logo size

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1194]
Please set max-width to the logo in the default template header
<img width="1482" alt="logo" src="https://user-images.githubusercontent.com/2631910/51977691-a60e9000-24ba-11e9-803b-82607db001c9.png">

**Comment by abantecart** [comment]
I am not sure we need this. If we do this, we need to add text notice to the user of that size

**Comment by BasaraABC** [comment]
We have static container max 300px width for logo. Larger logo will simply broke header
<img width="766" alt="2019-01-30_19-43-07" src="https://user-images.githubusercontent.com/2631910/51981996-597d8180-24c7-11e9-9288-cae6b31317ba.png">

**Comment by abantecart** [comment]
Updated max width and height. Image will be limited only by one dimension. Width or height (which ever is smaller) 

Correct logo size is 300 x 72 px
