### ISSUE TITLE
Improve downloads activation 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1195]
Allow multiply order statuses to select to activate downloads
http://forum.abantecart.com/index.php/topic,7309.0/topicseen.html
<img width="1051" alt="select" src="https://user-images.githubusercontent.com/2631910/52031476-5928c900-254f-11e9-9c86-7319a35e9fc1.png">

**Comment by abantecart** [comment]
I think this is a low priority. Moving to next version
