### ISSUE TITLE
inactive and active UI colors

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1196]
We need
*  to mark active tab for visual editor / source 
* improve on/off button.
Discussion
http://forum.abantecart.com/index.php/topic,7308.0/topicseen.html

**Comment by abantecart** [comment]
Let's work on some ideas/proposal for switch color combinations.

**Comment by BasaraABC** [comment]
proposal  for the source/visual editor tabs
![active](https://user-images.githubusercontent.com/2631910/52112507-4be80900-2639-11e9-8524-903c6359ed04.jpg)

**Comment by BasaraABC** [comment]
color proposal for inactive switch
<img width="1034" alt="switch" src="https://user-images.githubusercontent.com/2631910/52112675-cb75d800-2639-11e9-8d78-55f1c846a0fa.png">

**Comment by BasaraABC** [comment]
One more idea to hide text
![toggle](https://user-images.githubusercontent.com/2631910/52124867-2cfb6e00-265d-11e9-969f-95fa4eb72912.png)

**Comment by goatlady102** [comment]
I personally prefer the squares with the active selection in the darker color.  Seems tidier and takes less space

Lee

**Comment by abantecart** [comment]
I like last concept, but we can make it square .

**Comment by abantecart** [comment]
Implemented the solution. It looks like this now:

<img width="348" alt="screen shot 2019-02-05 at 9 35 08 pm" src="https://user-images.githubusercontent.com/1239995/52317430-f770c080-298d-11e9-8d23-600a839c56ca.png">
<img width="586" alt="screen shot 2019-02-05 at 9 35 02 pm" src="https://user-images.githubusercontent.com/1239995/52317431-f8095700-298d-11e9-9dbe-b226ff07eeeb.png">
<img width="394" alt="screen shot 2019-02-05 at 8 28 38 pm" src="https://user-images.githubusercontent.com/1239995/52317437-fc357480-298d-11e9-9726-692e5cb62f00.png">
