### ISSUE TITLE
Subcategory data cannot be fetched

### ISSUE THREAD

**Issue by arielwebriq** [abantecart/abantecart-src#1198]
http://sample.com/index.php?rt=a/product/category&category_id=71

{
category_id: "71",
parent_id: "0",
sort_order: "0",
status: "1",
date_added: "2019-01-08 21:43:48",
date_modified: "2019-01-08 23:12:40",
language_id: "1",
name: "TEAK LUMBER",
meta_keywords: "TEAK LUMBER",
meta_description: "TEAK LUMBER",
description: "",
store_id: "0",
products_count: "0",
tumbnail: "//buckwoodcraft.webriqshops.com/image/thumbnails/18/79/quarter_inch_teak_full_group_jpg-100253-120x120.jpg",
thumbnail: "//buckwoodcraft.webriqshops.com/image/thumbnails/18/79/quarter_inch_teak_full_group_jpg-100253-120x120.jpg",
total_products: "0",
total_subcategories: "2"
(Supposedly, there should be subcategories data here after total_subcategories???)
}

I am trying to get the subcategories data in which it was stated here:
https://abantecart.atlassian.net/wiki/spaces/DOC/pages/17695186/Catalog+API+Requests+Parameters+and+Responses

Is there a way or settings that will show subcategories after total_subcategories?

**Comment by abantecart** [comment]
I just applied a fix to get categories. Now you will get  "subcategories":[] with subcategories if any sub categories present.
