### ISSUE TITLE
Authorize.Net  deprecation and api updated

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#1199]
Hi Devs,

Just to be sure you're aware of the upcoming Authorize Net changes and deprecation  here is the body of my email  notification receive Jan 24

Dear Developer:        Authorize.Net is phasing out the MD5 based hash use for   transaction response verification in favor of the SHA-512 based hash   utilizing a Signature Key.  If your existing integrations or   clients are using MD5 hash, they will need to move to using the SHA-512 based   hash.  This applies to all Authorize.Net integration methods   including the Authorize.Net API, AIM, SIM/DPM and Relay Response.       The end of life for MD5 Hash will be done in two phases:       Phase 1 -   Remove ability to configured/update MD5 Hash setting in the Merchant   Interface by end of January 2019/early February 2019. This change has no   impact to the API response; it will be done in Phase 2.       Phase 2 - Stop sending the MD5 Hash data element in the   API response. The date for this change will be announced at a later time but   is expected in the next 2-3 months.       For specific details on upgrading to use the SHA-512 hash,   please see our support article: MD5 Hash End of Life & Signature   Key Replacement.   Thank you for your attention to this matter and for being an   Authorize.Net developer.

Lee
--

**Comment by abantecart** [comment]
Thank you Lee. Yes we are aware and this is in progress.

Note, that current AIM authorize.net will be deprecated and new PCI compliant payment method will replace it.

**Comment by abolabo** [comment]
https://github.com/abantecart/abantecart-src/commit/06b14ddd31728bb3226b640c46b3624e8de4a96e

**Comment by BasaraABC** [comment]
New Authorize.net credit cards processing is working. no issues found

**Comment by BasaraABC** [comment]
Payment details tab is broken.
<img width="1031" alt="2019-02-06_13-53-25" src="https://user-images.githubusercontent.com/2631910/52325183-b1137400-2a16-11e9-9808-b2d40f912800.png">
