### ISSUE TITLE
IMPORTANT: shopping cart and cookies rare issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#120]
Issue visible very seldom (Chrome and FF) - can not add products to cart. After page reloading shopping cart is empty see screenshot. To fix issue You need to remove all cookies manually. Looks like issue visible if work with several different installations (1.2.1 & 1.2.2) in same browser
![cart-emty-cookie](https://cloud.githubusercontent.com/assets/2631910/7274830/634d9326-e92a-11e4-9a97-4a3ec906b4ee.png)

**Comment by abolabo** [comment]
looks like browser issue. screenshot with cookies shows that all correct. session_id-per-subdirectory.

**Comment by abolabo** [comment]
low priority. 
cannot to replicate. need step-by-step instruction.

**Comment by abantecart** [comment]
Since this is a storefront, we need to pay more attention to this.

**Comment by abantecart** [comment]
We will comeback to this case in 1.2.3

**Comment by BasaraABC** [comment]
possibly similar Issue reported http://forum.abantecart.com/index.php/topic,3668.0/topicseen.html

**Comment by abantecart** [comment]
This happens if privacy on cookies set.

**Comment by abantecart** [comment]
This problem was addressed, but due to complexity in replication, can not be replicated anymore. 
Let's put this on monitoring till 1.2.4.

**Comment by BasaraABC** [comment]
more and more users report similar issue http://forum.abantecart.com/index.php/topic,3928.msg16923.html#msg16923

**Comment by abantecart** [comment]
This was addressed today with multiple modifications. 

1. Session ID is now more secure and specific to unique store ID
2. Faulty cookie is removed, that had session reset in the code. 

Please try to replicate this issue again with latest 1.2.4 pull

**Comment by BasaraABC** [comment]
Can not replicate issue for now

**Comment by BasaraABC** [comment]
replicated again in 1.2.5

**Comment by abantecart** [comment]
1.2.6?

**Comment by BasaraABC** [comment]
Did not see this issue in 1.2.6
