### ISSUE TITLE
Mobile template issues: 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1203]
## 1. Form width (padding left and right) incorrect on Contact us page
![paddinf](https://user-images.githubusercontent.com/2631910/52409348-d7650c80-2b07-11e9-99b2-8f45af093523.png)

## 2. Misplaced button on newsletter subscribe page
![mispla](https://user-images.githubusercontent.com/2631910/52409354-dc29c080-2b07-11e9-9b0d-cba16b8887ab.png)

## 3. Contact us page buttons are sticky.
<img width="711" alt="stick" src="https://user-images.githubusercontent.com/2631910/52409524-480c2900-2b08-11e9-8376-a56cda8d5657.png">

## 4. Landscape mode (firefox browser on android)
<img width="992" alt="pix" src="https://user-images.githubusercontent.com/2631910/52411253-b43d5b80-2b0d-11e9-9a9a-5ddd373f4a02.png">

## 5. Radio and Checkbox button are not visible  (firefox browser on android)
<img width="1087" alt="radio" src="https://user-images.githubusercontent.com/2631910/52411369-26ae3b80-2b0e-11e9-8848-f44297e1bf77.png">

## 6. Landscape mode in Iphone Safari browser. Customer menu font is not visible (login to see issue)
<img width="989" alt="font" src="https://user-images.githubusercontent.com/2631910/52412667-054f4e80-2b12-11e9-83ef-bf91cc243f18.png">

**Comment by abolabo** [comment]
![image](https://user-images.githubusercontent.com/1264239/54449843-b40d2d00-4757-11e9-8488-eedfe6eb8e76.png)

**Comment by abolabo** [comment]
Style of radio buttons depends on browser render. See screenshot above/
other fixed
