### ISSUE TITLE
Incorrect price shown in the Data Listing Block

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#121]
to replicate enable Display Prices with Tax settings. Issues found in the Listing Data Source: Specials offers, Custom Products, Popular products see screenshots
![data-listing-issue1](https://cloud.githubusercontent.com/assets/2631910/7346552/c1a7b3a6-ed09-11e4-9d74-89ca54e96b80.png)
------------------------------------------------
------------------------------------------------
![data-listing-issue2](https://cloud.githubusercontent.com/assets/2631910/7346553/c20a9af2-ed09-11e4-88bf-1864ee41b01f.png)
------------------------------------------------
------------------------------------------------
![data-listing-issue3](https://cloud.githubusercontent.com/assets/2631910/7346864/cab6f6d4-ed0c-11e4-9122-6d877f9b63d3.png)

original post http://forum.abantecart.com/index.php/topic,3420.new.html#new

**Comment by abolabo** [comment]
fixed
