### ISSUE TITLE
dev: PHP 7.3.1 warnings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1213]
warning: AbanteCart core v.1.2.14 Invalid argument supplied for foreach() in <b>/htdocs/abantecart/admin/controller/responses/product/product.php</b> on line <b>596</b>

warning:  AbanteCart core v.1.2.14 Invalid argument supplied for foreach() in <b>core/engine/html.php</b> on line <b>1001</b>

warning:  AbanteCart core v.1.2.14 Invalid argument supplied for foreach() in <b>/storefront/view/default/template/form/selectbox.tpl</b> on line <b>10</b>

warning:  AbanteCart core v.1.2.14 sizeof(): Parameter must be an array or an object that implements Countable in <b>core/engine/form.php</b> on line <b>633</b>

 warning:  AbanteCart core v.1.2.14 A non-numeric value encountered in <b>/abantecart/extensions/default_weight/storefront/model/extension/default_weight.php</b> on line <b>85</b>

**Comment by abantecart** [comment]
@abolabo please improve this section, there are few issues in here.
