### ISSUE TITLE
global attributes values in product

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1215]
To replicate try to add Global attribute Size (demo data) to product, select few values and save.
Then try to change values.
Install have multistore enabled. See also if #1209 issue related.
![global](https://user-images.githubusercontent.com/2631910/52787431-65a13b80-3090-11e9-9824-db2d3d873951.jpg)

**Comment by abantecart** [comment]
@BasaraABC I am not able to see the problem. I can add/edit/remove. All values are matching. 
Please elaborate more on this issue.

**Comment by BasaraABC** [comment]
@abantecart , @abolabo was able to replicate issue at friday.

**Comment by abantecart** [comment]
In this case, I leave it to you guys.
