### ISSUE TITLE
estimate block

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1216]
![est](https://user-images.githubusercontent.com/2631910/52842910-1fe97f00-3133-11e9-9fe5-71ce95bfd839.jpg)

**Comment by abolabo** [comment]
cannot to replicate
![image](https://user-images.githubusercontent.com/1264239/53977405-a29da280-4111-11e9-97fc-d3f5739f32ea.png)

**Comment by BasaraABC** [comment]
Same on my side on fresh install. Closed
