### ISSUE TITLE
dev: stock locations and order edit

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1217]
When product added to order by admin user the stock location quantities do not change.
![stockorder](https://user-images.githubusercontent.com/2631910/52934553-61736780-3389-11e9-9c84-dfd8a3931c81.jpg)

**Comment by abantecart** [comment]
Below code needs to be updated to use location/option based calculation:

public_html/admin/model/sale/order.php:377

                    //update stock quantity
                    $qnt_diff = -$product['quantity'];
                    $stock_qnt = $product_query->row['quantity'];
                    $new_qnt = $stock_qnt - (int)$product['quantity'];

                    if ($product_info['subtract']) {
                        $this->db->query("UPDATE ".$this->db->table("products")."
										  SET quantity = '".$new_qnt."'
						

public_html/admin/model/sale/order.php:393

                    $prev_subtract_options = array(); //array with previous option values with enabled stock tracking
                    foreach ($order_product_options as $old_value) {
                        if (!$old_value['subtract']) {
                            continue;
                        }
                        $prev_subtract_options[(int)$old_value['product_option_id']][] = (int)$old_value['product_option_value_id'];
                    }

**Comment by BasaraABC** [comment]
Main issue is fixed. However some minor available.
For example you have 2 location: 10 and 2 quantity
Then add to order 11 q-ty see what's happen
We will get location q-ty: -1 and 2

Also question in stock return if product removed from the order. Now we do not increase stock.

Lets discuss should we improve now or in 2.0?
![localtion1](https://user-images.githubusercontent.com/2631910/54124804-e9530b80-4435-11e9-84da-261e0aca0a9a.jpg)

**Comment by abolabo** [comment]
fixed. 
Also fixed new bug with increasing of qnty for deleted products.
Please check adding-deleting product into order with stock locations for option value and main qnty
