### ISSUE TITLE
embed console bug

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1219]
404 error in console when opened embed menu. See "undefined" in url call
![404](https://user-images.githubusercontent.com/2631910/53089452-33d01f00-353f-11e9-87ca-5ad8d2077317.jpg)

**Comment by abolabo** [comment]
cannot to replicate. needs more details

**Comment by BasaraABC** [comment]
Fresh installed AbanteCart 1.2.14
Chrome browser Version 72.0.3626.121
php 7.3 localserver
![script](https://user-images.githubusercontent.com/2631910/54008820-d8d33480-419a-11e9-8900-d5d9327fc98c.jpg)
