### ISSUE TITLE
Weight based shipping - multistore not supported

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#122]
Weight based shipping does not support different Rates for multistore. When you change store on General Tab in the extensions settings and locate Additional setttings Tab there are rates for default store. Please fix
http://forum.abantecart.com/index.php/topic,3483.0/topicseen.html

**Comment by abolabo** [comment]
fixed

**Comment by abolabo** [comment]
fixed

**Comment by simhanventure** [comment]
Hi, why after i copy all u code into the default weight.php, then when me change the rate for the store and submit, it does not show anything( see image attach) 
![untitled](https://cloud.githubusercontent.com/assets/12285580/7648965/1df8e49e-fb1b-11e4-9f11-ee43725bb2b3.jpg)

**Comment by abolabo** [comment]
what is in system/logs/error.txt ?

**Comment by simhanventure** [comment]
2015-05-15 3:18:37 - warning: AbanteCart core v.1.2.1 Cannot modify header information - headers already sent by (output started at /home/hanwebfusion/public_html/mybrandmart/extensions/default_weight/admin/controller/pages/extension/default_weight.php:1) in <b>/home/hanwebfusion/public_html/mybrandmart/core/engine/controller.php</b> on line <b>202</b>

**Comment by BasaraABC** [comment]
Not work for me too. On Weight Based Additional settings page if select store2 the "Page Not Found!" error shown
![weightbased](https://cloud.githubusercontent.com/assets/2631910/7650757/e2f48822-fb23-11e4-8db6-3d3f442653fd.png)

**Comment by abolabo** [comment]
found core bug and fixed. To make additional settings work you should to save "general" settings for additional store before and then click "Additional settings" tab. Or just reinstall extension.

**Comment by simhanventure** [comment]
why after i paste the code it show this error
![untitled1](https://cloud.githubusercontent.com/assets/12285580/7673362/574e7828-fd44-11e4-8aeb-653967d11b71.jpg)

**Comment by abolabo** [comment]
try to replace whole directory extensions/default_weight and check. 
i guess you did something wrong during editing.
