### ISSUE TITLE
multistore: default store data in Data listing block

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1226]
Data from default store visible in other stores and looks broken. I think we need to hide it
![data2](https://user-images.githubusercontent.com/2631910/53409542-be0efc00-39f3-11e9-88e3-1e752ccd1183.jpg)

**Comment by abolabo** [comment]
Block content cannot be per store. Fixed

**Comment by BasaraABC** [comment]
1. Issue is not fixed. Broken manufacturers still visible if another store in session.
2. Why Store selector removed? Block content (Custom Manufacturers) does work fine with multistore see screenshot.
![multistore](https://user-images.githubusercontent.com/2631910/53954293-66b20f80-4108-11e9-8995-f30e1e8b9a99.jpg)

**Comment by BasaraABC** [comment]
Installation is broken.
```
SQL Error: Column count doesn't match value count at row 1
Error No: 1136
SQL: INSERT INTO `bc_custom_lists` VALUES (1,12,'manufacturer_id',12,0,'2015-06-12 09:56:24','2015-06-12 09:56:24'); in /htdocs/core/database/amysqli.php on line 114
```
![install](https://user-images.githubusercontent.com/2631910/54103427-f6a0d380-43fe-11e9-8772-0067aacd22a0.jpg)

**Comment by BasaraABC** [comment]
Thank you. Fixed.
