### ISSUE TITLE
extensions grid: disabled mp extensions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1229]
Please hide disabled extensions in rt=extension/extensions/extensions
![extgrid](https://user-images.githubusercontent.com/2631910/53941067-bb925d80-40e9-11e9-95b7-3a3447e20b55.jpg)

**Comment by abantecart** [comment]
@BasaraABC I have uploaded this to live. Please check ASAP, as i am not sure this fix is correct. Doe s not look very right to me.

**Comment by BasaraABC** [comment]
Fixed. Thank you
