### ISSUE TITLE
Abante Cart stock issue

### ISSUE THREAD

**Issue by West2uk** [abantecart/abantecart-src#1235]
I have been having issues with Abante Cart the last 2 days with the stock element, basically most of our stock balance yesterday went to “0 Available” I have attached 2 screenshots from the Quick View to show you 2 scenarios, 1 is working and the other is not working highlighted in yellow, as we have 2 sites at the moment using the script from Abante Cart we are now not able to sell or even advertise anything from the site as they have all disappeared from the site making it look blank to anyone that browses. 
 
When we try and put items back into stock they just go straight to a 0 available and is very frustrating as I’m sure you can imagine, the test we did ran perfectly during the trial period and now that we have signed up to a2.Hosting I did intend on moving my domains to them from one.com since I can’t get Abante Cart on my one.com server

**Comment by BasaraABC** [comment]
Hello. Where is attached screenshots?

**Comment by BasaraABC** [comment]
Please also provide your AbanteCart version

**Comment by West2uk** [comment]
AbanteCart Version 1.2.14

**Comment by BasaraABC** [comment]
Still no screenshot provided. 
Did you update from 1.2.13 or have fresh installed 1.2.14?

**Comment by West2uk** [comment]
I did the update about 2 days before everything went all wrong. From 1.2.13
to the new version 1.2.14

 

I have attached the screenshots. See attached.

 

Working screenshot



 

 

 

  

 

 

 

 

NOT working screenshot



 

 

 

 

 

 

 

 

 

 

Thank you

 

Allan Jamieson

**Comment by BasaraABC** [comment]
So you upgrade to 1.2.14 and for a few days everything works fine and than you got issue?
Do you have some server/hosting crash recently? Make sure hoster do not restore some old db without your notify.
All products have that issue or only some of them?
Products with trackable option or without?
Did you run recently products import process?

P.S.
Screenshots are not visible (once again).

**Comment by abantecart** [comment]
Guys, let me remind you. This is not a support tread. If problem is not clearly indicated with steps to replicate, we will close the issue.

**Comment by West2uk** [comment]
Hi, and 1st can I say Thank you for taking the time to help resolve this
issue.

 

*	We had a server issue on the Amsterdam server that affected all of
the clients on a2.Hosting over a week age
*	I installed the update for AbanteCart a few days ago now but after
the server issue.
*	Its only affecting around 90% of the products, I am still trying to
amend them but with no luck so far, after a page refresh they still resort
to a 0 Availability. 
*	All our product are trackable
*	I have never imported any items, so far we've been building them in
1 at a time.

 

As for the attachments, Last email I send 2 in the attachments as well as
copied them into the email as a picture, don't know what else to do about
that.

 

Regards

 

Allan Jamieson

**Comment by BasaraABC** [comment]
Closed. No screenshots and confirmed recent server crash
