### ISSUE TITLE
Guest step 3 page doesn't show the product option image

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1236]
Hi,

On checkout/guest_step_3 page, the options specific image for product is not shown correctly. The one on checkout/confirm page for logged in accounts works.

product option image
![image](https://user-images.githubusercontent.com/225439/55092435-2cbfa200-50e5-11e9-979e-9816e9e9b50e.png)

guest_step_3
![image](https://user-images.githubusercontent.com/225439/55092387-19143b80-50e5-11e9-8ac8-d0e5f77b92c9.png)

checkout/confirm
![image](https://user-images.githubusercontent.com/225439/55092628-73ad9780-50e5-11e9-8a51-31ea90e11c22.png)

**Comment by BasaraABC** [comment]
Is it html resource like font-awesome icon?

**Comment by handoyo** [comment]
Yes it is, i use it for testing purpose.

**Comment by BasaraABC** [comment]
Issue is confirmed. Same with image (.jpg .png) see
<img width="903" alt="guest" src="https://user-images.githubusercontent.com/2631910/55134716-2e787c80-515c-11e9-9d61-7b068c9e9b22.png">

**Comment by handoyo** [comment]
Hi, apparently the issue still remains in guest step 3 checkout page.

![image](https://user-images.githubusercontent.com/225439/56458303-14266d00-63af-11e9-8f80-d442570fbdce.png)

![image](https://user-images.githubusercontent.com/225439/56458310-21435c00-63af-11e9-9646-86d416feeab7.png)

**Comment by handoyo** [comment]
Hi, 

In our pre-release testing of v 1.2.15  it appears the issue still remains in guest step 3 checkout page. Here are the screenshots:

![image](https://user-images.githubusercontent.com/225439/56458303-14266d00-63af-11e9-8f80-d442570fbdce.png)

![image](https://user-images.githubusercontent.com/225439/56458554-88164480-63b2-11e9-8876-5a6707b51fcd.png)

**Comment by BasaraABC** [comment]
Hi, handoyo. Can you please try with latest 1.2.15 code. I cant replicate issue

**Comment by handoyo** [comment]
Hi Basara,

We have used the latest 1.2.15 file from Github as per 22/4/2019 and i get the same issue. Here is the url along the creds:

https://abdev7.com/new1215/index.php?s=new1215
username: admin
password: new1215

The product that i use for testing is: 
https://abdev7.com/new1215/index.php?rt=product/product&product_id=121

Also, when you select the white color and then select the light blue color in the option block  the product image are changed.

![image](https://user-images.githubusercontent.com/225439/56515678-a4f17a00-6562-11e9-94ff-94ff3288bcf6.png)

**Comment by BasaraABC** [comment]
@abolabo can you please fix. To replicate add 2 options into product on last step of guest checkout product image in quick basket and in order are different.

<img width="680" alt="2019-04-23_13-38-22" src="https://user-images.githubusercontent.com/2631910/56559907-2bdb3c80-65cd-11e9-8898-765c31665526.png">

Thank you @handoyo

**Comment by BasaraABC** [comment]
@handoyo can you please double check that you have latest code? I see problem on your site but still cant replicate localy

**Comment by handoyo** [comment]
Hi @BasaraABC, 

i download the latest file from GitHub 1.2.15 branch, so i suppose that is the latest code, isn't it?

**Comment by BasaraABC** [comment]
Yes you are right.

**Comment by handoyo** [comment]
That is the file we're using in our testing site.

**Comment by handoyo** [comment]
@BasaraABC , @vdvpie22 

Thanks for the fix. We confirm that the product option image are now shown correctly in guest step 3 page.

**Comment by BasaraABC** [comment]
@handoyo thank you for reporting and testing!
