### ISSUE TITLE
product with track stock requires location or all set to zero quantities

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#1238]
on v 1.2.14  there is an issue with the track stock settings and the locations.  You have not set the locations as required if track stock is enabled.   I have tested this bug on multiple servers and a local machine it is a bug.
Steps I did:
On a server running PHP 7.2  install new 1.2.14 using Softaculous.
Made no changes or entries to anything -  still a virgin installation 
Choose any product without options.  If track stock is set to yes  - the locations fields show (no required setting or warning they are required)
Making NO changes - net even to quantity -  click on the save button at the page bottom
Quantities of all products without options and with track stock  set to yes without a location set  will be zeroed out.

![before save](https://user-images.githubusercontent.com/7943102/55433015-01600b80-555a-11e9-87dd-a7dc3e25eb5c.jpg)

![after save](https://user-images.githubusercontent.com/7943102/55433033-0de46400-555a-11e9-9951-7946ebca3469.jpg)

**Comment by BasaraABC** [comment]
Good catch. Issue confirmed

**Comment by BasaraABC** [comment]
@abolabo can you please provide a fix.

**Comment by BasaraABC** [comment]
### issue 1: Cant add Stock Location with quick save
Make sure to reload page to see issue after save.
![stock-issue1](https://user-images.githubusercontent.com/2631910/55532144-05fdfe80-56d7-11e9-9d2c-092960b31688.png)

**Comment by BasaraABC** [comment]
### Issue 2: Can't remove one location from the list.
Use global save button at the bottom of page to apply changes
![stock-issue2](https://user-images.githubusercontent.com/2631910/55532457-2c706980-56d8-11e9-999b-32769f561c4b.png)

**Comment by BasaraABC** [comment]
### Issue 3A: Quantity not updated 
USA q-ty should be 0 after save
### Issue 3B: Locations not sorted (sort order ignored)
USA have sort order 2 so Canada with sort order 100 should be at the bottom.
Note: save with global save button

![stock-issue3](https://user-images.githubusercontent.com/2631910/55533011-14014e80-56da-11e9-92bc-6ccb38806537.png)

**Comment by BasaraABC** [comment]
### Issue 4  (with latest fixes.)
<img width="839" alt="stock-77" src="https://user-images.githubusercontent.com/2631910/55551287-a9b1d380-5704-11e9-86f3-ff9b6dd16edf.png">

**Comment by BasaraABC** [comment]
Fixed and closed but I will give it some more testing
