### ISSUE TITLE
total quantity calculation issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1240]
### Issue A:  if one of the trackable options value is negative
![stock-issue4](https://user-images.githubusercontent.com/2631910/55535243-ca683200-56e0-11e9-875d-2fa2f81a61d9.png)

--------------------

See also another case.
### Issue B: opposite case. When one of the option value has Track DISABLED. The total quantity in grid is invalid
![stock-issue5](https://user-images.githubusercontent.com/2631910/55535485-980b0480-56e1-11e9-83b4-e3a015ae642b.png)

**Comment by BasaraABC** [comment]
I think we need to discuss: If one of the option is negative or zero logically we should not use in calculations (like Track stock id OFF)?

**Comment by abolabo** [comment]
qnty in grid means available stock quantity. Think negative values is zero during sum calculation

**Comment by BasaraABC** [comment]
Still issue in grid with positive value and Track Stock Disabled see
<img width="694" alt="stock-778" src="https://user-images.githubusercontent.com/2631910/55552432-863c5800-5707-11e9-9c1a-36974a7d528c.png">
