### ISSUE TITLE
stock locations and Stock Checkout

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1242]
related #1238 
Issues if tracking options values when Stock Checkout enabled (allow to buy Out of stock)
![stock-7](https://user-images.githubusercontent.com/2631910/55537572-b6bfca00-56e6-11e9-991a-1f44e72fc7a2.png)

**Comment by abolabo** [comment]
It's not a bug. We cannot decide for merchant what location of stock will be used in the future. Stock in locations cannot be negative.

**Comment by BasaraABC** [comment]
thank you. Closed
