### ISSUE TITLE
dev: menu permissions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1249]
With all permissions (read/write) enabled the Admin User within that User Group can not see some menu items:
* All Settings:  System > Settings > General, System > Settings > Checkout..... however System > Settings is available and after visit a page User can click on all Tabs
* Help menu is completely hidden
* Half of Extensions: Extensions > All Extensions, Extensions > Shipping (Payments, Templates, Languages, Taxes)
* Reports > Sales, Reports > Customers

**Comment by Ice-Drake** [comment]
I noticed that problem as well; however, based on the code implemention, it should work. Since it didn't, the problem lies elsewhere. Got any idea where the problem might be at?

**Comment by BasaraABC** [comment]
Not fixed:
> Reports > Sales, Reports > Customers

**Comment by BasaraABC** [comment]
Reposts are visible even if User has not permissions.
<img width="1364" alt="report2" src="https://user-images.githubusercontent.com/2631910/56040879-a0a6af00-5d61-11e9-9e67-b8a084855b71.png">

**Comment by Ice-Drake** [comment]
abolabo, about your additional elseif condition you made in the commit:

`elseif (!$rt && !$children){
                    continue;
             }`

You can combine it with the elseif condition shown below:

`elseif ($this->groupID !== self::TOP_ADMIN_GROUP
                        && !$http_rt
                        && !$this->permissions['access'][$controller_rt]
                ) {
                    continue;
                }`

The result will be:
`elseif ((!$rt && !$children) || ($rt && $this->groupID !== self::TOP_ADMIN_GROUP
                        && !$http_rt
                        && !$this->permissions['access'][$controller_rt])) { continue; }`

Using boolean algebra, it will yield the following:
(!$rt && !$children) || ($rt && $this->groupID !== self::TOP_ADMIN_GROUP && !$http_rt && !$this->permissions['access'][$controller_rt])

(!$rt || $rt) && (!$children || ($this->groupID !== self::TOP_ADMIN_GROUP && !$http_rt && !$this->permissions['access'][$controller_rt]))

(!$children || ($this->groupID !== self::TOP_ADMIN_GROUP && !$http_rt && !$this->permissions['access'][$controller_rt]))

In this else if, !$children will always be true, won't it make the top line to be just else case?

**Comment by Ice-Drake** [comment]
Never mind, I found a reason why $rt is added. You are making sure that $controller_rt is defined by checking first that $rt is defined.
