### ISSUE TITLE
order edit: incorrect q-ty deducted if increase

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1256]
If change purchased items to 1 the stock quantity in option value changed to 2 items. See all conditions in screenshot.
<img width="715" alt="oprder-edit-onemore2" src="https://user-images.githubusercontent.com/2631910/56031166-e0ad6800-5d48-11e9-9e34-4828873b3076.png">

related to #1250

**Comment by abolabo** [comment]
fixed. related to #1254

**Comment by BasaraABC** [comment]
Issue is not fixed. All conditions are same

**Comment by BasaraABC** [comment]
That case fixed. I will run few more tests with more complicated scenario.
