### ISSUE TITLE
Order cancellation API Needed

### ISSUE THREAD

**Issue by yash-nagdev-sc** [abantecart/abantecart-src#1294]
How to enable order cancellation through API...

**Comment by BasaraABC** [comment]
Hello. We order cancellation is currently not available in API. Please post your questions and feature request in forum.abantecart.com
github bug tracker is for Bugs Reports only.

**Comment by abantecart** [comment]
@yash-nagdev-sc Are you asking about Storefront or admin API? Admin API does not have order edits, but what you ask if probably needed in admin and not necessarily in storefront
