### ISSUE TITLE
Option selectbox ignores NO default set

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#1295]
There is inconsistent handling of options.  Selectbox ingores there are NO default set and adds the first item into the pricing before customer makes a selection.

Multiselect box and checkbox group act as expected and do not modify the total pricing until customer makes a selection.  

Can you please adjust selectbox to act consistently with the other types of options?

![image](https://user-images.githubusercontent.com/7943102/61415272-d5bd2300-a8b5-11e9-990c-cb3804796946.png)

![image](https://user-images.githubusercontent.com/7943102/61415208-b2927380-a8b5-11e9-87ea-74bcf0576a89.png)

Thanks for looking into this.
Lee

**Comment by abantecart** [comment]
I am not understanding the problem. There is no default value selected on your option values. It selects the first on the list for regular sect box. 
As for multi-select field, there is nothing selected. This seems to be logical to me. 
What do you expect to be selected by default?

**Comment by goatlady102** [comment]
Options by definition should be options  -  selected by the customer.   Think about a roll of carpet and the option of adding padding or installation to the order -  customer may only want carpet ,  but the way this works now -  the first option is automatically added even if customer doesn't want any.

On multi select and checkboxgroup -  it does not alter the total pricing until a  selection is made by the customer.   on the selectbox -  it ADDs the first option to the total pricing although there is NO default selected by the admin within the option  nor a choice made by a customer.  Now that would be correct if a default was set by Admin within the option.   If all defaults are unselected the correct action would be no change in the total pricing until an option was activated by selection by customer.

look at the t-shirt -  price is $9.99  ,  total price is $10.99 and customer has made no selection, and admin has not set any default.  The total price should remain at 9.99 until a selection is actually made.  

This become further problematic when there is more than one set of options on a product ,  and perhaps none of them are selected by customer.  

Admin could mangle up the selection by making the first option  -  No selection chosen  (your 'empty option ') and then continue on with other choices,  But that is cumbersome and not consistent with the other types of options.

**Comment by BasaraABC** [comment]
Hello. If you add a placeholder to your select-box no option values will be selected by default.

**Comment by goatlady102** [comment]
thanks,  that does work -  just seemed "wrong" to me for the system to ignore the no default selection and apply as if there was one.
