### ISSUE TITLE
nginx: system check report false positive warnings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1296]
If enable System > Settings > System Check on nginx it will report false warnings:
1. Seo urls not work
2. Incorrect index.php permission
3. Incorrect config file permissions
<img width="838" alt="nginx" src="https://user-images.githubusercontent.com/2631910/61435247-46217e00-a962-11e9-9a12-6578a5a1c04a.png">

**Comment by vdvpie22** [comment]
Not reproduce

**Comment by vdvpie22** [comment]
1. Changed to check from admin only, please try
2. Work correct
3. Work correct
