### ISSUE TITLE
Product prices fixation

### ISSUE THREAD

**Issue by HodardHazwinayo** [abantecart/abantecart-src#1298]
How to configure product prices in range not for decimal, For instance in default one is $ 23.00, but I want to configure like this $ 23.00 - 50.00 Negotiable how can I fix it, please help me. I already change product table form decimal to varchar but still having an issue.

**Comment by HodardHazwinayo** [comment]
How to configure product prices in range not for decimal, For instance in default one is $ 23.00, but I want to configure like this $ 23.00 - 50.00 Negotiable how can I fix it, please help me. I already change product table form decimal to varchar but still having an issue

**Comment by BasaraABC** [comment]
Please post your question on forum.abantecart.com
GitHub is for bug reports for latest version only

**Comment by abantecart** [comment]
This is not  forum or questions board. Here you can only report issues/bug and suggestion for improvment
