### ISSUE TITLE
Issue with default oprion value with image resource

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#130]
![122-issue3](https://cloud.githubusercontent.com/assets/2631910/7584177/be51f3d4-f8c5-11e4-9c97-7d884e905054.png)

**Comment by BasaraABC** [comment]
see issue http://dev06.******.net/abc122_m05d11/index.php?rt=product/product&manufacturer_id=21&product_id=111

**Comment by abolabo** [comment]
fixed
