### ISSUE TITLE
number format will cause huge price difference for 0.01 usd products

### ISSUE THREAD

**Issue by ghost** [abantecart/abantecart-src#1307]
i have products of 0.01 usd, problem is that the rounding will cause huge difference if purchased in other currencies, for example in GBP. A simple workaround would be an option to use one more decimal places, instead of two (globally). If i purchase 5 or 10k unit of such small product price, there can be even 40-50% difference in price due to decimal and currency conversion. if needed, i could provide link to test environment in private.

**Comment by BasaraABC** [comment]
Is this bug or feature request? Officially USD and GBP have 2 decimal points so what should AbanteCart do with this? Please provide detailed bug report in other case please move this dicsussion to AbanteCart community forum http://forum.abantecart.com
By the way you can change decimal points in USD and set price like 0.00976

**Comment by kolynet** [comment]
can i have your contact, i could provide a quick test link so you know what im talking about? its only affected with really small product price.

**Comment by kolynet** [comment]
i wouldnt say its a bug, it can be problematic for super rare cases, like mine, with prices like 0.01 usd.

**Comment by abantecart** [comment]
You can set your test case to help@abantecart.com or post it in here.

**Comment by BasaraABC** [comment]
Here is my case  with USD as base currency and 0.01 as price
Issue visible if add 1000 items to basket
in USD sub-total will be $10.00 but in GBP it is incorrect £10.00
decimal points for both currencies are default 2
<img width="580" alt="rates" src="https://user-images.githubusercontent.com/2631910/65965664-31488700-e489-11e9-9874-20101e39bfa0.png">
<img width="1009" alt="compare" src="https://user-images.githubusercontent.com/2631910/65965943-9e5c1c80-e489-11e9-8996-2df7d173ae89.png">

**Comment by BasaraABC** [comment]
As a solution for calculation set GBP to 4 decimal places but in this case all prices in storefront will be shown like £7.9000
<img width="520" alt="gbp2" src="https://user-images.githubusercontent.com/2631910/65966400-3a862380-e48a-11e9-8d89-81903755b3ae.png">

**Comment by kolynet** [comment]
yes, it solves my main problem with rounding, however in this 4 decimal case, payment extensions throw paypal checkout error, also for skrill. should i make some edit at core/lib/cart for rounding total? what would be the most ideal fix?

**Comment by BasaraABC** [comment]
Simplest solution for you is sell such products per packs like 100 items so price will be $1 and no issues with conversion or you have to modify your payment extensions to give payment gateway values they need

**Comment by kolynet** [comment]
yes, but thats not possible in my scenario. if i edit to send 2 decimal instead of 4 at payment module, it will be invalidated, due to total price difference. maybe can you please update where could i set the 2 decimal rounding, while using 4 decimal in settings/currencies?

i would like that it counts the totals with 4 decimal, but shows 2 decimal for total prices on frontend and/or checkout. 

best would be to just show fronent and proceed checkout with 2 decimal prices, but I could use deeper decimals for calculating totals and qtys in the background. 

I hope at least you understand the issue.

**Comment by abantecart** [comment]
I think what you are lookin for is very specific/custom scenario and will not be beneficial for other users. We will keep this open for others to comment.
