### ISSUE TITLE
coupon total recalculation not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#131]
All changes ignored - used initial value all the time
![122-issue4](https://cloud.githubusercontent.com/assets/2631910/7584923/42e53a84-f8cb-11e4-9479-36eb998c07ba.png)

**Comment by BasaraABC** [comment]
note: order is new

**Comment by abantecart** [comment]
This is working correctly. Recalculate will use setting in the coupon. To use custom value, you need to save without recalculation. 

Let me know if any other ideas how to make it more clear.

**Comment by abantecart** [comment]
Fixed. Please retest

**Comment by BasaraABC** [comment]
Recalculation is broken. Please see screenshot
![coupon](https://cloud.githubusercontent.com/assets/2631910/7649443/35f6cf88-fb17-11e4-8fd1-4a7b715bb277.png)

**Comment by abantecart** [comment]
This is very strange. What browser is this?

**Comment by abantecart** [comment]
Fixed. Total recalc will not be allowed if:
1. Product no longer available 
2. Totals (some or all) are disabled.
