### ISSUE TITLE
check stock on order confirmation

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1310]
Case: 
1 product in stock but 2 customer try to confirm order with same product in same time. We should return error in SF 
https://forum.abantecart.com/index.php/topic,8209.msg32808.html#msg32808

**Comment by BasaraABC** [comment]
moved to internal tracker

**Comment by tgmehar** [comment]
Is the solution to this problem available in any version? Looks like the check/validation on confirmation still does not work..
