### ISSUE TITLE
Custom List price format bug

### ISSUE THREAD

**Issue by DotNetToolKit** [abantecart/abantecart-src#1311]
My setup:
AbanteCart Version 1.2.15
I have a Custom List (on main page in the content footer block) based on Featured List (Limit: 20).
Currency: Ft (HUF) without decimal places
Hungarian thousand separator is comma by default and Ft is the suffix (no prefix used)
![currency](https://user-images.githubusercontent.com/12406914/70786891-e94db680-1d8d-11ea-8725-4c1b24003782.jpg)

The price shown correctly everywhere - exept in the custom list block. For example:
Product 1: 2,940Ft on product page (correct) but it's 4Ft in the custom list
Product 2: 10,980Ft vs. 17Ft
![custom - wrong](https://user-images.githubusercontent.com/12406914/70786894-e94db680-1d8d-11ea-861f-41068df1351f.jpg)
![product - ok](https://user-images.githubusercontent.com/12406914/70786895-e9e64d00-1d8d-11ea-82a1-5c5a2c5dcdb5.jpg)

I found a workaround:
I added an empty space (" ") into "Symbol Left" parameter of Currency. 
It is working now but I think we need a final solution.
![custom - ok](https://user-images.githubusercontent.com/12406914/70786892-e94db680-1d8d-11ea-89c5-b4850adbb7f0.jpg)

**Comment by BasaraABC** [comment]
Please post you custom block settings

**Comment by DotNetToolKit** [comment]
It's very simple:
![custom list settings](https://user-images.githubusercontent.com/12406914/70787406-db4c6580-1d8e-11ea-8094-6343d09a26d3.jpg)

**Comment by BasaraABC** [comment]
Issue confirmed. To replicate just set in currency Decimal Places: 0 and Symbol left: FT
