### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1312]

**Comment by BasaraABC** [comment]
Thank you @abolabo, now it works with last commit https://github.com/abantecart/abantecart-src/commit/7d34049258c2a0f587a05c7d1b33488511a4e52c
I will keep issue open to report anything I will find related to new php

**Comment by BasaraABC** [comment]
@abolabo See if you can replicate. When create database backup in admin task failed with next errors. PHP 7.4.3

`App Error: AbanteCart core v.1.2.16 Tar GZ compressing error: phar "abantecart/htdocs/admin/system/backup/manual_backup_20200406_081844.tar" unable to create temporary fileTrace:#0 abantecart/htdocs/core/helper/utils.php on line 846#1 abantecart/htdocs/core/lib/backup.php on line 481#2 abantecart/htdocs/admin/controller/task/tool/backup.php on line 199#3 abantecart/htdocs/core/engine/dispatcher.php on line 293#4 abantecart/htdocs/core/engine/dispatcher.php on line 216

 - DEPRECATED: AbanteCart core v.1.2.16 Unparenthesized a ? b : c ? d : e is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in <b>abantecart/htdocs/core/lib/targz.php</b> on line <b>179</b>
2020-04-06 8:18:45 - warning: AbanteCart core v.1.2.16 file_get_contents(): Filename cannot be empty in <b>abantecart/htdocs/core/lib/targz.php</b> on line <b>190</b>`

**Comment by abolabo** [comment]
@BasaraABC please check now
