### ISSUE TITLE
Abantecart shipping is not connecting because of API

### ISSUE THREAD

**Issue by humbertocaron** [abantecart/abantecart-src#1313]
![DE24F4FC-2988-442B-81CA-7086FD83292F](https://user-images.githubusercontent.com/60042796/72670112-aa072b00-3a07-11ea-96bc-acb3f6d4f439.jpeg)
![F57DD724-94C9-46CA-8DC8-B095722645D7](https://user-images.githubusercontent.com/60042796/72670113-aa072b00-3a07-11ea-8078-664924cce816.jpeg)

**Comment by abantecart** [comment]
Please indicate how is this a bug? We need technical details to this issue.

**Comment by BasaraABC** [comment]
Make sure your Fedex account is live and you use valid credentials
