### ISSUE TITLE
installation wizard: deprecated extension

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1315]
Please remove deprecated extension from the "Quick Start Wizard". (or replace with any available)
Also please change 1.2.15 version to 1.2.16
![payza](https://user-images.githubusercontent.com/2631910/74122815-13d9b580-4bff-11ea-9773-380fcb103406.jpg)

**Comment by BasaraABC** [comment]
Issue is not fixed.

**Comment by BasaraABC** [comment]
Issue is not fixed. Again

**Comment by abolabo** [comment]
What means "again"?
