### ISSUE TITLE
dev: cardconnect not work in test mode

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1317]
Test credentials from https://support.cardconnect.com/gateway-test-credentials
![cardconnect](https://user-images.githubusercontent.com/2631910/77526983-03834e80-6ebe-11ea-957c-0308b2811ce7.jpg)

**Comment by abolabo** [comment]
please retest with real site domain!

**Comment by BasaraABC** [comment]
Please check before closing tickets. Same issue on live domain
<img width="764" alt="www" src="https://user-images.githubusercontent.com/2631910/77749816-41ff4180-7055-11ea-8530-0913fa0ec333.png">

**Comment by BasaraABC** [comment]
Please change extension version to 1.0.2

**Comment by abolabo** [comment]
why? I already changed from 1.2 to 1.2.1

**Comment by BasaraABC** [comment]
https://github.com/abantecart/abantecart-src/blob/1.2.16/public_html/extensions/cardconnect/config.xml#L4 please change extension version

**Comment by abolabo** [comment]
https://github.com/abantecart/abantecart-src/commit/213c18e5d06fabf7322d91c57f3dd724d1fbf9fa
