### ISSUE TITLE
Totals recalculation 1.2.2 issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#132]
Total is not recalculated when changed low order fee value see screen
![122-issue5](https://cloud.githubusercontent.com/assets/2631910/7585122/f5b7cfa4-f8cc-11e4-87f2-d62e2627a940.png)
(Note: order is new)

**Comment by abantecart** [comment]
Can you please confirm that this is not old order? Remember that recalculate will use setting value not what you entered.

**Comment by abantecart** [comment]
We will need to update this document after release. This area becomes touchy
http://www.abantecart.com/ecommerce-documentation/user-manual/admin-user-manual/sales-menu/orders/orders

**Comment by abantecart** [comment]
What is the free amount setting in  low_order_fee?

**Comment by abantecart** [comment]
Fixed. Please retest
