### ISSUE TITLE
dev: email templates

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1326]
Default cart installation with the demo data. All templates have a date in the "Allowed Placeholder" field.

Also "Subjects" contain html tags. 
![allo](https://user-images.githubusercontent.com/2631910/78652324-c5d5eb00-78eb-11ea-943e-be2bc39baf26.jpg)

![html](https://user-images.githubusercontent.com/2631910/78652541-0f263a80-78ec-11ea-9a11-a54a3bab344d.jpg)

**Comment by vdvpie22** [comment]
Please reinstall
