### ISSUE TITLE
Product page thumb images misplaced if enable right column

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#133]
images misplaced if enable right column
![columnissue](https://cloud.githubusercontent.com/assets/2631910/7628181/66c1fcdc-fa4a-11e4-87e3-07da4cc661ac.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
You fix is wrong. Please see how it look on abc 1.2.1
![thumb](https://cloud.githubusercontent.com/assets/2631910/7652054/e9ed7842-fb31-11e4-9ad1-b870507b15ae.png)

**Comment by abolabo** [comment]
I have no another solution. There dynamic image width. Please close this ticket. 
Minor Issue.

**Comment by abantecart** [comment]
Wait. Let's check again

**Comment by abantecart** [comment]
Keep it open for 1.2.3

**Comment by abantecart** [comment]
Found better solution. 
https://github.com/abantecart/abantecart-src/commit/5f533e804fcf79a1519542ee417eaa64175dbb3e
