### ISSUE TITLE
registration redirect

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1333]
Full site registration redirect to embed mode page
![embed222](https://user-images.githubusercontent.com/2631910/78769726-eb302b00-79b7-11ea-982c-b73a737148f2.jpg)

**Comment by abolabo** [comment]
cannot to replicate. Looks like you did it once after "embed" testing

**Comment by BasaraABC** [comment]
Yes, I did test embed before. So "embed" was left in cookies, why not clear or ignore it if full site visited?

**Comment by abantecart** [comment]
Very rare case
