### ISSUE TITLE
Global search improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#134]
global search can't found retina Setting
![glsearch](https://cloud.githubusercontent.com/assets/2631910/7628310/e8869dd0-fa4b-11e4-884f-b3742f9a0490.png)

**Comment by abolabo** [comment]
i think it's enough.

**Comment by BasaraABC** [comment]
It is not enough. Global search should find setting and not only language definitions

**Comment by abantecart** [comment]
Additional observations.

1. Only 1 settings match is shown in quick search
2. In advanced search all tabs are missing. Only Language is present
