### ISSUE TITLE
RL linked to incorrect for Downloads

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#135]
RL did not show 'Linked to' info for Download resources
![rl](https://cloud.githubusercontent.com/assets/2631910/7651750/14339900-fb2e-11e4-9b8f-2ffb275d28aa.png)

**Comment by abolabo** [comment]
changed. Note: it's a "single" mode of RL here. That's mean non-mapping method of assigning of resource to object(download). I changed dropdown display. Now it will shown only for case when mode is not single or count of linked objects to resource greater than 0.

**Comment by BasaraABC** [comment]
Thank you.
