### ISSUE TITLE
dev local delivery: do not allow order confirm with empty phone

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1366]
<img width="844" alt="2020-04-15_17-12-51" src="https://user-images.githubusercontent.com/2631910/79326109-871fe080-7f3c-11ea-8a90-c4b2937db3cb.png">

**Comment by abolabo** [comment]
Cannot to fix this, because form of payment (with payment buttons) is dynamic. It built by payment controller and can send request on the 3d-party host. But not sure is it issue, because case only for already registered customers, not guests.
