### ISSUE TITLE
Issues running Abantecart with Apache non-default ports

### ISSUE THREAD

**Issue by gongomgra** [abantecart/abantecart-src#1371]
Hi,

I'm having the exact same issue reported in [#889](https://github.com/abantecart/abantecart-src/issues/889) with ports 8080 and 8443, in latest Abantecart version 1.2.15. I'm using the next components to run Abantecart

* Apache 2.4.43
* PHP 7.3.15
* MySQL 8.0.18

According to the linked issue, it seems it was fixed for version 1.2.11, but I have reproduced the error in that version as well when not using Apache's default ports. Can you tell me if I need to do some specific configuration to work with non-default ports? I took a couple of screenshot of my current installation

![Screenshot 2020-04-17 at 11 35 41](https://user-images.githubusercontent.com/6660452/79555549-11cd2080-80a0-11ea-82e4-0908a842bb7e.png)

![Screenshot 2020-04-17 at 11 32 14](https://user-images.githubusercontent.com/6660452/79555558-15f93e00-80a0-11ea-9926-14c70bf72dcb.png)

**Comment by abantecart** [comment]
@gongomgra Since you have 2 sets of ports for a website and images, is your Apache configured correctly for port 8080? Can you access site with port 8080?

**Comment by abolabo** [comment]
there is no bug. Please set correct port for https store url
