### ISSUE TITLE
Overriding store descriptions with empty source text from another language

### ISSUE THREAD

**Issue by abolabo** [abantecart/abantecart-src#1375]
1. Install second language.
2. Open settings ->store details and 
 - set second language as Source language for translation
 - switch "Override if source language text was changed" to ON
3. Switch to second "content" language and try to save store title with 1 whitespace.

Bug - First language overrided with empty value.

**Comment by BasaraABC** [comment]
Issue is not fixed.
1. install second language Italian for example
2. go to default store settings and set Source Language: Italian and Override if source language text was changed: ON
3. Create new store with "Copy default setting"
4. Bug: In new store you cant save Title in English. Save and reload to see it is always replaced with Italian (source language). 
Note: issue is not visible in default store
