### ISSUE TITLE
dev: webp images support

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1380]
@abolabo please check can we add webp format support (upload to RL and resize)
https://forum.abantecart.com/index.php/topic,8410.msg33458.html#msg33458

**Comment by BasaraABC** [comment]
I have error when upload images to RL. Also RL is broken after upload. Test files attached
<img width="773" alt="broken" src="https://user-images.githubusercontent.com/2631910/80805434-38cc3c00-8be2-11ea-9ba7-c31cfe8f7435.png">

[testfiles.zip](https://github.com/abantecart/abantecart-src/files/4564129/testfiles.zip)

`AbanteCart core v.1.2.16 Call to undefined function imagecreatefromwebp() in <b>/core/lib/image.php</b> on line <b>128</b>`

**Comment by abolabo** [comment]
php version?  GD2 version?

**Comment by BasaraABC** [comment]
PHP Version 7.4.4
GD Support | enabled
GD Version | bundled (2.1.0 compatible)

**Comment by abolabo** [comment]
weppy support still buggy in php.
