### ISSUE TITLE
product page rewiews

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1382]
Please show review text (product page tab) if **Display Reviews**  is ON
<img width="728" alt="aaaa" src="https://user-images.githubusercontent.com/2631910/80706322-5336e480-8b12-11ea-8096-d04b6f4e985d.png">

**Comment by abolabo** [comment]
please give more details how to replicate it.

**Comment by BasaraABC** [comment]
To replicate follow the settings you see on screenshot.
Display Reviews: ON
Post Reviews: Customer with verified order
Then go to storefront and visit product with the review as Guest for example. You will find that Guest can not see review text.
