### ISSUE TITLE
Usability problem when Email Activation for New Customers: ON

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#139]
to replicate:
1. set <b>Email Activation for New Customers</b> setting : to ON
2. Visit SF
3. Add any product to cart
4. Click checkout you will be prompted to register new account
5. Fill registration form and submit
6. On next step nothing happen you will be redirected to login page
 Actually issue: missed message about  like "To complete your registration, please visit url .....in  activation email"
Please note: issue visible only if try to checkout first. In case you start registration without checkout everything works fine.

**Comment by abantecart** [comment]
Fixed.
