### ISSUE TITLE
webp animated

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1390]
Animated webp are not resized and errors in the log.
[examples.zip](https://github.com/abantecart/abantecart-src/files/4573588/examples.zip)

`warning: AbanteCart core v.1.2.16 imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in <b>/1.2.16/core/lib/image.php</b> on line <b>128</b>`
<img width="554" alt="animated" src="https://user-images.githubusercontent.com/2631910/80949331-0dce2c00-8e1e-11ea-8f4f-c577d76346b1.png">

**Comment by abolabo** [comment]
gd2 does not works with animated weppies yet.
