### ISSUE TITLE
Problem extension zone

### ISSUE THREAD

**Issue by choi-ui** [abantecart/abantecart-src#1391]
Me want state plugin configuratione. Type zones. Please help 

- 1.2.15
- firefox, ie, chromium

https://abantecart.atlassian.net/wiki/spaces/DOC/pages/17956965/Extension+configuration+file
`<settings><item id="pickup_state">
   <type required="true">zones</type>
</item>`
![state extension xml](https://user-images.githubusercontent.com/64821733/81031915-330f7880-8eb8-11ea-9b8e-bb1d63f6d701.png)

**Comment by abolabo** [comment]
Thank you for your report.
Please use this
		```
<item id="pickup_state_country_id">
			<type>zones</type>
			<submit_mode>id</submit_mode>
			<zone_field_name>pickup_state_zone_id</zone_field_name>
			<default_zone_value>3613</default_zone_value>
			<default_value>3613</default_value>
		</item>
```
inside into your config.xml file.

Note: this solution will be works only v1.2.16 + 
Release of it will be very soon.

**Comment by BasaraABC** [comment]
@abantecart, @choi-ui  please check if issue is fixed.
