### ISSUE TITLE
Problem extension zone model

### ISSUE THREAD

**Issue by choi-ui** [abantecart/abantecart-src#1392]
Extension xml config file manual empty 
https://abantecart.atlassian.net/wiki/spaces/DOC/pages/17956965/Extension+configuration+file
How to receive zones?

```
<item id="pickup_state">
      <type required="true">selectbox</type>
      <variants>
        <item>0</item>
        <data_source>
          <model_rt>localisation/zone</model_rt>
          <method>getZonesByCountryId</method>
<country_id>1</country_id>
        </data_source>
        <fields>
          <field>zone_id</field>
          <field>name</field>
        </fields>
      </variants>
</item>
```

php error Too few arguments to function ModelLocalisationZone::getZonesByCountryId(), 0 passed in admin/controller/pages/extension/extensions.php on line 433 and exactly 1 expected in /admin/model/localisation/zone.php on line 234

**Comment by BasaraABC** [comment]
Hi. Could you please provide you AbanteCart and PHP versions?

**Comment by abolabo** [comment]
you cannot to use this method of model. This method requires at least one filtering parameter. Such methods not supported here. See #1391 for solution
