### ISSUE TITLE
multi-store critical: hide categories from another store

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1395]
If product assigned to store 2 do not allow to add (hide) categories assigned to store1.
see screenshot
Make sure to clear AbanteCart cache.
<img width="888" alt="multost" src="https://user-images.githubusercontent.com/2631910/81051377-c9a95d00-8eeb-11ea-95a2-966168711859.png">

**Comment by BasaraABC** [comment]
"Unknown" issue appear in case product assigned to both stores
<img width="827" alt="2020-05-06_15-53-06" src="https://user-images.githubusercontent.com/2631910/81158143-e3ad7300-8fb1-11ea-8550-d4461b62d8bf.png">

**Comment by BasaraABC** [comment]
When admin go to Catalog > Products critical error
`QL Error: Unknown table 'abantecart.cs'
Error No: 1051
SQL: SELECT c.*, cs.* FROM kd_categories c LEFT JOIN kd_category_descriptions cd ON (c.category_id = cd.category_id) WHERE c.parent_id = '0' AND cd.language_id = '1' ORDER BY c.sort_order, cd.name ASC PHP call stack: #0 htdocs/core/lib/db.php:100 #1`

**Comment by BasaraABC** [comment]
Issue is not fixed. 
To replicate: 
1. Open product from default store and assign it to New
2. Go to catalog > categories. Switch to new store and create one category
3. go to product from step one to see the "unknown" issue
<img width="1193" alt="fix" src="https://user-images.githubusercontent.com/2631910/81529474-1cba5e80-9389-11ea-8149-24a5f2ff7e06.png">

**Comment by BasaraABC** [comment]
Kindly ask you to check you changes. Again critical areas are broken.
Can not create a new product
![cart broken](https://user-images.githubusercontent.com/2631910/81562412-fdd6bf00-93be-11ea-9e34-2645b7236462.jpg)

**Comment by BasaraABC** [comment]
@abolabo please test well. Issue again not fixed. 
[video.mp4.zip](https://github.com/abantecart/abantecart-src/files/4626801/video.mp4.zip)
<img width="963" alt="default" src="https://user-images.githubusercontent.com/2631910/81908406-63ab8c80-95f3-11ea-8754-7f4343eedb6e.png">

**Comment by abolabo** [comment]
i tried to replicate on your testcase site and it's not works as on your video. With same product and the same substore

**Comment by BasaraABC** [comment]
Don't you think that it is categories cache related?

**Comment by BasaraABC** [comment]
Very easy to replicate. See my screen record with fresh install
[replicate.mp4.zip](https://github.com/abantecart/abantecart-src/files/4632453/replicate.mp4.zip)
