### ISSUE TITLE
new setting Generate high-res (retina) images issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#140]
When <b>Generate high-res (retina) images</b> is ON few issues on storefront:
1.  menu category's image is shown twice bigger (120x120 images scaled to 240x240 - on retina should be vise versa 240x240 images scaled to original size 120x120). Note to see issue please clear abc and browser cache
2. Similar issue for brand image on product info page - 57x57 images scaled to 114x114 on retina display
3. Image thumbnail on product info page are not retina. Please generate high-res images for them too

<em>please see screen for issue1</em>
![retina1](https://cloud.githubusercontent.com/assets/2631910/7701563/9f3c7b4e-fe52-11e4-866e-0617f6b92c8a.png)

**Comment by BasaraABC** [comment]
by the way I suggest to enable this setting by default for new demo 1.2.2

**Comment by BasaraABC** [comment]
2 and 3 are not fixed

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
high-res (retina) images is broken in 1.2.3
Note: setting enabled and .htacess.txt renamed to .htaccess  and cache cleared
![retin](https://cloud.githubusercontent.com/assets/2631910/7958262/f607b4cc-0a17-11e5-9e61-bea7d9f3cab4.png)

P.S
Please do not close issues. I will close them after checking fixes.

**Comment by BasaraABC** [comment]
I think this is something related to cache. When I disable Hi-res images and clear cache - so new images not created

**Comment by abolabo** [comment]
did you changed rewrite base inside .htacces file?

**Comment by BasaraABC** [comment]
Issues fixed. Can you please update Hi-res setting note regarding to rewrite base.
