### ISSUE TITLE
grid filters issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1402]
If filter grid by name but include few spaces before name the filters stop work. Please remove the spaces when search or filter in all grids
![loading](https://user-images.githubusercontent.com/2631910/81670777-4d29f780-9472-11ea-987e-0239e36009de.jpg)

**Comment by abantecart** [comment]
Minor issue (bug in JQgrid). The fix will require an upgrade for JQgrid and substantial testing.

**Comment by BasaraABC** [comment]
Please apply fix to all grids

**Comment by abolabo** [comment]
fix was global. Where i missed something?

**Comment by BasaraABC** [comment]
It does not work in the Customers grid
<img width="710" alt="grid" src="https://user-images.githubusercontent.com/2631910/105964931-70a2da00-60b5-11eb-84c7-dbb40053c6a2.png">
