### ISSUE TITLE
extensions install changes files permissions

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#1403]
On forum there is this posting:
http://forum.abantecart.com/index.php/topic,8437.msg33562.html#msg33562
Want to get your response to what our testing revealed.  

Today I tried several ways of installing one of our extensions, AddThis in AbanteCart v1.2.15. 
The originating files are set to 0644 and the folders are set to 0755.
1. Installing via FTP with our original files from our development the files remain set to 0644 and folders to 0755.
2. Installed via Extensions Upload (after downloading the files to a PC from MarketPlace) the files remain set to 0644 and folders to 0755.
3. Installing via a key the files and the folders are set to 0777.

So why/how are the files folders being changed?  Is this an issue within the network install? Can we add some parameter to our extensions to override this?

thanks
Lee

**Comment by abantecart** [comment]
Hello Lee,

Web-based Installation required files ad folders to be writable for the user who performs the operation. That is specific to each web server and OS configuration. We can not control this on the application level. 
For this reason, files and directories are set to 777. This is not required for all cases.
In some cases, where OS user is the same as web server permitted user, 777 will not be required and 644 will be enough. 

These should be addressed with your hosting company or administrator.
