### ISSUE TITLE
Same Page Add To Cart Feature

### ISSUE THREAD

**Issue by Formatado** [abantecart/abantecart-src#1405]
Hello!

I think there are some issues with that feature, ON or OFF always redirect to cart.

Abantecart 1.2.16 with default template
Local installation with xampp php 7.4.3

**Comment by abantecart** [comment]
Hello,

Can you please provide steps to reproduce this problem.  Please include screenshots if possible.

Thank you

**Comment by Formatado** [comment]
Admin side > System > Settings > Checkout
Scroll down... Same Page Add To Cart feature (select ON)

Go to frontpage and add a product to cart (always redirect to cart)
