### ISSUE TITLE
 AbanteCart galery resources trouble

### ISSUE THREAD

**Issue by roocky2** [abantecart/abantecart-src#1406]
Hi!

Im sorry for the level of this question but suddenly my image galery went blank and Im unable to either upload nor download images from it! 

I was uploading a png image and it all happened, I already cleared cache, deleted the image in cuestion from the cpanel, however the problem persist.

What can I do?

**Comment by abantecart** [comment]
What is the error you get? Any disk issues?

**Comment by BasaraABC** [comment]
Check the latest errors in /system/logs/error.txt and in the Cpanel server log.
What is your AbanteCart version?

**Comment by BasaraABC** [comment]
No details provided. Closed
