### ISSUE TITLE
Email templates - disable visual editor

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1410]
Please disable visual editor. See if we can add modal with HTML preview

**Comment by BasaraABC** [comment]
To discuss: we can enable most of HTML tags only for Email templates see https://stackoverflow.com/a/6267161

**Comment by abolabo** [comment]
There is no any tags restrictions for html.
Please give me examples what template broke

**Comment by BasaraABC** [comment]
Try **storefront_order_confirm** template. 
See quick comparision - template broken and a lot of removed after switch to Visual editor
<img width="1222" alt="2021-01-28_13-59-06" src="https://user-images.githubusercontent.com/2631910/106101813-064f6f80-6171-11eb-8bc6-4d15479f4410.png">

**Comment by BasaraABC** [comment]
One more thing the variables tags can be double and triple `{{var}} `or `{{{var}}}`

**Comment by BasaraABC** [comment]
Please return the toolbar to the Editor (not to Design > Templates)
<img width="1908" alt="2021-01-29_18-08-56" src="https://user-images.githubusercontent.com/2631910/106268191-53107480-625d-11eb-9eff-4203e0ae5b46.png">
