### ISSUE TITLE
Scrollbars for modal popup window showing Privacy Policy

### ISSUE THREAD

**Issue by rdasilva1** [abantecart/abantecart-src#1411]
Hello
We are Using abantecart 1.2.16 with Foxy Template. We are almost ready to open store.
Today we were doing final testing and noticed an issue on the customer signup page.

When a customer is creating a new customer account, at the bottom of the screen
there's the checkbox which a customer should click to agree to the Privacy statement.

Right in front of this checkbox, there's a link to the Privacy statement text.
When the customer clicks this link, a modal popup window is shown on the screen,
displaying all text of the Privacy statement.

Our Privacy statement has a lot of text, and only half of that can be read in the modal
popup window.  On my iphone 11 the policy is even less visible.

We Tried this in MS Edge, Chrome, Brave in Windows10Pro and in Safari on iphone11
How can we fix this issue.

Thanks
Rui

**Comment by abantecart** [comment]
Please provide visuals. Image or URL

**Comment by rdasilva1** [comment]
https://silviosfarm.com/store/index.php?rt=account/create

Thanks

**Comment by BasaraABC** [comment]
Hello. Please contact theme developer. There is no issue in the default AbanteCart template
