### ISSUE TITLE
Not getting an email with content from Contact form

### ISSUE THREAD

**Issue by barry819** [abantecart/abantecart-src#1413]
This is a problem that has appeared since upgrading from 1.2.15 to 1.2.16. There was not a problem prior to the upgrade.

When a customer leaves a message via the contact form on my site, I am sent an email that tells me that a customer left a message through the form. But I no longer receive the separate email that contains the content of that message, as was the way it worked under 1.2.15. That separate message allowed me to respond directly to the inquiry. The email address of the person who left the message via the contact form was contained in that email as the "reply to" address.

I can go into the message center and see the message that was left, but cannot reply from there, so replying involves a lot of cutting and pasting in a multi-step process. The old way in which I received a copy of the message was much more practical and efficient.

I've tried everything I can think of to fix this, but am stumped. I am getting all other system emails normally. I have tried re-saving all my email templates. I have made sure all are turned on. Neither of these steps helped.

If I understand this correctly, the email in question is the one linked as storefront_contact_us_mail. That one is not being generated and mailed when a customer leaves a message.

My email server was compatible before, and remains compatible for all other emails. So I have to believe there is something in the code that is causing this specific email to not be generated to be sent to me.

I am not a programmer. I am a user who can do all the things that are accessible through the dashboard, but not rewrite or edit code unless you give me VERY specific instructions. 

I can download and attach a copy of any program file IF you tell me its name and what directory to find it in.

**Comment by abantecart** [comment]
I found this on the forum https://forum.abantecart.com/index.php/topic,8600.15.html

@abolabo Please try to reproduce this problem.  Thank you

**Comment by barry819** [comment]
Yes, I tried there but the person attempting to reply was not at all helpful and the problem persists. I did everything that dvagner suggested and none of it addressed the problem. At the end he (or she?) just told me to pay for support instead of actually addressing all the evidence I supplied.

As I said, I have tried many different approaches and it all comes down to there being something in the programming that is beyond my ability to fix. The problem is not my email server, because if that was the case I wouldn't get any emails, and I am getting all the system emails except for one specific type, the storefront_contact_us_email with the content of a message sent by a customer through the Contact Us form on the website.

**Comment by BasaraABC** [comment]
Hello. Try to disable Mod_security to check is any false positive rules triggered
https://abantecart.atlassian.net/wiki/spaces/AD/pages/3604484/Mod+security+403+406+error

**Comment by barry819** [comment]
BasaraABC, can you tell me what to look for when I request that of my hosting provider? What would be a "false positive"? 

I don't understand how a security measure could be interfering with only one specific type of email being sent to me by the system.

**Comment by BasaraABC** [comment]
Hello barry819. In our tests AbanteCart 1.2.15 upgraded to 1.2.16 have worked "contact us" email so it is something on your side:
1. mail provider issue (outlook for example known for such things https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-not-sending-to-certain-email-addresses/56130066-e7ea-48e7-8aed-507eefdc6381)
2. mail sender issue (SMPT or hosting PHP mailer)
3. mods installed on your hosting like mod_security known to stop/block scripts execution without any notices to site owner...

AbanteCart is software and we can't predict what server or mailer settings you have. To find out we suggest you check mailer logs, server logs or disable temporary firewall, mod_security just to make sure they not affect

**Comment by BasaraABC** [comment]
This issue was closed because it has been inactive.
