### ISSUE TITLE
ant messages mark read

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1416]
Show ! near icon if message unread and do not show if ant message was already read, also make sure do not show read messages 
![unread](https://user-images.githubusercontent.com/2631910/90005529-8c5e2380-dcc1-11ea-96fc-08d159ab7109.png)

**Comment by BasaraABC** [comment]
The issue is not fixed correctly. All messages (unread) never appear

**Comment by abolabo** [comment]
how did you checked?

**Comment by BasaraABC** [comment]
Install the cart and go to admin unread messages are never showing up.
Here is a screenshot from 1.2.16
<img width="790" alt="2021-01-28_14-22-05" src="https://user-images.githubusercontent.com/2631910/106114989-d5783600-6182-11eb-8733-2fb94ec9cbab.png">

**Comment by abolabo** [comment]
![image](https://user-images.githubusercontent.com/1264239/106135104-26326380-6170-11eb-8c9b-503b11053311.png)

**Comment by abolabo** [comment]
after reinstall it shows me all unread messages. Bell badge indicates when at least one unread message presents (column of viewed=0 of table ant_messages). When you click at icon page sends ajax-request and marks message as read.
works fine

**Comment by BasaraABC** [comment]
As requested please make sure do not show read messages. See video the read message shown (Chrome 88)
https://user-images.githubusercontent.com/2631910/106561384-26a97080-655b-11eb-981f-1b13da2118a4.mp4
