### ISSUE TITLE
adblock improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1417]
[more modern browsers](https://lifehacker.com/the-best-browsers-for-ad-blocking-that-arent-chrome-1835130559) have built-in adblockers please remove the "Adblock" warning in admin and find a solution for stats 
<img width="1185" alt="dash" src="https://user-images.githubusercontent.com/2631910/90009284-faa5e480-dcc7-11ea-9012-1772f01bb689.png">

**Comment by abolabo** [comment]
1. What browser do you use on screenshot?
2. why we should do that?

**Comment by BasaraABC** [comment]
Opera and other Chromium browsers. 
We need to remove the annoying "Ads block is enabled in your browser." message in admin
<img width="804" alt="opera" src="https://user-images.githubusercontent.com/2631910/105947712-311bc400-609c-11eb-9b97-96e260a4bda0.png">
