### ISSUE TITLE
minor issue Admin-Design-Menu edit page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#142]
![menu](https://cloud.githubusercontent.com/assets/2631910/7703861/e632746a-fe64-11e4-9bb0-064b921047c3.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
your fix broke something. After new menu created all fields are empty
![broken](https://cloud.githubusercontent.com/assets/2631910/7958171/e6cf199c-0a16-11e5-8ad7-edf03464039e.png)

**Comment by abolabo** [comment]
fixed
