### ISSUE TITLE
SEO URL database limit

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1428]
When the length of the SEO URL in the cloned product too large (>250) the SQL error appears on the clone action
![dubl](https://user-images.githubusercontent.com/2631910/95572013-8a130e00-0a53-11eb-8b77-a4e97aa8d628.jpg)

**Comment by BasaraABC** [comment]
Issue is not fixed. 
`2021-01-27 6:43:25 - database error: AbanteCart core v.1.2.17 SQL Error: Duplicate entry '0001-00002-0003-1240001-00002-0003-1240001-00002-0003-1240001...' for key 'ac_url_aliases_idx'
Error No: 1062
SQL: INSERT INTO mm_url_aliases (`keyword`, `query`, `language_id`) VALUES ('0001-00002-0003-1240001-00002-0003-1240001-00002-0003-1240001-00002-0003-1240001-00002-0003-124-1250001-00002-0003-1240001-00002-0003-1240001-00002-0003-1240001-00002-0003-1240001-00002-0003-124-125001-00002-0003-1240001001-00002-0003-1240001001-00-126-12-128', 'product_id=128', '1')
PHP call stack:`

**Comment by abolabo** [comment]
now if seo-key is extremely large it will be replaced to md5 hash

**Comment by BasaraABC** [comment]
Issue once again not fixed. Please test your code
`2021-01-28 8:17:58 - database error: AbanteCart core v.1.2.17 SQL Error: Duplicate entry '00001000-000002-000003-00001000-000002-000003-00001000-000002...' for key 'ac_url_aliases_idx'
Error No: 1062
SQL: INSERT INTO ll_url_aliases (`keyword`, `query`, `language_id`) VALUES ('00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-0000new-1000-000002-000003-00001000-000002-000003-00001000-000002-00-12-126', 'product_id=126', '1')
PHP call stack:`

**Comment by abolabo** [comment]
how to replicate? give me precise data

**Comment by abolabo** [comment]
what seo-key must be for original product?

**Comment by BasaraABC** [comment]
You can see precise data in the erorr above.
Use like this SEO key in the product and then clone it to see bug 
`00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-00001000-000002-000003-0000new-1000-000002-000003-00001000-000002-000003-00001000-000002-00-12-126`

**Comment by abolabo** [comment]
no error for me

**Comment by abolabo** [comment]
may be remove cloninng of seo at all? what the benefit?
