### ISSUE TITLE
embed product 'checkout' not work on phones

### ISSUE THREAD

**Issue by eslamsidereel** [abantecart/abantecart-src#1429]
The embed buttons works great on the pc version and the phone version, but for some reason checking out from my phone gives me this

![Screenshot_20201013-171704](https://user-images.githubusercontent.com/45595948/95880877-46344780-0d78-11eb-8024-0b5f6b38ea44.jpg)

I don't know what's wrong. I can check out from both my desktop and my laptop. I tried clearing cash and cookies but the problem remained.
I will test the embed buttons on a tablet and a different phone and see what will happen.

Sorry for my bad English
PS: I am a graphic designer with very basic knowledge on coding (html, css, js).

**Comment by abantecart** [comment]
I do not think this a bug. 
Just checked on the demo and it works fine on my Iphone. 
https://www.abantecart.com/embed_demo/index.html

I think there is something wrong with a setup of your web server.

**Comment by eslamsidereel** [comment]
Does this means I did something wrong during setup?

I will try to reupload all abantecart files and test it again.

**Comment by abantecart** [comment]
You need to check web server log and AbanteCart log to identify the problem.

**Comment by eslamsidereel** [comment]
I found the problem. It was related to https. I checked my certificates and http redirects and it's working fine now.

Thank you for your time.
