### ISSUE TITLE
misplaced products in Latest block

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#143]
![absolue_eye_precious_cells](https://cloud.githubusercontent.com/assets/2631910/7705385/12bcd79c-fe6e-11e4-912d-56a37d6e612e.png)

**Comment by abantecart** [comment]
I am not able to replicate this in FF or Chrome. Let's keep this until we can replicate this.

**Comment by BasaraABC** [comment]
same issue with Category block reported by forum user http://forum.abantecart.com/index.php/topic,3570.msg15359.html#msg15359

**Comment by abantecart** [comment]
https://github.com/abantecart/abantecart-src/commit/d89b968a8c86f30914d5fe374500e3066a1a03d9

Fixed.
