### ISSUE TITLE
embed firefox: treated as cross-site cookie

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1439]
The Latest Firefox version 82 shows several warnings about the embed cookies. No warnings in the latest Chrome
<img width="1091" alt="cookies" src="https://user-images.githubusercontent.com/2631910/97848167-42666600-1d23-11eb-88b1-287342c4330b.png">

**Comment by abolabo** [comment]
need to retest with latest changes related samesite directive of cookie
