### ISSUE TITLE
Fedex rates and rates with product quanity

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#144]
initial issue reported at forum:
http://forum.abantecart.com/index.php/topic,1192.0/topicseen.html

Looks like when update products quantity in the cart - shipping calculate each product item as separate package
for example pre-configured product  has 1 pound weight and 10x10x10 cm dimensions
If add to cart 1 item - Fedex Ground cost 11.94 (From USA to USA address same state)
if update quantity to 2 items - Fedex Ground cost 23.88 (11.94*2)

I am not 100% sure but according Fedex Documentation see US rates http://images.fedex.com/us/services/pdf/FXG_StandardListRates_2015.pdf
1 lbs (pound) cost - 6.61
2 lbs (pounds) cost - 7.24

<b>Also rates are higher than in official Fedex doc</b>

**Comment by abolabo** [comment]
Is it still actual for 1.2.2? i remember that solved this issue in 1.2.0

**Comment by BasaraABC** [comment]
Yes, both problems are valid

**Comment by BasaraABC** [comment]
More users report issue with Fedex http://forum.abantecart.com/index.php/topic,3697.0/topicseen.html

**Comment by bsmith40** [comment]
Not sure how github works or who is with the developer team for Abante Cart fedex module but just want to stress to the right person we are in a pickle. All our orders are processed through fedex and customers are backing out. We just pointed all our links to the new cart and newslettered our customers not knowing we had this issue.
Does any one know if this is being worked on and when there might be a fix?

**Comment by bsmith40** [comment]
Any news for Fedex rates fix?

**Comment by abolabo** [comment]
will be

**Comment by abantecart** [comment]
I was not able to connect to our sandbox account from extension settings. 

Found 3 more issues/suggestions

1. We need test button to test connection from ext. settings (similar to paypal)
2. Need to show sand box mode background if test mode is on (similar to paypal)
3. Bug with editing values. Error is shown "Warning: Please fill required fields!"
All fields are present. Need to have more clear with an error and highlight of missing field.  
4. Extension enabled in test mode. It is not visible in storefront. If change to live mode, it is present in storefront with connection error.

**Comment by abantecart** [comment]
This is resolved. Now package calculation is based on total volume of all products in the order.

**Comment by BasaraABC** [comment]
Issue fixed but I noticed that only Fedex Ground service allowed for any address, for example from NY to NY or  from NY to island near Alaska only Fedex Ground. Can you please check do we have working other services?
P.S in fedex settings all other enabled
<img width="1379" alt="fedex" src="https://cloud.githubusercontent.com/assets/2631910/8796058/024e92cc-2fbc-11e5-967c-8a721fe1156c.png">

**Comment by bsmith40** [comment]
Should this be in extension update yet?
  ----- Original Message -----

**Comment by bsmith40** [comment]
Will this be in extension updates soon, I'll try it out.
  ----- Original Message -----

**Comment by abantecart** [comment]
There is a message from Fedex that services are temporarily unavailable:

                    [Message] => Rating is temporarily unavailable for one or more services:
PRIORITY_OVERNIGHT; STANDARD_OVERNIGHT; FEDEX_2_DAY_AM; FEDEX_2_DAY; FEDEX_EXPRESS_SAVER; ; ; ; ; ; . Please try again later. 
                    [LocalizedMessage] => Rating is temporarily unavailable for one or more services:
PRIORITY_OVERNIGHT; STANDARD_OVERNIGHT; FEDEX_2_DAY_AM; FEDEX_2_DAY; FEDEX_EXPRESS_SAVER; ; ; ; ; ; . Please try again later.

**Comment by abantecart** [comment]
This is not an issue
