### ISSUE TITLE
Abante Cart upgrade crash

### ISSUE THREAD

**Issue by rxandr** [abantecart/abantecart-src#1440]
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/xxx/public_html/xxx.COM/core/lib/PaymentHandlerInterface.php on line 22

**Comment by abantecart** [comment]
There is no such file in the source https://github.com/abantecart/abantecart-src/tree/master/public_html/core/lib

**Comment by rxandr** [comment]
Nay, iThink iFailed to upgrade previous versions first. Definitely didn't make it up=)
