### ISSUE TITLE
task_api.php

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1444]
Initial post https://forum.abantecart.com/index.php?topic=8808.0#msg35040
### 1. Running a task from task_api cron causes an error which can be found in the error log:
`Use of undefined constant RDIR_TEMPLATE - assumed 'RDIR_TEMPLATE'`

**Comment by abolabo** [comment]
to run all tasks needs to run command

task_cli.php run --force-all

**Comment by BasaraABC** [comment]
Copy language definitions from one language to another give the task_api errors
<img width="1278" alt="app" src="https://user-images.githubusercontent.com/2631910/107184908-06265e00-6a14-11eb-9c1f-3bfd63f1aa84.png">
