### ISSUE TITLE
Optimize demo images

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#145]
https://developers.google.com/speed/pagespeed/insights/?utm_source=MFT&utm_campaign=MFT&utm_medium=incoming-link&priorityGroup=USABILITY&url=http%3A%2F%2Fdemo.abantecart.com%2F&tab=desktop

![optimize](https://cloud.githubusercontent.com/assets/2631910/7810752/0a09f4de-03cf-11e5-8f0b-b74e8f5bfe2f.png)

**Comment by abantecart** [comment]
This is not a simple solution as it consists of code + server components. We can not address this as of yet.

**Comment by abantecart** [comment]
Looking for alternative resize approach ....

**Comment by BasaraABC** [comment]
at least we need optimize DEMO images manually...?

**Comment by abolabo** [comment]
it doesn't matter. original image will be resize to non-optimal thumbnail. need to solve on "image" class level

**Comment by abantecart** [comment]
Solution is straight forward and not stable. More research required.

**Comment by BasaraABC** [comment]
note: was optimized images in resources directory.
the images created after installation  (public_html/image/thumbnails) are not optimized
