### ISSUE TITLE
PHP8 and v1.3.0 email issue

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1457]
Hi admins,

We have started testing cart v.1.30 beta using PHP 8. When using default PHP mail we find that the email sent was using the text format email instead of html format.

![Snag_12f904e9](https://user-images.githubusercontent.com/225439/112923159-f4ba2200-9137-11eb-8aa8-84bc15ef40e1.png)

But if we use SMTP, we get the correct html format email.
![Snag_12ff8e50](https://user-images.githubusercontent.com/225439/112923701-f3d5c000-9138-11eb-86dd-af220eb23833.png)

Both Php 7.3 and 7.4 work correctly with either email setting.

**Comment by BasaraABC** [comment]
Thank you for sending the bug report

**Comment by abolabo** [comment]
unfortunately i cannot to replicate this bug.
My configuration is 
php8.03
mailer - php mail

What inner mailer (sendmail) do you use?

**Comment by handoyo** [comment]
Hi abolabo,

We have consult with our hosting provider about the malformed email. They found out that there was extra white space in front of the headers.

![image](https://user-images.githubusercontent.com/225439/124418248-3e448980-dd85-11eb-896a-984eeef34d4d.png)

I attach the screenshots between the broken and the working:

broken: 
![broken](https://user-images.githubusercontent.com/225439/124420467-b90fa380-dd89-11eb-8d16-29a5783c786b.png)

working:
![working](https://user-images.githubusercontent.com/225439/124420737-33402800-dd8a-11eb-9c1c-317a2e1160f1.png)

We didn't change anything but the php version,  the failure is only on PHP 8.

**Comment by abolabo** [comment]
@handoyo  please check this solution and let us know
https://github.com/abantecart/abantecart-src/commit/e628f29e9accacc862266f6c8a1b70445a835e95

**Comment by abolabo** [comment]
btw still cannot to reproduce this issue on my host

**Comment by handoyo** [comment]
@abolabo I have tried your solution and cleared the cache after apply the fix, but i still get the malformed email. 

Then i try to change 

`public $newline = "\n"; `

to  

`public $newline = "\r\n";`

and it works.

Do you think that is a correct solution or do you have other better solution

**Comment by abolabo** [comment]
I afraid your fix will cause an issues on windows systems. 
What about table email_templates, column headers? Do you have some data there?

**Comment by handoyo** [comment]
What is your thought?

I didn't change the default email template and headers.

**Comment by abolabo** [comment]
Can you try replace `public $newline = "\n"; ` with this `public $newline = PHP_EOL; ` ?

**Comment by handoyo** [comment]
I have test using `public $newline = PHP_EOL;` , cleared the cache and i still get the malformed.

**Comment by abolabo** [comment]
We think it's a issue of mail server. Not related to PHP8 and AbanteCart.
Regarding RFC we should to use \r\n, but some mailers think it's a wrong format.  
We prefer to follow the standards. 
Looks like you have a "qmail" on host as mailer. Btw i found a lot of complaints on mailer such this regarding \r\n symbols.
[https://www.php.net/function.mail#40204](https://www.php.net/function.mail#40204)

**Comment by handoyo** [comment]
I have ask our hosting and they are using "exim" as mailer.

**Comment by abolabo** [comment]
i am still confused.  PHP_EOL is \n 
I don't understand why it's not working for you.
What tool to you use to see email is malformed?

**Comment by handoyo** [comment]
I don't know why using the \n doesn't work in php8 but works in php7. And both are n the same server. I download the email as eml format and then open it in editor and found out that it has extra whitespace. Also i get the malformed in my email without using any tools. We have decided to move on by using smtp for now.

Apparently opencart users has the same issue as well. Here are the post:

[https://github.com/opencart/opencart/issues/8968](https://github.com/opencart/opencart/issues/8968)

[https://github.com/opencart/opencart/issues/9385](https://github.com/opencart/opencart/issues/9385)

**Comment by abolabo** [comment]
brrrr.. nuts
btw i use php8.0.7 on my localhost under ubuntu with inner mailer for smtp forwarding to gmail. Looks like gmail can fix outgoing email format or my mailer do this or my php version sends correct emails. 
Have no ideas yet.

**Comment by abolabo** [comment]
@handoyo can you test our fix of core/lib/mail.php file from 1.3.2 branch?
just replace your file with this https://raw.githubusercontent.com/abantecart/abantecart-src/1.3.2/public_html/core/lib/mail.php

**Comment by handoyo** [comment]
Yes i can test it. 

I will test it now and let you know the result.

**Comment by handoyo** [comment]
I'm still getting the ugly format.

![image](https://user-images.githubusercontent.com/225439/142172363-5df3c7ef-6f0f-4ba2-9f86-7702e923c6b2.png)

**Comment by abolabo** [comment]
i see source of email on your screenshot encoded in base64. It should be so.
How do you test email formatting?

**Comment by abolabo** [comment]
What email client do you use?

**Comment by handoyo** [comment]
i test by registering in our testing site using the mail().

i'm using gmail and i get that format in my email body.

**Comment by abolabo** [comment]
@handoyo please answer via PM on our forum

**Comment by handoyo** [comment]
@abolabo i have replaced the lib/mail.php and i still get the same message format in my email.

**Comment by BasaraABC** [comment]
We were not able to replicate it on our server. Can you create a mail account on your mail server and give us access to it (please pm to @abolobo)?

**Comment by handoyo** [comment]
@BasaraABC I have create the email account and send it to @abolabo just now.

Please check it.

**Comment by abolabo** [comment]
@handoyo 
can you set mail.add_x_header to Off on your php.ini configuration?

**Comment by abolabo** [comment]
@handoyo  As you wrote before the cause is in whitespace before some mail headers.
i tried to switch your testcase into smtp mode and emails become valid.
So, issue is in the inner mailer of your host, NOT php-code.
By some reason your inner mailer adds whitespaces. When Abantecart have mail mode as "mail" this mean php use your inner mailer (sendmail etc).

**Comment by abolabo** [comment]
![image](https://user-images.githubusercontent.com/1264239/142425906-f7a7bc9e-ab39-4bb6-90a0-c308cbeaa79e.png)

**Comment by abolabo** [comment]
@handoyo 
i guess i found solution

please replace your file core/lib/mail.php with https://raw.githubusercontent.com/abantecart/abantecart-src/1.3.2/public_html/core/lib/mail.php and test

**Comment by handoyo** [comment]
@abolabo 

I have replace the existing core/lib/mail.php your fix in the testing site (the one that i have share with you).

I tried register and place an order but i didn't get any email for both of them.

And there are no error in the error log file.

**Comment by abolabo** [comment]
@handoyo  i noted your mail-server can send mail only on it's mail-boxes. Looks like some spam-filters works.
i tested with customer email address that you gave for me.

**Comment by handoyo** [comment]
Hi @abolabo ,

Sorry for late reply. 

So what should we do so your fix with our mail-server?

**Comment by abolabo** [comment]
just upgrade cart to 1.3.2. Fix there
