### ISSUE TITLE
Dashboard top icon shown in big size 

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1458]
Hi,

We found another issue while updating from 1.2.16 to 1.3.0 beta using abantecart_upgrade_130.

The top icon is big

![Snag_134e3439](https://user-images.githubusercontent.com/225439/112930677-f211f980-9144-11eb-8f48-b4ccf2c5836c.png)

It gets back to the normal size after i use ctrl + f5 in chrome. This is in Php 7.4.

**Comment by BasaraABC** [comment]
Please clear your browser cache

**Comment by handoyo** [comment]
Hi Basara,

I did tell you I  cleared the browser cache by using ctrl + f5 and it is showing the normal size.

We just want to let you know so admins when updating would not make a lot of posts.

**Comment by BasaraABC** [comment]
Thank you.
