### ISSUE TITLE
Demo data minor issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#146]
Empty record in System-Data-File Uploads section
![fileuploads](https://cloud.githubusercontent.com/assets/2631910/7960479/18605778-0a2b-11e5-92a8-a3c0ae7c073b.png)

**Comment by abantecart** [comment]
Add 1 samples example

**Comment by BasaraABC** [comment]
To see issue install fresh AbanteCart with demo data and visit System-Data-File Uploads section

**Comment by abolabo** [comment]
Problem is in full path of uploaded files in dataset. Core (AFile->getUploadFilePath()) saves full path instead relative. We need to fix it and then we can add some file in demo data. This method used by order and customer attributes extensions too, but only for saving info about uploads. If we decide to change core we need to change files-grid data view on admin side too.

**Comment by abolabo** [comment]
fixed
