### ISSUE TITLE
Missed Content language selector

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#147]
Missed Content language selector in Admin-Catalog-Reviews

**Comment by abolabo** [comment]
table with review does not contain language at all. We cannot filter data by language. Need think about adding this issue into backlog

**Comment by BasaraABC** [comment]
So why when you select admin language to Spanish no review shown? Another bug?

**Comment by abantecart** [comment]
Review is not multilingual. Not a issue.

**Comment by BasaraABC** [comment]
Reopened issue due to my previous comment "So why when you select admin language to Spanish no reviews shown? Another bug?"
<img width="794" alt="comentarios" src="https://cloud.githubusercontent.com/assets/2631910/8588769/8048f1d2-2638-11e5-9ffc-59ef49942883.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Critical error when visit Admin-Catalog-Reviews
"database error: AbanteCart core v.1.2.3 Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
Error No: 1064
SELECT DISTINCT r.product_id, pd.name
FROM 44reviews r
LEFT JOIN 44product_descriptions pd
ON (r.product_id = pd.product_id AND pd.language_id = '1' in <b>/abc123_m07d14/core/database/mysql.php</b> on line <b>114</b>"

**Comment by abolabo** [comment]
was a type. fixed
