### ISSUE TITLE
Hide price in Call for order mode. 

### ISSUE THREAD

**Issue by abantecart** [abantecart/abantecart-src#1470]
Issue you reported on the forume post:

https://forum.abantecart.com/index.php?action=post;topic=9021.0;last_msg=35733

![zHI8MdVvgx](https://user-images.githubusercontent.com/1239995/116070053-200e2f00-a65a-11eb-9f3c-bbcab3976564.png)

**Comment by BasaraABC** [comment]
It is not a bug. The setting "Block Product From Ordering" should put the product to display mode only with no ability to order.  It should not hide price
