### ISSUE TITLE
Default UPS is using the wrong production URL

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1473]
Hi,

I have made some test and found out the production API endpoint for UPS is wrong. It should be:

`https://onlinetools.ups.com/ups.app/xml/Rate`

and not:

`https://www.ups.com/ups.app/xml/Rate`

![ups endpoint](https://user-images.githubusercontent.com/225439/117742503-2215e780-b22f-11eb-9dcb-da6ee7679db7.png)

The UPS Curl error message is referring to the wrong UPS Curl being called by the default UPS extension.

Now i am able to get the rates.

**Comment by handoyo** [comment]
Hi Basara,

I download the doc from [https://www.ups.com/upsdeveloperkit?loc=en_US](url) > Rating. 

![Snag_870d8e81](https://user-images.githubusercontent.com/225439/117762747-e80b0c80-b253-11eb-9e50-220046b80938.png)

You must be logged in in order to be able to download the docs.

And this is XML Rating doc in pdf format:
[Rating Package XML Developer Guide.pdf](https://github.com/abantecart/abantecart-src/files/6456649/Rating.Package.XML.Developer.Guide.pdf)

The info is in page 16.

**Comment by BasaraABC** [comment]
@handoyo could you please try the fix?

**Comment by handoyo** [comment]
@BasaraABC Yes i can try the fix. I will let you know the result.

**Comment by handoyo** [comment]
I have test it and i get the rates.

These are my settings:

![Snag_b23f6f7](https://user-images.githubusercontent.com/225439/125433179-c805146e-181d-4074-a4cf-f0682b54f884.png)

And these are the results: left side is our testing site and the right one is [ups calculator](https://wwwapps.ups.com/ctc/request?loc=en_US)
![image](https://user-images.githubusercontent.com/225439/125433663-5687291f-3da9-40dd-927c-5a81c3d91ca5.png)

**Comment by BasaraABC** [comment]
thank you @handoyo

**Comment by handoyo** [comment]
you're welcome
