### ISSUE TITLE
WordPress 5.8: Collections embed height issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1483]
To replicate the issue please add Collection block with large amount of products to the Wordpress Page. 
Issue visible in latest Chrome v91
<img width="983" alt="2021-07-12_12-59-54" src="https://user-images.githubusercontent.com/2631910/125244190-39e61680-e319-11eb-956e-94f5e4ba43a2.png">

**Comment by abolabo** [comment]
cannot to replicate.
Is URL for collection contains height parameter at the end?

**Comment by BasaraABC** [comment]
height parameter  = 50
<img width="1257" alt="2021-07-14_13-06-16" src="https://user-images.githubusercontent.com/2631910/125571459-ec89f658-e76e-488d-a599-254a0fffa2b7.png">
