### ISSUE TITLE
Login Display Prices OFF block issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1493]
The products are misaligned on the home page when the "Login Display Prices" is disabled in the settings
![login](https://user-images.githubusercontent.com/2631910/131083914-9ca530b5-5eb8-4d44-9fb6-d3030c8ebfd0.png)

**Comment by abolabo** [comment]
@BasaraABC  what is screen size on your screenshot? I cannot to replicate

**Comment by BasaraABC** [comment]
I see it in almost any desktop resolution. Chrome browser 1680x1050

**Comment by HADY2021** [comment]
everything is fine after this update. Thank you guys.
