### ISSUE TITLE
Maximum Weight of Parcel

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1497]
The maximum Weight of the Parcel is not working.
Case: product with weight 350.09 kg added to the cart in quantity 2 (total parcel weight is 700.18 kg)
The Free Shipping extension setup to allow max of 700kg. 
Expected result: Free Shipping is not available in the checkout
<img width="1163" alt="2021-09-16_17-15-43" src="https://user-images.githubusercontent.com/2631910/133595453-aba81ab0-beb3-498a-8401-6a50d7c04f61.png">

**Comment by abolabo** [comment]
cannot to replicate

**Comment by BasaraABC** [comment]
Set Store default Weight class to KG (config_weight_class in rt=setting/setting/details)
Set product weight to 350.09 with weight class KG
Set some shipping extension and  Maximum Weight of Parcel (Kilogram) 700
Add product to cart **with quantity 2** 
Possible it is a cache issue, try to add different products to the cart and go back to the product with 350.09kg X 2 qty

Please see video 

https://user-images.githubusercontent.com/2631910/134119001-3185abda-8f0f-499f-beb6-00b9d696c5a5.mp4
