### ISSUE TITLE
"Wrong Dimensions of product" error

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1498]
Case: one of the shipping extensions has a minimum **weight** limit of 1 kg and **no shippings have the volume limits!**
The customer goes to checkout and can choose from several available delivery methods

### Bug 1: Admin receives the "APP Error: wrong dimensions" in the administration panel 
 in my opinion, he should not receive it because nothing wrong with the dimensions, no volume limits set in any shipping methods so product dimensions are not required

### Bug 2: the title of the error is misleading 
Current message title: "App Error"
The current text: "Wrong Dimensions of the product Product Name grams ID # 51! Trace: #0 /home/htdocs/132sep16/core/lib/cart.php on line 657 # 1 ............."

Suggested message title: "Product # 51 warning"
Suggested text: "Product <a href="...">Product Name #51</a> dimensions inaccurate. " 
and _please hide the trace of all PHP files._ Product configuration warnings do not require such a level of debugging info

### Bug 3: product in the message must have a link 
Please add the clickable link to the product in the message so admin user can quickly find and resolve issue

### To discuss 4: case some enabled shipping method require volume but others not require.
Should we send a warning to the admin in that case?

![2021-09-16_19-05-22a](https://user-images.githubusercontent.com/2631910/133611025-5969a488-7da4-4ba8-8662-6fe1c689d589.jpg)

**Comment by BasaraABC** [comment]
Case: one of the Shipping methods is configured with Volume limits.
Product in the cart (Require Shipping) has missing dimensions (no _length class_ and 2 of 3 dimensions are 0).
_As discussed in the meeting_ in such cases should be notification warning for the administrator "Product dimensions inaccurate...." if the customer attempts to checkout it.
With the latest changes, no notifications were received

<img width="1312" alt="2021-09-22_16-03-08" src="https://user-images.githubusercontent.com/2631910/134316593-0a2452b0-84b1-498d-b853-4e8727077119.png">

**Comment by abolabo** [comment]
i see warning in the messages.

**Comment by abolabo** [comment]
![image](https://user-images.githubusercontent.com/1264239/134318818-e104d65a-6dbf-4692-81c5-21d89375a64c.png)
