### ISSUE TITLE
Minimal order parcel size volume not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1499]
Minimal order parcel size volume in (cubic Inch) = 551 is not work. Visible with Fedex shipment and product with the volume 549 cubic inch
![2021-09-17_13-11-29](https://user-images.githubusercontent.com/2631910/133733587-c9c5c6a6-499d-4068-bb3e-b29b60c9179f.jpg)

**Comment by BasaraABC** [comment]
Issue reopened. Please check with FedEx carrier with min volume limit > 0 and product with 0 volume

https://user-images.githubusercontent.com/2631910/134481626-120f1168-7c54-4d07-a476-c50069273539.mp4

**Comment by abolabo** [comment]
You set minimal volume for parcel, but i cannot to calculate actual volume (all dimensions are zero). Why should i block purchasing here? 
Why we discussing this case again?
We agreed to show message for admin in this case and not set limitation for checkout process.

**Comment by BasaraABC** [comment]
In my opinion, it is wrong to allow to place an order if shipping has minimal volume but the product does not have it (0 or invalid due to missing data), anyway as per the discussion issue closed.
