### ISSUE TITLE
Brands Scrolling List Not Working Correctly

### ISSUE THREAD

**Issue by moedawood** [abantecart/abantecart-src#1508]
Hi 

Not sure if the following bug was logged 

The list of brands wraps to two lines instead of scrolling in firefox and chrome  on version 1.3.1

https://forum.abantecart.com/index.php?topic=9039.0

Please check attached image

![image](https://user-images.githubusercontent.com/62351382/136960080-3154f249-0919-4546-911a-5d19ca286533.png)

**Comment by moedawood** [comment]
Hi 

I see the following fix is not working on abantecart v1.3.2

Please see attached image

![image](https://user-images.githubusercontent.com/62351382/147233154-c64a233f-fa5e-4d10-80ee-b69343f05bc7.png)

**Comment by BasaraABC** [comment]
Works on my 1.3.2
Did you clean the browser cache after the upgrade?
![2021-12-23_20-58-17](https://user-images.githubusercontent.com/2631910/147250646-5ab95447-5ea3-43fe-aff1-ece0e87e4b18.gif)
