### ISSUE TITLE
Sorting setting bug

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#151]
How to replicate:
1. set <b>Default Items per Page (Storefront)</b> to 4
2. set <b>Sort Products as default by</b> to Rating Highest
3. visit Skincare category at SF /index.php?rt=product/category&path=43
4. click to view 2nd page
issue: <b>Creme Precieuse Nuit 50ml</b> product visible on 1st and second page, actually problem in Sorting - on 2nd page admin settings ignored

Also bug reported on forum http://forum.abantecart.com/index.php/topic,3645.msg15649.html#msg15649

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Can you please fix this issue in all listings? 
Manufacturers, specials listings have same issue

**Comment by abolabo** [comment]
fixed
