### ISSUE TITLE
cPanel installation not allowing any image/file uploads

### ISSUE THREAD

**Issue by sumitkm** [abantecart/abantecart-src#1510]
I am a bit new to PHP and AbanteCart so it is possible I am doing something wrong but whatever I try I am unable to get my cart setup to allow file uploads.
![image](https://user-images.githubusercontent.com/578882/141539966-2a2e53d3-17d6-4c51-9c6a-560d275b5c05.png)
I get this whether I try to upload new file or replace existing files.

I checked this [forum link](https://forum.abantecart.com/index.php/topic,4709.msg20522.html#msg20522) and I am very skeptical about setting every resources folder to 0777. Is that the requirement?

I enabled system check and  got errors for index.php and config.php permissions, which I fixed and the errors went away.
![image](https://user-images.githubusercontent.com/578882/141540471-8151b84b-9167-48ae-bf2e-f012d78997f7.png)

I still can't upload images. 

Log files are coming up empty.

My PHP settings
![image](https://user-images.githubusercontent.com/578882/141541005-cc9d38ab-d9a0-41e4-b98b-ff838f8eabc4.png)

My PHP extensions
![image](https://user-images.githubusercontent.com/578882/141541055-81d3e350-a473-47d9-81f4-122f57239877.png)

Any suggestions?

**Comment by abantecart** [comment]
The message is self explanatory. You need to set correct permissions on the files. Permissions needs to be 755 or 655 on php files 
This is not a bug in AbanteCart application. Please refer to AbanteCart forum for help.

**Comment by sumitkm** [comment]
> The message is self explanatory. You need to set correct permissions on the files. Permissions needs to be 755 or 655 on php files This is not a bug in AbanteCart application. Please refer to AbanteCart forum for help.

Thanks, I did set the permissions to the required files and the messages went away. 

I still can't upload files. 

But I have some guesses why, I'll report back here.

**Comment by sumitkm** [comment]
So I finally solved this. It is not an AbanteCart bug, but it will be nice if it is documented and comes up when someone searches for it so here goes.

Essentially when you use cPanel/Softaculous to install Abantee cart you have to select a domain name on which the cart is being installed. So for example http://mydomain.com. However if say you are not ready to point your DNS entries to the new site yet (because it is not ready, you are still setting it up etc) cPanel may allow you do generate site preview URLs via service providers like `skipdns`. Here lies the twist - Services like `skipdns` will give you a temporary URL  and you will be able to see your cart fine. You will be able to update the products, and walk about, add to cart etc. However when you try to update any images, it will fail. It will give the generic error `Some problem happen with file upload. Check error log for more information`. 

This is not a setup issue/permissions issue. You just have to make sure you point your DNS entry to the domain where your cart is setup.

If you are not ready with the domain name, I created a subdomain called staging.mywebsite.com and installed the cart there to test things out.

Hope this helps someone from tearing their hair out for two nights straight :D :D :D 

I haven't used AbanteCart in anger yet, but it looks awesome. So many thanks to the authors and contributors.

**Comment by BasaraABC** [comment]
thank @sumitkm for details
