### ISSUE TITLE
Multistore issue 

### ISSUE THREAD

**Issue by handal59** [abantecart/abantecart-src#1511]
Hello

I have a 2 stores website, cloned my website and upgraded the cloned site to abantecart version 1.3.1 and installed the extensions. 

I have the SEO pack extension from Natani, and below i explain the issue

1- My cart is a 2 store, default store and Wholesale store

2- In the Admin panel If i put in the Settings >> Store setting >> System >> Use SEO URL's to ON on the default store and ON on the wholesale store then all categories links in the wholesale store will refer you to the retail [Default} store, that is, when you are in the wholesale store and click on a category or page in the wholesale category it will take you to the retail store instead of taking you to the required page in the wholesale store.

3- In the Admin pane If i put in the store Setting >> Store settings >> System >> Use SEO URL's to ON on the default store and OFF on the wholesale store then the category links in the wholesale store work properly BUT there will not be SEO links

I reported this issue to Natani the developer of the SEO pack extension and after checking my website and data base he thinks that this is a V1.3.1 issue related to subdomains

**Comment by abantecart** [comment]
@handal59 Did you configure both domains correctly? Do you test with SEO pack extension disabled?

**Comment by handal59** [comment]
Yes both domains are configured correctly. My website is functioning properly with abantecart V1.2.16 with also SEO pack. This issue happened only when i upgraded to abanyecart 1.3.1 and SEO pack 2.2.1

I restored my website back to the older version and you can see it working here properly
Default store:  https://bethlehemcasting.com
Second store subdomain: https://wholesale.bethlehemcasting.com

**Comment by handal59** [comment]
Sorry i did not mean to close it because it is not fixes yet

**Comment by abantecart** [comment]
I browsed your site on wholesales site and all links work correctly. 
I still do not see how to reproduce the bug that your report.

**Comment by handal59** [comment]
The site visited is the actual site built on Abantecart V1.2.16 and it is working properly.

I have a cloned site for testing with Abantecart 1.3.1 and that one is not working properly, this means, that if i upgrade to abantecart V1.3.1 i will face these issues.

Here is the cloned site for testing 
https://test.bethlehemcasting.com/
https://wholesale.test.bethlehemcasting.com/ 

When you are on the second domain https://wholesale.test.bethlehemcasting.com/ click on a category and see that it will show you the categories of the first [default] site

**Comment by BasaraABC** [comment]
@abolabo I was able to replicate the glitches when SEO URLS are **ON** (please clear AbanteCart cache).
To replicate setup to stores 
default in subdomain.newhost.local
second store in *test*.subdomain.newhost.local
<img width="1033" alt="m1" src="https://user-images.githubusercontent.com/2631910/141935616-84f61d3b-e34e-4380-9d4c-a9e996c984a0.png">


Please also install different theme to catch when it stop working.
Note: when seo urls are On the second store urls not work even without seo key like https://test.subdomain.newhost.local/index.php?rt=product/category&path=72
<img width="1925" alt="m2" src="https://user-images.githubusercontent.com/2631910/141935646-38627481-fb2b-403f-a905-c635d85019a7.png">

**Comment by handal59** [comment]
Hello Basara
I did not understand what you explained can you please explain??

You mentioned that on second store SEO urls do not work when ON, in version 1.2.16 it is working properly.

**Comment by BasaraABC** [comment]
@handal59 I refer to 1.3

**Comment by handal59** [comment]
You mean that there is a bug in Version 1.3??

**Comment by abolabo** [comment]
@handal59 Did you tried to disable all seo extensions for both stores? Issue still presents? i mean SEO Pack

**Comment by abolabo** [comment]
Also please try to replace your file core/lib/config.php with this
https://raw.githubusercontent.com/abantecart/abantecart-src/1.3.2/public_html/core/lib/config.php

**Comment by handal59** [comment]
No need to disable all SEO extensions, the SEO extension that makes this issue is the SEO pack of Natani and as i mentioned in a previous message  If from the admin panel Settings >> Store settings >> system I disable the "Use SEO URl's" in the subdomain [put to OFF] then the links work properly.

I will try now to replace the config file you sent me and inform you.

If you want to check yourself some issues i can give you access to my admin panel but send me a direct email

**Comment by handal59** [comment]
> Also please try to replace your file core/lib/config.php with this https://raw.githubusercontent.com/abantecart/abantecart-src/1.3.2/public_html/core/lib/config.php

I Compared this file with the file installed file with Notepad ++ and there is no difference, anyway i changed the file and still links do not work correct

**Comment by BasaraABC** [comment]
@abolabo please read my post above. It is a bug not related to any extension and I was able to replicate it in 1.3.2

**Comment by BasaraABC** [comment]
@handal59 what is your hosting provider?

**Comment by handal59** [comment]
https://hostarmada.com

**Comment by abolabo** [comment]
@handal59 please check our fix from dev1.3.2
https://raw.githubusercontent.com/abantecart/abantecart-src/1.3.2/public_html/core/lib/config.php

**Comment by handal59** [comment]
> @handal59 please check our fix from dev1.3.2 https://raw.githubusercontent.com/abantecart/abantecart-src/1.3.2/public_html/core/lib/config.php

I tested this new config.php file and it is working properly
