### ISSUE TITLE
tags with apostrophe

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1515]
Tag Shop `De'Longhi` after saving changed to `Shop De\'Longhi` the next save will change it to `Shop De\\\'Longhi`
![apostroph](https://user-images.githubusercontent.com/2631910/145777459-b36557b9-f391-4018-aaac-80fee87ae685.jpg)

**Comment by BasaraABC** [comment]
@abolabo I think we should remove special chars from tags.

**Comment by BasaraABC** [comment]
Multilanguage support is broken. 
<img width="520" alt="multilanguage" src="https://user-images.githubusercontent.com/2631910/150760453-cb0afe5f-0685-4a5d-b6bb-785f3575032b.png">

**Comment by abolabo** [comment]
@BasaraABC  what this mean? cannot replicate

**Comment by BasaraABC** [comment]
Type in main language next tags: De'Longhi, тест1, тест2
The expected result after save: **DeLonghi, тест1, тест2** but now we have **1,2,DeLonghi** so your fix removes all non-latin chars and this is wrong.
