### ISSUE TITLE
Data listing block: limit translatable

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1518]
Limit setting should not be translatable
<img width="1889" alt="multilng" src="https://user-images.githubusercontent.com/2631910/149076461-72dad0ec-5c97-4b4c-aa3b-8bf7f93ece67.png">

**Comment by abolabo** [comment]
nope. it can be different depends on language

**Comment by BasaraABC** [comment]
All translatable fields must be marked as translatable. I don't think the limit was designed to be different per language
<img width="777" alt="translatable" src="https://user-images.githubusercontent.com/2631910/150759547-be91b691-a437-4127-bd79-41e3a9094be0.png">

**Comment by abantecart** [comment]
@BasaraABC Are you talking about the text?

**Comment by abolabo** [comment]
@abantecart limit field is language dependant.

**Comment by BasaraABC** [comment]
@abantecart I talk about the "Limit" field
