### ISSUE TITLE
Weight Based Shipping and Display Prices With Tax issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1519]
Tax applied twice when Shipping (weight based) are taxable and the store has the Display Prices With Tax enabled
<img width="1162" alt="2022-01-21_15-30-44" src="https://user-images.githubusercontent.com/2631910/150493671-18dd4d9a-c2b7-4bfb-a6df-927d063609fa.png">
Make sure to set shipping to be taxable to see the issue

<img  alt="weight" src="https://user-images.githubusercontent.com/2631910/150493819-463089d2-bda2-404f-96e1-c6301c077d82.png" width=400>

**Comment by abolabo** [comment]
affected flat rate shipping too

**Comment by BasaraABC** [comment]
The issue is not fixed. Even when Display Prices With Tax is disabled tax to shipping applied twice.

**Comment by moedawood** [comment]
Hi 
Any update on this ?

**Comment by abolabo** [comment]
> The issue is not fixed. Even when Display Prices With Tax is disabled tax to Weight based shipping is applied twice.

please give me precise conditions to replicate

**Comment by BasaraABC** [comment]
1. go to Weight Based Shipping and set **Tax Class** to Taxable Goods
2. go to settings and disable **Display Prices With Tax**
3. go to the storefront and product to the cart and select Weight-based shipping in the Estimator

Here is an example for the product with a price $100 and weight-based settings 1:100.00,10:200.00
The expected total is : $100+$100+8,5% = $217 but we have $225.22
Same total should be when **Display Prices With Tax** is enabled
<img width="688" alt="tax" src="https://user-images.githubusercontent.com/2631910/173290927-d2faaa08-4ec4-490d-a695-53dc291e235a.png">

**Comment by abolabo** [comment]
all works fine. You set tax class for shipping method and then wait pure shipping cost without tax. it's wrong
Shipping method have it's own tax class for shipping rate.

no bug here

**Comment by abolabo** [comment]
issue was in the calculation order of tax total extension.

**Comment by BasaraABC** [comment]
How does it affect the promotions and discounts? 

Other shipping does not calculate tax. For example:
# flat rate
<img width="1628" alt="flat" src="https://user-images.githubusercontent.com/2631910/173514546-368c7073-ea06-4087-9041-3e303e8acb8e.png">

# local delivery
<img width="1432" alt="local" src="https://user-images.githubusercontent.com/2631910/173516423-fbb6b76f-6aac-4238-b111-64caf7ad4e08.png">
