### ISSUE TITLE
php 8.0: Call to undefined function set_time_limit

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1521]
User report an issue visible in the php 8.0
`2022-01-27 10:22:21 - Unknown Error: AbanteCart core v.1.3.2 Call to undefined function set_time_limit() in <b>/public_html/admin/controller/responses/common/resource_library.php</b> on line <b>22</b>`

**Comment by abolabo** [comment]
php8 supports this function https://www.php.net/manual/en/function.set-time-limit.php
