### ISSUE TITLE
product page zoom is not working

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1526]
Please see js error in the browser console.
![zoom](https://user-images.githubusercontent.com/2631910/156983541-ae217e52-b2cc-46f5-9dbe-a761e1f14a17.jpg)

**Comment by abolabo** [comment]
cannot to replicate

**Comment by BasaraABC** [comment]
Issue is valid. Visible in 1.3.3 branch on product like /index.php?rt=product/product&path=68_69&product_id=116
<img width="913" alt="branch" src="https://user-images.githubusercontent.com/2631910/172778756-51b0d8dd-1c73-40e6-be8e-2c1964e1e6fe.png">
