### ISSUE TITLE
Google Analytics 4 is replacing Universal Analytics

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1530]
Google Universal Analytics deprecate notice. We use Universal Analytics in the 1.3
<img width="650" alt="ga4" src="https://user-images.githubusercontent.com/2631910/164382964-c86a3921-5626-4af1-b1be-00d0a313fe9e.png">

**Comment by BasaraABC** [comment]
The real-time working and some leads, landing page-like data is visible but E-commerce data in Drive online sales > Ecommerce Purchases is not visible (I wait for 24 hours)
theme bs5 with FC (all default settings Cash On Delivery)

**Comment by abolabo** [comment]
purchase event now works in all templates. Adding to cart/wishlist, begin_checkout, product view events available only in bs5

**Comment by BasaraABC** [comment]
## Issue A: The purchase was even written twice 
<img width="1302" alt="twice" src="https://github.com/abantecart/abantecart-src/assets/2631910/6125ae03-2eef-4428-908e-8946db1c509d">

### Issue B: all orders recorded as "Items purchased by Order coupon"
I did not place orders with coupons (looks like when you send a coupon: null it is considered a real coupon)
<img width="635" alt="coupon" src="https://github.com/abantecart/abantecart-src/assets/2631910/e0d6a9e1-4d7c-4081-aef3-75cb855d4fb4">
