### ISSUE TITLE
Store is not loading

### ISSUE THREAD

**Issue by DiceInstitute** [abantecart/abantecart-src#1533]
https://diceindiagroup.net is my store address. And it's not loading. Funny thing is if I reset the customer tracking report it's loading. But after loading one page again it's not loading. Again after reset loading.

**Comment by DiceInstitute** [comment]
![image](https://user-images.githubusercontent.com/69249490/167271328-3b08f285-4ecc-48b7-9e41-eb80153132ce.png)

**Comment by DiceInstitute** [comment]
If I reet this again it'll load
![image](https://user-images.githubusercontent.com/69249490/167271359-6a2d0531-c339-450c-9d73-78d6a9e9f99b.png)

**Comment by DiceInstitute** [comment]
Reseting done
![image](https://user-images.githubusercontent.com/69249490/167271383-4c25a29a-02b7-4a67-b94c-a7b7be1cca8f.png)
Opening again
![image](https://user-images.githubusercontent.com/69249490/167271398-359c3093-6e50-4afb-915d-10251268fbc5.png)

**Comment by DiceInstitute** [comment]
Today tried with php7. it seems your product not working with php8

**Comment by BasaraABC** [comment]
Hello. Please post to the AbanteCart forum https://forum.abantecart.com or provide the full and detailed bug report including the AbanteCart version and PHP version
