### ISSUE TITLE
marketplace connect: issue with login

### ISSUE THREAD

**Issue by jamiemc71** [abantecart/abantecart-src#1538]
Hello me again :(

i seem to have an issue with login/connecting my account to the marketplace.

when i go to the the connect button it asks me for my username and password and come sup with the following message.

{"error_title":"Login Error!","error_text":"You are not logged in. You will be redirected to login page","show_dialog":true,"reload_page":true,"error_code":401}

i get this by going to  Extensions then the orange connect button.
i also get it by going to system>updater>connect

i have upgraded to version V1.3.3

many thanks

**Comment by BasaraABC** [comment]
Thank you for the bug report. What is your browser and browser version?
Can you please clear all browser caches and try again?

**Comment by jamiemc71** [comment]
good morning.

im currently on chrome version Version 102.0.5005.115 (Official Build) (64-bit) and also get the error on Microsoft Edge Version 102.0.1245.41 (Official build) (64-bit)

i have cleared my cache on all browsers and also via the cache option in the system.

there are no errors showing up in the log file its only when clicking on connect

**Comment by abolabo** [comment]
please open developer tools in the Chrome (press F12) and look into console tab. 
Do you have an errors after click?

**Comment by BasaraABC** [comment]
The issue described may happen when hosting does not allow server-to-server connection from your AbanteCart to the marketplace

**Comment by BasaraABC** [comment]
Please try the following:
1. Make sure you visit AbanteCart admin via the secure URL (HTTPS)
2. Clean browser cache (to remove the insecure cookies saved by the browser)
3. try to login
