### ISSUE TITLE
[1.2.2] Error in joins when selection is empty

### ISSUE THREAD

**Issue by gob33** [abantecart/abantecart-src#154]
You have an error generalized when editing tables joined like ..._to_stores or ..._to_layout
Example, in editCategory($category_id, $data), you write:
```
if (isset($data['category_store'])) {
	$this->db->query("DELETE FROM " . $this->db->table("categories_to_stores") . " WHERE category_id = '" . (int)$category_id . "'");
	foreach ($data['category_store'] as $store_id) {
		$this->db->query("INSERT INTO " . $this->db->table("categories_to_stores") . " SET category_id = '" . (int)$category_id . "', store_id = '" . (int)$store_id . "'");
	}
}
```
But when the user deselect all stores, POST data doesnt contain any 'category_store[]',
so the isset($data['category_store']) is FALSE and no change is done.
You must put the delete outside the if() like this:
```
$this->db->query("DELETE FROM " . $this->db->table("categories_to_stores") . " WHERE category_id = '" . (int)$category_id . "'");
if (isset($data['category_store'])) {
	foreach ($data['category_store'] as $store_id) {
		$this->db->query("INSERT INTO " . $this->db->table("categories_to_stores") . " SET category_id = '" . (int)$category_id . "', store_id = '" . (int)$store_id . "'");
	}
}
```
They are many places to changes...
(Unless you dont want to record an empty set which is logical ?)

**Comment by abolabo** [comment]
Hi, gob33.
I don't think it's a bug. You can't have an unassigned entity (category, product, manufacturer) to some store, i mean "orphans". You should to assign it to at least one store otherwise you should to regulate it via entity status. Anyway empty stores list means "no changes" there.

**Comment by gob33** [comment]
View like that (always assigned to at least one), it is acceptable.
