### ISSUE TITLE
no placeholder in the Global attributes 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1543]
Please add the Placeholder (default value for placeholder) field to selectbox and checkbox Global attributes
https://forum.abantecart.com/index.php/topic,9753.0/topicseen.html
<img width="1500" alt="placeholder" src="https://user-images.githubusercontent.com/2631910/198243617-2b349370-f380-4cc7-8f5a-e7066588ab62.png">

**Comment by immakdas** [comment]
@abolabo we have this field when you add option to product, can you please add it to Global attributes?

**Comment by BasaraABC** [comment]
We use the "placeholder" in other option types. For example in select box we use it as "no selection value" Please see screenshot
<img width="2141" alt="noselection" src="https://github.com/abantecart/abantecart-src/assets/2631910/deeb1441-cb8f-45d4-9d6f-c6c2ec9db45f">
