### ISSUE TITLE
clean session after password change

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1549]
logout from all admin user/customer sessions when the password changed

**Comment by BasaraABC** [comment]
Changed password in admin but sessions in other browsers are Active
<img width="876" alt="pass1" src="https://github.com/abantecart/abantecart-src/assets/2631910/b51efd6c-94f7-43ae-a6ee-c801f2e2ab5d">


Same for a storefront. Change password in one browser and it is logged out but others browser are active
<img width="1070" alt="sfpass" src="https://github.com/abantecart/abantecart-src/assets/2631910/766bbebb-679f-4137-b778-6f3b789ba6da">

**Comment by abolabo** [comment]
to solve need to manage sessions. Complex for now

**Comment by BasaraABC** [comment]
Found an issue with the customer password reset.
1. login to the customer account in Browser A
2. go to the "Forgot your password" page (rt=account/forgotten/password) in Browser B and request the "Password reset link has been sent to your e-mail address."
3. when the link is received in an email visit it in Browser C and set a new password (Your password has been successfully updated.)
4. BUG: The customer in Browser A should be logged out but he has an active session.

**Comment by abantecart** [comment]
@BasaraABC fixed and ready for QA. Thank you
