### ISSUE TITLE
CAPTCHA not work in some browsers

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#155]
forum user report problem with CAPTCHA, see testing results with Admin Forgot Password page 
index.php?rt=index/forgot_password&s=your_admin
IE11                 Win7 x64 - ok
Chrome 43      Win7 x64 - ok
FireFox 38.0.5 Win7 x64 - ok
FireFox 38.0.5 Mac OS - not work (Verification code does not match the image!)
Chrome 43      Mac OS - not work (Verification code does not match the image!)
Safari               Mac OS - ok
Opera   30       Mac OS - ok

Actually in Chrome (Mac OS) visible that after page load Captcha image is reloaded without any reason, hope this help.

**Comment by abantecart** [comment]
Review new google capture as alternative.

**Comment by BasaraABC** [comment]
@abantecart >>Review new google capture as alternative. 
new captcha is not a solution because:
1. it is very glitch (for me)
2. to get new reCaptcha you need to have gmail account and assign reCaptcha API to domain
<img width="715" alt="recaptcha__easy_on_humans__hard_on_bots" src="https://cloud.githubusercontent.com/assets/2631910/8588861/8131bc40-2639-11e5-872a-6ffa976c9c91.png">

**Comment by abantecart** [comment]
I was not able to replicate this problem. I suspect it is related to session issue that was resolved. If session is some how reset, there is no record of capture to be matched.
