### ISSUE TITLE
add Resource to global attribute values

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1550]

**Comment by abolabo** [comment]
what for? any thoughts?

**Comment by BasaraABC** [comment]
when you assign a Global attribute to a product every time you need to add resources (for example images). 
What if you want to add a Global attribute to 20 products? You will need to manually add resources to 20 products.
I think it was asked by @abantecart in some project.

**Comment by goatlady102** [comment]
I ask for this many months ago,  And the request was for adding placeholder field into the global.  Reasoning -  if there are standard options used on most products and there should be a placeholder to help customer make correct input.  Admin needs to add the place holder to every new product that uses the GLOBAL attribute.   Please  add this when you get to this in 1.4.0
