### ISSUE TITLE
Click the current language in the bootstrap5 template language selector goes to undefined

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1553]
Hi core devs,

We found out that when we click the current language in the bootstrap5 template language selector it goes to undefined page. It doesn't happen in the default template.

Is it a normal  behavior or is it a bug?

I have attached a video of how i get the undefined page.

https://user-images.githubusercontent.com/225439/196757803-4d3e84eb-8711-4a21-a681-efecb86ab8e2.mp4

**Comment by BasaraABC** [comment]
Thank you @handoyo.
