### ISSUE TITLE
wordpress 6 embed css refused to apply

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1556]
The embed.css refused to apply in the WordPress 6.1

<img width="1080" alt="wp" src="https://user-images.githubusercontent.com/2631910/198534768-12943df5-334b-48d1-8cf4-7cddbbba2585.png">

**Comment by BasaraABC** [comment]
### Issue A: The issue is not fixed. the add to cart and quantity look cutof
<img width="819" alt="cut" src="https://github.com/abantecart/abantecart-src/assets/2631910/6610ef08-bb43-4ed0-95e0-db4872d68ead">

### issue B: if possible increase the start modal width to at least 900px 
this to show the product page properly. 
<img width="1350" alt="WIDTH" src="https://github.com/abantecart/abantecart-src/assets/2631910/1934f60c-75ae-4198-bb34-540059348f93">

### Issue C: please add some padding to all pages
<img width="936" alt="padding" src="https://github.com/abantecart/abantecart-src/assets/2631910/df798824-1c0f-4bd0-b78d-2ab4109bda2b">

**Comment by abolabo** [comment]
browser? Cannot to reproduce in chromium and ff

**Comment by BasaraABC** [comment]
Chrome Version 114. Use https://live.browserstack.com/. I can replicate it theme (Windows 11 Chrome Latest)
