### ISSUE TITLE
php 8.1 - unknown encoding in ini

### ISSUE THREAD

**Issue by thebosshu** [abantecart/abantecart-src#1557]
i get warnings on every url request:

PHP Warning:  Unknown: Unknown encoding &quot;UTF-8;&quot; in ini setting in Unknown on line 0
PHP Warning:  Unknown: INI setting contains invalid encoding &quot;UTF-8;&quot; in Unknown on line 0

even without the charset set in the ini. in 7.3 it was okay. can someone confirm?

**Comment by BasaraABC** [comment]
The latest version does not support 8.1 try 8.0 and please zip and post your ini file
