### ISSUE TITLE
Editor text alignment doesn't work if the text is not wrapped by <p></p> or <div></div>

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1558]
Hi core devs,

The text alignment in the texteditor doesn't work if the text is not wrapped by <p></p> or <div></div>. Is it a bug or intentional?

I attached the video for how to reproduce the issue.

It is a clean installation of AbanteCart v1.3.3 and using Php 8.1.

https://user-images.githubusercontent.com/225439/198845507-d59dafdc-1e91-4441-b758-919bae90e539.mp4

**Comment by BasaraABC** [comment]
Hello. The visual editor is a 3rd party tool TinyMCE. For plugins, configurations etc visit https://www.tiny.cloud

**Comment by goatlady102** [comment]
Hello Basara -  I would like to add some clarity that you seem to have missed -  this reported issue is occurring in **default core** installation.   the above video  is using a demo product that loads on installation and this is the product description box.
Core devs have coded the TinyMCE to be used with adding descriptions into products.   If there is an issue with the configuration is core devs.

You can go to the AbanteCart.com demo  and test for yourself.   
Try adding a product to the test site.    Make some description, save.  Try enabling the text alignment for centering or right justified.  You can try adding the text in either html/text  or visual tab.   If fails with either.  With cart v 1.3.3  admin has manually add the <P> or <div> . This has not been the requirement in version prior to 1.3.3

**Comment by BasaraABC** [comment]
Thanks for the comments. My opinion is - this is basic HTML, you cant apply styles if no element. @abolabo can you please try to upgrade the TinyMCE editor to the [latest version (6+)](https://github.com/tinymce/tinymce) if the license allows it? 
The current we use is version: 5.6.2 (2020-12-08)
@handoyo @goatlady102 take a note if configure the editor to add much HTML it may break the HTML descriptions for many products with complex HTML and the advantages of auto adding `<p>` to every text may produce much more problems

I suggest to follow tinyMCE 5 documentation and configure Visual Editor as you prefer https://github.com/abantecart/abantecart-src/blob/master/public_html/admin/view/default/template/common/head.tpl#L48

**Comment by goatlady102** [comment]
I remain confused and concerned about your reply  -  we are reporting a change in the way the default AbanteCart has worked until v 1.3.3  Seems you are suggesting that ALL admins using AbanteCart 1.3.3  will be unaware of the "new" requirement to add html tags to get an alignment condition they are use to having.  So many users of AbanteCart are not well versed in altering core code.  How you support your core product and arrange it's features is of course your business decision to make. 

Regards
Lee

**Comment by abolabo** [comment]
html cannot align plain text. You should to style it. It can be done only one way - wrap text into tag, for example <p> and then add css rules. 
fyi. 1.3.4 now includes fresh tinymce editor.
