### ISSUE TITLE
Error Decimal Separator "," and Thousand Separator "." with Big amounts

### ISSUE THREAD

**Issue by alfaromora** [abantecart/abantecart-src#156]
I am using decimal separator "," and thousands separator " . "

The problem occurs when the order entry to edit in the admin and change the quantity of a product

![1](https://cloud.githubusercontent.com/assets/12860153/8130072/cb756770-10cc-11e5-8603-637a655bfeb9.jpg)

The first thing that happens is that it changes formats separators

![2](https://cloud.githubusercontent.com/assets/12860153/8130073/cb7ae150-10cc-11e5-8d8e-a421b3e6923f.jpg)

Then when I pressed the Save button , the change amounts wrongly

![3](https://cloud.githubusercontent.com/assets/12860153/8130074/cb7e27ca-10cc-11e5-8e5b-780cea4f3d67.jpg)

This was true even using this fix

https://github.com/abantecart/abantecart-src/commit/b2ad50c6390c95781427fc3f52693b617328b2b7

If i use decimal separator "." and thousands separator "," there is no problem.

**Comment by abantecart** [comment]
We are looking into this problem.

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
fixed. Checked with Decimal Separator "," and Thousand Separator "."
