### ISSUE TITLE
Customers and Orders disappearing

### ISSUE THREAD

**Issue by gewing1964** [abantecart/abantecart-src#1560]
Hi, my customers and order details have disappeared.
I have tried different browsers but same thing happens. It will show the details but when you go to a different screen, then go back to customer or orders, they've gone again

**Comment by BasaraABC** [comment]
Hello.
Please provide more details on the issue:
1. AbanteCart version
2. browser version
3. PHP version
4. last errors in the AbanteCart error log etc
5. screenshot

**Comment by gewing1964** [comment]
Hi There,
Apologies for the delay.

The thing is it sometimes does work. It’s almost like it’s cached some configuration.. I can’t work it out.

I also have an issue emailing out but I’m working with Microsoft on that one.

Thanks in advance
George.

From: BasaraABC ***@***.***>
Date: Monday, 31 October 2022 at 07:48
To: abantecart/abantecart-src ***@***.***>
Cc: gewing1964 ***@***.***>, Author ***@***.***>
Subject: Re: [abantecart/abantecart-src] Customers and Orders disappearing (Issue #1560)

Hello.
Please provide more details on the issue:

  1.  AbanteCart version – 1.3.3
  2.  browser version – Safari Version 16.1 & Chrome Version 106.0.5249.119 & Edge Version 107.0.1418.26
  3.  PHP version – 7.4.30
  4.  last errors in the AbanteCart error log etc – See Attached
  5.  screenshot – See attached

**Comment by gewing1964** [comment]
I just noticed something.

When you login, you land on the Dashboard page.  From there I can see 3 orders but when it goes wrong it only shows one record and that record, I’ve attached screenshots for you to see.



From: ***@***.*** ***@***.***>
Date: Tuesday, 1 November 2022 at 09:15
To: abantecart/abantecart-src ***@***.***>
Subject: Re: [abantecart/abantecart-src] Customers and Orders disappearing (Issue #1560)
Hi There,
Apologies for the delay.

The thing is it sometimes does work. It’s almost like it’s cached some configuration.. I can’t work it out.

I also have an issue emailing out but I’m working with Microsoft on that one.

Thanks in advance
George.

From: BasaraABC ***@***.***>
Date: Monday, 31 October 2022 at 07:48
To: abantecart/abantecart-src ***@***.***>
Cc: gewing1964 ***@***.***>, Author ***@***.***>
Subject: Re: [abantecart/abantecart-src] Customers and Orders disappearing (Issue #1560)

Hello.
Please provide more details on the issue:

  1.  AbanteCart version – 1.3.3
  2.  browser version – Safari Version 16.1 & Chrome Version 106.0.5249.119 & Edge Version 107.0.1418.26
  3.  PHP version – 7.4.30
  4.  last errors in the AbanteCart error log etc – See Attached
  5.  screenshot – See attached

**Comment by BasaraABC** [comment]
Hello. Please do not reply to email. Visit this page https://github.com/abantecart/abantecart-src/issues/1560 and attach files

**Comment by gewing1964** [comment]
Hi Guys,
I noticed that when the issue happens it changes the orders that are seen on the Dashboard\Home. I've attached screenshots of what I mean.
![IMG_9659](https://user-images.githubusercontent.com/24951721/199223963-f8cde471-11fa-49e2-9b46-b73fd3e79ee1.jpg)
![IMG_9660](https://user-images.githubusercontent.com/24951721/199223983-cc07cfcb-55fc-4924-9493-d42cf4cbaf84.jpg)

Thanks in advance
G

**Comment by BasaraABC** [comment]
Thank you for the screenshot, can you please make one more go to Sales > Orders and click to filter _All Orders_
<img width="796" alt="all" src="https://user-images.githubusercontent.com/2631910/199224923-db93ec25-13d6-4b61-82c6-f9f8eff6551e.png">

**Comment by gewing1964** [comment]
![Screenshot 2022-11-01 at 11 52 32](https://user-images.githubusercontent.com/24951721/199226819-a5cd05b1-420b-4e42-b838-cb11656ddbbf.png)

**Comment by gewing1964** [comment]
Hmmm... it seems steady now after I made a slight change.

In Store details, I changed the URL to store.rochfordallotments.com/ralga from store.rochfordallotments.com/default.

I think I set Jennifer Spiteri on the /default store... would that be the issue?

**Comment by BasaraABC** [comment]
When you have multistore you must log in to admin from the default store URL
