### ISSUE TITLE
Option Values not showing in website

### ISSUE THREAD

**Issue by musawwirbd** [abantecart/abantecart-src#1561]
Hi 
I want to add product size from >Product Summary>Option
But it not showing on website
![website](https://user-images.githubusercontent.com/117055042/198922563-69c11c25-268f-44aa-9886-fc31b2719ce2.jpg)
![admin panel](https://user-images.githubusercontent.com/117055042/198922566-66517e92-b6f0-4c6a-8797-8c12ae538432.jpg)

**Comment by BasaraABC** [comment]
Hello @musawwirbd. You can post questions on our AbanteCart forum https://forum.abantecart.com/
