### ISSUE TITLE
change Stripe statement

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1562]
Replace our statement (order number) with Stripe Dashboard value (statement from the stripe profile https://dashboard.stripe.com/settings/public)
https://forum.abantecart.com/index.php/topic,9910.msg38659.html#msg38659
<img width="872" alt="dash" src="https://user-images.githubusercontent.com/2631910/200602603-702d38dd-598a-46cc-bd23-d2190766239f.png">

**Comment by goatlady102** [comment]
hello,  any way you might get this fixed in near future,  it should be an easy fix.   I have clients that have customers who are quite upset with the order number only appearing in their card statements.  

Thanks in advance for considering sooner rather than later.

**Comment by goatlady102** [comment]
I have just updated the forum post  [https://forum.abantecart.com/index.php/topic,9910.msg38852.html#new](url)
I updated the forum to alert other cart users of the continuing problem .

Please fix this.   It is your issue.   Stripe side is set correctly  according to them and to me.   It is the API interface that is wrong.
You guys are better than this.   Users of this Stripe interface should not be facing customer complaints and disputes because you got it wrong.

**Comment by goatlady102** [comment]
As you know I had contacted Strip support late last week.   They had asked me to provide them with details of my requests to AbanteCart to fix.  I did that.  

This is there reply back to me this afternoon -  ( the bold is my enhancement to call your attention to the important part of the message in IMO.

Hi Lee, 

Thank you for your response. I’m sorry to hear that AbanteCart is still unable to fix the issue with the integration of your account. 

Per checking, your Stripe account is set up properly. However, **your third party platform AbanteCart is making an API call for a dynamic descriptor. You can check this specific log req_zXf7cLyBPYClnm. This is where AbanteCart is passing this dynamic descriptor.** 

As we don't have control for the integration created by a third party application. **Could you kindly let AbanteCart know that checking and fixing the integration of the account is part of the service agreement with the business and the third party integration and this is beyond Stripe's scope?**

I look forward to your response. 

Best, 
Jez

**Comment by BasaraABC** [comment]
For the reference, there is a related Pull request https://github.com/abantecart/abantecart-src/pull/1567 posted by [handoyo](https://github.com/handoyo)

**Comment by BasaraABC** [comment]
@handoyo you may be interested to check this change in a new version of the Stripe before we released it.

**Comment by handoyo** [comment]
@BasaraABC thanks for the information. I would like to discuss with @goatlady102 first about the changes.

**Comment by handoyo** [comment]
@BasaraABC and @abolabo 

I have download the current stripe extension and test it using our testing creds.. It appears that the store name is not called in the statement descriptor. I only see the order id suffix. Refer to the following screenshot:

![image](https://github.com/abantecart/abantecart-src/assets/225439/2b84d0eb-fee2-4efe-b9ba-d92bcbe8c55d)

This is the public business information:

![image](https://github.com/abantecart/abantecart-src/assets/225439/0878bb86-2bff-4f7f-a3fd-a7d8a4b72d75)

In testing,  it seems you are using the shortened descriptor field and if it is empty are you deferring to the business name?

**Comment by handoyo** [comment]
If the shortened descriptor field is NOT empty  it reports correctly.

![image](https://github.com/abantecart/abantecart-src/assets/225439/72368af8-cabd-439a-9d39-494252a8676a)

![image](https://github.com/abantecart/abantecart-src/assets/225439/699ba701-d974-4711-b51e-278cb565829e)

**Comment by abolabo** [comment]
@handoyo in the new stripe extension we set store name form AbanteCart settings as statement descriptor and phrase "Order #123" as statement_descriptor_suffix. I guess stripe API use your descriptors from the stripe merchant account as default values. But i am not sure. Please check this case. Try to set empty values of descriptors on stripe side and create order.

**Comment by BasaraABC** [comment]
@handoyo the statement issue was fixed see commit https://github.com/abantecart/abantecart-src/commit/e0d82215557c808424bbc3cf21505fc4852b0f40
