### ISSUE TITLE
low priority: option type Checkbox: value not visible

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1564]
The value of Checkbox option is not visible in the cart, order etc
<img width="1831" alt="cheboxv" src="https://user-images.githubusercontent.com/2631910/200780258-c966cf7c-2cc1-447b-ba78-a81edf2abd69.png">

**Comment by abolabo** [comment]
cannot to replicate

**Comment by BasaraABC** [comment]
To replicate create the option with the type Checkbox and some text value
<img width="887" alt="check" src="https://github.com/abantecart/abantecart-src/assets/2631910/39ada31b-87e3-4192-bba9-ced1a3b4e9b7">

**Comment by abolabo** [comment]
i already did it. all works fine

**Comment by BasaraABC** [comment]
fine? The missing value is not a fix. Please fix the issue.
<img width="822" alt="optvalue" src="https://github.com/abantecart/abantecart-src/assets/2631910/39786e88-201a-4292-a0ea-25513e2d11ea">

**Comment by BasaraABC** [comment]
Hello. I use fresh install and the type of the option "Checkbox" with text value does not work. Please check again on fresh install and the newly create option
See today's screenshot

![checkbox](https://github.com/abantecart/abantecart-src/assets/2631910/de007a3d-c744-41c0-8a2b-fc7ba4977bcf)

**Comment by abolabo** [comment]
the same. All works fine. In FF and Chromium.
