### ISSUE TITLE
product level Stock Checkout ignored

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1565]
the **Stock Checkout** setting on _product level_ ignored and customer can not purchase _out of stock options values_
![out2](https://user-images.githubusercontent.com/2631910/200783054-8c99e05b-dcec-44f5-9177-110fa84207b3.png)

**Comment by abolabo** [comment]
why you think option level must be lower than product level? If you tune up product who decide it?
I think it's not a bug. Merchant have it's own responsibility.

**Comment by BasaraABC** [comment]
It is a bug but only in the **option with type Multiselect or Checkboxgroup**. If the same condition but other option types (select, checkbox ) it works as I expected - checkout allowed even if cart quantity is higher than option value quantity. 
Note: Track Stock and Stock Checkout are not the same thing.
