### ISSUE TITLE
Thumbnails quality issue

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1568]
Im trying to upload high quality PNG as for product images, so which is visible in category page / category listing, seems like there are these 5-10kb thumbnails generated from the original resource. Is there a way to improve the quality or disable thumbnail generation? I havent been able to find the controllers or core files for compression or resizings. 

I have tried changing some settings in cache and high res image generation, turned off caching, but its something different. If i reupload changing the old thumbnail with higher it will also not get updated and if i clear cache, it will just regenerate the small ones again.

**Comment by BasaraABC** [comment]
Check the dimensions settings (pixels sizes) and the quality setting for images

**Comment by kolynet** [comment]
no, i upload a full high quality photo in png and it gets blurry, i upload 1600x1600 but dimensions doesnt change anything, tried super high resolution, smaller, it always get reduced. i set thumb to 250x250 i also upload the new photo in 250x250 high quality 160kb size then it puts 5kb thumbnails which not look ok. its something with the core thumbnail generation

**Comment by BasaraABC** [comment]
Hello. Could you please provide full details:
* AbanteCart version
* attach an image
* where do you upload this image, if it is a product page what is your default template?
* PHP and **GD library** versions (you can find this in [php.info](https://abantecart.atlassian.net/wiki/spaces/AD/pages/7667770/PHP+Info))
* your settings for [image sizes](https://abantecart.atlassian.net/wiki/spaces/AD/pages/7110674/Appearance+Settings#Images-Sizes)
*  [jpeg quality setting](https://abantecart.atlassian.net/wiki/spaces/AD/pages/7700576/Jpeg+Images+Compression) value
* link where issue is visible
