### ISSUE TITLE
Authorize.net Extension is not working 

### ISSUE THREAD

**Issue by maurice6392** [abantecart/abantecart-src#1569]
I am hosting on GoDaddy, and I have used Installitron about 20 times and uninstalled and deleted everything cleared all files and caches trying to get the extension to work but it will not.
I then downloaded Abantecart master.zip file and uploaded to my website and installed this last time, following the instructions.
This fixed a few minor issues with things, that were not working that are now working fine.

But the Authorize.net Extension is still not working and will not process any cards, I enter the information
API LOGIN:
TRANSACTION KEY:
PUBLIC KEY:
This is the ERROR I get in the error log in Abantecart on the Admin side:
Here is the error I am getting:
2023-03-11 19:57:43 - Unknown Error: AbanteCart core v.1.3.3 Class "net\authorize\api\contract\v1\MerchantAuthenticationType" not found in <b>/home/lrtr9wz13wxw/public_html/PEGASUSADULTSTORE.COM/extensions/default_authorizenet/storefront/model/extension/default_authorizenet.php</b> on line <b>36</b>

my server is running PHP Version 8.1
Note: I have the demo products in the cart at this time. as that is fine for testing to see if it will work.
It is not in Test or Demo mode, it is in LIVE mode.

**Comment by abolabo** [comment]
please check if this directory presents on your host
https://github.com/abantecart/abantecart-src/tree/master/public_html/extensions/default_authorizenet/vendor
If not - just download it from github and let us know.

**Comment by maurice6392** [comment]
Hello,
Yes the vendor folder is there.
this is an install from Abantecart that I downloaded from the link, unziped and ftp uploaded it on 3-10-2023 and ran the install per instructions.

I have attached the file manager screen shot.png file so that you can see it is there.

    On Sunday, March 12, 2023 at 03:14:34 PM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


please check if this directory presents on your host
https://github.com/abantecart/abantecart-src/tree/master/public_html/extensions/default_authorizenet/vendor
If not - just download it from github and let us know.

**Comment by maurice6392** [comment]
Sorry I forgot to state that i took the PHP from version 8.1 to 8.0 restarted the server then tried and received the same error...



    On Sunday, March 12, 2023 at 03:14:34 PM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


please check if this directory presents on your host
https://github.com/abantecart/abantecart-src/tree/master/public_html/extensions/default_authorizenet/vendor
If not - just download it from github and let us know.

**Comment by BasaraABC** [comment]
Hello [maurice6392](https://github.com/maurice6392). When you reply to a GitHub notification in the mail client the attachments are not added.

**Comment by abolabo** [comment]
@maurice6392 please download this file
https://github.com/abantecart/abantecart-src/raw/65ffe587f2d28bd4bb3a8b07dd41cb9e891095e1/public_html/extensions/default_authorizenet/main.php
and replace your main,php with it.

**Comment by maurice6392** [comment]
Hello i did attach the file, and verified the sent email had the screen capture image.

I have attached the the image to this reply also...

    On Monday, March 13, 2023 at 03:10:08 AM EDT, BasaraABC ***@***.***> wrote:  
 
 


Hello maurice6392. When you reply to a GitHub notification in the mail client the attachments are not added.

**Comment by maurice6392** [comment]
Question is it supposed to be a file or just the PHP code to edit and replace the content inside the file ?
as when I click the link the php code is shown...

i will wait on your reply

    On Monday, March 13, 2023 at 06:59:28 AM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


@maurice6392 please download this file
https://github.com/abantecart/abantecart-src/raw/65ffe587f2d28bd4bb3a8b07dd41cb9e891095e1/public_html/extensions/default_authorizenet/main.php
and replace your main,php with it.

**Comment by abolabo** [comment]
@maurice6392  replace content of file...

**Comment by maurice6392** [comment]
Ok, I will do that now and restart the server then test and let you know, the results.

    On Monday, March 13, 2023 at 01:27:21 PM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


@maurice6392 replace content of file...

**Comment by maurice6392** [comment]
Question, should I be using php version 8.0 or 8.1 ?

    On Monday, March 13, 2023 at 01:27:21 PM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


@maurice6392 replace content of file...

**Comment by abolabo** [comment]
8.0

**Comment by maurice6392** [comment]
Hello,
on the test on the customer side i receive an unknown error, I went to the admin side and here is the error:
2023-03-13 17:34:31 - Unknown Error: AbanteCart core v.1.3.3 Email "errors" does not comply with addr-spec of RFC 2822. in <b>/home/lrtr9wz13wxw/public_html/PEGASUSADULTSTORE.COM/vendor/symfony/mime/Address.php</b> on line <b>56</b>

But the test order seemed to go through and i receive email as the merchant from Authorize.net and from my Abantecart as I should.



    On Monday, March 13, 2023 at 06:59:28 AM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


@maurice6392 please download this file
https://github.com/abantecart/abantecart-src/raw/65ffe587f2d28bd4bb3a8b07dd41cb9e891095e1/public_html/extensions/default_authorizenet/main.php
and replace your main,php with it.

**Comment by maurice6392** [comment]
Hi,
On the customer side this is the ERROR shown.!
i have also attached the file




    On Monday, March 13, 2023 at 01:27:21 PM EDT, Dmytro Suprunenko ***@***.***> wrote:  
 
 


@maurice6392 replace content of file...

**Comment by abolabo** [comment]
_is there a way to add you to the admin side so you can see for your self ???_

Yes, sure. Please contact us via https://managed.abantecart.com/#contact
