### ISSUE TITLE
TinyMCE upgrade

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1575]
Please upgrade to the latest v6

**Comment by BasaraABC** [comment]
# minor issue 1: please make Quotation look similar as it looks in the admin. 
<img width="1138" alt="quotes" src="https://github.com/abantecart/abantecart-src/assets/2631910/353c54d0-e991-4d99-b5fc-23c0cfe10a66">

**Comment by abolabo** [comment]
added css into bs5 for blockquotes. see https://developer.mozilla.org/ru/docs/Web/HTML/Element/blockquote for details
