### ISSUE TITLE
1000+ fake orders in less than 10 mins Error No: 1062

### ISSUE THREAD

**Issue by maulikvrl2010** [abantecart/abantecart-src#1577]
I have use abantecard more than 3 years but never happened this 
[color=red][size=12pt]I am getting about 1000+ fake orders in less than 10 mins.[/size][/color]
When i show in error log it's show me like that ?
Every orders with change IP address.
Did any one please help my website and my bussiness stop working bez of this.
Help me to solve this error.

database error: AbanteCart core v.1.3.3 SQL Error: Duplicate entry '14401-0-0' for key 'prefix_orders.PRIMARY'
Error No: 1062
SQL: INSERT INTO `prefix_orders`
SET order_id = '14401', store_id  = '0',
store_name = 'store',
store_url = '',
customer_id = '0',
customer_group_id = '1',
firstname = 'kaccexqycze',
lastname = 'kaccexqycze',
email = 'kaccexqycze@gmail.com',
telephone = '1234567890',
fax = '',
total = '7',
language_id = '1',
currency = 'USD',
currency_id = '1',
value = '1',
coupon_id = '0',
ip = ''(every time IP address change),
shipping_firstname = '',
shipping_lastname = '',
shipping_company = '',
shipping_address_1 = '',
shipping_address_2 = '',
shipping_city = '',
shipping_postcode = '',
shipping_zone = '',
shipping_zone_id = '0',
shipping_country = '',
shipping_country_id = '0',
shipping_address_format = '',
shipping_method = '',
shipping_method_key = '',
payment_firstname = 'kaccexqycze',
payment_lastname = 'kaccexqycze',
payment_company = '',
payment_address_1 = 'kaccexqycze kaccexqycze',
payment_address_2 = '',
payment_city = 'kaccexqycze',
payment_postcode = '00000',
payment_zone = '',
payment_zone_id = '0',
payment_country = 'Antarctica',
payment_country_id = '8',
payment_address_format = '',
payment_method = '',
payment_method_key = '',
comment = '',
date_modified = NOW(),
date_added = NOW()
PHP call stack:
#0 /home/somefolder/public_html/store/core/lib/db.php:102
#1 /home/somefolder/public_html/store/core/engine/extensions.php:1162
#2 /home/somefolder/public_html/store/core/engine/extensions.php:383
#3 /home/somefolder/public_html/store/core/lib/db.php:68
#4 /home/somefolder/public_html/store/storefront/model/checkout/order.php:237
#5 /home/somefolder/public_html/store/core/engine/extensions.php:1162
#6 /home/somefolder/public_html/store/core/engine/extensions.php:383
#7 /home/somefolder/public_html/store/storefront/model/checkout/order.php:106
#8 /home/somefolder/public_html/store/core/lib/order.php:412
#9 /home/somefolder/public_html/store/extensions/fast_checkout/storefront/controller/responses/checkout/pay.php:477
#10 /home/somefolder/public_html/store/extensions/fast_checkout/storefront/controller/responses/checkout/pay.php:397
#11 /home/somefolder/public_html/store/extensions/fast_checkout/storefront/controller/responses/checkout/pay.php:1545
#12 /home/somefolder/public_html/store/core/engine/dispatcher.php:306
#13 /home/somefolder/public_html/store/core/engine/response.php:87
#14 /home/somefolder/public_html/store/core/engine/router.php:223
#15 /home/somefolder/public_html/store/core/engine/router.php:86
#16 /home/somefolder/public_html/store/index.php:97
in <b>/home/somefolder/public_html/store/core/database/amysqli.php</b> on line <b>137</b>

**Comment by BasaraABC** [comment]
Hello. 
What are your payment methods?

**Comment by maulikvrl2010** [comment]
Hi there are good point Ty
Is there any way scan my website there are no thread or viruses now my checkouts page working stop.
it's checkout page and submit from
store/index.php?rt=checkout/fast_checkout

redirect me this page(when i click on back page it's redirect me my original page)
store/index.php?rt=r/checkout/pay/address&type=payment

but my original page is
store/index.php?rt=checkout/cart
Ty for all

**Comment by maulikvrl2010** [comment]
Thanks for every one there JS error for mobile patten
