### ISSUE TITLE
PayPal commerce payment address issue

### ISSUE THREAD

**Issue by thebosshu** [abantecart/abantecart-src#1578]
Is it currently a bug that payment address not being updated in case customer doesnt provide informations? On old pp express extensions it was updating nicely the addresses after payment. Thanks

**Comment by BasaraABC** [comment]
Hello. PayPal Express and PayPal Commerce build on different APIs so they work differently. 
Please post questions at the [AbanteCart Community forum](https://forum.abantecart.com/)
