### ISSUE TITLE
remove double touch 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1580]
touch devices like iPhones require two taps to open a link or add to a cart the listings.
See the video on how to add to cart button requires two taps to work. 
Note: some users report even links require also two taps

https://user-images.githubusercontent.com/2631910/236811984-8fef84bf-f770-4204-9af3-b1e425722ea3.mp4

**Comment by BasaraABC** [comment]
Hello. Any update on why you Won't Fix this? I think we discuss this

**Comment by BasaraABC** [comment]
Ajax "add to cart" is redirecting to the cart page on mobile Chrome (Android) in the listing LIST mode see video

https://github.com/abantecart/abantecart-src/assets/2631910/94bc1eb8-4cec-4041-b8a9-d389c25b8f34

**Comment by abolabo** [comment]
there are two buttons. I cannot to replicate on my real device. click on cart icon adds product to basket, click on "check" redirects to cart page. no bug here

**Comment by BasaraABC** [comment]
Please check the video again. The is no "check" button! See time 00:10 second!

**Comment by BasaraABC** [comment]
I double check on fresh install in IOS Safari and Android Chrome, the issue is valid in the LIST view. 
NO "check" icon shown as you can see on the new video the one TAP was only on the "add to cart" icon.

https://github.com/abantecart/abantecart-src/assets/2631910/00ee9a74-bb95-41b0-a6e9-681064bd7076
