### ISSUE TITLE
GA4 add to cart in EUR

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1588]
GA4 configured to USD main currency but if customer switch to EUR and AddToCart the value send seems to be wrong (sent as 30,05eur but should be 30,05$)
<img width="1156" alt="currency" src="https://github.com/abantecart/abantecart-src/assets/2631910/92f0f8d7-146a-4d58-984c-d7035e7cac57">

**Comment by abolabo** [comment]
let's postpone it

**Comment by BasaraABC** [comment]
Issue is not fixed. The value is in USD
<img width="1036" alt="value" src="https://github.com/abantecart/abantecart-src/assets/2631910/4de7e6a0-48ab-4676-91a0-fade989e0904">
