### ISSUE TITLE
IPAD minor issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#159]
* Issue 1: zip-code text misplaced
![c7c191e4-7e51-4427-9f79-ada9ce222d6e](https://cloud.githubusercontent.com/assets/2631910/8429362/18c2f21c-1f51-11e5-8bae-6acde2932605.png)
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------

* Issue 2: price misplaced
![3052c121-4e2a-41b6-a6fa-2e133598f70a](https://cloud.githubusercontent.com/assets/2631910/8429364/18caf3ae-1f51-11e5-80b5-6c2f72c78b29.png)
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------

* Issue 3:
![427b9d87-74d8-4026-984c-6613e2ad784b](https://cloud.githubusercontent.com/assets/2631910/8429363/18c4cd30-1f51-11e5-92ec-89a26f9bb572.png)
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
* Issue 4:
![4c51a763-e5bb-41aa-8a33-1e20900b6b36](https://cloud.githubusercontent.com/assets/2631910/8429365/18cb52d6-1f51-11e5-9122-e8969d2dc882.png)

**Comment by abantecart** [comment]
Fixed.
