### ISSUE TITLE
GA4 purchase not in report

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1590]
I made a few purchases in EUR and GBP as well in different languages but Ecommerce Purchases report does not show **Items purchased**
Note: debugger show the purchase event see screenshot
![norecord](https://github.com/abantecart/abantecart-src/assets/2631910/32dabe5c-b12c-4f36-912e-70883a96cb32)

**Comment by abolabo** [comment]
made type casting for item's quantity. let's check result

**Comment by BasaraABC** [comment]
The issue is valid. Few orders in USD and GBP but no purchases (new install and new GA property)
<img width="1193" alt="noitems" src="https://github.com/abantecart/abantecart-src/assets/2631910/c3d06e28-8132-46a7-84a9-4eee9be66352">

**Comment by abolabo** [comment]
fixed. Data will be send on first load of success page. Reload of page will not work!

**Comment by BasaraABC** [comment]
2 critical problems

### Issue A: purchase event not cached with Klarna stripe purchase
<img width="1312" alt="gaklarna" src="https://github.com/abantecart/abantecart-src/assets/2631910/5e6c4213-185f-417c-bbaa-5a1f3dcc91d3">


### Issue B: wrong ID of transaction sent to GA with other payments
<img width="1593" alt="orders" src="https://github.com/abantecart/abantecart-src/assets/2631910/eee2508f-5958-4284-b1cb-1e7e47d157de">

**Comment by BasaraABC** [comment]
I believe it is broken now. Tested with logged-in customer on fresh install the debugger shows NULL 
(first-order after install with Fast checkout, BS5 theme, Cash On Delivery)
<img width="1425" alt="loggedin" src="https://github.com/abantecart/abantecart-src/assets/2631910/ad25de18-5ffb-4ea0-b92f-5805dd1407b6">
