### ISSUE TITLE
Cannot load any shipping extension on Abantecart (localhost - XAMPP)

### ISSUE THREAD

**Issue by yiedpozi** [abantecart/abantecart-src#1594]
### Describe the bug
After performing a fresh installation of **Abantecart version 1.3.3**, I tried to add a product on the storefront. However, upon being redirected to the cart page, I received the following error message: `undefined`

![image](https://github.com/abantecart/abantecart-src/assets/7779434/3e09a4ae-4a72-4169-a0b1-43d834ce7b6f)

Upon checking the **Network** tab in my Chrome browser, got **400 HTTP error** on `index.php?rt=r/checkout/cart/change_zone_get_shipping_methods`. The response is as follows:

```
{
    "error_title": "Application Error!",
    "error_text": "Please check error log for more information",
    "error_code": 400
}
```

This is the error log message from the `system/logs/error.txt` file.

```
2023-07-07 9:29:12 - load error:  AbanteCart core v.1.3.3 Error: Could not load model extension/default_flat_rate_shipping
Trace: 
#0 C:\xampp\htdocs\abantecart\core\engine\controller.php:332
#1 C:\xampp\htdocs\abantecart\storefront\controller\responses\checkout\cart.php:121
#2 C:\xampp\htdocs\abantecart\core\engine\dispatcher.php:306
#3 C:\xampp\htdocs\abantecart\core\engine\response.php:87
#4 C:\xampp\htdocs\abantecart\core\engine\router.php:223
#5 C:\xampp\htdocs\abantecart\core\engine\router.php:86
#6 C:\xampp\htdocs\abantecart\index.php:97
 in <b>C:\xampp\htdocs\abantecart\core\engine\loader.php</b> on line <b>122</b>
```

I also tried to disable the flat rate shipping and use another shipping method, but I encountered the same error.

### Steps to Reproduce

1. Install Abantecart version 1.3.3 on XAMPP.
2. Add any product, then navigate to the cart page.
3. You will see an error message popping up on your cart page as per above screenshot.

### Expected Behaviour

After adding a product to the cart, we should be able to see the item and select a shipping method on the cart page.

### Environment

- XAMPP: 8.0.7
- PHP: 8.0.7

**Comment by BasaraABC** [comment]
Hello.
Make sure the URL you visit and Store URl are same in your settings https://abantecart.atlassian.net/wiki/spaces/AD/pages/5832828/Store+URLs+SSL

**Comment by yiedpozi** [comment]
Store URL set in the system settings:
![image](https://github.com/abantecart/abantecart-src/assets/7779434/25d9035e-21da-4328-ad01-18a862cb6c37)

Cart page that I visited: http://localhost/abantecart/index.php?rt=checkout/cart

**Comment by BasaraABC** [comment]
Please try to set both the Store url and Secure url and enable HTTPS for both. For localhost accept browser warning to visit site.

**Comment by yiedpozi** [comment]
Still returns same error message on https://localhost/abantecart/index.php?rt=checkout/cart after updating both Store URL and Secure URL and enable HTTPS for both settings. Also tried on incognito, same results.

**Comment by abolabo** [comment]
_Could not load model extension/default_flat_rate_shipping_
@yiedpozi is this file presents on hard drive?
i mean public_html/extensions/default_flat_rate_shipping/storefront/model/extension/default_flat_rate_shipping.php

**Comment by yiedpozi** [comment]
Yup, the file exists and accessible.

**Comment by BasaraABC** [comment]
@yiedpozi the file permissions can be incorrect and your local server cannot access it

**Comment by yiedpozi** [comment]
Nope, file permissions is okay.

**Comment by BasaraABC** [comment]
The issue can be OS-related (if you have Windows) you can try to use a docker for localhost
https://hub.docker.com/r/abantecart/abantecart
https://abantecart.atlassian.net/wiki/spaces/AD/pages/1118339077/Docker+Installation

**Comment by yiedpozi** [comment]
Issue solved after using Docker on my OS (Windows), as recommended by @BasaraABC. Thanks ya.
