### ISSUE TITLE
base currency code change

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1597]
https://forum.abantecart.com/index.php/topic,10192.msg39641.html#msg39641
If admin changes the currency code the base currency code still contains the old currency code in the database

**Comment by abolabo** [comment]
cannot replicate

**Comment by BasaraABC** [comment]
to replicate look at the database. After code changes the value in DB is not updated and this will cause issues.
See the video for details
https://github.com/abantecart/abantecart-src/assets/2631910/2ba7abe3-48c8-407b-8860-0959469fa2c6

**Comment by BasaraABC** [comment]
The issue is not fixed right. Please do not change the store default currency every time the non-default currency code changes.
Example: store default currency is USD, now if you change the second currency code like GBP to GBA the stores default currency will be British Pound
