### ISSUE TITLE
Typo.  Do you want it reported here?

### ISSUE THREAD

**Issue by bcsteeve** [abantecart/abantecart-src#160]
First, I have a very minor issue to report.  Second, I want to know if you want me to bother you with minor issues (at all, and if so, is here the place to do it)?.

I'm a new user so seeing things fresh can sometimes be a helpful perspective.

public_html\extensions\default_[LANG]\admin\language\english\default_[LANG]\default_[LANG].xml

Line 16.  Change "automatiacly" to "automatically"

**Comment by BasaraABC** [comment]
Hello.
You can post issues for <b>latest stable version only</b> here. I mean in github bug tracker https://github.com/abantecart/abantecart-src/issues
Thank you for your time.

**Comment by BasaraABC** [comment]
fixed. thank you
