### ISSUE TITLE
USPS Ground Advantage

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1602]
USPS is merging First Class Package and Parcel Select Ground and renaming them Ground Advantage. 
Please remove deprecated and add new service to USPS
https://support.pirateship.com/en/articles/8050803-usps-july-2023-changes-new-rates-first-class-package-and-parcel-select-merge-into-ground-advantage
https://forum.abantecart.com/index.php/topic,10265.msg39666.html#msg39666

**Comment by abolabo** [comment]
We had no code to manage these options.

**Comment by BasaraABC** [comment]
Please check the screenshot. We have a switch for each method, maybe we need to add one more?
<img width="936" alt="methods" src="https://github.com/abantecart/abantecart-src/assets/2631910/5b763f76-8fb4-4cfa-a76f-6beeff7d2815">

**Comment by BasaraABC** [comment]
Looks like API reply with new method but it is not visible in Storefront see
<img width="1265" alt="ground" src="https://github.com/abantecart/abantecart-src/assets/2631910/c22185e2-42bf-489e-a673-953e4ed73278">
