### ISSUE TITLE
pp commerce: refunded payment

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1606]
If a refund action was successful please make REFUND button not active. Show date of refund or refund transaction number if possible

https://github.com/abantecart/abantecart-src/assets/2631910/797358b4-fc9d-4cf3-ad4a-5936c5c6d248

**Comment by abolabo** [comment]
![image](https://github.com/abantecart/abantecart-src/assets/1264239/80afef75-7ebc-40ce-b550-bd5242bf4f94)
have no idea what i should to do.
All works fine. How to replicate this issue?

**Comment by BasaraABC** [comment]
I also can not replicate it anymore. Closed
