### ISSUE TITLE
In Create Account page (User registration), Region/State is presented as a required field, but is actually not

### ISSUE THREAD

**Issue by rubinghimire** [abantecart/abantecart-src#1608]
This bug is in Create Account (User Registration) Page

![image](https://github.com/abantecart/abantecart-src/assets/5090546/b4c9485b-29bf-4d8f-b1a9-d7a7dd61846d)

Please refer to image above. 

Steps to reproduce:
1. Fill in all details for registration except Region/State which is shown as a required field.
2. Proceed with registration (Click on Continue).

Expected behavior:
1. Error message warning user that Region/State is a required field.
2. User unable to register

Actual behavior:
1. No error message/field not "required".
2. User is able to register.

**Comment by BasaraABC** [comment]
Thank you @rubinghimire for the report

**Comment by BasaraABC** [comment]
@rubinghimire please apply changes to 2 files from [this commit](https://github.com/abantecart/abantecart-src/commit/9487da4c162ab4e08f860d87639a7a3bef2d2a2c)
