### ISSUE TITLE
User able to register using previously used email stored in database

### ISSUE THREAD

**Issue by rubinghimire** [abantecart/abantecart-src#1609]
![image](https://github.com/abantecart/abantecart-src/assets/5090546/ea296f3d-bf70-4dc7-aa5b-6fd8da2a42ef)

Please refer to image above.

Steps to reproduce:

    Fill in email used by another user account during registration
    Fill in other fields as required
    Proceed with registration (Click on Continue).

Expected behavior:

    Error message warning that email has been used by another account
    User unable to register

Actual behavior:

    No error message for email
    User able to register (tested this using valid inputs in other fields unlike as shown in image)

**Comment by BasaraABC** [comment]
Are you on the latest code? In my test registration returns error if email already registered
<img width="763" alt="email" src="https://github.com/abantecart/abantecart-src/assets/2631910/469a9c00-7f05-42f7-a715-e65c6429493b">

**Comment by rubinghimire** [comment]
Mine is version 1.3.4
Great if this was already fixed. Thanks!

**Comment by BasaraABC** [comment]
Which theme are you using? I see that the login and password errors are displayed under each field on my screen, but yours show them on the top.
<img width="999" alt="my_account" src="https://github.com/abantecart/abantecart-src/assets/2631910/509817b4-67aa-4868-a3fa-395192a2a2e1">

**Comment by BasaraABC** [comment]
Did you install any extensions from third parties or change any registration specific settings?

**Comment by rubinghimire** [comment]
![image](https://github.com/abantecart/abantecart-src/assets/5090546/7b88842c-c1a8-4cf5-8e8f-f51fbd50771b)

These are the extensions that are installed and enabled. No registration specific settings were changed.

**Comment by BasaraABC** [comment]
Could you please test the frontend issue on the 1.3.4 demo version? https://www.abantecart.com/shopping-cart-demo

**Comment by rubinghimire** [comment]
It seems to work just fine in the demo. Hmm.

**Comment by BasaraABC** [comment]
Did you upgrade your store from 1.3.3 to 1.3.4 or did you do a fresh installation? How did you install the software? Did you use the regular installation method or an auto-installer like a virtual machine or Softaculous?

**Comment by rubinghimire** [comment]
I used the Sofaculous installer
