### ISSUE TITLE
Text for Cart in site footer says "Basket". Uniformity required?

### ISSUE THREAD

**Issue by rubinghimire** [abantecart/abantecart-src#1611]
As a suggestion, the text for the cart menu item in the site footer should say "Cart" (says "Basket": refer attached image) as that is how it is in the rest of the website. This uniformity creates a better user experience in my opinion. Thanks!

Note: I'm using the bootstrap template

![image](https://github.com/abantecart/abantecart-src/assets/5090546/2f2963ff-ce86-47a5-b798-215114b51bfd)

**Comment by BasaraABC** [comment]
thank you
