### ISSUE TITLE
Usability: User checkout asking for telephone input 

### ISSUE THREAD

**Issue by rubinghimire** [abantecart/abantecart-src#1619]
In version 1.3.4 (tested on demo.abantecart.com), during registration the telephone field is not required.

But, the checkout process for this user is as follows:
1. When the user logs in and wants to buy a product, they are taken to fast-checkout which is a great convenience.
2. However, selecting Local shipping or Flat rate shipping takes the user to a page where they have to update their telephone (obviously this is because it's required for shipping)
3. Updating the telephone takes them to their account page (see image)
4. There's no redirection to checkout
5. The checkout flow is broken

This is bad from a usability perspective. 

Suggestion:
1. Make the telephone field required
2. Or, remove the requirement to update telephone during checkout (this wouldn't make sense as it's required for shipping)

![image](https://github.com/abantecart/abantecart-src/assets/5090546/2c192d8e-e0ea-4d40-bcbc-bcea45c572de)

**Comment by abolabo** [comment]
please use fast_checkout extension.
![image](https://github.com/abantecart/abantecart-src/assets/1264239/f3da9e21-4ea3-4560-abda-991aa501ddbf)
