### ISSUE TITLE
iPad Admin Front

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#163]
Few minor issues on iPad

issue 1: No possible to select store on ipad device. When you click on field somethimes selection dropdown shown, sometimes no also in some sections (product edit page) cursor jump to another filed
![ipad](https://cloud.githubusercontent.com/assets/2631910/8498732/91fff3a4-21b4-11e5-8bd0-44739826c95f.png)

_____________________________________
issue 2: minor misplacement on Category edit page
![ipad-issue1](https://cloud.githubusercontent.com/assets/2631910/8498692/1590884c-21b4-11e5-8e9d-a0d94a68ff70.png)

**Comment by abantecart** [comment]
#1. I tried many different scenarios and I can not replicate this problem. Let keep it in mind. 
#2. Fixed.
