### ISSUE TITLE
messages not closed automaticly

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#164]
In some admin sections like when add transaction to customer in admin all messages shown permanently. Please close them after timeout
![issue2-transactions](https://cloud.githubusercontent.com/assets/2631910/8498770/052cebc0-21b5-11e5-917a-3575c2bfddcb.png)

**Comment by abantecart** [comment]
Error should not autohide.

**Comment by BasaraABC** [comment]
but Success message is not autohide too

**Comment by abantecart** [comment]
Keep for now.
