### ISSUE TITLE
embed code #QA 1

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#166]
Tested embed code admin only because SF side not work

ISSUE 1: not to see issue please clear browser cache
<img width="993" alt="embed-issue1" src="https://cloud.githubusercontent.com/assets/2631910/8564933/fb525904-257a-11e5-8740-3468e66fcca2.png">
______________________________________________
______________________________________________

ISSUE 2: development in process?
<img width="969" alt="embed-issue2" src="https://cloud.githubusercontent.com/assets/2631910/8564934/fb5696d6-257a-11e5-9782-207f8e53d623.png">
______________________________________________
______________________________________________

ISSUE 3:
<img width="796" alt="embed-issue3" src="https://cloud.githubusercontent.com/assets/2631910/8564937/fb5bdb8c-257a-11e5-9fe9-dbf737155af1.png">
______________________________________________
______________________________________________

ISSUE 4: responsive issue
<img width="873" alt="embed-issue4" src="https://cloud.githubusercontent.com/assets/2631910/8564936/fb59f5ec-257a-11e5-8397-0ab3658d3129.png">
______________________________________________
______________________________________________

ISSUE 5: not a bug - suggestion
<img width="1070" alt="embed-issue5" src="https://cloud.githubusercontent.com/assets/2631910/8564938/fb5e984a-257a-11e5-8606-e185600ba7ce.png">
______________________________________________
______________________________________________

ISSUE 6: not a bug - suggestion
<img width="998" alt="embed-issue6" src="https://cloud.githubusercontent.com/assets/2631910/8564935/fb56faa4-257a-11e5-9657-5a40937e7c61.png">
______________________________________________
______________________________________________

ISSUE 7: single Category embed code generation broken
<img width="976" alt="embed-issue7" src="https://cloud.githubusercontent.com/assets/2631910/8564939/fbb268c6-257a-11e5-8741-da40f4e93668.png">

______________________________________________
______________________________________________
ISSUE 8: multistore conflict
<img width="1000" alt="embed-issue8" src="https://cloud.githubusercontent.com/assets/2631910/8564940/fbb4e3a8-257a-11e5-978b-2b07a856a5c5.png">

______________________________________________
______________________________________________
ISSUE 9: settings name hard to understand
<img width="889" alt="embed-issue9" src="https://cloud.githubusercontent.com/assets/2631910/8565141/e8694314-257c-11e5-8ce8-6c4fe8053afb.png">

**Comment by BasaraABC** [comment]
Issues #1,2,3,7 FIXED

**Comment by abolabo** [comment]
regarding issue 6. it's doesn't matter what you checked there. disabled categories will be skipped on remote side

**Comment by BasaraABC** [comment]
issues 2,3,4,6,7,8 fixed
issue 1 not fixed and moved to #191 
5 and 9 awaiting fix or feedback

**Comment by abantecart** [comment]
5 we need to add text. It was discussed before to have a text there 
9. Options should be:
- Same page Modal Dialog
- Open new page in same window
- Open new page in new tab

**Comment by abolabo** [comment]
fixed
