### ISSUE TITLE
embed code: product page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#167]
on product page missed Logo and some typo appear see screenshot
<img width="957" alt="embed-issue10" src="https://cloud.githubusercontent.com/assets/2631910/8569671/0efb0b3a-25a4-11e5-9466-d0a8890e3f27.png">

**Comment by abolabo** [comment]
probably already fixed

**Comment by BasaraABC** [comment]
missed log is still a problem

**Comment by abantecart** [comment]
I can not replicate. Please post link or code

**Comment by BasaraABC** [comment]
Dima fix it. Closed
