### ISSUE TITLE
catch mail send crush

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1686]
Original post https://forum.abantecart.com/index.php/topic,10715.0/topicseen.html
The registration process is crushed if some issue with the email sent. The customer is registered but seems white page because the email send failed, please add try-catch to make sure the customer did not see a white screen in case of a mail issue

**Comment by abolabo** [comment]
added parameter to method AMail->send($silent = false)
Silent emails only for order confirmation and order update processes. Other should work as earlier

**Comment by BasaraABC** [comment]
@abolabo not sure what is "silent emails" but please add it to the registration process
