### ISSUE TITLE
Unable to update Appearance settings

### ISSUE THREAD

**Issue by jcschott** [abantecart/abantecart-src#1687]
AbanteCart logo is reverted back to original after saving settings from both the default and Novator templates. 
- Fresh install of 1.4.0
- Confirmed all directories in install.txt are writable
-Steps to reproduce: 
1) Navigate to Settings --> Appearance
![Screenshot 2024-05-02 091135](https://github.com/abantecart/abantecart-src/assets/4073091/1dc21add-6b31-4b39-b2bb-43a475b2f4ef)

2)  Click Remove under default Store Logo
3) Click add
4) Upload logo
![Screenshot 2024-05-02 091225](https://github.com/abantecart/abantecart-src/assets/4073091/f751383e-ef45-4b0f-9048-0a6a266502c7)
5)Click save and apply
![Screenshot 2024-05-02 091241](https://github.com/abantecart/abantecart-src/assets/4073091/81d85883-ff9f-4979-9219-c54665ff16ca)

6) Scroll down and click save on edit settings page. 
7) Confirm success message, logos are reverted back to abantecart. 

- New Logo is available in Resource Library and is uploaded to server successfully.
-  Edited original abantecart logo and did not resize or change file type to confirm no issues with size with same result.
- Issue appears with attempting to change email logo as well. 
- Tried with both templates (novator and default) 
- Tried while template is disabled and enabled
- Tried to remove logo and save. Original logo is reset while success message appears to user.

**Comment by BasaraABC** [comment]
Thank you for bringing this issue to our attention. Issue is confirmed

**Comment by Robbty** [comment]
I have the same problem.
Is there a workaround until this issue is solved?

**Comment by BasaraABC** [comment]
Hello @Robbty 
We would like to update you that version 1.4.0 is under active development. In the meantime, we recommend utilizing the stable version 1.3.4

**Comment by Robbty** [comment]
I'm using version 1.3.4 with cPanel.

**Comment by Robbty** [comment]
I installed it again. Now it works.
Thanks you.
