### ISSUE TITLE
embed modal height

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#169]
modal popup's height is too large. Note: tested on popular resolution 1366X768 (33% of all PC see http://www.w3schools.com/browsers/browsers_display.asp)
![embed-issue12](https://cloud.githubusercontent.com/assets/2631910/8569929/a9235954-25a6-11e5-8ce4-36723904ef8f.png)

**Comment by abantecart** [comment]
I do not think this is a issue. Height can be different depending on options and blurb

**Comment by BasaraABC** [comment]
Even when content height is small we still show modal with height more that users display see <img width="1097" alt="new_blog__new_pr" src="https://cloud.githubusercontent.com/assets/2631910/8741297/b319a360-2c80-11e5-9650-8ce6fd419a64.png">
