### ISSUE TITLE
 Filetype not allowed

### ISSUE THREAD

**Issue by ambika1us** [abantecart/abantecart-src#1693]
when tried to upload a image it troughs the following error.

2024-06-08 11:52:27 - Unknown Error: AbanteCart core v.1.3.3 Attempt to assign property "error" on null in <b>/home4/shopi7q1/pasmedlifeindia.com/admin/controller/responses/listing_grid/file_uploads.php</b> on line <b>37</b>

any suggestion.

**Comment by abantecart** [comment]
What is the file type are you uploading? Please provide more details with STR.

**Comment by BasaraABC** [comment]
Hello. It appears you're encountering an error with AbanteCart version 1.3.3. I recommend upgrading to the latest version (1.3.4) as it may contain fixes for the issue you're experiencing. After updating, if the error persists, please provide a detailed step-by-step guide on how you encountered this error.
Please also check this forum topic https://forum.abantecart.com/index.php/topic,10572.msg41367.html#msg41367
