### ISSUE TITLE
unable to receive email

### ISSUE THREAD

**Issue by PHarris2024** [abantecart/abantecart-src#1696]
I requested to change admin  pw on my website.  Abantecart  gives a message that they sent information to my email address. When I check my email, it does not show up in inbox or spam. How do I change pw without receiving the needed reset?

**Comment by BasaraABC** [comment]
This does not seems like a bug report. The issue could be related to your mail server or hosting mail function, among other possibilities. For further assistance, please post your query on the AbanteCart community forum.
