### ISSUE TITLE
Bug on guest checkout AbanteCart  v1.3.4

### ISSUE THREAD

**Issue by MoeDawood15** [abantecart/abantecart-src#1697]
Hi 

Hope all is well 

I have picked up a bug on V1.3.4 on Guest Checkout, It allows a customer to continue without populating the State dropdown, this in turn plays with tax as tax is not calculated on the order 

Steps to reproduce 

Default template enabled same as the demo site

Fast checkout is disabled

Steps to Reproduce

Add Item to cart
Click on checkout
Select guest checkout
Fill in details
Leave state/region as is
Click continue , this will bypass guest checkout

This used to work on the previous version of AbanteCart

I have replicated on the demo site with the default template 

I have also tried to get a Fix on the forum with no luck - https://forum.abantecart.com/index.php/topic,10836.msg41588.html#msg41588

**Comment by BasaraABC** [comment]
@abolabo please suggest a fix for 1.3.4

**Comment by abolabo** [comment]
@MoeDawood15 see my reply on forum
