### ISSUE TITLE
Misplaced main product image

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#171]
<img width="839" alt="absolue_eye_precious_cells" src="https://cloud.githubusercontent.com/assets/2631910/8588620/d632156c-2636-11e5-86e8-4baccdb20206.png">

**Comment by abantecart** [comment]
Since we used Cloud Zoom it is hard to manage it. Added easyzoom

**Comment by BasaraABC** [comment]
few minor issues found with new zoom
Issue 1:
<img width="838" alt="zoom-bug1" src="https://cloud.githubusercontent.com/assets/2631910/8614503/68cba5ae-2714-11e5-8fff-b861b72c9ccb.png">
-----------------------
-----------------------
Issue 2: visible on Ipad
![zoom-bug2](https://cloud.githubusercontent.com/assets/2631910/8614504/68d1033c-2714-11e5-98c6-3095c238db75.png)

**Comment by abantecart** [comment]
Issue 1 is intentional.

**Comment by abantecart** [comment]
Issue 2: This is zoom action on hover. This is normal to cover other items if space no permitting. 
Not an issue.
