### ISSUE TITLE
Cannot login to admin storefront and cannot manage from back end

### ISSUE THREAD

**Issue by eyorkcmaa** [abantecart/abantecart-src#1713]
We had a changeover in staff and are now unable to access the admin side of our account - how to set up/connect new user as admin or transfer admin to another staff user? Help us get back into our account!

**Comment by BasaraABC** [comment]
Thank you for reaching out. However, GitHub is not the appropriate platform for account-related issues or administrative assistance. For help with accessing or transferring admin roles in AbanteCart, we recommend posting your question on the [AbanteCart Community Forum](https://forum.abantecart.com/) where the community can assist you.

Alternatively, contact [managed AbanteCart service](https://managed.abantecart.com/)
