### ISSUE TITLE
pickup from store: duplicate address

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1715]
When a registered customer places an order with the Shipping Method **Pickup From Store** the Store address is added to the account.

![pickup](https://github.com/user-attachments/assets/e955e2a3-72dc-429e-beee-04b9336930fe)

**Comment by BasaraABC** [comment]
The issue is not fixed and appears randomly. See the video where the customer has 2 addresses, but when checkout starts, the new address is used as the delivery address. To replicate, place a quest order and then log in to this customer (act on behalf). 


https://github.com/user-attachments/assets/e4ba42dd-df9b-4383-82c3-a2f2c264fc20

**Comment by abolabo** [comment]
this extension creates new address before checkout and remove it once purchase is finished.
