### ISSUE TITLE
Option Values Issue

### ISSUE THREAD

**Issue by jcschott** [abantecart/abantecart-src#1717]
When setting up an Option with a type: label 

the option values are not saved and the tab does not reload upon clicking save. 
Steps to reproduce: 
1) Navigate to product options
2) Add New Option
3) Select Element Type Label and click add
![Screenshot 2024-12-03 154143](https://github.com/user-attachments/assets/322c6563-ddca-4691-9a34-f6f98f341a15)
4)Update price modifier and any other details
![Screenshot 2024-12-03 153736](https://github.com/user-attachments/assets/dd3f9410-0d4f-4748-8c12-6505079d4ee1)
5) Click Save and tab does not load and data is not saved or reflected on product page
![Screenshot 2024-12-03 153802](https://github.com/user-attachments/assets/c016f1ac-b74f-4f36-9e4c-4b387c8df039)

**Comment by BasaraABC** [comment]
Thank you @jcschott for your detailed report. 
@abolabo the error in log occurs `Unknown Error: AbanteCart core v.1.4.1 array_map(): Argument #2 ($array) must be of type array, null given
Trace:
#0 //public_html/qa/141/admin/model/catalog/product.php(3062): array_map()
#1 //public_html/qa/141/admin/controller/responses/product/product.php(696): ModelCatalogProduct->validateOptionValues()
#2 //public_html/qa/141/core/engine/dispatcher.php(306): ControllerResponsesProductProduct->update_option_values()
#3 //public_html/qa/141/core/engine/response.php(87): ADispatcher->dispatch()
#4 //public_html/qa/141/core/engine/router.php(222): ATypeResponse->build()
#5 //public_html/qa/141/core/engine/router.php(86): ARouter->route()
#6 //public_html/qa/141/index.php(101): ARouter->processRoute()
#7 {main} in //public_html/qa/141/admin/model/catalog/product.php on line 3062`
