### ISSUE TITLE
ContactUs Form - Enquiry field value for regular expression pattern not saving

### ISSUE THREAD

**Issue by mpenterman-1** [abantecart/abantecart-src#1719]
I somehow changed the regular expression pattern for the 'enquiry' field on the contact us form. I cannot get the form to submit on my site without throwing an error (Enquiry must be between 10 and 3000 characters!). I went to the demo store, copied the regular expression pattern, pasted it into the field, and then saved. When I come back to the enquiry field, it reverts to the previous value. I have tried clearing cache, and it doesn't seem to make a difference. I cannot get the value to save (/^.{3,1000}$/su).

**Comment by BasaraABC** [comment]
Thank you @mpenterman-1 for reporting the issue. Issue is confirmed
![form](https://github.com/user-attachments/assets/4c77ada1-6b83-4d3c-a17a-d102f1cf2b39)
