### ISSUE TITLE
Cannot Switch Templates

### ISSUE THREAD

**Issue by ghhigbee** [abantecart/abantecart-src#1721]
I want to preface this by saying this issue exists after updating from 1.3 to 1.4 using the upgrade tool. I did not test with a fresh install. 

Issue: In Settings -> Appearance, when you attempt to switch from the Novator template to the Default template the settings value for config_storefront_template is not updated to default. The same holds true when switching from Default to Novator. The only way to switch templates is to directly edit the database to change the settings value.

**Comment by BasaraABC** [comment]
The Appearance setting switch does not change the storefront template. Please switch it in Design > Template.
