### ISSUE TITLE
embed issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#173]
1. no way to change currency on shopping cart page or in category listing
2. Payza not work in modal next errors appear "We apologize, but the payment button settings are incorrect. The following problems occurred
ap_purchasetype field is invalid. Acceptable values are item, service, item-goods, item-auction and subscription.
The ap_currency field is invalid.
The ap_itemname field cannot be left empty.
Sorry the merchant account is invalid."
3. 2checkout work but after you click confirm order and redirected to 2checkout side then Modal closed and 2checkout loaded in full page. After your complete order it redirect you to abantecart side in same window.
4. Paypal STD not work. After you click Confirm Order the load button shown infinity (note: PayPal PRO works)
5. problem with last visited page in modal CHROME BROWSER!. for example with categories embed code - on html page with embed code click on any category the category listing appear then add to cart and go to shopping cart page or my account page. Close the modal. Next click on embed category again - in Chrome browser opened last visited my account page instead of category listing

**Comment by abantecart** [comment]
#1 implemented into embed building section. Only 1 language/currency set is supported per embed code.

**Comment by abantecart** [comment]
I am not able to replicate # 5

**Comment by abantecart** [comment]
All resolved. Please refer to document with list of unsupported payments.
