### ISSUE TITLE
CSS Validation - home page 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#174]
see if you can fix some of them 
http://jigsaw.w3.org/css-validator/
<img width="906" alt="issue1" src="https://cloud.githubusercontent.com/assets/2631910/8648039/84c9b1b8-2987-11e5-823a-07c3435a0d32.png">

**Comment by abantecart** [comment]
I fixed 1 problem but now there are more errors. 
There is no css3 validator yet. 
Please read:
http://stackoverflow.com/questions/21166019/w3c-validator-css3-and-bootstrap

**Comment by BasaraABC** [comment]
thank you
