### ISSUE TITLE
Forms Manager -contact us form

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#176]
few issues if add few new fields to Contact Us form.
* ISSUE 1: typo in the FILE type field
<img width="446" alt="forms_manager_issue2" src="https://cloud.githubusercontent.com/assets/2631910/8648638/71bb7976-298c-11e5-9d9c-fe5164b2ed1b.png">

_______________________________________
_______________________________________
* ISSUE 2: can not save field status
<img width="777" alt="forms_manager_issue3" src="https://cloud.githubusercontent.com/assets/2631910/8649626/4c71600e-2996-11e5-9328-03bfa81011ce.png">

_______________________________________
_______________________________________

* ISSUE 3: field values not visible in enquiry
<img width="782" alt="forms_manager_issue4" src="https://cloud.githubusercontent.com/assets/2631910/8649627/4c74192a-2996-11e5-91df-d52b6f1f2e6a.png">

**Comment by abolabo** [comment]
fixed
