### ISSUE TITLE
Banner Slider - Open in New Window setting

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#177]
<b>Open in New Window</b> setting not work for Banner Slider. Not sure this is bug or not but setting has no effect
<img width="661" alt="banner_manager" src="https://cloud.githubusercontent.com/assets/2631910/8669426/bf673536-2a3e-11e5-8689-7e791ac0b6e5.png">

**Comment by abolabo** [comment]
fixed. setting removed for text-banners
