### ISSUE TITLE
menu, RL and drag-drop feature

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#180]
Image not linked to the menu if add it using Drag-n-drop to RL window. See screenshot (important to drag-n-drop to RL winodw showed in screenshot!)
<img width="870" alt="isue" src="https://cloud.githubusercontent.com/assets/2631910/8670068/d03c01a2-2a43-11e5-980d-039771fbb90f.png">

**Comment by abolabo** [comment]
fixed
