### ISSUE TITLE
Products SEO Url on cart page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#181]
seo urls not work on Shopping cart page
<img width="830" alt="seo" src="https://cloud.githubusercontent.com/assets/2631910/8670701/5fcfb7f0-2a49-11e5-8d48-e86ea7d06e23.png">

**Comment by abolabo** [comment]
seo url unavailable here. Each url have "key" instead "product_id". Key - is unique hash of product that separate two equal products with different options.
not a bug.

**Comment by abantecart** [comment]
SEO URL in Cart? This is never accessed by google. Not an issue.
