### ISSUE TITLE
SEO Urls and languages

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#182]
<img width="887" alt="2" src="https://cloud.githubusercontent.com/assets/2631910/8670857/92d2ad46-2a4a-11e5-8a20-589ed8d45037.png">
In my opinion this is important for usability do not skip please.
Take a not a Google recomendation:
<blockquote>Google uses the content of the page to determine its language, but the URL itself provides human users with useful clues about the page’s content. For example, the following .ca URLs use fr as a subdomain or subdirectory to clearly indicate French content: http://example.ca/fr/vélo-de-montagne.html 
Signaling the language in the URL can also help you to discover issues with multilingual content on your site.</blockquote>

**Comment by abantecart** [comment]
This is not a bug. We are wrapping up with 1.2.3.  Let's do this in 1.2.4.

**Comment by abantecart** [comment]
Use non SEO function in language switcher.

**Comment by abolabo** [comment]
fixed, but need to retest seo feature in diff places

**Comment by BasaraABC** [comment]
thank you. Fixed.
