### ISSUE TITLE
embed ignore 'Block Product From Ordering' and 'Out of stock'

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#186]
<img width="1000" alt="embedis2" src="https://cloud.githubusercontent.com/assets/2631910/8692417/3c92d484-2af8-11e5-8714-5e99f23c1ea5.png">
Note: add to cart button not work in this case

**Comment by abolabo** [comment]
fixed. now when product out-of-stock or call-to-order button will not show with qnt input
