### ISSUE TITLE
embed product 'add to cart' not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#187]
embed product 'add to cart' not work. No errors in firebug
<img width="471" alt="embedis3" src="https://cloud.githubusercontent.com/assets/2631910/8692523/077f14aa-2af9-11e5-92f7-106863147d68.png">

**Comment by abolabo** [comment]
tried your url - it works!

**Comment by BasaraABC** [comment]
issue related to cookies problem mentioned in #188  and #120
