### ISSUE TITLE
embed: Can not Add to cart product with options

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#188]
Checked in FireFox and Chrome browsers
<img width="819" alt="embedis4" src="https://cloud.githubusercontent.com/assets/2631910/8693024/f163b02c-2afd-11e5-888e-eaaef611a880.png">

**Comment by BasaraABC** [comment]
I think this bug is similar to https://github.com/abantecart/abantecart-src/issues/120

**Comment by abantecart** [comment]
What is your cookie security mode?

**Comment by BasaraABC** [comment]
Security mode default. I see this issue in FF, Chrome, Safari. 
Note: if clear browser cache issue gone that's why I think it is similar to #120 
<img width="575" alt="ff" src="https://cloud.githubusercontent.com/assets/2631910/8717066/bf45a112-2bc1-11e5-9250-7296aa153e09.png">

**Comment by abolabo** [comment]
i need to know how to replicate this bug. All works for me

**Comment by BasaraABC** [comment]
@abolabo issue described in #120 
I see issue all the time because I install fresh abc every day on same domain by in different folders so in my opinion cookies from old carts broke new one

**Comment by abantecart** [comment]
Basically, this is a collision between multiple stores installed on the same domain.
Looks like browser bug, but we can think of solution.

**Comment by BasaraABC** [comment]
closed because it duplicate with #120
