### ISSUE TITLE
New zoom - retina images enabled issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#193]
Issue visible on retina displays when Hi-res images enabled
<img width="1206" alt="_hello_flawless___custom_powder_foundation_with_spf_15" src="https://cloud.githubusercontent.com/assets/2631910/8698670/2e3cb76a-2b2a-11e5-8128-be290e8b7f31.png">

**Comment by abantecart** [comment]
Fixed.

**Comment by BasaraABC** [comment]
Please fix thumbnails images too
<img width="674" alt="thumb" src="https://cloud.githubusercontent.com/assets/2631910/8722099/52320b9a-2beb-11e5-9d53-1d6da1f4ce26.png">

**Comment by abantecart** [comment]
I do not think it is critical

**Comment by abantecart** [comment]
On real Retina display this thumb images will be shown smaller, right?

**Comment by BasaraABC** [comment]
yes. 90px image should be shown in 45px container. @abolabo fix similar issues when Hi-res setting added to AbanteCart

**Comment by abantecart** [comment]
Fixed.
