### ISSUE TITLE
embed - modal styles

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#194]
Modal follow source page styles but problem is it follow original styles only partly. See example on screenshot. Issue: modal follow link color and mouseover color but it show links on white bg and in result we have not visible links
<img width="926" alt="styles" src="https://cloud.githubusercontent.com/assets/2631910/8699383/56153618-2b2f-11e5-9f43-fe1a3fb02735.png">

**Comment by abantecart** [comment]
I made some CSS adjustments to prevent conflicts. It is up to web developer how to control styles.
