### ISSUE TITLE
embed: product info page and SEO url issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#198]
To replicate bug you need to access product info page from category with SEO url Enabled. Category or product should have seo url!
<img width="1492" alt="cateeis" src="https://cloud.githubusercontent.com/assets/2631910/8719973/cf40601c-2bd9-11e5-97d5-083ed575269b.png">

**Comment by abantecart** [comment]
No SEO urls should be present in embed modal. 

Fixed.
