### ISSUE TITLE
embed basket and modal

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#203]
<img width="1151" alt="new_blog__categ" src="https://cloud.githubusercontent.com/assets/2631910/8745129/ded4b3c0-2ca6-11e5-9acd-13d0768bb65c.png">

**Comment by BasaraABC** [comment]
Problem also actual after order completed. The basket still shows products in cart
<img width="1167" alt="new_blog__categ2" src="https://cloud.githubusercontent.com/assets/2631910/8745182/5667b5b8-2ca7-11e5-9bd8-f1c212f85f9e.png">

**Comment by abantecart** [comment]
There is no connection to this cart element from modal. That is why it was hidden before. 
I suggest to completely turn this cart off once modal is open and show again on close.

**Comment by abolabo** [comment]
fixed. will hide on modal show
