### ISSUE TITLE
demo orders wrong Store url and Date added minor issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#204]
<img width="1052" alt="orders" src="https://cloud.githubusercontent.com/assets/2631910/8770657/c28c85a4-2edf-11e5-9b12-1c9f2ef4979d.png">

Also there is small problem - all demo orders have Date Added at same day of cart installation. Is it possible to change this approach? See http://forum.abantecart.com/index.php/topic,3728.msg16102.html#msg16102

**Comment by abantecart** [comment]
Fixed and new demo data is loaded.

**Comment by BasaraABC** [comment]
All demo orders still have cart installation date and there is small issue in fixed url see screen
<img width="1085" alt="2015-07-21_13-23-35" src="https://cloud.githubusercontent.com/assets/2631910/8794297/687407b8-2fac-11e5-89db-216665ffc149.png">
About new demo products - all looks copied right...

**Comment by abantecart** [comment]
This is correct. There is no URL in the order demo data set, that is why it say demo.
