### ISSUE TITLE
Upgrade write permissions list message

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#207]
Permissions warning mislead user to change write permission for file in case permission for folder needed see screenshot
<img width="715" alt="upgrade" src="https://cloud.githubusercontent.com/assets/2631910/8772826/7396b194-2ef9-11e5-981b-93a65c3011dc.png">

**Comment by abantecart** [comment]
This is fixed. To test, you need to replace updated files into 122 and runt upgrade to 123.
