### ISSUE TITLE
Time error and mail not send or receive in any case 

### ISSUE THREAD

**Issue by kdeepak1226** [abantecart/abantecart-src#212]
Hello sir i am having this issue that email is not working in any case, not on contact us form, not forget mail, after registration, placing order or any case user and admin both not getting email. please fix it up. 
Time is also not correct in order history or invoice.
![tim](https://cloud.githubusercontent.com/assets/8141222/8778491/e992c3fc-2f1b-11e5-8c4d-883ce711aa5d.png)

**Comment by abantecart** [comment]
Are you confident, this is not a mail setting issue? Do you have any errors in the log?
Did you check this:
http://forum.abantecart.com/index.php/topic,3330.msg14277.html#msg14277

**Comment by kdeepak1226** [comment]
I have fixed the mail issue but. Time is still different in invoice as my
local time.

Thanks
