### ISSUE TITLE
Edit this block

### ISSUE THREAD

**Issue by kdeepak1226** [abantecart/abantecart-src#213]
![forum](https://cloud.githubusercontent.com/assets/8141222/8792952/b57137ae-2f8c-11e5-9b8e-53c12fd71951.png)
After slider there are shown 4 boxes one of them written as Free Shipping all over in world over 200$, I want to change this text to 'all over india' or something else. Thanks.

**Comment by BasaraABC** [comment]
Hello.
Can you please ask questions at AbanteCart forum http://forum.abantecart.com/ 
Github is place for bugs tracking only
Thank you.

**Comment by kdeepak1226** [comment]
I have tried to search, but i have not find any link to post the question.
I have created account, on forum but no link where to find the link to post
the query in forum .

Thanks

**Comment by BasaraABC** [comment]
<img width="1166" alt="general_support" src="https://cloud.githubusercontent.com/assets/2631910/8797004/0a424fc6-2fc3-11e5-95f4-e85e4ab1d20b.png">

**Comment by kdeepak1226** [comment]
Thanks i got it.
