### ISSUE TITLE
product option type FILE

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#217]
<img width="1388" alt="file" src="https://cloud.githubusercontent.com/assets/2631910/8799695/2a330b3c-2fd6-11e5-87c7-67d28d52b8a8.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
fix is not visible in 1.2.3 
Do you apply fix for 1.2.4?

**Comment by abantecart** [comment]
1.2.4 was not created at the time. so it is 1.2.3

**Comment by abolabo** [comment]
fixed
