### ISSUE TITLE
errors after successful extension installation

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#220]
<img width="868" alt="error_log" src="https://cloud.githubusercontent.com/assets/2631910/8847168/6991c5bc-3156-11e5-8714-02c7fbc42504.png">
Note: installation is successful and extension works. Package was downloaded from MP

**Comment by abantecart** [comment]
What extension did you use?

**Comment by BasaraABC** [comment]
new template in mp id=287

**Comment by BasaraABC** [comment]
@abolabo , can you please also check product_id 286.
 vendor upload it but it is not packed right absent .tar.gz !!! We already contact with him but He can not explain why we have this problem

**Comment by abolabo** [comment]
287 was installed without any problems.
Regarding product_id 286. I see that v.1.0.8 of this extension it's a zip-archive actually (not tar.gz). That's why it cannot be installed. it's a mp-bug. need to move into another issue tracker.

**Comment by BasaraABC** [comment]
Please try to install on dev server. What I see is warning
"2015-09-08 2:44:13 - warning: AbanteCart core v.1.2.4 array_unique() expects parameter 1 to be array, null given in <b>...../abc124_m09d08/admin/controller/pages/tool/package_installer.php</b> on line <b>571</b>"
Note: I use latest file1.0.7.tar.gz from product id 287

Regarding product 286 - thank you I will move bug to mp tracker

**Comment by abolabo** [comment]
warning fixed
