### ISSUE TITLE
Allow installation with user acknowledgment 

### ISSUE THREAD

**Issue by abantecart** [abantecart/abantecart-src#221]
![screen shot 2015-07-23 at 10 27 17 am](https://cloud.githubusercontent.com/assets/1239995/8852847/90be99ca-3125-11e5-8e12-5085752edbe3.png)

We need to add a check mark to offer user to acknowledge potential issues and allow continuing with installation.

**Comment by abantecart** [comment]
Same for "Warning: Your server have opcache php module enabled. Please disable it before installation!"

**Comment by abolabo** [comment]
fixed
