### ISSUE TITLE
Installation: Select Mysqli by default if both Mysql options are present 

### ISSUE THREAD

**Issue by abantecart** [abantecart/abantecart-src#222]
Default view
![screen shot 2015-07-23 at 10 34 57 am](https://cloud.githubusercontent.com/assets/1239995/8853024/9e017dae-3126-11e5-862f-a037dbab1a68.png)

![screen shot 2015-07-23 at 10 35 05 am](https://cloud.githubusercontent.com/assets/1239995/8853020/9b392a7c-3126-11e5-8af1-3f89b0286204.png)

**Comment by goatlady102** [comment]
fyi,  on my server I run Maria and on manual installs during the pre-123 testing  my default database driver always came us MySqli  -  I was impressed that it did.

**Comment by abolabo** [comment]
done
