### ISSUE TITLE
Update manager improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#223]
Update manager say «Your's extensions are up to date. Nothing to do.»   when new version available at MP
note for @abolabo:  abc is 1.2.3 and extension version compatible with 1.2.3

**Comment by abantecart** [comment]
This is tested and now needs to be developed on MP side.

**Comment by abolabo** [comment]
can not to replicate.
Conditions are:
1. Your store must be connected to MP.
2. Request for updates contains only installed extensions.
3. New version of extension must be greater then installed and also must support abantecart version that calls.
4. status of customer's orders must be "completed"
5. status of order downloads must be ON

**Comment by BasaraABC** [comment]
### Let me explain few problems in the current Updater logic.
> 1 . Your store must be connected to MP.

In this case on Updater page should be message "please connect to MP"


------------ | -------------
> 4 . status of customer's orders must be "completed"

No if set order status to Failed (manually in MP admin) I am still see update available in Updater

------------ | -------------
> 5 . status of order downloads must be ON

This also not work for me. Then I purchase addthis extension and then set all versions files to Off in the order and even set addthis version 1.2.1 file Off at product side - Updater still tell me about new 1.2.1 version


------------ | -------------
One more issue: If you have installed extension version 1.2.0 and on mp there are few new versions of this extension 1.2.1, 1.2.2 and 1.2.3 (addthis extension) the Updater tell you about 1.2.1 update. This is wrong - it should update to latest 1.2.3

- [x] Note: tested on AbanteCart 1.2.4 with test purchase free extension addthis and install with Extension upload addthis v1.2.0

**Comment by abolabo** [comment]
Changing of statuses of order downloads will affect only after 24 hours (or after clearing of cache) under abc v1.2.4-
In 1.2.5 added updating of data on updater page in admin.
Issue with latest version of extension fixed on MP-repository and can be checked after moving of code into production

**Comment by BasaraABC** [comment]
thank you for comments. I will close issue after new mp code will be moved to production

**Comment by abantecart** [comment]
What is the status here?

**Comment by BasaraABC** [comment]
Issue fixed. Close
