### ISSUE TITLE
notification window

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#224]
Can not open links from notifications. After click on link message closed and nothing opened.
<img width="569" alt="2015-07-27_16-46-11" src="https://cloud.githubusercontent.com/assets/2631910/8903008/19347f98-347f-11e5-99b1-4ac8b49af8a1.png">

**Comment by abolabo** [comment]
link becomes from ANT-server and now works correctly

**Comment by BasaraABC** [comment]
issue not fixed. The problem is when you click on it nothing clicked actually - only message window closed.
I see issue in FireFox and Chrome browsers. Please see updated screenshot
<img width="461" alt="links" src="https://cloud.githubusercontent.com/assets/2631910/9652061/0933d266-5242-11e5-815f-55216b206601.png">
P.S 
Do not close issue untill I check it.

**Comment by BasaraABC** [comment]
video with bug https://youtu.be/K2oAt_th0Lc?t=27s

**Comment by abolabo** [comment]
bug visible on design/template page. On dashboard all works fine. :/

**Comment by BasaraABC** [comment]
Please fix

**Comment by abantecart** [comment]
Fixed.
