### ISSUE TITLE
embed links

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#228]
Not all links can be embed please fix
working example: 
<pre>
&lt;a data-href=&quot;http://demo.abantecart.com/index.php?rt=r/content/content&amp;content_id=2&quot;  data-html=&quot;true&quot; data-target=&quot;#abc_embed_modal&quot; data-toggle=&quot;abcmodal&quot; href=&quot;#&quot;&gt;your menu item title&lt;/a&gt;
</pre>

but some links <b>not work</b> for example specials page loaded white page
<pre>
&lt;a data-href=&quot;http://demo.abantecart.com/index.php?rt=r/product/special&quot;  data-html=&quot;true&quot; data-target=&quot;#abc_embed_modal&quot; data-toggle=&quot;abcmodal&quot; href=&quot;#&quot;&gt;your menu item title&lt;/a&gt;
</pre>

also shopping cart page work only if you add <b>/embed</b> at the end of url so this code will <b>not work</b>
<pre>
&lt;a data-href=&quot;http://demo.abantecart.com/index.php?rt=r/checkout/cart&quot;  data-html=&quot;true&quot; data-target=&quot;#abc_embed_modal&quot; data-toggle=&quot;abcmodal&quot; href=&quot;#&quot;&gt;your menu item title&lt;/a&gt;
</pre>

**Comment by abolabo** [comment]
added new controller for embedding specials. second url must works.
regarding cart page. data-url http://demo.abantecart.com/index.php?rt=r/checkout/cart/embed works fine. Please clarify what's wrong.

**Comment by BasaraABC** [comment]
Shopping cart link not work see code example

```
<a data-href="http://dev06.*******/abc124_m09d04/index.php?rt=r/checkout/cart"  data-html="true" data-target="#abc_embed_modal" 
 data-toggle="abcmodal" href="#">Shopping Cart link</a>
```
White screen when open shopping cart embed link
<img width="982" alt="new_blog__test_embed_links_124" src="https://cloud.githubusercontent.com/assets/2631910/9679626/6497dafc-531a-11e5-84c0-36358a47faca.png">

**Comment by BasaraABC** [comment]
Should we fix cart link issue or add to embed manual separate example for cart link embeding?

**Comment by abantecart** [comment]
Shopping cart RT is only exception
'r/checkout/cart/embed'

Please add this to the manual
