### ISSUE TITLE
Header link in admin go to wrong page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#230]
<img width="913" alt="link" src="https://cloud.githubusercontent.com/assets/2631910/9133116/1628b768-3d23-11e5-892e-c01c56165269.png">

**Comment by abolabo** [comment]
it's not a bug. Page was created to come over permission restriction

**Comment by abantecart** [comment]
To add clarification. 

page #1 to edit your own user details. 
page #2 to edit other users (including yourself) 
This page is under permission management. 

Boris, If this was asked on forum, please clarify.
