### ISSUE TITLE
It's hard to discern which options are shared for a given language and which are different.

### ISSUE THREAD

**Issue by mksystem** [abantecart/abantecart-src#231]
Lack of indications (en, ru, es, etc) for the language-dependent fields generates mass misunderstandings.

For example, in a very simple way you can overwrite the product's "SEO keyword" - that is shared to all languages but (when generating) is based on product name, which is different for each product. 

But this is just a small example.

**Comment by BasaraABC** [comment]
Issue fixed in 1.2.4 
Thank you
