### ISSUE TITLE
It's hard to discern which options are shared for a given store and which are different.

### ISSUE THREAD

**Issue by mksystem** [abantecart/abantecart-src#232]
Some fields are shared beetwen stores, some not.

Lack of indications (default, store1, store2, etc) for the store-dependent fields generates misunderstandings.

**Comment by abantecart** [comment]
Possibly it is a bug. All settings are store ID based. Do you have an example or screenshot?

Thank you

**Comment by abantecart** [comment]
Please let us know what fields (you think) are more store dependent. All settings should be store based.

**Comment by abantecart** [comment]
Since there is no reply, I push this to 1.2.6

**Comment by abantecart** [comment]
Closed. No reply with details
