### ISSUE TITLE
bug in settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#233]
If you replace (upload) new logo it saves on save and link OK
 But
If you select different image from RL list and do Save & Link it adds to page, but does not save to setting. Saves only on whole page save

**Comment by abantecart** [comment]
Please retest in template edit area.

**Comment by BasaraABC** [comment]
there is still problem: after your upload new image and click 'Save and Link" button the logo filed changed and "Resource successfully updated" message shown BUT if reload page old logo appear

**Comment by BasaraABC** [comment]
fixed. Warning about not saved settings appear. Thank you
