### ISSUE TITLE
paypal custom logo

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#234]
PayPal custom logo not showed on Paypal side see
<img width="666" alt="paypal" src="https://cloud.githubusercontent.com/assets/2631910/9376628/05e3f22a-473a-11e5-8e50-257835552407.png">

**Comment by abantecart** [comment]
I tried this on dev01.... and it works just fine. 
Where did you try this?

**Comment by BasaraABC** [comment]
I see it on dev06 sandbox account (test mode: Yes)
also firebug report
"NetworkError: 500 Internal Server Error - https://www.sandbox.paypal.com/securecontent/image/c8395d5f6d066ed1d8187ae1270288635202a116fe06e5866943d584a9cc9a4c538506824147c2e08d0ffd5c7641e8caef7fc98d495b400dd9de2884edb554f62cc50f7be43afe0749f8c58e591d5a755bd17212661f1286bcc69a4238b673db74022d6c65063abc368160744b6fe638"

**Comment by abantecart** [comment]
Try live

**Comment by BasaraABC** [comment]
Yes it work in live mode.

**Comment by abantecart** [comment]
I think there is a problem with PayPal sandbox. Closing for now. We should let customers on a forum know about this,
