### ISSUE TITLE
Weight Based shipping and Free shipping products

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#235]
If you have multiply items in cart and one of the product have Free Shipping on then all products are free shipping (bug in Weight Based shipping)
http://forum.abantecart.com/index.php/topic,3935.msg16960.html#msg16960

**Comment by abolabo** [comment]
fixed

**Comment by webdevmerc** [comment]
I tested this quickly and it seems to be working ok.   Do you know of a quick way to also disable the free shipping for an order if, say a buyer wanted to upgrade to faster shipping with only free ship items in their cart?

This seems to work fine if a non-free ship item is in the cart also, but if only free shipping is there, other shipping options become free as well.

I have an Upgrade to Priority Mail option which has a fee, but with this fix, it seems to make that option Free as well.  My work around would be to raise the free item's weight to over the limit of when the Upgrade option is available (only available if items are < 1/2 pound), but wanted to see if you had a quick idea to deal with this case.

Thanks for the quick turnaround and work as always!

**Comment by BasaraABC** [comment]
Please move conversation to the AbanteCart forum http://forum.abantecart.com/

Bug fixed
