### ISSUE TITLE
textarea attribute - new line

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#236]
Customer report that new line in textarea attribute shown as "\r\n" in order history sf & admin, shopping cart page and checkout.

Should we replace this characters and display more human readable new line? See screenshots
<img width="1100" alt="newline" src="https://cloud.githubusercontent.com/assets/2631910/9513888/2cc02adc-4cbf-11e5-9463-097b8c7b6ddf.png">

forum post http://forum.abantecart.com/index.php/topic,3940.0/topicseen.html

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Few problems with fix:
###### 1. Why option name is not visible on product page?
<img width="393" alt="opt" src="https://cloud.githubusercontent.com/assets/2631910/9599408/f527f994-50bd-11e5-82ae-f81fefaeda5b.png">


---------------------------
###### 2. Why your limit text in Admin > Sale > Orders > Order edit page? How admin should find full version of text? As we discussed your should limit only on Storefront pages
<img width="517" alt="adm" src="https://cloud.githubusercontent.com/assets/2631910/9599435/205bf4da-50be-11e5-9743-172a4990db29.png">



---------------------------
###### 3. Initially issue was about "\r\n" symbols for new line - the problem still there. On SF and admin we display "\r\n" instead of new line.
<img width="1090" alt="rissues" src="https://cloud.githubusercontent.com/assets/2631910/9599319/21ada424-50bd-11e5-8bf8-6c6fe4382bd2.png">



---------------------------
###### 4. We discussed to remove all html, right? Now html tags are not striped. (for example `<p><b>This text is bold.</b></p>`  in the cart, checkout and order history goes same)
<img width="548" alt="html" src="https://cloud.githubusercontent.com/assets/2631910/9599387/bf811b7c-50bd-11e5-8fe4-158407099ac4.png">

**Comment by abolabo** [comment]
fixed
