### ISSUE TITLE
wizard button on settings page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#241]
Please restart wizard if it is started from settings page.
Also why we wizard have not 'previous' (back)  button?
<img width="983" alt="wizard" src="https://cloud.githubusercontent.com/assets/2631910/9574782/4786e4f4-4ff4-11e5-873f-a2739a815a21.png">

<strong>Note: browser session is same with first admin login</strong>

**Comment by abantecart** [comment]
I do not agree. Wizard is completed. If settings needed, they are available in regular place.  Wizard will restart next time you login. 

Again, the goal here to give quick walk though the settings, this is NOT another screen to manage settings.
