### ISSUE TITLE
warning in log if visit templat edit section

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#242]
To replicate visit yoursite/index.php?rt=design/template/edit&tmpl_id=default&s=your_admin

warning: AbanteCart core v.1.2.4 Invalid argument supplied for foreach() in <b>/.../htdocs/abc124_m08d31/admin/view/default/template/pages/design/template_edit.tpl</b> on line <b>15</b>

**Comment by abantecart** [comment]
resolved
