### ISSUE TITLE
CKeditor RL: can not insert Resource  HTML in FF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#245]
No way to add Resource HTML to the description. See screen
<img width="1100" alt="src" src="https://cloud.githubusercontent.com/assets/2631910/9598829/0bbd046a-50b9-11e5-8b61-355ac8c05eee.png">

**Comment by abolabo** [comment]
You forgot to click "Source" button after code pasting. 
Note, almost all html-code will not shown on admin side because it use storefront template styles and base url(for relative urls). You should to check resource-code  ONLY  on SF side!

**Comment by BasaraABC** [comment]
No I did not forgot. Source is empty (I recheck once again).
Please check in the text banner. Admin > Design > Banner Manager > Edit Text banner

**Comment by BasaraABC** [comment]
Update: bug visible in FF only
tested in FireFix 39 Windows, FireFox 40.0.3, Firefox 40 Mac OS
in other browsers issue not visible

**Comment by abolabo** [comment]
some errors in firebug console ?
tried to reproduce in FF v40 under ubuntu linux. works fine

**Comment by BasaraABC** [comment]
Did you note that issue visible on Windows and Mac?
Anyway see video https://www.youtube.com/watch?v=yTUSnsMeqx0&feature=youtu.be
No errors in the firebug

**Comment by abolabo** [comment]
no chance to replicate. tried under linux and win7

**Comment by abantecart** [comment]
Works on Mac as well, but on earlier version of FF. I will try later on FF 40.0.3

**Comment by abolabo** [comment]
probably fixed

**Comment by BasaraABC** [comment]
thank you. Now works in major browsers.
