### ISSUE TITLE
embed style minor issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#247]
Add to cart button is not visible in default wordpress theme.
Can we fix this? WP is very popular and at least in default theme buttons should be visible
<img width="770" alt="wp" src="https://cloud.githubusercontent.com/assets/2631910/9627759/713b0102-5190-11e5-818a-0451a1b74bb8.png">

**Comment by abantecart** [comment]
This is specific to parent window CSS. I think we need to include style for buttons in embed.

**Comment by abolabo** [comment]
fixed
