### ISSUE TITLE
Brands admin multilanguage

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#249]
<img width="1023" alt="seo" src="https://cloud.githubusercontent.com/assets/2631910/9651944/f1036f7c-5240-11e5-9ec4-dbb2068072bc.png">

**Comment by abantecart** [comment]
Manufacture is NOT multilingual!!!

**Comment by BasaraABC** [comment]
But Manufacturers SEO keyword is multilingual
