### ISSUE TITLE
footer docs link

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#251]
<img width="899" alt="dashboard" src="https://cloud.githubusercontent.com/assets/2631910/9655676/19746904-525d-11e5-9793-942fd1695e70.png">

http://docs.abantecart.com/

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Please also fix in the installation footer
install/index.php?rt=finish

**Comment by abantecart** [comment]
Updated 4 more places with new link
