### ISSUE TITLE
js errors on index.php?rt=index/home

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#252]
firebug report errors if visit home page with 
index.php?rt=index/home
Note: no errors if visit without this parametrs
<img width="1203" alt="hello_worlds" src="https://cloud.githubusercontent.com/assets/2631910/9656061/ad71f3c2-525f-11e5-9490-079ec6358c67.png">

**Comment by abantecart** [comment]
Fixed.
