### ISSUE TITLE
description RL button

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#256]
when insert existing resource image
it is not inserted. Instead of image inserted "text to insert" text
<img width="656" alt="bugrl" src="https://cloud.githubusercontent.com/assets/2631910/9717139/6286e280-559a-11e5-9154-b0fc12bb662e.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Please check this video
https://youtu.be/aA3WCIQuDdc
issue same with #245 but visible now in Chrome too
