### ISSUE TITLE
installation without demo data

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#260]
Minor usability issue if install cart without demo data
on first login user see 3 messages in one time. Improve required.
Please see screenshot
<img width="1205" alt="dashboard" src="https://cloud.githubusercontent.com/assets/2631910/9811503/e7425298-58a1-11e5-81a8-2f4dfe326cf0.png">

**Comment by abantecart** [comment]
There is no easy away to resolve this. 

I will check.

**Comment by abantecart** [comment]
I improved a bit, but messages will still show.

**Comment by BasaraABC** [comment]
On first admin login wizard say "You have completed quick starter wizard. "
<img width="813" alt="dashboard" src="https://cloud.githubusercontent.com/assets/2631910/9842688/900ca046-5adb-11e5-8bc2-a60bfc05487a.png">

**Comment by BasaraABC** [comment]
Also please fix typo
<img width="919" alt="dashboard2" src="https://cloud.githubusercontent.com/assets/2631910/9842780/da9834f8-5adc-11e5-81c9-b0d5e28fba8a.png">

**Comment by abantecart** [comment]
Fixed
