### ISSUE TITLE
if remove product image still in RL

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#261]
Try to delete <b>Seaweed Conditioner</b> product
then search in RL for <b>demo_product19</b>. Product removed but image still in the RL

**Comment by abantecart** [comment]
Currently, resources are not deleted if product is deleted. We will consider to add this step in 1.2.5

**Comment by BasaraABC** [comment]
Update: When you delete resource in RL - original image is removed from /resources/image/… folder but generated thumbnails    /image/thumbnails/….  are not deleted. We need to delete everything related to deleted resource

**Comment by abolabo** [comment]
fixed
