### ISSUE TITLE
Relations Tab

### ISSUE THREAD

**Issue by itecfx** [abantecart/abantecart-src#264]
The Relations Tab has problems displaying the Related Products when the name of the product contains a single quote.

**Comment by BasaraABC** [comment]
Please upload screenshot and post your AbanteCart version

**Comment by BasaraABC** [comment]
Can not replicate with double or single quotes. Please report with screenshot.

**Comment by itecfx** [comment]
![relations_relatedproduct_has_singlequote](https://cloud.githubusercontent.com/assets/3938469/10127883/5b566c78-655e-11e5-91db-a1c7d3cc464a.png)
![relations_relatedproduct_no_singlequote](https://cloud.githubusercontent.com/assets/3938469/10127884/5b68c616-655e-11e5-84ad-0b92f9806c77.png)


The version of abantecart I am using is 1.2.4. These images show the difference when the name of the related product has a single quote and when you remove the quote. You can select related items the first time, after that the field disappears.

**Comment by BasaraABC** [comment]
Issue confirmed. We will fix it in 1.2.5

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
issue is visible if few products added as related. Please see screenshot
![symbol](https://cloud.githubusercontent.com/assets/2631910/10214775/7b82dcd6-6845-11e5-9881-e386d23263f7.png)

**Comment by abolabo** [comment]
fixed
