### ISSUE TITLE
email address validation improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#266]
currently email field validation do not allow to register with email like admin@seeme.fashion
<img width="476" alt="email" src="https://cloud.githubusercontent.com/assets/2631910/10214867/5a26ae04-6846-11e5-9e7b-10f8e4e0fc4d.png">
Please fix in all places where validation work (admin/sf)
http://forum.abantecart.com/index.php/topic,4047.0/topicseen.html

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
fix is not work. If register new account same error E-Mail Address does not appear to be valid!

**Comment by abolabo** [comment]
fixed
