### ISSUE TITLE
thousand and decimal separators

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#267]
When you change thousand and decimal separators problems appear if save price with new separators see screen
Note: AbanteCart cache were cleared.
![sep](https://cloud.githubusercontent.com/assets/2631910/10218236/6be0ea92-685f-11e5-97f0-4b6e5a145221.png)

http://forum.abantecart.com/index.php/topic,4049.msg17524.html#msg17524

**Comment by SveinGystad** [comment]
Yes, I have done this several times as I have clearly stated. If you will look at my abantacart it now says 1.000,00 on the storefront, but in the product register it says: 1,000,00! So like I mentioned, if I add another item in the product register for Kr. 3.400,00 the thousand separator reverts to US default (comma), and the price appears on the storefront as Kr.3,40 since the system now considers the thousand separator as decimal point!

**Comment by abolabo** [comment]
Please check "thousand_point" definitions for both sections, i mean for "admin" and "storefront". You can filter grid of definitions on page.

**Comment by BasaraABC** [comment]
Hello. I found where were the problem. You need to change points definitions for two sections: Admin and Storefront. Like in screenshot attached.
![points](https://cloud.githubusercontent.com/assets/2631910/10241263/d071c376-6910-11e5-897d-1524032444cb.png)
note: in case you cannot find definition for admin please clear AbanteCart cache then visit product page in admin and come back to Language Definitions to check

**Comment by SveinGystad** [comment]
It’s all sorted now, had to change it 4 different places!

 

Fra: BasaraABC [mailto:notifications@github.com] 
Sendt: Friday, October 02, 2015 8:23
Til: abantecart/abantecart-src
Kopi: SveinGystad
Emne: Re: [abantecart-src] thousand and decimal separators (#267)

 

Hello. I found where were the problem. You need to change points definitions for two sections: Admin and Storefront. Like in screenshot attached.
 <https://cloud.githubusercontent.com/assets/2631910/10241263/d071c376-6910-11e5-897d-1524032444cb.png> points
note: in case you cannot find definition for admin please clear AbanteCart cache then visit product page in admin and come back to Language Definitions to check
