### ISSUE TITLE
Reports reset

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#269]
Products Purchased Report  reset not work.
<img width="988" alt="reports" src="https://cloud.githubusercontent.com/assets/2631910/10275749/250335a4-6b74-11e5-940f-d9fa200e55a3.png">

**Comment by abolabo** [comment]
button replaced by search form with date range

**Comment by BasaraABC** [comment]
two new problems:
1. Please show default date range see how it works in the Reports > Sales > Orders 
Currently date ranges are empty.
2. When date field empty and you click on it  - the default month is incorrect. Should be shown current month (October) but shown previous month (September)
<img width="487" alt="month" src="https://cloud.githubusercontent.com/assets/2631910/10301422/96f02ec0-6c2c-11e5-92b1-79afa2687dac.png">

**Comment by abolabo** [comment]
added default date range 30days
