### ISSUE TITLE
Automatically populating $HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by greencopper** [abantecart/abantecart-src#270]
Trying to install abantecart on PHP 5.6.14, getting the following error on "Data configuration" page:

Following error has occurred during installation:
OK: 
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0
{"ret_code":50}
Name	Info
2::warning
session_start(): Cannot send session cache limiter - headers already sent in /var/www/abantecart/core/lib/session.php on line 86

**Comment by greencopper** [comment]
Had to downgrade to PHP 5.5 to get it installed.

**Comment by abolabo** [comment]
AbanteCart  do not use old predefined variables like $HTTP_RAW_POST_DATA.
Usually warning "Warning: Cannot modify header information - headers already sent..." relates to disabled output buffering in php.ini. 
Please check http://php.net/manual/en/book.outcontrol.php

**Comment by abantecart** [comment]
I am closing this. If this is still an issue, please reopen or create a new issue.
