### ISSUE TITLE
add Italian into 1.2.5

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#273]
Please add Italian language to core

**Comment by BasaraABC** [comment]
Italian added but 
### 1. a lot of missed translations.
On Create account page index.php?rt=account/create
Newsletter subsribe page index.php?rt=account%2Fsubscriber&email=

### 2. in admin no way to edit product option values. Edit form is not loaded.
Firebug report an error
__SyntaxError: missing } after property list
error_attribute_not_selected: 'Seleziona l'opzione da aggiungere!'__
Please note I report similar issues before - if text has ' symbol we get errors. Possibly core bug

**Comment by abantecart** [comment]
Please, Update to have a correct extension name default_italian
remove junk file Thumbs.db

**Comment by abantecart** [comment]
Fixed
