### ISSUE TITLE
Admin order update Notify guest customer issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#276]
When you update order in admin with Notify  - Guest customer receive email with not working link
"To view your order click on the link below:
<my website url>/index.php?rt=account/invoice&order_id=14"
http://forum.abantecart.com/index.php/topic,4081.msg17658.html#msg17658

**Comment by abolabo** [comment]
link to order removed from email.

**Comment by BasaraABC** [comment]
reopened please read https://github.com/abantecart/abantecart-src/commit/7f33455e65f5b5dc00f56f1ed3fdb4823f3b40d9#commitcomment-14064308

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
#303
