### ISSUE TITLE
Pagination links are broken when default sorting is by name or price

### ISSUE THREAD

**Issue by dchekanov** [abantecart/abantecart-src#279]
Details and how to reproduce:

1. Log in into demo instance http://demo.abantecart.com/?s=demo_admin
2. Change `config_catalog_limit` to 2
3. Change `config_product_default_sort_order` to "Name A-Z"
4. Go to http://demo.abantecart.com/index.php?rt=product/category&path=36
5. Notice that products are sorted as expected
6. Go the the second page via pagination link
7. Notice the sorting order switches to "Default" and products are sorted accordingly

I guess you need to add prefixes for $sorting_href defined at https://github.com/abantecart/abantecart-src/blob/master/public_html/storefront/controller/pages/product/category.php#L120 just like it is done for $sort a few lines below that. Other listings could be affected as well (specials, manufacturer).

**Comment by abolabo** [comment]
fixed. 
thanks to you for bug-report:)

**Comment by BasaraABC** [comment]
Bug is visible in Specials listing. Please fix

**Comment by abolabo** [comment]
fixed.

**Comment by BasaraABC** [comment]
Specials listing fixed.
Question: what is Default sort by option? Now if set in admin *Sort Products as default by: Name A-Z* and them select in listing *Sort by: Default* the sorting result is different
<img width="437" alt="special_offers" src="https://cloud.githubusercontent.com/assets/2631910/10759813/2217687c-7cec-11e5-9ec0-d84fcc7fc972.png">

**Comment by abolabo** [comment]
default means by "sort order" field
