### ISSUE TITLE
Minor migration text update

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#280]
Please update texts in Migration tools. See screenshots:

1. Update error message when entered database info is wrong
<img width="728" alt="cart_migration1" src="https://cloud.githubusercontent.com/assets/2631910/10659385/9894d07e-78c9-11e5-91f1-86341dc3ba71.png">

2. Migration work for Opencart 2.x please update text
<img width="775" alt="cart_migration2" src="https://cloud.githubusercontent.com/assets/2631910/10659387/9d35b198-78c9-11e5-81cb-1b8f22afe73c.png">

3. Migration work for Zencart 1.5x too. Please update text to "Zencart 1.3x-1.5x"

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
You forgot to update Zencart text

**Comment by abolabo** [comment]
oops.
done.
