### ISSUE TITLE
Bug in Extension Installation 

### ISSUE THREAD

**Issue by abantecart** [abantecart/abantecart-src#282]
2 bugs here 

STR #1:

1. Install cart in dev or your copy  
2. Connect to MP
3. Get extension is click install. 
DO NOT INSTALL or agree to license, 
4. Click on get extensions menu and get another extension and install. 
5. Follow installtion
Problem: First extension is installed, should be last one. 

STR #2:
This is harder to replicate, but possible. 
1. Install new cart on dev sever (needs to be new cart not ever connected). 
2. Connect to MP 
3. Get extension that you never got before in your account. 
4. Click Agree 
Problem: Page redirected to install page and no installation. 

Observation:  It happens on Dev server, I did not try local. 
After initial install, first extension purchased from MP does not install. Install process redirects back to install section. I debug it, and discovered this is related to line 261:

		if (!$disclaimer && !$this->session->data['installer_disclaimer']) {

During 3-4 debugs, problem went away and I stopped. 
Please follow the logic and add comments, it is not clear what is going on in there. 

		if ($this->request->is_POST()) { // if does not agree  with agreement of file size
and 
				$disclaimer = (int)$this->request->get['disclaimer'];

How can it be GET if it is submitted in the post in the form?

Please revisit and fix the bug.

**Comment by abolabo** [comment]
str.1 fixed

**Comment by abantecart** [comment]
Boris. We need to test extension installation process very detailed. Thank you

**Comment by BasaraABC** [comment]
Extension install with Url not work
![extension](https://cloud.githubusercontent.com/assets/2631910/11089357/ad1a77f6-889b-11e5-97cb-dd15cecacef3.jpg)

**Comment by abolabo** [comment]
fixed
