### ISSUE TITLE
missing language definitions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#285]
If enable Warnings for missed language definitions the next warning appear for english
definition "text_looking_for" is missing for "English"
definition "text_continue_typing" is missing for "English"

**Comment by BasaraABC** [comment]
To replicate:
1. go to System > Settings and enable **Warn for missing language text**
2. Visit storefront and search something
<img width="577" alt="message_manager2" src="https://cloud.githubusercontent.com/assets/2631910/10811286/e15850d8-7e3c-11e5-8edf-401c5a46fc63.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue not fixed

**Comment by BasaraABC** [comment]
Few new warnings:
![message_manager](https://cloud.githubusercontent.com/assets/2631910/11031113/cb1750aa-8704-11e5-9706-4bcda365a049.jpg)
