### ISSUE TITLE
Data listing block with popular_brands_content_bottom.tpl wrapper

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#289]
If create Data Listing block with custom wrapper **popular_brands_content_bottom.tpl** the links of products will be broken see screen
<img width="1500" alt="home" src="https://cloud.githubusercontent.com/assets/2631910/10811405/3b263ec6-7e3e-11e5-9275-cdb6eee6561a.png">
Also customer report that in some cases links not work on mobile devices see http://forum.abantecart.com/index.php?topic=4165.msg18143#msg18143

**Comment by abolabo** [comment]
fixed. please retest all listings.

**Comment by BasaraABC** [comment]
Issues:
1. Limit **quick save**: when it shown it doesnot work. And sometimes it doesn't show at all (select new listing type to see).
2. Popular products. When you click top product (first in block) and revisit page with block. Then clicked product moved to the bottom or to the middle of block. Why? It start to be less popular? How popularity calculated?
3. Specials Offers. Unlimited is not working. When **Limit** value is empty only 4 products shown!
4. Manufacturers. **Limit** doesnot work. All brands shown!
5. Featured. **Limit** doesnot work. All featured products shown!  Clear cache not help.
6. Featured - waring in the log warning: AbanteCart core v.1.2.5 Missing argument 1 for ModelCatalogProduct::getFeaturedProducts() in <b>//abc125_m11d04/storefront/model/catalog/product.php</b> on line <b>657</b>
7. Latest products. **Limit** doesnot work. All latest products shown!

**Comment by abolabo** [comment]
1. qs disabled there
2. popular means most viewed
other fixed

**Comment by BasaraABC** [comment]
Issue 2 - not fixed.

**Comment by abolabo** [comment]
now fixed
