### ISSUE TITLE
Contact Us page - new line in message

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#293]
If use new line (keyboard Enter) in the message then 2 problems:
1. new lines not visible in message received
2. warning in log warning: AbanteCart core v.1.2.5 Invalid argument supplied for foreach() in <b>//abc125_m11d03/storefront/view/default/template/mail/contact.tpl</b> on line <b>32</b>

**Comment by abolabo** [comment]
fixed
