### ISSUE TITLE
message menager minor bug

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#295]
popup text doesnot hide after you click to view few messages please see screenshot
Browser: FireFox 42.0
<img width="976" alt="message_manager" src="https://cloud.githubusercontent.com/assets/2631910/10935743/b96814ea-831a-11e5-92c2-28ecdd52ea88.png">

**Comment by abantecart** [comment]
This is possibly computer. Dima, check that close even if fired, this can happen due to JS error.

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue visible if click to view Unread messages. Maybe something happen when it is marked as read

**Comment by abolabo** [comment]
it's a bootstrap.js bug. Tooltip hide based on mouseoout event but not on click. I did unfocus for element and tooltip starts hide after modal close. but issue still present if try to multi click on rows. Tries to bind click event on all elements with tooltips failed.
