### ISSUE TITLE
reCaptcha error message

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#299]
new reCaptcha  have not code and image
![create_account](https://cloud.githubusercontent.com/assets/2631910/10995269/2c8dfd92-84ae-11e5-9869-3c687b58e5a3.jpg)

**Comment by abantecart** [comment]
I tested your site and it work OK. Please try again. Possibly 2nd key was missing at that time?

**Comment by BasaraABC** [comment]
You did not understand issue. Error message is wrong. Recaptcha have not "code in verification image"

**Comment by abantecart** [comment]
How do you cause this error to happen

**Comment by BasaraABC** [comment]
To replicate do not select "I am not a robot" checkbox and click Continue button

**Comment by abantecart** [comment]
I have updated text for the message to be generic
