### ISSUE TITLE
RL broken listing in Chrome

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#301]
To replicate bug upload new logo first
<img width="944" alt="template_manager" src="https://cloud.githubusercontent.com/assets/2631910/11027314/b010e816-86e6-11e5-94e7-5525fd684127.png">

**Comment by abantecart** [comment]
I can not replicate this. Are you still able to replicate?

**Comment by BasaraABC** [comment]
Now after new Logo upload RL broken and Firebug got error (FF, Chrome)
Note: no errors in the log
![template_manager](https://cloud.githubusercontent.com/assets/2631910/11059949/954f09ba-87cf-11e5-9933-7d1a41e1b42f.jpg)

**Comment by abantecart** [comment]
I do not get this. How do you add the logo? Can you replicate this again?

**Comment by BasaraABC** [comment]
Can not replicate on fresh install. Possibly were server issue
