### ISSUE TITLE
recaptcha in the custom forms

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#302]
![capcha](https://cloud.githubusercontent.com/assets/2631910/11028158/8b49ef7a-86ee-11e5-9554-b9d830874db3.jpg)

**Comment by abantecart** [comment]
Fixed. 
+
Improved form entry and clearing of modal for new field creation
Remember entered fields if form error.

**Comment by BasaraABC** [comment]
Initial bug fixed but problem with old capcha - image not visible. See screen
![account_login1](https://cloud.githubusercontent.com/assets/2631910/11060286/b457a342-87d1-11e5-913d-161e19e69c87.jpg)

**Comment by abantecart** [comment]
Fixed
