### ISSUE TITLE
IE Edge Windows 10: html editor cause page reload

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#309]
When working in the HTML editor in IE Edge browser after 1-2 minute page no respond or reloaded. Also cursor is moving accidentally when typing to start of line or doc. 
To replicate issue create few lists, change colors and font sizes
Note: default windows 10 installation, no plugins, no special software, no windows updates installed.

![bug2](https://cloud.githubusercontent.com/assets/2631910/11056645/d8f362aa-877b-11e5-9760-13d70363f106.jpg)

**Comment by abantecart** [comment]
Probably we need to upgrade JS library we use. Need to wait for update from them. Low priority for IE. Pushed to 1.2.6

**Comment by abolabo** [comment]
IE Edge is still in development...

**Comment by BasaraABC** [comment]
No, it is included in windows 10 release https://www.microsoft.com/en-us/windows/microsoft-edge

**Comment by abolabo** [comment]
yes. it is in MS style( :-) ), i mean include into release not fully functional browser. They writes full functional browser will be Edge v.13

**Comment by BasaraABC** [comment]
closed due Editor replacement
