### ISSUE TITLE
IE Edge: Drag-n-Drop 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#310]
<img width="1190" alt="bug3" src="https://cloud.githubusercontent.com/assets/2631910/11057158/bb7e62ce-8780-11e5-9310-67275172310d.png">

**Comment by abantecart** [comment]
We will look into this one, only if we have time left.

**Comment by abantecart** [comment]
Probably we need to upgrade JS library we use for drag. Low priority for IE. Pushed to 1.2.6

**Comment by abolabo** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/8964523-support-html5-drag-and-drop-of-files-from-explorer

**Comment by abantecart** [comment]
Was Edge finally released?

**Comment by BasaraABC** [comment]
According to wiki Stable Edge v.25 released in Windows 10 November 12, 2015 but looks like drag-n-drop is not well supported for now https://dev.windows.com/en-us/microsoft-edge/platform/status/draganddropdirectories?filter=f3f0000bf&search=drag (current status In Development)

**Comment by BasaraABC** [comment]
Issue related to browser.
