### ISSUE TITLE
DEV issue: HTML editor - RL button not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#311]
![2015-11-10_15-19-37](https://cloud.githubusercontent.com/assets/2631910/11057588/f2f05c56-87be-11e5-8365-1d069a6507f3.jpg)

**Comment by abolabo** [comment]
problem is in memory_limit size. 64mb is not enough for image resizing.

**Comment by BasaraABC** [comment]
What image? RL even didnot start

**Comment by abolabo** [comment]
trust me:) it's a memory overflow

**Comment by abolabo** [comment]
added error message for error ajax call

**Comment by BasaraABC** [comment]
In fresh cart install RL work but if upload new image it is not visible in the HTML mode.
Note: I see uploaded image in the source mode like `<img src="resources/image/18/79/d.png">`
![editor](https://cloud.githubusercontent.com/assets/2631910/11085095/182d59f4-8875-11e5-9f5e-7c853d2aee45.jpg)

**Comment by abantecart** [comment]
Fixed.
