### ISSUE TITLE
Click Install not work for some extensions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#313]
Some extension can not be installed via click install see screenshot.
Note: I replicate issue twice but with same extension pricecheck feed. Important - if download extension it is installed via extension upload without issues.
![extesnions-bug1](https://cloud.githubusercontent.com/assets/2631910/11114628/a16e2142-8958-11e5-903f-8fc66c1a9bd2.jpg)

**Comment by abolabo** [comment]
pricecheckfeed is broken package
