### ISSUE TITLE
old default template settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#318]
After update to new default htm5 template we have few settings which one have no sense and does not work.
These not working settings disappoint users
<img width="535" alt="12_4m_-_template_manager" src="https://cloud.githubusercontent.com/assets/2631910/11293011/0d32a81e-8f88-11e5-8beb-9afe0c77c8ec.png">

http://forum.abantecart.com/index.php?topic=4219.msg18381#msg18381
http://forum.abantecart.com/index.php/topic,4114.msg17798.html#msg17798

**Comment by abolabo** [comment]
fixed by css. all settings needed

**Comment by BasaraABC** [comment]
**Large Window Preview Width/Height** setting not work. Where did you use it

**Comment by abolabo** [comment]
it's a probably deprecated settings. We used it for preview images inside popup-window, but now we use zoom-lens js-script for preview. Probably some old or custom templates need it.
i think we can remove it.

**Comment by abantecart** [comment]
Please double check that we do not use it. If 100% sure, remove it.

**Comment by abantecart** [comment]
I suggest that we keep all the settings as they might be used in the custom templates.

**Comment by abantecart** [comment]
I can see config_image_popup_width and config_image_popup_height used in products.

Let's keep it open for future clean up.

**Comment by BasaraABC** [comment]
related to zoom
