### ISSUE TITLE
resource url import 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#319]
Problem with pdf files save.
Please note double // in the save path
<img width="821" alt="urls1" src="https://cloud.githubusercontent.com/assets/2631910/11335221/2dc502c0-920d-11e5-978a-535b7d86200d.png">

**Comment by abantecart** [comment]
Check permission on resources directory.

**Comment by BasaraABC** [comment]
resources directory have 777 permission

**Comment by abantecart** [comment]
Please attach Excel document for test.

**Comment by BasaraABC** [comment]
Problem found. The /resources/pdf_document/ directory is not exist and import can not create it (resources folder 777). If folder created manually then import works. Please add this folder when cart installed to avoid beginners mistakes

**Comment by abantecart** [comment]
Fixed
