### ISSUE TITLE
Language definitions comma and javascripts

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#320]
in 1.2.5 the known problem with upper ' symbol in translation still cause problems see screen.
![comma](https://cloud.githubusercontent.com/assets/2631910/11338156/03f69dd8-9225-11e5-87fd-ea0cd24e00d1.jpg)

**Comment by abolabo** [comment]
cannot to replicate in 1.2.6

**Comment by abantecart** [comment]
Are you sure you used single quote?

**Comment by BasaraABC** [comment]
I try this symbols  **λ   '' \r\nMedia's z'n "eye", össe ô \u2028 '"': '\\"'**
works fine in the grid but broke in other places see screenshot
<img width="969" alt="2016-02-01_20-35-12" src="https://cloud.githubusercontent.com/assets/2631910/12718817/8f3492bc-c923-11e5-9790-c2a5f29f8cb7.png">
