### ISSUE TITLE
rare Import issue "Data is empty or corrupted"

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#321]
Please check the fix and apply to 1.2.6 if it is Ok.
http://forum.abantecart.com/index.php/topic,4072.msg18477.html#msg18477

**Comment by abolabo** [comment]
added correct error message for zero-byte uploaded file

**Comment by BasaraABC** [comment]
Please respond on initial request (user found solution "add type of 'application/csv'" check it please)

**Comment by abolabo** [comment]
added "accept" attribute with file extension as value.
