### ISSUE TITLE
Encryption extension minor ui issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#322]
<img width="1007" alt="link" src="https://cloud.githubusercontent.com/assets/2631910/11416715/f8bc50be-9442-11e5-9fb1-5a0d75ca2322.png">

**Comment by abolabo** [comment]
cannot to replicate on 1.2.6

**Comment by BasaraABC** [comment]
To replicate bug click on Additional settings Tab and then try again. Bug visible when Tab is active

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
After fix when you click on active tab - the broken page loaded see screen
<img width="1027" alt="2016-02-03_16-43-59" src="https://cloud.githubusercontent.com/assets/2631910/12778552/d589be22-ca95-11e5-9d93-50a0036e6f2c.png">

**Comment by abolabo** [comment]
fixed
