### ISSUE TITLE
wrong block title

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#324]
To replicate issue enable Cart block on the product page.
<img width="1118" alt="block-name-bug" src="https://cloud.githubusercontent.com/assets/2631910/12087516/44cc7150-b306-11e5-9eb5-d32f50070556.png">

http://forum.abantecart.com/index.php/topic,4344.0/topicseen.html

**Comment by abolabo** [comment]
needs more details... tried to replicate on fresh install

**Comment by abantecart** [comment]
I have seen this problem. Heading is shown incorrectly. We need to find way to replicate this. 
Try to install additional template, I think that cause the issue.

**Comment by abantecart** [comment]
This is language scope staking issue. Sequence is incorrect.

**Comment by BasaraABC** [comment]
Cannot replicate too in 1.2.6
Installed stylish and can not replicate for both templates
