### ISSUE TITLE
When create new text banner. Group name is saved as 0

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#325]
Visible on clean install if not select Add new group name
<img width="843" alt="banner0" src="https://cloud.githubusercontent.com/assets/2631910/12232507/b1b33e62-b891-11e5-8f60-4e9c4dfa63d5.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue reopened due to new bug. Adding new group old approach is broken see screenshot
<img width="896" alt="2016-02-01_15-03-11" src="https://cloud.githubusercontent.com/assets/2631910/12711822/851a5bb4-c8f5-11e5-9745-5bd798d9ed49.png">

**Comment by abolabo** [comment]
fixed
