### ISSUE TITLE
admin global search improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#331]
Issue A: if copy paste text to search it doesnot search see screen
<img width="338" alt="issuea" src="https://cloud.githubusercontent.com/assets/2631910/12636072/3ad1da50-c5bc-11e5-8e38-66d6f13127c0.png">

Issue B: global search can not find setting by its name (only language definition found) see screen
<img width="353" alt="issueb" src="https://cloud.githubusercontent.com/assets/2631910/12636080/51e12ec6-c5bc-11e5-86d7-0d6a298032cd.png">

**Comment by abantecart** [comment]
I get same result in both cases. What browser is this?

**Comment by abolabo** [comment]
fixed
