### ISSUE TITLE
Product Image Thumb Width setting doubled on SF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#335]
For unknown reason image is doubled size on SF.
Note: Hi-res images were enabled, then disabled and cache cleared but image size still doubled see screenshot
<img width="988" alt="2016-02-02_17-08-14" src="https://cloud.githubusercontent.com/assets/2631910/12746192/f8a66e4e-c9cf-11e5-80a2-840c0835589a.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Fix not work (when Hires Images is On) and more issues. Logo is broken too.
<img width="1051" alt="benefit_girl_meets_pearl" src="https://cloud.githubusercontent.com/assets/2631910/12774567/c07124c0-ca78-11e5-8f58-3456bba59513.png">

**Comment by abantecart** [comment]
Dima. I do not remember how to enable HR images. Please check.

**Comment by abantecart** [comment]
This can be related to zoom using actual size with 2x

**Comment by BasaraABC** [comment]
Issue cover not only zoom images. As you can see on last screenshot Logo is giant too. To enabled HR images you need enable .htaccess and set ON hr images in system settings

**Comment by BasaraABC** [comment]
Update: in latest install issue visible for main product image only

**Comment by abolabo** [comment]
fixed. logo issue fixed by other commit
