### ISSUE TITLE
not all transactions visible in Customer Transactions report

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#336]
Admin > Reports > Transaction doesnot show correct info
<img width="917" alt="2016-02-02_19-16-39" src="https://cloud.githubusercontent.com/assets/2631910/12749316/64e7f976-c9e2-11e5-84f2-d439b5965d5f.png">

**Comment by abolabo** [comment]
please post more details. cannot to replicate (checked on your abc126_m02d02 too)

**Comment by BasaraABC** [comment]
Hello. Very easy to replicate. Compare transactions list 
in the **Transaction report** http://dev06.*******/abc126_m02d02/index.php?rt=report/customer/transactions&s=your_admin
and in the **Customer's Transaction** list http://dev06.*****/abc126_m02d02/index.php?rt=sale/customer_transaction&customer_id=14&s=your_admin
they are differen

**Comment by abantecart** [comment]
This is important to be fixed

**Comment by abolabo** [comment]
fixed
