### ISSUE TITLE
Customers Online report

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#337]
Customers Online report show incorrect information.
Did not show all guest users, only shown one. Tested from few devices with different IPs and internet provider. All the time showed one online user even when 3 guest users access site
<img width="917" alt="customers_online" src="https://cloud.githubusercontent.com/assets/2631910/12750109/8cfa6c32-c9e7-11e5-98a2-d9535f0a1c58.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Small problem in pagination
<img width="882" alt="customers_online" src="https://cloud.githubusercontent.com/assets/2631910/12807551/4a5bed0e-cb42-11e5-8716-180f9896e803.png">

**Comment by BasaraABC** [comment]
Few more issues.
issue A: missed per page values
<img width="883" alt="customers_online3" src="https://cloud.githubusercontent.com/assets/2631910/12807663/636a96fa-cb43-11e5-9e68-7b29358c3791.png">

issue B: broken sort by Name
<img width="483" alt="customers_online2" src="https://cloud.githubusercontent.com/assets/2631910/12807664/63cd8ecc-cb43-11e5-80a8-e884e5fb0332.png">

**Comment by abolabo** [comment]
1. fixed.
2. limits for paginations shows automatically. it's depend on total rows count.
3. There is no sorting now.
