### ISSUE TITLE
dev: logo in email

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#338]
Not sure is this bug or new approach but in dev1.2.6 missed store logo in all emails. Please confirm.
<img width="626" alt="emails" src="https://cloud.githubusercontent.com/assets/2631910/12774268/c0869c5e-ca75-11e5-832e-2546370c405a.png">

**Comment by abantecart** [comment]
This is an issue. Good catch.

**Comment by abantecart** [comment]
Should be image.

**Comment by abantecart** [comment]
Fixed.
