### ISSUE TITLE
Setup Wizard, RL and scroll problem

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#339]
<img width="917" alt="2016-02-03_13-00-32" src="https://cloud.githubusercontent.com/assets/2631910/12774412/3bd5f46c-ca77-11e5-8c0a-7fd0ee6d5c9e.png">
When you scroll only background site scrolled but Wizard Window is not scrollable.

**Comment by abantecart** [comment]
Problem is related to 2 modals. 
I think we spend to much time on Editor in wizard. I suggest to remove HTML editor from wizard and leave basic texture

**Comment by BasaraABC** [comment]
Agree.

**Comment by abantecart** [comment]
Dima please relace ANY editor with regular textarea as I originaly suggested

**Comment by abolabo** [comment]
done
