### ISSUE TITLE
dev issue: editor,newlines and mails

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#344]
New lines are no visible in received email. 
<img width="681" alt="2016-02-05_17-21-53" src="https://cloud.githubusercontent.com/assets/2631910/12843659/63369676-cc2d-11e5-8a9c-1b5c490080fd.png">

**Comment by abolabo** [comment]
fixed. 
NOTE: if message contains html-tags newlines will not applied. new line converter works only for plain text.
