### ISSUE TITLE
Send Mail suggestion

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#345]
Suggestion to move "To customers ordered" to the all "To" dropdown and display products lookup field only when appropriate option selected.
<img width="1557" alt="2016-02-05_17-39-05" src="https://cloud.githubusercontent.com/assets/2631910/12844082/dba133ee-cc2f-11e5-9a2a-cd5818886fca.png">

**Comment by abolabo** [comment]
done
