### ISSUE TITLE
"Approval message" shown when approval is OFF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#347]
<img width="977" alt="2016-02-05_18-18-12" src="https://cloud.githubusercontent.com/assets/2631910/12845004/768afac0-cc35-11e5-9a13-47c1d4f18cfc.png">

**Comment by abantecart** [comment]
This is working correctly. If you do not want to Auto approve customers, you will get notification. 
We need to change the text. 
Try to turn this ON. Do you get notification?

**Comment by BasaraABC** [comment]
Hello. It is not working correctly. No matter is settings OFF or ON admin receive "Action of approval is required!" message in case of _**Newsletter**_ account registered

**Comment by abantecart** [comment]
Now newsletter will be on the same rule as customer approval. Approval is not forced off as before.

**Comment by abantecart** [comment]
Fixed
