### ISSUE TITLE
Parcelfore 48 - not worked features

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#35]
Display Delivery Weight, Display Insurance and Display Delivery Time not work.
![11272014_54713 pm](https://cloud.githubusercontent.com/assets/2631910/5215801/a6011746-765d-11e4-93bf-bc9da53ca959.png)

**Comment by abolabo** [comment]
https://github.com/abantecart/abantecart-src/commit/61e8f0bffc3f30c109b61e0b1b88be30eeabf50d
