### ISSUE TITLE
dev issue: Visual editor misplaced in Categories

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#352]
<img width="948" alt="2016-02-08_17-02-53" src="https://cloud.githubusercontent.com/assets/2631910/12882730/2452e54e-ce86-11e5-827d-4ae668ba6545.png">

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
Issue appear on category page load (fresh install)
<img width="883" alt="categories" src="https://cloud.githubusercontent.com/assets/2631910/13107006/f4013afc-d59d-11e5-99ba-9d108321a2b0.png">

**Comment by abantecart** [comment]
Fixed
