### ISSUE TITLE
dev issue: new editor and extremly large html crush Chrome

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#353]
Not a bug because html extremly large but FYI if in Chrome 48 insert attached html code several times to the Text editor mode then page crushed
[facebook.html.zip](https://github.com/abantecart/abantecart-src/files/121467/facebook.html.zip)
<img width="715" alt="2016-02-08_17-53-35" src="https://cloud.githubusercontent.com/assets/2631910/12884124/c2a6f336-ce8e-11e5-9b43-77d699f3ebe6.png">

**Comment by abolabo** [comment]
i have no problem under chromium under linux.. you can make bug report on their bug tracker. it's not abc-problem.

**Comment by abantecart** [comment]
Boris, what will happen if you put same code into WP?

**Comment by BasaraABC** [comment]
In new install I can not replicate this in AbanteCart or WP. So not a problem.
