### ISSUE TITLE
dev issue: new visual editor insert link

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#355]
Missed target types. Please add all types See http://www.w3schools.com/tags/att_a_target.asp
<img width="593" alt="categories" src="https://cloud.githubusercontent.com/assets/2631910/12884586/d19ed66c-ce91-11e5-993f-4ba248f3067e.png">

**Comment by abolabo** [comment]
no. we have no any frame. Only _blank and _self.
