### ISSUE TITLE
dev issue: Visual editor did not support <code> tag

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#356]
Visual editor broke code:  new lines added and more `<code>` added

<img width="649" alt="2016-02-08_18-36-12" src="https://cloud.githubusercontent.com/assets/2631910/12884819/6b488410-ce93-11e5-9b7c-9e1a869d6e1f.png">

**Comment by abantecart** [comment]
You are not putting code correctly. Need you use <xmp> code </xmp> to show code in the browser.
Anything else will be a problem and will conflict with html code. 

http://stackoverflow.com/questions/2820453/display-html-code-in-html
