### ISSUE TITLE
dev issue:  editor looks broken if start Wizard from settings page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#357]
<img width="964" alt="settings" src="https://cloud.githubusercontent.com/assets/2631910/12886828/b30f27c2-cea2-11e5-811b-81fe9412e343.png">

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
Issue visible in VISUAL Editor mode in fresh install (Firefox and Chrome browsers)

**Comment by abantecart** [comment]
Fixed. 

Another bug is still present. 
If text editor is present in the main page (general settings) and open wizard with one more editor, visual part does not open.

**Comment by abantecart** [comment]
I think this was fixed.
