### ISSUE TITLE
dev issue: when adding new resource to library

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#358]
when adding new resource to library 2 loading circles shown
<img width="1176" alt="2016-02-09_17-01-55" src="https://cloud.githubusercontent.com/assets/2631910/12913055/08167a3e-cf4f-11e5-98ac-4c7720acdce1.png">

**Comment by abantecart** [comment]
Can not replicate. Possibly cache issue.

**Comment by BasaraABC** [comment]
Issue is still visible in fesh install in different browsers. Possibly visible on slower ISP
![img_11022016_145510](https://cloud.githubusercontent.com/assets/2631910/12971629/de0747b4-d0cf-11e5-9e1d-9a5d975cef3a.png)

**Comment by abantecart** [comment]
I can not get the same result. Please grab the file name of a blue image and CSS used. Use FF inspector

**Comment by abantecart** [comment]
Need element that you see.

**Comment by BasaraABC** [comment]
Can not replicate now. Tried all browsers and 2 PC
