### ISSUE TITLE
Liqpay not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#36]
1. no way to pay with Liqpay. After confirm order xml shown see screenshot.
![11272014_90139 pm](https://cloud.githubusercontent.com/assets/2631910/5217867/cb0f9a56-7678-11e4-958f-06d3425137bd.png)

2. If you have time please add support for test mode. In Liqpay doc this mentioned see
![11272014_90403 pm](https://cloud.githubusercontent.com/assets/2631910/5217890/fe949a98-7678-11e4-94df-ad9678ebd39e.png)

**Comment by abolabo** [comment]
temporary removed from distributive

**Comment by BasaraABC** [comment]
issues reopened - we need to resolve it later. Do not close issue
