### ISSUE TITLE
Admin product edit page ignore sort order

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#367]
<img width="897" alt="2016-02-10_14-28-42" src="https://cloud.githubusercontent.com/assets/2631910/12941227/ed56c1b8-d002-11e5-8aa5-5b67156b6251.png">

**Comment by abantecart** [comment]
Please retest

**Comment by BasaraABC** [comment]
Issue not fixed and visible in fresh install

**Comment by abantecart** [comment]
Fixed.
