### ISSUE TITLE
admin product images not show all resources

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#368]
![2016-02-10_15-14-23](https://cloud.githubusercontent.com/assets/2631910/12941962/eda8ad46-d009-11e5-8924-baf80205b83b.png)

**Comment by abantecart** [comment]
There is a limit of 12 set. We cannot have ajax ran without limits. 
Probably we should have pagination here, but it is duplicated as we have it in opening window. 
I will add text to clarify
