### ISSUE TITLE
missed 'archive' file type

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#37]
When add new media to the product in 1.2.0.b missed archive file type
![bug1](https://cloud.githubusercontent.com/assets/2631910/5224742/c9b37b12-770b-11e4-9de0-652c0da5bb1a.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/3e7384fefe812b074eb694f13d921b184754d4c8
