### ISSUE TITLE
Coupon report double all values

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#370]
Every time you apply coupon to the ONE order in reports it shown as TWO orders 
<img width="951" alt="discounts_report" src="https://cloud.githubusercontent.com/assets/2631910/12946045/25494e58-d024-11e5-9f4e-65ba518ae1bb.png">

**Comment by abolabo** [comment]
fixed. 
P.S. Please provide active languages count for that cases (when something doubling)
