### ISSUE TITLE
dev issue: RL manager horizontal scrollbar

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#373]
![img_11022016_144407](https://cloud.githubusercontent.com/assets/2631910/12971486/3b38dd8c-d0ce-11e5-99a2-98584efc64af.png)

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
Scroll bar visible in IE11 on mouseover see screenshot. In Chrome visible too.
![img_17022016_201518](https://cloud.githubusercontent.com/assets/2631910/13110557/60b76b16-d5b3-11e5-9b0d-08c426ec3cdc.png)

**Comment by abantecart** [comment]
I think, this is duplicate
