### ISSUE TITLE
dev issue: RL window scrollbars

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#375]
Check in Windows 7 (IE, Chrome).
![img_11022016_145945](https://cloud.githubusercontent.com/assets/2631910/12971680/5a4afb5e-d0d0-11e5-885f-19d51dcf25ad.png)

**Comment by abantecart** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue not fixed in visible in all borwser
![img_17022016_132138](https://cloud.githubusercontent.com/assets/2631910/13101770/9280db74-d57b-11e5-9604-a940f0669e89.png)

**Comment by abantecart** [comment]
Try now.

**Comment by BasaraABC** [comment]
fixed
