### ISSUE TITLE
dev issue: RL manager ui issue - no way to search non-image resources

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#378]
Products Media
![51d0771c75ff443a9122f0d2a3360167](https://cloud.githubusercontent.com/assets/2631910/12973837/1f1f1c74-d0e2-11e5-9f7d-d628b6dfee49.png)

**Comment by abantecart** [comment]
I think this works correctly. RL list window operated in the RL type selected. 
If you need to add new RL type, you use right side selector, if you need to list other types you can open new window from right place or again  click on the tabs on the right.

This is more clear and will not confuse users.
