### ISSUE TITLE
dev issue: RL manager change folder issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#381]
When folder name changed in Media Library - it is not updated in other sections (Catalog > Downloads)
<img width="747" alt="2016-02-11_18-40-12" src="https://cloud.githubusercontent.com/assets/2631910/12975552/41a01afc-d0ef-11e5-8198-3a698e85c77b.png">

**Comment by abantecart** [comment]
Probably we need to disabled editing for directory name. Updating all resource paths in downloads might cause instability. Not sure.

**Comment by BasaraABC** [comment]
actually URL is work with new folder but link text is not updated. So maybe show link text like:
variant 1: **/18/7a/8.pdf**
variant 2: **resources/[downloads_folder]/18/7a/8.pdf**

**Comment by abantecart** [comment]
We can not yet allow dir of resource directory

**Comment by abantecart** [comment]
Downloads save path into the table and update will be required.
