### ISSUE TITLE
Catalog > Downloads

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#382]
When change file in the download the save message have issues:
issue A: misplaced
issue B: incorrect text
<img width="628" alt="screen_shot_2016-02-11_at_18_47_02" src="https://cloud.githubusercontent.com/assets/2631910/12975791/51dd145e-d0f1-11e5-8316-2fee75631762.png">

**Comment by abantecart** [comment]
Tried all possible ways. I do not get this. Please help to replicate this.

**Comment by BasaraABC** [comment]
1. go to Catalog > Downloads and create new without file. Save
2. Click to edit new download and select any file from RL. Click SAVE button. 
I see issue in latest firefox.

**Comment by abantecart** [comment]
I still can not replicate this issue. Tried same steps.

**Comment by abantecart** [comment]
Close?
