### ISSUE TITLE
dev improve: RL common Media Library issue language selector

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#383]
Note: issue visible only in the common Media Library. (selector works fine on product RL level)
<img width="1128" alt="2016-02-12_16-05-03" src="https://cloud.githubusercontent.com/assets/2631910/13002675/e3b3722c-d1a2-11e5-9335-fa526f0db7a2.png">

**Comment by abantecart** [comment]
Fixed. Now language switcher in admin needs to be tested in content sections.
