### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#386]
Issues found
1.  in RTL Left column should be shown on the Right (valid for SF and Admin)
2. Products in the Listings and products in the Related Tab on product page should align to the right and be displayed **in order from Right to Left** (issue visible if you have 3 products in listing - they aligned to left and displayed in order from Left to right)
3. Footer and Header ignore RTL (example: in LTR logo on the left so in RTL logo should be on the right)
4. Product **box's content** in the listing  - ADD TO CART should be on the left and price on the right
5. SF content page - CONTINUE button ignore RTL
6. SF testimonials block doesnot show anything
7. SF Login page - input fields are misplaced and should be in left block (register user and login boxes should be vise versa)
8. SF categories dropdown menu is algined incorrectly so dropdown for few first categories not visible
<img width="429"  alt="screen shot 2016-02-16 at 17 37 49" src="https://cloud.githubusercontent.com/assets/2631910/13073948/19c23ae0-d4d4-11e5-89a0-73dce2036209.png">
9. SF categories menu. Incorrect display order - categories in RTL shold be displayed from Right to left
10.  Admin ignore RTL. Looks buggy - a lot of misplacements and sections where RTL ingored (for example Right panel with Orders/New Customers)

_suggestion for developer: try to see how it work in popular CMS like WP install this plugin https://wordpress.org/plugins/rtl-tester/_

**Comment by abantecart** [comment]
Since we do not have any RTL language in core, I think it makes sense to postpone this till we have one RTL core language. 
This can be also addressed if we create new core template in the future.
