### ISSUE TITLE
Shipping cart page ZIP field minor issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#389]
If add block to right column the ZIP field is too short
<img width="1225" alt="shopping_cart" src="https://cloud.githubusercontent.com/assets/2631910/13107857/642b8a22-d5a2-11e5-9427-b36120efd689.png">

**Comment by abantecart** [comment]
Fixed this issue, but keep this open. 
We need to create separate layout for cart page and remove order summery from it.

**Comment by BasaraABC** [comment]
fixed
