### ISSUE TITLE
False Loading data error

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#391]
annoying and duplicated error shown.
How to replicate:
1. Open RL modal
2. Close it  and immediately go to any other page
3. So after you close RL modal it reload resources on the page. If you do not want to wait ( or slow internet ) and visit any other admin page this error appear multiply times. Actually log is empty so message is false
<img width="608" alt="2016-02-18_14-05-43" src="https://cloud.githubusercontent.com/assets/2631910/13136119/6e25590c-d649-11e5-849e-23ede1e15c7f.png">

**Comment by abantecart** [comment]
This is a case there all RL resource loads are terminated. Fixed
