### ISSUE TITLE
Sendmail Store selector

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#395]
Sales > Sendmail. Actually selector exist but it is not editable (user cannot select)
<img width="1016" alt="2016-02-18_15-39-25" src="https://cloud.githubusercontent.com/assets/2631910/13137851/3342b8ea-d656-11e5-82d9-b80358d311b5.png">

**Comment by abantecart** [comment]
This was done intentionally. I added store switcher, but It is missing now. Dima?

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Your fix broke something. **From** selector is missing

**Comment by abolabo** [comment]
no! see store switcher at heading now!

**Comment by BasaraABC** [comment]
Hello. I saw it. But **From:** selector was designed by Pavel. He told me before it is important. That's why I report problem
