### ISSUE TITLE
Multi-store improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#396]
1. Catalog > Downloads : selector is missing
2. Catalog > Reviews : selector is missing:FIXED
3. Catalog > Global Attributes  : selector is missing
4. Sales > Coupons : selector is missing (important)
5. Design > Menu selector is missing (same menu for all stores?)
6. Extensions > Order totals: selector is missing and if you select not default store somewhere before - then you can not save Order Total values (bug)
7. System > Localization > Languages: selector is missing (can not control available languages per store)
8. System > Localization > Currencies: selector is missing (can not control available currencies per store)
9. All Reports : selector is missing

**Comment by abolabo** [comment]
1. added for reviews.
2. Shared downloads and global attributes cannot be assists to store. It's a "patterns"
3. The same with languages and currencies
4. implementation for coupons can be complex. Coupons can be applied to some products that can be assigned to stores.

**Comment by BasaraABC** [comment]
1. Downloads - closed. possibly issue were resolved because bug opened long time ago
2. Reviews - still issue here. If in the Reviews grid select default store then all review displayed, from all stores and no matter assigned product to default store or not. Note: selector works great for non-default stores
3. Global attributes - closed. possibly issue were resolved because bug opened long time ago
4. Coupons - lets skip it. @abantecart  already improve coupons for multistore week ago

7 . and 8. - Agree. Skip this

**Comment by abolabo** [comment]
2 fixed. Related to core class issue
