### ISSUE TITLE
All grids gap if hide left colum

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#398]
![img_18022016_180611](https://cloud.githubusercontent.com/assets/2631910/13142186/0ab05c58-d66e-11e5-9219-49f63d5384ab.png)

**Comment by abantecart** [comment]
Not sure if we can manage this easy without effecting something else

**Comment by abantecart** [comment]
Fixed. This requires good testing for grid in multiple places.

**Comment by BasaraABC** [comment]
Issue is visible in case you hide left column **permanently**. So if you just turn column Off it looks fixed but if you load page with left column off issue still here

**Comment by abantecart** [comment]
Good catch. Fixed.
