### ISSUE TITLE
dev issue: demo accounts notification settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#406]
I think Order Updates via Email should be enabled by default for all accounts.
<img width="796" alt="notifications_and_newsletter" src="https://cloud.githubusercontent.com/assets/2631910/13213223/e29181f2-d979-11e5-9055-ae646787f346.png">

**Comment by abolabo** [comment]
not agree. Demo accounts have fake email addresses. It will call errors in log.
