### ISSUE TITLE
dev issue: storefront IM settings - can not save uncheck all

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#407]
Can not save SF notification settings when all options are not selected. **To replicate bug use same settings please.**
<img width="794" alt="2016-02-22_15-38-01" src="https://cloud.githubusercontent.com/assets/2631910/13213399/2063f16c-d97b-11e5-86c5-a00ff8634f03.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
I am still able to replicate issue. Please use Firefox and follow screenshots configiration

**Comment by abolabo** [comment]
fixed
