### ISSUE TITLE
dev issue: SF Newsletter section ignore Disabled Notification settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#408]
<img width="779" alt="2016-02-22_15-47-19" src="https://cloud.githubusercontent.com/assets/2631910/13213743/9970d2ee-d97d-11e5-8fc2-19034215bac6.png">

**Comment by BasaraABC** [comment]
Note: also we have Newsletter select box in the Admin > Sales > Customers > Customer edit page

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
There is still abovementioned conflict with  Admin side.
In Admin > Sales > Customers > Customer Edit page admin can enable/disable Newsletter but there is no Email/SMS options so this looks buggy for example 
<img width="789" alt="2016-02-26_17-14-21" src="https://cloud.githubusercontent.com/assets/2631910/13349483/be36f676-dcac-11e5-8074-b376075d698b.png">
Administrator should have full control of customer account

**Comment by abolabo** [comment]
was fixed earlier
