### ISSUE TITLE
dev issue: old notifications settings disappointment

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#413]
There are several notification related settings and messages are not visible in new notifications UI for admin:
1. account require approve
2. New order Alert
3. System check messages 
4. admin login failed 
5. Admin password reset requested
....etc
Lets discuss because UI is not  clear. Should we remove them and put to Admin notification settings or leave them like now and duplicate in notifications? 
<img width="1401" alt="2016-02-22_17-28-09" src="https://cloud.githubusercontent.com/assets/2631910/13215811/b48f2ece-d98a-11e5-9eb8-95a141f013ba.png">

**Comment by BasaraABC** [comment]
@abolabo

**Comment by abantecart** [comment]
Dima is working on this as we discussed. 
Please rename Order Updated to New orders and updates

**Comment by abantecart** [comment]
4 & 5 I think we need to add to new send point. Admin account updates. Is is hard?

**Comment by abolabo** [comment]
sendpoints list was changed. need to review.
