### ISSUE TITLE
dev issue: Twillio extension broke SF features

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#415]
If Twillio can not send SMS (wrong number?) the error returned to the write review at SF. (review should be written even when SMS not possible to send to administrator user ). To replicate issue please enable **Added New Product Review** notification for admin user!
<img width="1011" alt="2016-02-22_18-14-53" src="https://cloud.githubusercontent.com/assets/2631910/13216904/697860e8-d991-11e5-9d0b-95c0f513f99e.png">

**Comment by BasaraABC** [comment]
Same problem with order cancellation. If user request order cancel and admin have enabled order updates notification the critical error appear on Storefront
<img width="886" alt="screen shot 2016-02-22 at 18 32 49" src="https://cloud.githubusercontent.com/assets/2631910/13217108/b305f652-d992-11e5-8692-63108621540f.png">

**Comment by abolabo** [comment]
fixed
