### ISSUE TITLE
form data lost if one of required fileds empty

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#416]
<img width="1237" alt="2016-02-23_14-07-57" src="https://cloud.githubusercontent.com/assets/2631910/13244256/68e15c06-da37-11e5-8475-f3e4a9e20ca9.png">

**Comment by abolabo** [comment]
it works correctly! We cannot to preset extensions settings like status. It will confused user.

**Comment by BasaraABC** [comment]
You can skip Status. Main problem in other input data lost.

**Comment by abolabo** [comment]
duplicate of https://github.com/abantecart/abantecart-src/issues/340
fixed
