### ISSUE TITLE
dev issue: Sales > Send Mail > SMS error message

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#417]
Error message shown when SMS section selected. This message is not clear. Please note: twillio extension is installed/enabled and selected as default Provider in System > Settings > IM
What exactly missed  if _nothing were selected yet_? 
<img width="761" alt="send_sms" src="https://cloud.githubusercontent.com/assets/2631910/13244359/2fd6bac2-da38-11e5-93e6-3e54e4b89ebb.png">

**Comment by abolabo** [comment]
Database does not contain ANY mobile phone numbers. Who recipient in that case?

**Comment by BasaraABC** [comment]
The error shown on SMS page load. Why it check for recipient (receiver) phone if Administrator did not start to choose any recipients? This error should appear only after Administrator select some Customers and they have not any phones.

**Comment by abolabo** [comment]
This check runs over ALL customers. Sending sms to nobody have not sense.

**Comment by BasaraABC** [comment]
No, In test database I register new customer with phone number and if you check Demo Data you will see phone numbers are available too.

**Comment by abolabo** [comment]
no. you talking about phone, but customer data have field "MOBILE phone". it's not the same.

**Comment by BasaraABC** [comment]
well, that's I am talking about. Message is not clear. For beginners "recipient data" is not clear in compare with human language "your customers have not Mobile phone data"
Kindly ask you to made this error message readable for beginners.

**Comment by abolabo** [comment]
changed
