### ISSUE TITLE
dev issue: IM storefront UI problems

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#418]
<img width="1337" alt="2016-02-23_14-45-34" src="https://cloud.githubusercontent.com/assets/2631910/13245045/e710a992-da3c-11e5-9642-3f7522b492a8.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
**Issue A** is not fixed.

**Comment by abolabo** [comment]
fixed. related to https://github.com/abantecart/abantecart-src/issues/449
Pavel, please add correct text in xml
