### ISSUE TITLE
dev issue: email notification for customers not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#419]
Email Notifications for all Sendpoints not work. 
Test case: only email notifications ON
<img width="764" alt="2016-02-23_15-20-40" src="https://cloud.githubusercontent.com/assets/2631910/13246007/892bf4d8-da43-11e5-82b4-00b0453ee845.png">

when order status changed in admin grid - no notification for customer
when admin add more products/recalculate order in admin -  no notification for customer
when admin change customer name and group in admin - no notification for customer
when admin add new transaction to the customer balance - - no notification for customer
when customer change password at SF - no notification for customer (if change other data it work)

> 
QA stopped because looks like something is broken

P.S.
Mail is work (email received when order created) and spam folder is empty

**Comment by abolabo** [comment]
No it works. i got email notification in spam-folder.(on abc domain)

**Comment by BasaraABC** [comment]
Hello. I double check on fresh install. My spam folder is empty. Also note that I receive notification in case of account name changed by customer, But in other case NO Notification received.
Let me explain more detailed.
**Order Updates Notification** - if enabled customer should receive notification when order is changed. For example: admin modify it (change products/recalculate tax/...or any), admin change order status, admin add new transaction 
**Account Updates** - if enabled customer should receive notification when his account changed. For example - password change (important for security reasons), new address added or address modified, when administrator change customer's balance (debit/credit), when account was completely disabled....etc
**Newsletters** - this section looks buggy and not completed. My test user have disabled Newsletter Notification but I am still receive it (send from Sales > Send Mail) maybe because it was enabled before? Also when administrator edit user account he have not control for the Email/SMS notifications (only Newsletter Enabled or Disabled)

Also in my opinion notifications should be detailed. What were changed and what time.  

_Summary: if new notification system not work in this way it is useless. We can discuss this with all team members if you are not agree._
