### ISSUE TITLE
USPS currency in Estimate block

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#42]
Issue originally reported here <a href="http://forum.abantecart.com/index.php/topic,2909.msg12342.html#msg12342"> http://forum.abantecart.com/index.php/topic,2909.msg12342.html#msg12342</a>
Estimate block show incorrect shipping cost in Euro see screenshot
![1212014_54136 pm](https://cloud.githubusercontent.com/assets/2631910/5244393/9bbe0fc4-7981-11e4-994e-f8efec94aa8d.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/375cc722e4021d079cda8c60f5b6be6606e03998
