### ISSUE TITLE
suggestion: user registration

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#420]
Since new version will be with SMS it is strongly important to explain new customer:
1. Mobile phone can be used for SMS
2. Explain correct phone format to avoid problems  (with + or not; with country code; skip zero problem; spaces and other characters like " - () ")
3. If possible add regex to this field (?)
<img width="621" alt="create_account" src="https://cloud.githubusercontent.com/assets/2631910/13248535/71dffc76-da51-11e5-97c2-18537e2c0d26.png">

**Comment by BasaraABC** [comment]
In fresh cart install this filed missed. Please add it to user registration form
<img width="653" alt="create_account" src="https://cloud.githubusercontent.com/assets/2631910/13277367/fd4efd8a-dafa-11e5-9ebd-d4e3309adf3d.png">

**Comment by abolabo** [comment]
you had set twilio as sms-provider but disable it. What field in form do you expect?:)

**Comment by abantecart** [comment]
Dima: What about regex for validation? 

Please add standard comment at the top of extension setting (Note). Not at the help popup.
**Note: This extension will enable Mobile Phone field for the customers to provide. Remember that disabling of this extension will hide this field. 
If added to existing store with customers, keep in mind that this information will be missing.**


Boris, please add this to the Docs later.

**Comment by abolabo** [comment]
regaring regex. you cannot to enter something except numbers. There jquery.mobileNumber.js script processing input. 
Note added.
