### ISSUE TITLE
Edit Shared Download popup loaded very slow

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#426]
When popup opened about 9sec to full load see firebug report
<img width="950" alt="shared_downloads" src="https://cloud.githubusercontent.com/assets/2631910/13278950/e3a9523e-db06-11e5-981b-5e5f5eb6abdf.png">

**Comment by abolabo** [comment]
cannot replicate it. probably cause is in firebug

**Comment by abantecart** [comment]
I am sure you can if you try some variations. I bet this is a SLOW Sql.

**Comment by abantecart** [comment]
Please do not close this until it is resolved.

**Comment by abantecart** [comment]
I think this is your network issue. Requests are to external query. 
I will close this issue.
Boris, please monitor this in the future and provide bigger screenshot or text with full requests and times
