### ISSUE TITLE
dev issue: new review notification for admin improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#428]
<img width="829" alt="invox" src="https://cloud.githubusercontent.com/assets/2631910/13280508/1b0b5c72-db11-11e5-9cc3-57d3d97de443.png">

**Comment by abolabo** [comment]
it's an abstract subject. One for all. Details are inside message. 
Product name no needed there. Also url was fixed earlier and now you must get correct url on product page.
