### ISSUE TITLE
dev issue: Send Mail task popup

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#429]
<img width="802" alt="2016-02-24_16-48-20" src="https://cloud.githubusercontent.com/assets/2631910/13281490/b5e4b978-db16-11e5-8ddd-3aba17d49e08.png">

**Comment by abolabo** [comment]
no. it will interrupt task in process!

**Comment by abantecart** [comment]
Please correct the text. 
**Task was completed**
**Messages have been sent!**

**Comment by abolabo** [comment]
fixed
