### ISSUE TITLE
dev issue: incomplete tasks problem

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#430]
After new task run successfully the old Incompleted task changed. Also another problem Incompleted **Tasks** show only one **task**, so it should be renamed to latest one incompleted task or show all somehow
<img width="1048" alt="2016-02-24_18-14-36" src="https://cloud.githubusercontent.com/assets/2631910/13283897/37d7a844-db23-11e5-99d9-98c03cca127a.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue reopened. It is valid in new cart install
<img width="809" alt="2016-03-02_16-16-18" src="https://cloud.githubusercontent.com/assets/2631910/13455856/902e6888-e092-11e5-8f7b-6670c02fa556.png">

**Comment by abolabo** [comment]
fixed
