### ISSUE TITLE
dev issue: Sales > Send Mail > SMS UI problem

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#431]
Send SMS UI have issues
<img width="1103" alt="2016-02-24_20-26-20" src="https://cloud.githubusercontent.com/assets/2631910/13286775/0ef6d586-db36-11e5-9911-11ebdf4a9cd3.png">

**Comment by abolabo** [comment]
"sender" is not requred field for different sms-drivers. For twilio use mobile phone number (or few numbers) that was set inside twilio account on them site. This ui "problem" cannot be resolved.

**Comment by BasaraABC** [comment]
In this case:
1. rename Subject to "Sender"
2. made it not required
3. add help note and mention that it is visible only for some providers only

**Comment by abolabo** [comment]
issue A. i wrote above.  I cannot to determine which sender of sms will been used! In some cases it's stores on third-party side.
issue B - subject field removed for sms-form.
