### ISSUE TITLE
Backup path problem in popup

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#435]
Issue visible when you create backup without compression
<img width="944" alt="backup___restore___load" src="https://cloud.githubusercontent.com/assets/2631910/13311407/f6eeb892-dbc0-11e5-9282-a008f30a5a5c.png">

**Comment by abolabo** [comment]
tried do the same on dev-server with different screen sizes. cannot to replicate. keep this issue open

**Comment by BasaraABC** [comment]
try Chrome browser

**Comment by abolabo** [comment]
fixed
