### ISSUE TITLE
Data > Backup > XML load button hint shedule task

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#436]
<img width="815" alt="2016-02-25_13-27-14" src="https://cloud.githubusercontent.com/assets/2631910/13311762/c367cf1a-dbc3-11e5-9dd9-33a1feaf0463.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue not fixed. I get same result on fresh install.

**Comment by abolabo** [comment]
fixed
