### ISSUE TITLE
Mobile field and Guest Orders

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#438]
We collect mobile phone for guest checkout but it is not visible in the admin. Also why Fax in admin visible on the shipping address tab (it is common user data not shipping related)?
<img width="1505" alt="2016-02-25_14-07-04" src="https://cloud.githubusercontent.com/assets/2631910/13312498/b286bca0-dbc9-11e5-8d31-3f38113521fe.png">

**Comment by abolabo** [comment]
fixed
