### ISSUE TITLE
Embed my account page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#442]
<img width="923" alt="new_blog__pruduct_embed_126" src="https://cloud.githubusercontent.com/assets/2631910/13317665/dfc26466-dbe8-11e5-96f6-4e9d37e8f690.png">

**Comment by abolabo** [comment]
postponed

**Comment by abantecart** [comment]
Why? I can look at GUI/HTML issues.

**Comment by abantecart** [comment]
Fixed.
