### ISSUE TITLE
dev issue: IM Admin status OFF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#447]
Not sure is this issue or not but when IM for Admin is OFF it is still present in following sections:
1. Admin user able to add/edit Mobile number
2. Sales > Send Mail have Send SMS section
What exactly this status disable?
<img width="901" alt="2016-02-26_17-42-34" src="https://cloud.githubusercontent.com/assets/2631910/13350106/83b03888-dcb0-11e5-8ac9-ac6f42d72e91.png">

**Comment by abolabo** [comment]
this status disables sending of notifications.

**Comment by abantecart** [comment]
Boris please clarify your concern.

**Comment by BasaraABC** [comment]
It is not clear for me that **Admin: OFF** related only for administrator notifications only. Add help note or rename settings to something like "Administrator notifications: OFF" or whatever this setting disable. 
Actually it is not big problem.

**Comment by abolabo** [comment]
i added tooltips text for this switches. Pavel promised to correct them later

**Comment by BasaraABC** [comment]
thank you
