### ISSUE TITLE
Edit  Admin User page - follow standards

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#448]
![users2](https://cloud.githubusercontent.com/assets/2631910/13350720/58229f0e-dcb4-11e5-8a91-5c7a85dd4dad.png)

**Comment by abolabo** [comment]
this section totally changed

**Comment by BasaraABC** [comment]
Issue are valid for  new pages too. Moving same content to new pages are not fix. Please follow standards.
**rt=user/user/update&user_id=1**
and 
**rt=user/user/im&user_id=1**

**Comment by abolabo** [comment]
added for buttons with gears

**Comment by BasaraABC** [comment]
Thank you. Please also add 'loading' button to this page **index.php?rt=index/edit_details&s=your_admin** . You can access it from admin header

**Comment by abolabo** [comment]
hm..it's already there. see css-class "lock-on-click" for button

**Comment by BasaraABC** [comment]
maybe glitch. In fresh install it works OK.
