### ISSUE TITLE
suggestion: Storefront Notification notes

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#449]
Suggestion to improve Storefront notification UI. Give more human readable Sendpoints names and detailed note with how actually it work
<img width="579" alt="notification_settings" src="https://cloud.githubusercontent.com/assets/2631910/13353361/616ce1ac-dcc6-11e5-9eb1-c3f574dcd66d.png">

**Comment by abantecart** [comment]
Dima, let's add more text for customers. We will discuss

**Comment by BasaraABC** [comment]
Notes added but not defined.
<img width="911" alt="notifications_and_newsletter" src="https://cloud.githubusercontent.com/assets/2631910/13389009/61f6af9e-def7-11e5-8947-21c2f7c8e5ca.png">
