### ISSUE TITLE
dev issue: error in log after install

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#451]
error: AbanteCart core v.1.2.6 Call to a member function send() on a non-object in <b>/.../abc126_m02d29/core/lib/message.php</b> on line <b>123</b>
Note: install fresh cart on dev server and log in to admin. Then check error log

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Thank you this issue fixed. But in fresh install new text in log
`2016-03-03 0:29:38 - system_messages` 
I dont know what does it mean. Please remove or update error text if needed
