### ISSUE TITLE
dev issue: when new order  placed admin receive 2 notifications

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#461]
When customer confirm new order - administrator receive 2 email notifications, 2 sms (and "You have received an order" email if **Alert** setting ON)
<img width="830" alt="2016-03-01_21-19-27" src="https://cloud.githubusercontent.com/assets/2631910/13429589/898cb786-dff3-11e5-919c-940b0dff85f0.png">

**Comment by abolabo** [comment]
what sendpoints was enabled? new order + system messages?

**Comment by abolabo** [comment]
what sendpoints was enabled? new order + system messages?

**Comment by BasaraABC** [comment]
All sendpoints for admin was enabled

**Comment by abolabo** [comment]
notifications for sendpoint 'system messages' now will be sent only for warning  or error messages. Notices will be ignored.
