### ISSUE TITLE
dev issue: administrator receive incorrect notification when new admin user added

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#462]
ISSUE A: administrator receive incorrect notification when new admin user added 

ISSUE B: when Top administrator make changes in another admin user (for ex. change User group) same notification received - _New Customer #2 have been added!_ (account changed, not added)
<img width="988" alt="2016-03-02_12-26-33" src="https://cloud.githubusercontent.com/assets/2631910/13451564/e80dd018-e072-11e5-90a9-c42901d2fd99.png">

**Comment by abolabo** [comment]
this functionality now disabled

**Comment by BasaraABC** [comment]
Issue reopened. Administrator still receive this notification when update another admin account
