### ISSUE TITLE
dev issue: Critical error when customer change password

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#463]
When customer change password on SF - critical error appear.
_Important note: while you are work with this section please make sure that customer receive notification when password changed!_
<img width="872" alt="2016-03-02_13-22-20" src="https://cloud.githubusercontent.com/assets/2631910/13452435/444dc2aa-e07a-11e5-97f2-b9153574739e.png">

**Comment by abolabo** [comment]
fixed
