### ISSUE TITLE
dev issue: html in text sms

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#464]
![screenshot_2016-03-02_1423](https://cloud.githubusercontent.com/assets/2631910/13453452/d6ee8b82-e082-11e5-8524-2eda24f1cd30.png)

**Comment by abolabo** [comment]
fixed. added strip html-tag in all sms messages

**Comment by abantecart** [comment]
We need to allow links. I guess it can be just a URL. Boris can you test if you can click URL if it comes in the message?

**Comment by BasaraABC** [comment]
After fix I can not receive this message but in notification for admin about new review:
1. in android link in SMS is clickable but it is broke (page not found)
2. in email notification link is not clickable (text)

**Comment by abantecart** [comment]
I think we are good here. 
1. Admin updates, should not send notification to other admins.  Only exclusion of this rule is admin details update including password. Notification is sent to that admin 

2. URL in text is OK. This is up to specific devise to handle it. It might not be cleanable. 
NOTE: NO HTML can be present in SMS.

**Comment by BasaraABC** [comment]
Url is broken in SMS. Why issue closed?

**Comment by abolabo** [comment]
phone's sms-chat  is not html renderer. All html tags will removes.

**Comment by BasaraABC** [comment]
Issue not in html tags. Issue in the url. 
In email it looks like http://----/abc126_m03d04v3/index.php?rt=catalog/review/update&review_id=79&s=your_admin
but in android sms it is looks like http://----/abc126_m03d04v3/index.php?rt=catalog/review/update**&amp**review_id=79&**amp**s=your_admin
and it doesnot work

**Comment by abolabo** [comment]
fixed
