### ISSUE TITLE
Order status update notification problem

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#465]
When administrator change order with comment and set Notify Customer ON then customer receive message only to email. Should customer receive SMS notification too (_Order Update_  SMS is ON in customer settings)? 
<img width="863" alt="2016-03-02_14-31-12" src="https://cloud.githubusercontent.com/assets/2631910/13453717/c5b7fd9c-e084-11e5-9c94-c41702e3acb6.png">

**Comment by abolabo** [comment]
added functionality into IM of sending from admin side to customer.
