### ISSUE TITLE
dev issue: when new review added administrator receive 2 notifications

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#466]
administrator receive 2 notifications when new review added at SF

#1 m_system_messages_admin_text !!!!! 

#2 New product review have been added. See details http://....

**Comment by abolabo** [comment]
it's ok. Where is issue? Admin can manage notifications

**Comment by BasaraABC** [comment]
1 action should not give you 2 notifications.

**Comment by abantecart** [comment]
Let's retest this.

**Comment by abolabo** [comment]
i changed "system messages" sendpoint call. Now it will call only in case error or warning. new review is a "notice" and now admin will get only one notification.
fixed
