### ISSUE TITLE
dev issue: administrator order update sms notification

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#467]
Some disappointment with notification for Administrator when order changed in admin front
* when edited Order details (for ex. changed product quanity) - notifications email/sms
* when changed Shipping details in the order                           - notification email only
* when changed Order status in the grid (sales> orders)          - notification email only

Issue: sms notification not received in several cases

**Comment by abantecart** [comment]
Dima, I thought, we agreed to remove notification to admins with admin changes.

**Comment by abolabo** [comment]
all sendpoints in admin removed

**Comment by abantecart** [comment]
Do you mean admin to admin email sending?

**Comment by BasaraABC** [comment]
What "Order Update" notification for admin mean? When it work now?
<img width="560" alt="users" src="https://cloud.githubusercontent.com/assets/2631910/13488617/edf196d0-e154-11e5-8b69-100b2c5dd116.png">

**Comment by abolabo** [comment]
it works on sf-side now.

**Comment by abolabo** [comment]
@abantecart , yes. admin-admin now blocked

**Comment by BasaraABC** [comment]
@abolabo,  I am still have no answer what "Order Update" in administrator notifications actually do? Give me a case how to check it

**Comment by abantecart** [comment]
This is cancel request for now. We should group new orders and order updates to single Order Notifications.
