### ISSUE TITLE
improve: Notify customer selector to transactions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#469]
Please consider to add _Notify customer_ (ON/OFF) to the add transaction modal. If ON customer receive notification (you can link it with customer Account Update SF sendpoint or add new sendpoint).
Currently admin can not inform customer about balance change
<img width="920" alt="2016-03-02_16-32-59" src="https://cloud.githubusercontent.com/assets/2631910/13456225/a8ede720-e094-11e5-9b29-fc7f6283a7fd.png">

**Comment by abantecart** [comment]
Dima, we need to add check box here (off by default) to notify customer with transaction.

Just having Description for customers is not clear if customer will be notified.

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Small bug. When admin decrease account for ex. -25 the customer receive "the amount of **$0.00**."
<img width="753" alt="2016-03-04_10-47-53" src="https://cloud.githubusercontent.com/assets/2631910/13517545/f730a91e-e1f6-11e5-9fce-ca33e61d9237.png">

**Comment by abolabo** [comment]
fixed
