### ISSUE TITLE
loading button onsubmit SF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#470]
Please add loading button after user click on Submit buttons in SF. Now user can send multiply requests.
I suggest to add this to all submit buttons  (not only contact us)
<img width="643" alt="2016-03-02_17-27-36" src="https://cloud.githubusercontent.com/assets/2631910/13457792/829000e2-e09c-11e5-9d73-29758b6699ba.png">

**Comment by abolabo** [comment]
added concept 'lock-on-click' into common.js on SF side. Now on contact-us page. 
i think we need to add this on other pages. @abantecart what do you think?

**Comment by BasaraABC** [comment]
Contact Us page fixed. Thank you. Will be great to apply this for all SF areas (product review form and othes)

**Comment by abolabo** [comment]
yes.. we will add this in the future.

**Comment by BasaraABC** [comment]
Please also add to admin side for the PayPal and PayPal Pro extensions

**Comment by abolabo** [comment]
already added

**Comment by BasaraABC** [comment]
Still it is NOT added to Submit review, Account registration  also above mentioned paypal std and pro have same issue. Please add to all buttons for all SF areas and paypal in admin

**Comment by BasaraABC** [comment]
Issue with payment allows you to send CC again if error occur: Autorize.net
<img width="492" alt="2016-12-02_20-10-26" src="https://cloud.githubusercontent.com/assets/2631910/20835245/135c31ba-b8cc-11e6-88cf-712fa5664206.png">

**Comment by BasaraABC** [comment]
Issue C: cashflows is broken
<img width="829" alt="2016-12-06_16-32-36" src="https://cloud.githubusercontent.com/assets/2631910/20920258/d4efcc4e-bbd1-11e6-9699-37f33beb094b.png">

**Comment by abolabo** [comment]
issue with cashflow not related to locking of button but fixed. Please check commit for affected extensions.
