### ISSUE TITLE
parametr in seo url

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#471]
Please hide sort parameter from urls when SEO enabled. 
 It should not show by default only if diff sort selected. See forum http://forum.abantecart.com/index.php/topic,4447.msg19539.html#msg19539

**Comment by abantecart** [comment]
Fixed.

**Comment by abantecart** [comment]
Fixed to show to sorting on default listing, but if sorting is changed, there will be sort params visible in URL. This can not be removed.
