### ISSUE TITLE
Sales > Send SMS improve 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#472]
Please show also error when SMS is OFF 
<img width="1358" alt="2016-03-03_13-20-30" src="https://cloud.githubusercontent.com/assets/2631910/13486899/bcd0b804-e147-11e5-97eb-abb0d8ce547f.png">

**Comment by abantecart** [comment]
Let's talk about it. Please fix the text. there is an error

**Comment by abantecart** [comment]
Error text:. Attention! No customers with mobile phone numbers. 

About Boris suggestion. 
Let me clarify scenarios. 
1. No extension installed. No option to send SMS
2. If extension installed, there is no connection to setting in your screen shot. 
These settings are for automatic notifications and you can still send SMS to customers from admin manually

Need text above settings page:
These settings are for instant messages sent automatically during AbanteCart events.

**Comment by abolabo** [comment]
fixed
