### ISSUE TITLE
dev issue: administrator out of stock notification problem

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#473]
<img width="1573" alt="2016-03-03_15-08-23" src="https://cloud.githubusercontent.com/assets/2631910/13488227/6d5ecb02-e152-11e5-8444-17922101f959.png">

**Comment by abolabo** [comment]
track stock ?

**Comment by abantecart** [comment]
Does product have track stock on?

**Comment by abolabo** [comment]
this notification works only on SF-side!

**Comment by BasaraABC** [comment]
Why nobody read what I am write? 
> @abantecart
no it is OFF and in any case quantity is 1000

> @abolabo
Please read bug subject. #473** administrator **out of stock notification problem. When this product purchased on my side Administrator receive "Product with ID #63 is out of Stock."

**Comment by abantecart** [comment]
Dima it is a bug.

**Comment by abolabo** [comment]
found and fixed

**Comment by BasaraABC** [comment]
Still problems here: administrator did not receive notification when Option values are out of stock
<img width="723" alt="products" src="https://cloud.githubusercontent.com/assets/2631910/13562747/437b769a-e46e-11e5-839f-cc895e731238.png">
