### ISSUE TITLE
mobile number and user registration

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#474]
Please add mobile number unique validation. Currently anyone can register several account with same mobile and receive someone sms notifications

**Comment by abantecart** [comment]
Validation for uniqueness is not needed. There can be same number for multiple accounts. 

What is needed actually, a validation for mobile number with text sent. I will implement it.

**Comment by abantecart** [comment]
And we probably need setting for this.

**Comment by abantecart** [comment]
Verify mobile number with customer (Off by default)

**Comment by abantecart** [comment]
Decided for next release.
