### ISSUE TITLE
Order start number settings not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#475]
Setting not work. After I save 100 value new order come with id 17
<img width="552" alt="settings" src="https://cloud.githubusercontent.com/assets/2631910/13517343/18e7dbd8-e1f5-11e5-9c39-211d8add8772.png">

**Comment by abantecart** [comment]
This is invoice # not order ID. I already bumped in here before.

**Comment by BasaraABC** [comment]
No. We have 2 settings - one for invoice and new for orders

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
thank you
