### ISSUE TITLE
failed login attemp and no notification

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#478]
When failed login attempt to admin detected the administrator did not receive any notification (email/sms).
Note: all notification sendpoints are On. All others settings are cart installation defaults
<img width="565" alt="2016-03-07_12-29-37" src="https://cloud.githubusercontent.com/assets/2631910/13561541/c7e6afca-e460-11e5-99cb-06c041c7d37b.png">

**Comment by abantecart** [comment]
This is not a issue, but a nice feature to have. 
There are some downsides that we need to discuss first.

**Comment by abantecart** [comment]
Let's pass on this for now.
