### ISSUE TITLE
dev: State before Zip issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#479]
## Issue A: state is after zip in Guest Checkout
<img width="540" alt="2016-03-07_14-28-54" src="https://cloud.githubusercontent.com/assets/2631910/13563094/31b36e56-e471-11e5-9fdf-5aeae52ae20e.png">

### Issue B: bug in generated invoice. If save address in admin then State is removed from invoice
<img width="854" alt="2016-03-07_14-35-40" src="https://cloud.githubusercontent.com/assets/2631910/13563559/2f6b5448-e475-11e5-825f-181ea496a1be.png">

**Comment by abantecart** [comment]
Fixed
