### ISSUE TITLE
Custom form - file type field issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#48]
Still have issues with file type field. See screenshot
![1222014_31753 pm](https://cloud.githubusercontent.com/assets/2631910/5259671/87731a36-7a36-11e4-8a47-887bee2e77eb.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/e33415f3f74d18665ed3cb05cf2b10e14c5293a8
