### ISSUE TITLE
paypal pro: parsererror SyntaxError

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#483]
<img width="606" alt="checkout_confirmation" src="https://cloud.githubusercontent.com/assets/2631910/13595514/8c492090-e53e-11e5-9017-9b681d8895e3.png">

Also warning in log warning: AbanteCart core v.1.2.6 curl_errno(): 112 is not a valid cURL handle resource in <b>/../abc126_m03d08/extensions/default_pp_pro/storefront/controller/responses/extension/default_pp_pro.php</b> on line <b>265</b>

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Still errors
<img width="621" alt="checkout_confirmation" src="https://cloud.githubusercontent.com/assets/2631910/13661604/bb0b2728-e6c6-11e5-8ac3-3d72f79f45c2.png">

**Comment by abolabo** [comment]
fixed. problem related to sslv3 support of web-server
