### ISSUE TITLE
New user registration and Approve ON

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#489]
Missed message after new account creation if Approve new customers is ON.
To replicate:
1. install fresh cart.
2. Set **Approve new Customers ON**
3. go to SF and add any product to cart
4. Click Checkout
5. When asked select Register new account and create one
6. bug: After customer submit account form it is just redirected to the Login page without any message about approve process or any.

please note using this steps issue were replicated twice. Please fix

**Comment by abolabo** [comment]
fixed
