### ISSUE TITLE
Forms manager - date field menu

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#49]
Date selection menu looks broken
![1222014_33318 pm](https://cloud.githubusercontent.com/assets/2631910/5259783/90f337ce-7a38-11e4-8b56-00fa6c7c0aec.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/4fd81f1e8dd2aaf9f96b4ca43886e60318d6d0d4
