### ISSUE TITLE
dev: not defined error 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#490]
When you go from Sales> Send Mail to Sales> Send Sms the not defined error appear.
Also warning in log 
warning: AbanteCart core v.1.2.6 array_unique() expects parameter 1 to be array, null given in <b>s/abc126_m03d11/admin/controller/responses/sale/contact.php</b> on line <b>350</b>
<img width="904" alt="send_sms" src="https://cloud.githubusercontent.com/assets/2631910/13695488/d312f28a-e791-11e5-9f31-8d0b5435c2c7.png">

**Comment by abolabo** [comment]
fixed
