### ISSUE TITLE
dev: registration without mobile improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#491]
When customer register new account and DO not touch mobile field (ex. customer have not mobile or do not what to add it into account) the error appear. Please improve this. Customer should not manually remove +1 to be allowed create account
<img width="860" alt="create_account" src="https://cloud.githubusercontent.com/assets/2631910/13697063/91ebbfe2-e79d-11e5-8492-5a188b8de4f1.png">

**Comment by abolabo** [comment]
fixed
