### ISSUE TITLE
embed and product image settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#492]
<img width="890" alt="2016-03-11_17-57-25" src="https://cloud.githubusercontent.com/assets/2631910/13700345/0731c8a4-e7b3-11e5-9b9d-b152f05cb2e1.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue is not fixed. Checked in 1.2.7

**Comment by abolabo** [comment]
mmm, where is list of products here? Why we should to change something here?

**Comment by BasaraABC** [comment]
In my opinion Embed is more related to listing. Why we use _product page_ image size for _embed listing_ products?

**Comment by abolabo** [comment]
fixed
