### ISSUE TITLE
save and recalc in admin order details doesn't recalc subtotal and tax

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#496]
Hi admins, i just found another issue in v1.2.6. I try to edit sample order details by adding a product quantity, click on the save and recalc button. The subtotal and tax are not recalc, instead they are 0. Only the total are recalc. Here are the screenshots:

No SubTotal And Tax
![no subtotal and tax](https://cloud.githubusercontent.com/assets/225439/13941570/6c0bd682-f01b-11e5-98a1-31de43a6201c.png)

before edit order
![default](https://cloud.githubusercontent.com/assets/225439/13941571/6c130984-f01b-11e5-801e-756e13356ccc.png)

after edit order
![no subtotal](https://cloud.githubusercontent.com/assets/225439/13941572/6c13e34a-f01b-11e5-94c9-fb1ea3adf521.png)

**Comment by handoyo** [comment]
One more thing, the tax recalc button is not working too.

**Comment by BasaraABC** [comment]
Hello, handoyo. _Thank you for the report_ but you need to check on real new orders. The Demo orders are not the same thing. Just create new order and recheck.

**Comment by handoyo** [comment]
Hi Basara, you're right. I just checked new order, and it calculates both sub total and tax. Sorry for the wrong reported issues. Thanks you Basara. :)

**Comment by BasaraABC** [comment]
It is Ok. Feel free to post new issues. We will check
