### ISSUE TITLE
Incomplete Order Expiration setting

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#497]
Incomplete Order Expiration setting is not work. Incomplete orders not deleted when expired 
_rt=setting/setting/checkout_

**Comment by abantecart** [comment]
If this might not be working because of abandon order extension. Extension, need to reset this setting. 
We need to put code back. Older incomplete order needs to be removed based on the settings.

**Comment by BasaraABC** [comment]
Issue is not fixed. I set setting to value to 1 and after 2 day Incomplete orders not removed

**Comment by BasaraABC** [comment]
Again issue not fixed. **Incomplete Order Expiration** set to **1 day**. The incomplete order made 04/20/2016 not removed after 2 days.

**Comment by abolabo** [comment]
please check update date of order. Expiration based on it.

**Comment by BasaraABC** [comment]
I have not access to database so I can not check what Update date for this order. In admin only Date Added see order link http://dev06.*******/abc127_m04d20/index.php?rt=sale/order/details&order_id=14&s=your_admin
Note: there are 5 days left after order placed and nobody update it.

**Comment by abolabo** [comment]
it works. 
order cleanup runs every time when somebody creating order (visiting confirmation page).

**Comment by BasaraABC** [comment]
Please add note about this to setting
