### ISSUE TITLE
online customers and IPs

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#498]
maybe issue with customer detection.
Test case:
2 stores (multistore)
1 customer account logged in to both stores once!
in the second store customer logged in with Chrome + Google popular extension https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac

Issue: one customer account showed as 4 users logged in
need to discuss: can this cause any logg in/hack possible problems?
<img width="1190" alt="window_and_customers_online" src="https://cloud.githubusercontent.com/assets/2631910/14040702/76564888-f29c-11e5-91b8-b49e5f09e3fc.png">

**Comment by abantecart** [comment]
Looks like a reporting bug. Right?

**Comment by BasaraABC** [comment]
I am not sure. From one side 1 customer account used but from another side you can see that someone use several logins for one account...
