### ISSUE TITLE
enable Table in visual editor

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#500]
Please add Table button to the Visual editor. We have already Table plugin files. Just add it to toolbar http://forum.abantecart.com/index.php/topic,4554.msg19840.html#msg19840
![abantecart-tinymce](https://cloud.githubusercontent.com/assets/2631910/14167736/85e6370e-f747-11e5-8693-1a6f0e1a6fa5.png)

**Comment by abolabo** [comment]
added
