### ISSUE TITLE
broken popup in Extensions > Get extensions

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#501]
Issue visible in latest Chrome, FireFox
<img width="767" alt="extensions_marketplace" src="https://cloud.githubusercontent.com/assets/2631910/14176436/293cb9cc-f77b-11e5-82f0-4d16a43fe3d6.png">

**Comment by abolabo** [comment]
related to slow internet connection. cannot to reproduce for now.

**Comment by BasaraABC** [comment]
I dont think that it is related to slow internet. Issue replicated in FireFox 52 on 10MB internet.
Why not change popup script?
<img width="593" alt="2017-03-30_18-49-24" src="https://cloud.githubusercontent.com/assets/2631910/24537244/18d448c0-160b-11e7-80db-615c6f137882.png">
