### ISSUE TITLE
PHP 5.6 compatibilty

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#502]
Hi admins, I'm using PHP 5.6 on my local machine for extensions development purpose. One thing that I found out is that I get the mcrypt_encrypt warning that says only 16,24,32 key is the only supported key in 5.6 while I'm testing the guest checkout. So the guest order check link is not generated in the order_confirm.tpl file. Perhaps AbanteCart should add a note about it in the System requirements. And maybe admins are considering to update abantecart so it will works nicely on 5.6+?

**Comment by BasaraABC** [comment]
Fixed. Checked on local server with php 5.6.19
