### ISSUE TITLE
package_installer.php error

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#504]
After installing some extensions with Package Upload the error in the log
`App Error: AbanteCart core v.1.2.6 Error: Cannot to find package directory after unpacking archive. in /admin/controller/pages/tool/package_installer.php on line 501`
Note: installation is succesfull. Please test with extension id 340 (mp)

**Comment by abolabo** [comment]
it's a MP-bug related to repacking of package (no root folder inside tar.gz). 
please move this issue into mp-bug-tracker
