### ISSUE TITLE
zoom image size

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#505]
There is no way to control zoom image size. We can use **Large Window Preview Width** setting but you need to set it about 350-380 by default (currently its value 500 and it is not used in html5 template)
<img width="1426" alt="appear" src="https://cloud.githubusercontent.com/assets/2631910/14239905/9a44412a-fa6a-11e5-8e1d-07030bbce227.png">

**Comment by abolabo** [comment]
easyzoom jquery plugin does not allow to change lens size on the fly, only with css. This setting related to our default template, but other templates can use it

**Comment by abolabo** [comment]
to solve needs to update easyzoom plugin
