### ISSUE TITLE
can not enable Encryption 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#506]
Can not enable encryption on dev server and localserver. Once this line added to config.php
`define('DATA_ENCRYPTION_ENABLED', true);` - cart stop work and the following errors in the log

- `LEFT
 JOIN dsabc_customer_groups cg ON (c.customer_group_id = cg.customer_group_id) WHERE DATE(c.date_added) = DATE('2016-04-04') AND c.store_id = 0 in <b>/abc127_m04d04/core/database/amysqli.php</b> on line <b>106</b>
, c.key_id FROM dsabc_customers_enc c
cg.name AS customer_group
CONCAT(c.firstname, ' ', c.lastname) AS name,
c.customer_group_id,
c.approved,
c.status,
c.sms,
c.email,
c.loginname,
c.lastname,
c.firstname,
16-04-04 4:26:10 - database error: AbanteCart core v.1.2.7 Error: <br />SELECT c.customer_id,
c.firstname,
c.lastname,
c.loginname,
c.email,
c.sms,
c.status,
c.approved,
c.customer_group_id,
CONCAT(c.firstname, ' ', c.lastname) AS name,
cg.name AS customer_group
, c.key_id FROM dsabc_customers_enc c
LEFT JOIN dsabc_customer_groups cg ON (c.customer_group_id = cg.customer_group_id) WHERE DATE(c.date_added) = DATE('2016-04-04') AND c.store_id = 0 in <b>/abc127_m04d04/core/database/amysqli.php</b> on line <b>106</b>`

**Comment by abolabo** [comment]
it's not a bug. When you install encryption manager it creates duplicates of tables. When you change config.php - you know what you do. To add conditions for check of installed encryption manager will be wrong. This check adds limitation for other encryption extensions.

**Comment by abantecart** [comment]
Dima. There is not resolution and issue fixing in your answer
Encryption should work and used to work with config change as instructed. There was no SQL error before. 
Make use customer / customer_enc and order / order_enc tables' definitions match 100%

**Comment by abantecart** [comment]
It is important to follow instruction and install extension first. After installing extension, you can edit the config file.

**Comment by BasaraABC** [comment]
Extension were installed and enabled BEFORE edit config.php file. Why issue closed?

**Comment by BasaraABC** [comment]
Issue reopened. Tried one more time on fresh install. Extension Installed and Enabled (Status ON) next after your add `define('DATA_ENCRYPTION_ENABLED', true);` to the config file the store is broken

**Comment by abolabo** [comment]
fixed
