### ISSUE TITLE
dev issue: brands scroll block - distorted images

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#507]
<img width="869" alt="your_store" src="https://cloud.githubusercontent.com/assets/2631910/14347705/a3fcc14a-fce2-11e5-9ac9-c5999e0fc1cc.png">

**Comment by abolabo** [comment]
fixed. please check also automatic listings of listing blocks

**Comment by BasaraABC** [comment]
Data listing block create process is  broken. See screenshot 
<img width="1329" alt="brands" src="https://cloud.githubusercontent.com/assets/2631910/14454937/17a3cf20-00c7-11e6-91fc-d6af6b5a88be.png">

**Comment by abolabo** [comment]
please provide more detailed steps to replicate this issue
