### ISSUE TITLE
IE9 minor misplacement

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#511]
<img width="805" alt="dashboard" src="https://cloud.githubusercontent.com/assets/2631910/14453921/c55c296a-00c1-11e6-9ac8-c4784f75c0c2.png">

**Comment by abolabo** [comment]
tried to replicate in IE10 under IE9 emulation mode but unfortunately.

**Comment by abantecart** [comment]
Only 0.4 % of IE9 users. 
http://www.w3schools.com/browsers/browsers_explorer.asp

Unless this is seen in any other browsers, we can skip this.
