### ISSUE TITLE
mobile devices: IOS gap on product info page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#516]
<img width="740" alt="dashboard2" src="https://cloud.githubusercontent.com/assets/2631910/14564438/c112b9fa-0350-11e6-98e9-42d7a33f6222.png">

**Comment by abolabo** [comment]
looks like safari render bug. cannot to replicate on ff and chrome

**Comment by abantecart** [comment]
It is reproducible.

**Comment by abantecart** [comment]
Fixed. Please retest image zoom as it might be affected

**Comment by BasaraABC** [comment]
Issue reopened. Bug is visible on real Iphone 4s
