### ISSUE TITLE
mobile devices: product tabs not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#517]
there is no way to select Reviews or Tags tabs on product info page. When click user redirected to home page
Note: tested on real device iphone 4s and in browserstack devices (samsung galaxy...etc)
<img width="368" alt="tabs" src="https://cloud.githubusercontent.com/assets/2631910/14564685/ebf7eee6-0351-11e6-80de-d9095efdc2e7.png">

**Comment by abolabo** [comment]
tested on real android device. works fine. please test in your again. this page was changed earlier and probably bug already fixed.

**Comment by BasaraABC** [comment]
thank you. Issue fixed.
