### ISSUE TITLE
misplacement on Ipad Air 2

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#518]
On product info page header blocks misplaced  see screenshot
<img width="917" alt="responsive" src="https://cloud.githubusercontent.com/assets/2631910/14580084/7e68730a-03ec-11e6-9c8b-e7cbe39da246.png">

**Comment by abolabo** [comment]
mmm..where is main menu header block on your screenshot
![2016-04-27 23 00 45](https://cloud.githubusercontent.com/assets/1264239/14866341/effeb212-0ccb-11e6-8415-020315c9f34d.png)
?

**Comment by abantecart** [comment]
Fixed.
