### ISSUE TITLE
unserialize warning upon adding payment to shippings

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#519]
Hi admins, today i try to add paypal express to default usps extension. When i click on the save button. I got this message:
    warning: AbanteCart core v.1.2.6 unserialize() expects parameter 1 to be string, array given in          <b>C:\xampp\htdocs\testing\t126\core\helper\utils.php</b> on line <b>109</b>

**Comment by BasaraABC** [comment]
This configuration cause an issue. No need to save the warning go to log on page load
<img width="667" alt="united_states_postal_service" src="https://cloud.githubusercontent.com/assets/2631910/14675633/1654bd3c-0734-11e6-8fcc-6363f1302c70.png">

**Comment by abolabo** [comment]
we already fixed it.
please check this commit https://github.com/abantecart/abantecart-src/commit/60abdaf7a4a9bd7b2e90d72f6826c39ae0067f7b

**Comment by handoyo** [comment]
Thanks abolabo and Basara
