### ISSUE TITLE
2Checkout

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#52]
Can not checkout with 2CO. Test mode is on. Sandbox details in our doc.
![1252014_24424 pm](https://cloud.githubusercontent.com/assets/2631910/5312490/3e990812-7c8d-11e4-9115-5e67e40a3701.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Can not figure out how to complete order. Currently after 2Checkout return "Your payment has been processed" then in AbanteCart admin we have Incomplete order and I did not see way how to complete it
<img width="889" alt="2c0" src="https://cloud.githubusercontent.com/assets/2631910/8590051/e1c869fc-2646-11e5-9399-9ab27e6ca0c7.png">

**Comment by abolabo** [comment]
seems like 2CO IPN does not work in sandbox. i tested callback with ipn testing tool and it works fine.
