### ISSUE TITLE
dev issue: broken selected data blocks

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#522]
Issue visible in Chrome and FF. When you search in **Data to be listed** field the selected brands broken. (create Data Listing block > Custom Manufacturers)
<img width="644" alt="blocks" src="https://cloud.githubusercontent.com/assets/2631910/14701199/4a0fd798-07ce-11e6-8bbd-266f4cdfd0a8.png">

**Comment by abolabo** [comment]
probably fixed with previous commits. cannot to replicate
