### ISSUE TITLE
improve: all grids loading UI issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#524]
when working with Grids in admin - the loading is bad visible or sometimes is not visible at all. Because the loading text is small, not centered on the page and colors are not contrast with grid content
<img width="941" alt="grids" src="https://cloud.githubusercontent.com/assets/2631910/14701888/c54b4dcc-07d1-11e6-88ba-460b65cb828e.png">

**Comment by abantecart** [comment]
fixed
