### ISSUE TITLE
dev issue: low jpg image quality

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#531]
<img width="831" alt="2016-04-25_14-15-20" src="https://cloud.githubusercontent.com/assets/2631910/14776463/04b209b6-0af1-11e6-9b48-2bc0fecb71b6.png">

**Comment by BasaraABC** [comment]
Issue closed. Related to the Google Chrome - Data Saver plugin

**Comment by abantecart** [comment]
Please make sure that default setting generate good quality images. Check them in retina.
