### ISSUE TITLE
Design > Blocks improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#538]
<img width="1238" alt="blocks" src="https://cloud.githubusercontent.com/assets/2631910/14811818/3708baa8-0bc4-11e6-8bda-ad7152353819.png">

**Comment by abolabo** [comment]
store selector not needed here. Blocks assigns to layout, not store.

**Comment by BasaraABC** [comment]
Issue A: is not fixed
Issue B: 'store selector' is required here because Data Listing block show data related to store. For example custom Categories/Products. You can not find any product from store 1 if in session you have selected store2.
