### ISSUE TITLE
dev issue: product page zoom mobile

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#542]
Few problems with product's image zoom on mobile devices:
1. main image distorted in proportions see screenshot
2. zoom is not work
3. after you tap zoom area - you can not scroll page
<img width="817" alt="dashboard" src="https://cloud.githubusercontent.com/assets/2631910/14881452/3cc43580-0d5e-11e6-9150-f5c77c898461.png">

**Comment by abantecart** [comment]
There is still away to scroll. This problem is not easy to fix. I suggest to address this in the future.

**Comment by BasaraABC** [comment]
issue1 is not fixed right: now image width is too large (more than screen)
issue2 is not fixed: Zoom is completely not work. When you touch on the product image new window opened with image url
Checked on real device and browserstack too see screenshot 
<img width="502" alt="2016-07-20_18-46-46" src="https://cloud.githubusercontent.com/assets/2631910/16985445/9473199e-4eaa-11e6-831a-7035f3abc117.png">

**Comment by abolabo** [comment]
1. fixed.
2. zoom works only on large screen devices (exclude sm, md, sx). Easy zoom blocks scrolling.
3. link on img removed
