### ISSUE TITLE
dev issue: IE and admin grids

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#544]
Grids in admin not work on some machines with IE13, IE11 see screenshot
<img width="1045" alt="ie" src="https://cloud.githubusercontent.com/assets/2631910/14911243/500ffa32-0e1e-11e6-8d7d-62dd5c8b2fa1.png">

**Comment by BasaraABC** [comment]
@abolabo

**Comment by abantecart** [comment]
I tried edge 13 on windows and grid is working ok. See attached. 
![screen shot 2016-04-29 at 1 26 30 pm](https://cloud.githubusercontent.com/assets/1239995/14924032/7810eeca-0e0e-11e6-8508-163a5db8f9fb.png)
