### ISSUE TITLE
calculate product tax that was added via admin order detail page

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#546]
Hi admins, would you consider to add product tax calculation for products that was added via admin order details page into order_products table? Currently only name,model,price,total, and quantity that was added into that table. Thanks

**Comment by abantecart** [comment]
There is a tax calculation in admin order page, I believe since version 1.2.5. Can you please take this for further discussion in appropriate section on our forum?

This section is for issues/bugs only. 

Thank you.

**Comment by handoyo** [comment]
Hi admin, i'm not asking to add a feature. Instead want to let you know that i found an issue within admin order page. This is what i'm talking about.

![default table](https://cloud.githubusercontent.com/assets/225439/14989767/8f83d342-1183-11e6-910a-701f69179de0.png)
![added product](https://cloud.githubusercontent.com/assets/225439/14989768/8f84e5a2-1183-11e6-9ff3-eb84b473586d.png)
![add product](https://cloud.githubusercontent.com/assets/225439/14989766/8f8395d0-1183-11e6-843f-2f24c30cd0a6.png)
![default](https://cloud.githubusercontent.com/assets/225439/14989769/8f876c6e-1183-11e6-92fc-136051d27b97.png)

**Comment by handoyo** [comment]
Hi admin, sorry if i didn't explain clearly previously. Actually i'm not asking for a feature request, but i found an issue. I attach the screenshots here.

Existing order:
![default](https://cloud.githubusercontent.com/assets/225439/14990640/b4985384-1187-11e6-81c1-c003b1c38d98.png)

Order Products table:
![default table](https://cloud.githubusercontent.com/assets/225439/14990212/bd7738a0-1185-11e6-9672-0f648bee5479.png)

Add new products: 
![add product](https://cloud.githubusercontent.com/assets/225439/14990675/dbee29ea-1187-11e6-9d1e-59c747919cfb.png)

**Comment by BasaraABC** [comment]
fixed in 2.0
