### ISSUE TITLE
on success upgrade issue 1.2.6 > 1.2.7

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#547]
Few problems on success upgrade from 1.2.6 to 1.2.7:
1. Abantecart version in admin footer show old version
2. Backup is not created before upgrade
3. Error in log "warning: AbanteCart core v.1.2.6 file_put_contents(//htdocs/abc126/core/version.php) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in <b>/htdocs/abc126/core/lib/package_manager.php</b> on line <b>723</b>"
![upgrade](https://cloud.githubusercontent.com/assets/2631910/15042529/0410c370-12ef-11e6-9307-c80cc3ae2a1d.png)

**Comment by abolabo** [comment]
added attention and warning at start of upgrade process. automatic backup disabled.
tried to replicate bug with version-file update on 127>128 but unsuccessfully.
