### ISSUE TITLE
admin modify order bug

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#55]
All products from search added see screenshot 
![12152014_60842 pm](https://cloud.githubusercontent.com/assets/2631910/5434537/78ea3f04-8485-11e4-8102-52ed7827a1b5.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/a650fe5b2c42ee914342cad659dd5c7359a97dd1
