### ISSUE TITLE
dev issue: missed pagination

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#554]
Possibly browser glitch (FF) or bootstrap. Please check on few machines.
Note: upload few images before
[imagestest.zip](https://github.com/abantecart/abantecart-src/files/257262/imagestest.zip)

<img width="1183" alt="categories" src="https://cloud.githubusercontent.com/assets/2631910/15148012/a8d7be8e-16ed-11e6-83ee-4a9bfe81c6be.png">

**Comment by abantecart** [comment]
I tried images and FF + other browsers. I can not replicate. Let's see if it comes back again.

**Comment by abantecart** [comment]
Fixed. Added scroll bar to the right for smaller size windows.
