### ISSUE TITLE
dev: Product List issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#555]
Issue with one of the products if set Product List Width/height to 250px*450px see screenshot
<img width="1155" alt="special_offers" src="https://cloud.githubusercontent.com/assets/2631910/15149147/a1d8775e-16f2-11e6-867f-bc0be07af523.png">

**Comment by abolabo** [comment]
probably related to browser cache. did you tried to refresh page with ctrl+f5 ?

**Comment by abantecart** [comment]
Remember, that if width or height matching your setting size, there will be no resize. Original image needs to be proportional.

**Comment by BasaraABC** [comment]
The original image is 900px. x 900px. So if Hi-res Images ON, the 450px image setting give this problem in listing
