### ISSUE TITLE
app warning after emails sent

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#559]
Warning in log after successful email sent from Sales> Mail
Note: tested on php 7, no additional extensions installed - only Twillio

<img width="656" alt="mail" src="https://cloud.githubusercontent.com/assets/2631910/15174853/d69ba556-178d-11e6-8042-26a660539591.png">

**Comment by abantecart** [comment]
Why this is in 1.3.0? Is it difficult to fix warning? Should not be
