### ISSUE TITLE
Homepage Banner Block is messed up

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#56]
Misplaced banner in any screen resolution see screenshot 
![banner-wrap-](https://cloud.githubusercontent.com/assets/2631910/5500696/cbba2d26-877c-11e4-8cc1-7f84811b5395.jpg)
Issue at forum http://forum.abantecart.com/index.php/topic,3036.0/topicseen.html

**Comment by abantecart** [comment]
Fixed. 

Please test banner listing for content and bottom position.
