### ISSUE TITLE
MAC OS: broken multiselect elemnt in Chromium browsers

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#561]
Visible in Chrome, Opera
Note: not visible in FF
To replicate try to create new Location. 
<img width="794" alt="locations" src="https://cloud.githubusercontent.com/assets/2631910/15209823/801fb534-185d-11e6-8eb8-008a8740ef74.png">

**Comment by abolabo** [comment]
chrome version?
i tested on 49.0.2623.108. any luck. looks good

**Comment by BasaraABC** [comment]
Chrome version 50.0.2661.94,
Opera 37.0.2178.43
Important to create new location to see issue

**Comment by abantecart** [comment]
I never seen this issue on mac. Tried it now and all good. I think we need to watch for this.

**Comment by abantecart** [comment]
Low priority

**Comment by BasaraABC** [comment]
Issue is valid. Chrome Version 54.0.2840.98 (64-bit)
