### ISSUE TITLE
tax exempt for guest

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#565]
<img width="787" alt="tax_classes" src="https://cloud.githubusercontent.com/assets/2631910/15213674/fd6a06c4-1872-11e6-9943-9ff4e89c12a2.png">

**Comment by goatlady102** [comment]
IMO  that would be a correct handling -   A tax exempt customer needs to provide proof they are entitled to tax exemption.   Admin is in control of assigning them into a tax-exempt group once tax-exemption status has been verified. IMO those customers should be account only customers - no guests.

**Comment by BasaraABC** [comment]
thank you for your comment

**Comment by abantecart** [comment]
I agree. Let's hold off on this

**Comment by BasaraABC** [comment]
moved to internal tracker
