### ISSUE TITLE
The contactus form  - two issues -  ignores form manager email address when sending, and has difficulty with hyphen in email address

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#566]
The email address within the forms manager seems to be ignored in the Contact Us form.
It uses the system > settings  >  store details  email field.   This works the same in both 126 and 127.

Additionally if there is a '-' hyphen in the email address  eg  info@loveisreal-believe.com
-  it works for sending the order confirmation but the phpmailer in contactus fails.  I have not tested for other characters in the email address
- but fails on the contact us form submittal

![contactus-sending](https://cloud.githubusercontent.com/assets/7943102/15222492/a6743700-1835-11e6-9d8e-b6ef9e978889.jpg)

**Comment by abantecart** [comment]
We are fixing first issue. 
Please remember that AbanteCart has only one configuration of email. 
Sending email with different FROM address will trigger spoofing and mail recipient will move your email to junk or trash. 

There is nothing we can do here in the code as this should be handled on mail server side.  

I think your "-" issue is related to this. 
We tried and email with "-" or any other email (not mating original) goes to spam.

**Comment by goatlady102** [comment]
I have some confusion then on why there is a setting on the forms manager for an email address - if there is only one configuration of email. 

In regards to the "-"  in the email  address info@loveis-real.com   the email order confirmations are received from that address without issue.   It is only the ones in the contactusform that have been an issue.  Perhaps the form manager settings fix will solve that issue. If you are using php mail this was what I was thinking was perhaps the cause - 
https://www.digitalocean.com/community/questions/why-won-t-php-mail-send-emails-to-hyphenated-email-addresses-e-g-digital-ocean-hotmail-com
