### ISSUE TITLE
dev issue: manufacturer seo and multilanguages

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#568]
In AbanteCart the Manufacturers have not multilanguge support. But if change content language in any other grid you can save two different seo urls for different languages

**Comment by BasaraABC** [comment]
When content language changed somewhere in admin you able to save seo url for Manufacturer in other languages
<img width="941" alt="2016-05-13_18-43-38" src="https://cloud.githubusercontent.com/assets/2631910/15246954/009d04b8-193b-11e6-870f-5ded564ca2ab.png">

**Comment by abantecart** [comment]
Even though we only support 1 languges for manufacture, we still need to save SEO keword for every language. These different URLs will point to the same manufacture. Users can keep same keyword in the case.
