### ISSUE TITLE
dev issue: Use SEO URL's OFF and seo cache

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#569]
Please remove seo cache when _Use SEO URL's_ set to OFF. For now cached seo urls still works when _Use SEO URL's_ OFF

**Comment by abantecart** [comment]
Fixed.

**Comment by BasaraABC** [comment]
Issue is not fixed. Tested with HTML cache On

**Comment by abolabo** [comment]
added cache flush when any cache or seo setting changed.
