### ISSUE TITLE
Missing Icon media type ( PDF, ZIP etc ... ) on Right listing_block 

### ISSUE THREAD

**Issue by PlamenVaysilov** [abantecart/abantecart-src#575]
Missing Icon media type ( PDF, ZIP etc ... ) on Right listing_block .

**Comment by BasaraABC** [comment]
Hello. Can you please attach screenshot with problem?

**Comment by PlamenVaysilov** [comment]
http://a2heaven.com/webshop/index.php?rt=product/product&path=74&product_id=135

On right section ( MANUAL ) is missing link to Icon image  ( Both links point to same content ) .

Version 1.25 not have this issue .

**Comment by BasaraABC** [comment]
Thank you. Issue confirmed. 
Data listing block, Listing Data Source : Media
<img width="998" alt="2016-05-30_18-01-19" src="https://cloud.githubusercontent.com/assets/2631910/15647880/bf6f71de-2690-11e6-8c7f-0cf6a1febda8.png">

**Comment by BasaraABC** [comment]
Icons are missed on Admin side and problems with other data types: archive, video...etc

- issue1

<img width="523" alt="2016-07-26_20-09-13" src="https://cloud.githubusercontent.com/assets/2631910/17139004/eeff9434-536c-11e6-84b9-d016db921a92.png">


- issue2 (please note: no permission problems with pdf files)

<img width="671" alt="2016-07-26_20-12-15" src="https://cloud.githubusercontent.com/assets/2631910/17139176/88d33e3a-536d-11e6-8560-490824d227cc.png">

**Comment by BasaraABC** [comment]
I think it is related to #558

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Still bug here. In last version pdf and audio download links stop working (note: if use archive media type - link work)
<img width="1173" alt="2016-08-02_14-49-28" src="https://cloud.githubusercontent.com/assets/2631910/17321128/2d4276f4-58c1-11e6-8527-2bb3db44f93d.png">

**Comment by abolabo** [comment]
Note:  now download-resources cannot be placed in the listing block.
Also you cannot to download product file(downloads) of another customer. And you cannot to download file by download_id that have activation not 'before_order'.

**Comment by BasaraABC** [comment]
Thank you for your comments but you did not read issue. It is about MEDIA and not about Download Files. Please fix.

**Comment by abolabo** [comment]
archive-resources now have it's own subdirectory archive inside resources folder.
All media in listing block have direct link into it.

**Comment by abantecart** [comment]
NOTE: Archive resource type is now moved to resource/archive location. This makes this type public for download.
At this point only download resource type is not available for direct public access.
