### ISSUE TITLE
where is backup file?

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#58]
It is not clear for user where to locate archive after backup
![12232014_32906 pm](https://cloud.githubusercontent.com/assets/2631910/5535807/abe5fa36-8ab8-11e4-958e-6ffa7257dc58.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/2deab86557d385a7e5588a4aa7e3f943e0a43cb0
