### ISSUE TITLE
Single Product info not returning thumbnail in api response

### ISSUE THREAD

**Issue by ravdeepsingh22** [abantecart/abantecart-src#580]
http://evilengineerlabs.com/android2/public_html/index.php?rt=a/product/product&product_id=51&api_key=ravdeep

product_image is null

**Comment by ravdeepsingh22** [comment]
i have forknd ed this repo  afixed this issue and one more issue

**Comment by BasaraABC** [comment]
https://github.com/abantecart/abantecart-src/pull/581

**Comment by abantecart** [comment]
This has been resolved.
