### ISSUE TITLE
Api Call to Edit or Delete Address 

### ISSUE THREAD

**Issue by ravdeepsingh22** [abantecart/abantecart-src#585]
Need Api Call to Edit or Delete Address

**Comment by ravdeepsingh22** [comment]
Added the Functionality to Delete Address 
Please check the Pull Request

**Comment by abolabo** [comment]
mmmm.. don't see your pull request :(

**Comment by ravdeepsingh22** [comment]
Please check this 
Delete functionality with checks 

https://github.com/ravdeepsingh22/abantecart-src/commit/e4d9d82b1a11faf6c59b5f7cbf7a1c7c838909b0

**Comment by abolabo** [comment]
Thank you for your contribution!
