### ISSUE TITLE
Error: E-Mail from required! Form manager related

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#59]
By default we have empty <b>Default Sender</b> and <b>Default Sender Email</b> settings
 in Admin-Extensions-All extensions-Forms Manager extension.
This will cause error after form submit: Error: E-Mail from required!

![cz](https://cloud.githubusercontent.com/assets/2631910/5547947/22add6be-8b97-11e4-849c-c0e29567ce78.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/e6687da6fac4d5e00d83f6f8430a16a41a22b9d7
