### ISSUE TITLE
show system time somewhere in setting -> system section

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#592]
we need to show system time somewhere in setting -> system section
All orders and other times are based on system time.

**Comment by abolabo** [comment]
it presents on phpinfo page in settings->system

**Comment by abantecart** [comment]
I think we need to show it mode visible. It can be in admin dropdown or in the bread crumb.

**Comment by abantecart** [comment]
It should say "Server date & time: 12/31/2016 12:00:00
Use date_format_long

**Comment by BasaraABC** [comment]
Agree we need to show time and maybe system time zone?
