### ISSUE TITLE
Dashboard stats improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#593]
Total sales today show incorrect result. It show sales for last 24h. Please improve to select only for today based on server time
Please apply fix to other stats (today orders, customers...)
<img width="246" alt="2016-07-05_19-08-22" src="https://cloud.githubusercontent.com/assets/2631910/16584137/204cbf10-42e4-11e6-8efb-31c0e8444c5d.png">

**Comment by abolabo** [comment]
no. it shows results from begin of day (00:00:00).
