### ISSUE TITLE
dev issue: resource load bug

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#596]
Product images loaded on page without any products/listing/cart
HTML cache is OFF
<img width="776" alt="2016-07-06_14-16-13" src="https://cloud.githubusercontent.com/assets/2631910/16610409/43e2736a-4385-11e6-8ff3-93be8d1e6031.png">

**Comment by abolabo** [comment]
this is not a bug! you show picture from categories menu
