### ISSUE TITLE
design issue - too large Audio media icon at SF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#60]
enable Media block on product info page. If media available in product block shown with very large media icon see screenshot
![12252014_34000 pm](https://cloud.githubusercontent.com/assets/2631910/5553191/4f9629b4-8c4c-11e4-92a9-866b9de41624.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/00a14ba925c4a80612a3d407fdb6814d703dcf8a
