### ISSUE TITLE
dev: web perfomance improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#600]
Chrome browser audit tool report few issues. Important to fix inline script which blocking parallel downloading
<img width="1117" alt="2016-07-11_15-08-45" src="https://cloud.githubusercontent.com/assets/2631910/16723823/9e89b092-4779-11e6-8c4e-70b842cde07f.png">

**Comment by abolabo** [comment]
moved to 1.3.0. cannot be fixed at this template

**Comment by BasaraABC** [comment]
moved to internal tracker
