### ISSUE TITLE
dev: quick view - category edit links broken

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#605]
<img width="919" alt="2016-07-11_17-55-25" src="https://cloud.githubusercontent.com/assets/2631910/16728548/1c7bd824-4791-11e6-8de3-8baf68abea42.png">

**Comment by abolabo** [comment]
probably already fixed. cannot to reproduce

**Comment by BasaraABC** [comment]
issue is valid. Please check latest code (I have fresh install on dev06)

**Comment by abolabo** [comment]
Pavel, please look on it. i guess it's a bug related to MacOS.
