### ISSUE TITLE
dev: customer quick view and IM

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#607]
<img width="953" alt="2016-07-11_20-52-24" src="https://cloud.githubusercontent.com/assets/2631910/16732943/9ea2b0ee-47a9-11e6-9185-ded1a4b43891.png">

**Comment by abantecart** [comment]
I can not see any error on my side. Dima?

**Comment by abantecart** [comment]
I got this error after code refresh. This is something new.

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
issue visible on fresh install
<img width="748" alt="2016-07-14_17-59-17" src="https://cloud.githubusercontent.com/assets/2631910/16837307/c2178f82-49ec-11e6-8959-dbaee23eee8e.png">
