### ISSUE TITLE
dev issue: critical error when add total to order

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#608]
Note: order with Flat Shipping Rate

<img width="819" alt="2016-07-12_17-49-19" src="https://cloud.githubusercontent.com/assets/2631910/16764628/6d7e77e0-4859-11e6-88e9-8e202268f76b.png">

`2016-07-12 6:28:59 - load error: AbanteCart core v.1.2.8 Error: Could not load model extension/default_flat_rate_shipping from /htdocs/abc128_m07d12/core/lib/order_manager.php on line 231 in <b>htdocs/abc128_m07d12/core/engine/loader.php</b> on line <b>105</b>`

**Comment by abolabo** [comment]
needs more details how to replicate it

**Comment by BasaraABC** [comment]
1. Create new order and make sure your shipping is **Flat Shipping Rate**
2. Login to admin and open order page
3. Click add total button
4. type 2 in amount filed and click save

**Comment by BasaraABC** [comment]
I am able to replicate issue on fresh 1.2.8
Please follow this steps:
1. install new! cart in a_tools
2. actonbehalf any customer 
3. create order with few products in the cart
4. go to Admin open last order and add coupon in same way you see on the screenshot
<img width="1008" alt="2016-07-21_15-15-39" src="https://cloud.githubusercontent.com/assets/2631910/17015850/82582324-4f56-11e6-90f7-1fe73bedeb9a.png">

**Comment by abolabo** [comment]
after long time debugging resume that is something on dev-server. Please note when you install cart is default_flat_rate_shipping shows as installed in extensions list and let us know if is not. 
default_flat_rate_shipping must be installed after cart installation!
