### ISSUE TITLE
Product Thumbnail Size With multiple Templates 

### ISSUE THREAD

**Issue by tomtjsol** [abantecart/abantecart-src#61]
When you have multiple templates available the Product Image thumbnail size pulls the values from the last template only not the active template. I am not sure about any of the other setting on this page admin page. This is in the admin -> setting -> appearance.

**Comment by abantecart** [comment]
Thank you. Abolabo will check this.

**Comment by abolabo** [comment]
tomtjsol, what the active template do you mean? Is it compatible with v1.2?
