### ISSUE TITLE
dev issue: account confirmation issue 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#611]
Note: to replicate enable _Email Activation for New Customers_ in System > Checkout settings
<img width="1191" alt="activate" src="https://cloud.githubusercontent.com/assets/2631910/16839489/849e3fc2-49f9-11e6-9f2f-753948f823be.png">

It start work only when you resend link again and click one more time.

**Comment by abantecart** [comment]
Fixed. Please test.

**Comment by BasaraABC** [comment]
Bugs here visible when customer click activation link in email. See screenshot
<img width="961" alt="2016-07-18_16-28-08" src="https://cloud.githubusercontent.com/assets/2631910/16910810/ea105486-4d04-11e6-93c1-853f3fe90219.png">

**Comment by abantecart** [comment]
Fixed.
