### ISSUE TITLE
dev account text improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#612]
When **Email Activation for New Customers** is ON - this text disappoint user. Please change to something like "Account created but activation required" or "Activation required. Follow instructions"
<img width="945" alt="2016-07-18_16-21-14" src="https://cloud.githubusercontent.com/assets/2631910/16910671/2e5dadf6-4d04-11e6-835d-a81b20d02991.png">

**Comment by abantecart** [comment]
Need to consider in new template on 1.3
