### ISSUE TITLE
dev issue: quick edit modal is not responsive

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#613]
<img width="960" alt="2016-07-18_18-51-32" src="https://cloud.githubusercontent.com/assets/2631910/16915795/bd5ae496-4d23-11e6-8d5b-d1bea27ac700.png">

**Comment by abolabo** [comment]
quick preview now available only for large screen devices

**Comment by BasaraABC** [comment]
We have same problem with modal in any other cases so maybe better to fix and not remove feature? See modal on mobile if you have not payment installed and visit Admin dashboard
<img width="978" alt="2016-07-28_18-34-04" src="https://cloud.githubusercontent.com/assets/2631910/17211250/8d674a14-54f2-11e6-8ac1-7c1664f73a10.png">

**Comment by abolabo** [comment]
agree. rewrote
