### ISSUE TITLE
Fatal Error! "Load data error. please check the error log."

### ISSUE THREAD

**Issue by TenyVille** [abantecart/abantecart-src#615]
![abante error](https://cloud.githubusercontent.com/assets/20530974/16939852/ed8d7e98-4d8d-11e6-81fc-2bd7d86aeb72.PNG)
When I look at the error log this is what i see
2016-07-18 15:51:07 - error: AbanteCart core v.1.2.7 Allowed memory size of 268435456 bytes exhausted (tried to allocate 63600 bytes) in <b>/home/kilundo/public_html/tenyville.com/core/lib/image.php</b> on line <b>108</b>
I have tried all the methods that are online like increasing the ram allocation, tweaking the php code. I have even tried uninstalling the cart and reinstalling it afresh but the same error keeps coming up.

**Comment by BasaraABC** [comment]
Looks like this is configuration issue. Please move this discusstion to the forum.abantecart.com
For the **Allowed memory size** please contact with your hosting support.
