### ISSUE TITLE
grave accent in password

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#616]
Customer get _Error: Password must be between 3 and 20 characters!_ if try to register customer account with ` (grave accent) symbol in the password. Please fix or correct message if grave accent is not supported

**Comment by abantecart** [comment]
This worked for me like 123`

**Comment by BasaraABC** [comment]
Users report issues with similar passwords see http://forum.abantecart.com/index.php/topic,4892.msg21649.html#msg21649

**Comment by BasaraABC** [comment]
To replicate issue try to create SF account with passwords like:
**x?QRhndv"7bz\c(W**      ( 16 chars) error "Password must be between 3 and 20 characters!"

Take a note same password without " is OK ( **x?QRhndv**7bz\c(W  )  so looks like problem with `' "` chars

**Comment by abantecart** [comment]
Fixed. 
Testing required for:
Customer creation 
Password change and forgotten password reset.

**Comment by BasaraABC** [comment]
Issue fixed. Tested with passwords like 
123u'XP8{]?sbuHdTLG" 
and 
{]?sbuHdTLG”@;’`’тіЄ
so different grave accents work as well
