### ISSUE TITLE
IM enabled issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#619]
When IM enabled and customer have mobile number saved in account - please show mobile number in invoice, order email, order edit page, quick view.
Please note issue only for logged in customer (guest order show mobile number)!

**Comment by BasaraABC** [comment]
Update: please also show fax number if available (requested on forum)

**Comment by abolabo** [comment]
please test im-sending too.

**Comment by BasaraABC** [comment]
Issue is not fully fixed.  Mobile phone is still missed in order edit page in admin, order quick view in admin, order email (plain text format)

**Comment by abolabo** [comment]
fixed except mail data issue (#631)
