### ISSUE TITLE
Data listing block (popular) incorrect price 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#62]
Incorrect price shown in the Data Listing Block (Popular products) in few cases:
1. When product has Special price - block did not show Special
2. When 'Displayprices with Tax' ON - block shown price without tax
![issue1](https://cloud.githubusercontent.com/assets/2631910/5716788/89919132-9b27-11e4-80c2-9ebd4a651d25.jpg)
![issue2](https://cloud.githubusercontent.com/assets/2631910/5716789/899cde0c-9b27-11e4-9239-7a8adc5c6948.jpg)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/a87377e5e4a89230339b88274d996c87cef9a033
