### ISSUE TITLE
Extensions grid: sort by date not work correct

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#624]
Sort by Update Date is not work correct. Extension installed after cart install should be first see screenshot
<img width="954" alt="2016-07-27_13-15-33" src="https://cloud.githubusercontent.com/assets/2631910/17165700/8083da16-53fc-11e6-88ef-6524b96887a3.png">

**Comment by abantecart** [comment]
Sorting should be based on date updates considering time (in the screenshot there is a update date sorting)

**Comment by abolabo** [comment]
related to sql. Please test after 2 minutes from the end of installation process!
