### ISSUE TITLE
SQL Error: Duplicate entry '2' for key 'ac_url_aliases_idx'

### ISSUE THREAD

**Issue by buzzfrog** [abantecart/abantecart-src#626]
Error No: 1062
SQL: INSERT INTO abvh_url_aliases (`keyword`, `query`, `language_id`) VALUES ('', 'product_id=128', '2') in /home/xxxxx/public_html/shop/core/database/amysqli.php on line 106

When trying to insert a new product. (I have changed the default language to Swedish.)

/dag

**Comment by BasaraABC** [comment]
Hello. Thank you for reporting but this issue is already fixed. Please apply code changes from here #584 
In case issue is not fixed for you please reply.
