### ISSUE TITLE
Activation email - missed plain format

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#629]
Looks like store send only HTML format in Activation email.
If set in mail client Plain Text email format then html code is visible
Note: what are the double commas at the end of url?
<img width="807" alt="2016-08-03_14-53-34" src="https://cloud.githubusercontent.com/assets/2631910/17358396/04d05508-598c-11e6-8fba-638e6b53635c.png">

**Comment by abolabo** [comment]
commas at the end related to encryption hashes.

**Comment by abolabo** [comment]
added changes related to transferring of encrypted hashes. i mean url parameters such as ot, rid, ac...
that used for url to order invoice page  for guests or token for activation for non-activated customers

**Comment by abantecart** [comment]
There is a further fix needed here.

**Comment by abantecart** [comment]
https://github.com/abantecart/abantecart-src/commit/92dab48934ce68d3a76f8452302b127ba6c936f7

Please retest.
