### ISSUE TITLE
Parent categories dropdown

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#63]
Parent categories dropdown broken in Chrome, IE, Opera see details http://forum.abantecart.com/index.php/topic,3126.msg13240.html#msg13240

**Comment by abantecart** [comment]
https://github.com/abantecart/abantecart-src/commit/a9c14815080c13974e294b1e4bac42a1ec24031c

**Comment by abantecart** [comment]
Basara, please confirm in IE10+
Thank you

**Comment by BasaraABC** [comment]
fix works in IE 11, Opera, Chrome
