### ISSUE TITLE
dev issue: order cancellation broken

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#630]
<img width="909" alt="2016-08-03_18-14-56" src="https://cloud.githubusercontent.com/assets/2631910/17363761/95fa2558-59a6-11e6-8be3-1010d6660c5d.png">

**Comment by abantecart** [comment]
I can not replicate it. There is no such line. I think this was fixed before.

**Comment by BasaraABC** [comment]
Issue reopened. Bug visible for guest orders in fresh install
visit this link 
dev06.*******.net/abc128_m08d09/index.php?rt=account/invoice&ot=CikfrQ4pRE4ziiSqgZKMtaA58XGhTCo6Mz0lXAy_Jlk%2C
 and click Cancel Order button

**Comment by abantecart** [comment]
This works on my install as well. Dima fixed this error before
