### ISSUE TITLE
dev issue: approve required and approved emails format

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#634]
Email received by customer after administrator approve account have wrong format see screenshot
<img width="1481" alt="2016-08-04_16-10-37" src="https://cloud.githubusercontent.com/assets/2631910/17396974/141cc210-5a60-11e6-93e3-f4bb599d079b.png">
Note: mail client set to 'Original HTML format'

**Comment by BasaraABC** [comment]
#631  related

**Comment by abolabo** [comment]
added url into mail-text for both variants
