### ISSUE TITLE
responsive order page SF issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#635]
In both normal and rotating view order table looks broken
<img width="725" alt="2016-08-04_17-10-29" src="https://cloud.githubusercontent.com/assets/2631910/17398498/52cd1c6a-5a67-11e6-9144-dd1173ee044c.png">

**Comment by abantecart** [comment]
Fixed, but top portion is suppose to be like that. You need to scroll left to right.
