### ISSUE TITLE
IM: customer notify for Order Status change 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#637]
Customer did not receive SMS when Notify Customer is ON
<img width="739" alt="2016-08-04_17-52-29" src="https://cloud.githubusercontent.com/assets/2631910/17399517/a1938406-5a6c-11e6-9efd-5e3a780cbce6.png">
Note: other sms IM is work so problem is not in configuration

**Comment by abolabo** [comment]
note: im does not work for guests yet. added "todo"
