### ISSUE TITLE
Sub-total order total ignore calculation setting?

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#64]
When chnage calculation order (see screenshot) there is NO changes in cart (clear AbanteCart cache not help)
![totals-issue](https://cloud.githubusercontent.com/assets/2631910/5854219/1c241622-a25e-11e4-88fa-f0d466fa3daf.png)

**Comment by abolabo** [comment]
it's not a bug. Sub-total always will be first in order calculation because of other calculations of totals depends on it. But in this case we have UI misunderstanding. yes, agree

**Comment by BasaraABC** [comment]
please improve UI. We discussed this before. I am still able to change calculation and sort order in grid and in Edit Order Totals page for Sub-total -  no notes or error/warning message showed  (checked in latest 1.2.1)

**Comment by abolabo** [comment]
i added note to promotion extension (see extensiton settings page) about order total calcualtion order. Core works correctly. Yes, you can edit sort and calculation orders and it's right.
