### ISSUE TITLE
HTML validation

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#640]
https://validator.w3.org/
Home page/category listing/ product page -  7 errors
Please fix

**Comment by BasaraABC** [comment]
Please enable few languages. There are one issue if 2 or more languages enabled

**Comment by BasaraABC** [comment]
Still visible 2 errors in fresh install
<img width="1047" alt="2016-08-09_12-39-07" src="https://cloud.githubusercontent.com/assets/2631910/17505910/ba60bf92-5e2e-11e6-9a3e-3841d2bb459a.png">

**Comment by abolabo** [comment]
need the steps. i tried on dev-server. installed cart, opened sf-side, installed italian, turned on and check sf - 
Document checking completed. No errors or warnings to show.

**Comment by BasaraABC** [comment]
The steps are same. I have fresh install on dev server with 2 languages installed. And  2 errors on home page
