### ISSUE TITLE
USPS ignore free shipping setting

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#65]
USPS ignore per product setting <b>Free shipping</b> see post 
http://forum.abantecart.com/index.php/topic,3205.0/topicseen.html
![uspsissue1](https://cloud.githubusercontent.com/assets/2631910/5870726/857b2f5a-a305-11e4-8351-76959adbf2d2.png)
NOTE: same with <b>Fixed Shipping Price</b> setting

abolabo FYI - working test account credentials in sandbox doc

**Comment by BasaraABC** [comment]
P.S another USPS issue waiting for fixes https://github.com/abantecart/abantecart-src/issues/42

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/375cc722e4021d079cda8c60f5b6be6606e03998

**Comment by BasaraABC** [comment]
two issues with fixes:
<b>issue1.</b> If enable 'Fixed shipping price' or 'Free shipping' USPS works incorrectly - it is allow shipping with USPS to incorrect address see screenshot.
![usps-issue1](https://cloud.githubusercontent.com/assets/2631910/5919333/78d9741a-a665-11e4-8f09-7e439661089a.png)
------------------------------------
<b>issue2.</b> USPS ignore 'Ship products individually' see screenshot
![usps-issue2](https://cloud.githubusercontent.com/assets/2631910/5919353/9628c0b6-a665-11e4-84d9-b959debd0260.png)

**Comment by abolabo** [comment]
implementation of support for individual deliveries in multi optional shipping methods currently impractical because of multiple API queries server-to-server.

**Comment by BasaraABC** [comment]
What about issue1?

**Comment by abolabo** [comment]
usps API ignores zip-code format. For shipping estimate takes only country and zone.
