### ISSUE TITLE
to-do: account created and last access date

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#655]
Add account created and last access dates to customer account

**Comment by abantecart** [comment]
We need to add this to all data objects (edit pages) such as products, categories, manufacturers, etc..
This help to see then data was originaly create and last updated.

**Comment by BasaraABC** [comment]
Few issues and suggestions (we can discuss with all team members)
Issue A: if customer never login please display 'never' text
<img width="829" alt="2016-12-06_17-36-33" src="https://cloud.githubusercontent.com/assets/2631910/20922496/ead37638-bbda-11e6-9089-129d23b14267.png">
Suggestion B: Please show also account created date as requested in original post
Suggestion C: Please add last login and data created to the Quick View modal

**Comment by BasaraABC** [comment]
Empty box on Address Edit page (admin index.php?rt=sale/customer/update_address&customer_id=15&address_id=15)
<img width="684" alt="2016-12-07_14-12-11" src="https://cloud.githubusercontent.com/assets/2631910/20958271/4a9fe4dc-bc87-11e6-8099-e4f654aacbc0.png">
