### ISSUE TITLE
all settings and search problem related to template settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#657]
![2016-08-19_20-30-19](https://cloud.githubusercontent.com/assets/2631910/17811287/1e2dd1f2-664c-11e6-808e-59f4315539b9.png)

**Comment by BasaraABC** [comment]
Issue A is not fixed.

**Comment by abolabo** [comment]
We have filter for core settings here. Settings for extensions are forbidden here. 
We don't know where extension's setting can be edited, on generic setting page of extension or on extension additional settings page or template edit page. @abantecart ?

**Comment by abolabo** [comment]
Settings are related to extension and do not belong here
