### ISSUE TITLE
template settings edit issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#658]
No way to remove logo and icon. After user hint save the removed logo/icon shown

**Comment by abantecart** [comment]
Need more details here. I am able to remove logo and icon

**Comment by BasaraABC** [comment]
1. install third party template (for example bootstrap)
2. remove logo and click Save. 
After page reloaded - removed logo will show

**Comment by abantecart** [comment]
Are you sure this is an AbanteCart issue and not third party? I think it is a bug in the template that you look at.
