### ISSUE TITLE
Maximum Quantity limit not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#66]
Shopping cart ignore Maximum Quantity limit (set it in product settings)
![maxissue](https://cloud.githubusercontent.com/assets/2631910/5873918/58d4b416-a32e-11e4-960d-db85b6b59bce.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/9471b7acf7dd5c1f65dd8157b5cf8dc2daabc983
