### ISSUE TITLE
language definitions popup issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#661]
When you add _several_ language definitions one by one the Insert popup show previous popup info see screenshot
<img width="749" alt="2016-08-25_21-03-36" src="https://cloud.githubusercontent.com/assets/2631910/17972157/08ab05be-6b08-11e6-93c0-f2eee2063258.png">

**Comment by abolabo** [comment]
cannot to reproduce

**Comment by BasaraABC** [comment]
Please see gif video with how it work in my FireFox browser on latest 129 installation.

![video-bug](https://cloud.githubusercontent.com/assets/2631910/20657442/74529994-b568-11e6-9732-bea314a56ee0.gif)

**Comment by BasaraABC** [comment]
I replicate issue in IE11 Windows 8.1, Firefox Window 10, Chrome OS X. Not sure why you can not replicate

**Comment by abantecart** [comment]
I also have problem replicating this. Let's connect to work on this

**Comment by BasaraABC** [comment]
I replicate in browserstack.

**Comment by BasaraABC** [comment]
minor issue not visible in all browsers.

**Comment by abantecart** [comment]
Fixed
