### ISSUE TITLE
Address State improve required

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#662]
Few problems require improve related to customer address:
- some countries have not states (for example Singapore )
- a lot of countries have States, Districts and Sub-Districts http://forum.abantecart.com/index.php/topic,3039.msg18877.html#msg18877

**Comment by abantecart** [comment]
We will need help here to locate all the conditions and data here. Best to hear back from users from these regions. 
Let's reschedule this for next release.

**Comment by goatlady102** [comment]
You may find this link quite helpful  -  it offers a complete database and is kept up as it is used by major shippers and international companies 

http://www.unece.org/cefact/locode/welcome.html

And here is a slightly out of date project that has a good start on this issue.

https://github.com/astockwell/countries-and-provinces-states-regions

**Comment by BasaraABC** [comment]
I think we need to create a more flexible Address forms in respect of settings in each country:
1. make fields required or not (some countries do not require Town or State at all)
2. add more fields (a lot of countries require sub-states or disctricts)

**Comment by abantecart** [comment]
Yes, agreed. We will get to this soon.

**Comment by goatlady102** [comment]
Hello guys,
Please consider adding the features we (WHY2) in the marketplace have on our extensions Telephone Option http://marketplace.abantecart.com/telephone_option
and VaxTax ID http://marketplace.abantecart.com/taxid_option?keyword=vat&category_id=0

I believe these features belong in the core product -  and would enlarge the EU and Asian Market considerable.   And I would be delighted to not have to keep these extension up to date.

Thanks
Lee

**Comment by BasaraABC** [comment]
moved to internal tracker
