### ISSUE TITLE
Abantecart reset all settings one in a while

### ISSUE THREAD

**Issue by thealmogg** [abantecart/abantecart-src#663]
Hi,
I have abantecart - for some reason the store just reset it self one in like month or two and change almost everything.
Changes the logo, CSS colors back to stock, changes images of items to some perfumes.
Is there a bug or something?
The problem is that I'm reverting all the settings manually, leave the store like this without
changing anything and it's just doing it again automatically!

**Comment by BasaraABC** [comment]
Hello. Thank you for reporting problems but please move this question/discussion to the public http://forum.abantecart.com/
In first look your hosting restore backup or something. AbanteCart have not tool to do this automatically so contact your hosting support please.
