### ISSUE TITLE
Administration Language setting issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#666]
Administration Language setting works incorrect. If set to Spanish and login to admin with clean browser cache then Content Language is Spanish but Admin Interface is English
<img width="528" alt="2016-09-08_18-06-14" src="https://cloud.githubusercontent.com/assets/2631910/18347329/2e9ebc6a-75ef-11e6-9302-e0fa9d18c3ad.png">

**Comment by BasaraABC** [comment]
Please also add notes to SF/Admin language setting that changes will be visible after session cookie removed

**Comment by abolabo** [comment]
cannot to reproduce. Deleted all cookies, russian was set as admin side language. opened login page - works correct.

**Comment by BasaraABC** [comment]
Unfortunately issue is still replicatable on my side even with rusian language. Please check my steps and use them to replicate issue:
1. FireFox browser - install fresh cart, install rusian language and enable it.
2. FireFox browser - go to store setting and set **Administration Language** setting to Русский
3. Chrome browser - clear all cache
4. Chrome browser - access admin page with http://*********/abc129_m11d28/index.php?s=youradminlink
5. First you will see that loaded login page in English
6. After login - Administration language is English but Content Language is Rusian. So Setting is not work

**Comment by BasaraABC** [comment]
Hello.
1. **All** browser cache cleared. 
2. Default input language in Chrome is english. There are no other languages

**Comment by abolabo** [comment]
setting works only if browser language not found in active cart languages. added help note
