### ISSUE TITLE
multilanguage support for store settings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#667]
I think these fileds should be multi-language 
<img width="900" alt="2016-09-09_15-20-50" src="https://cloud.githubusercontent.com/assets/2631910/18380427/7529c974-76a1-11e6-8a09-e58b0c9ca26f.png">

**Comment by BasaraABC** [comment]
Thank you. Issue is fixed. Can you please add AbanteCart default icon for multilanguage fields?
<img width="148" alt="2016-12-07_12-47-41" src="https://cloud.githubusercontent.com/assets/2631910/20956251/5fcaf9c0-bc7b-11e6-9b3f-2be6899a9f5a.png">

**Comment by abolabo** [comment]
sure. done.

**Comment by BasaraABC** [comment]
Can you please add this fields to the list of Load Missing data copy from source language.
