### ISSUE TITLE
Auto Update Currency issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#668]
When **Auto Update Currency** is On it change your base currency (all product prices currency) to the config_currency setting. 
When Auto Update Currency is Off the config_currency setting is work like default storefront currency to display.

**Comment by abantecart** [comment]
What is the issue exactly? I am not very clear with the comment. Thanks

**Comment by abantecart** [comment]
Let me clarify my understanding. 
There is no automatic recalculations or adjustments needed if base currency is changed. 

Base currency needs to be set to 1.00 of value and other currencies needs to be adjusted manually in respect to base currency. 
Prices will need to be adjusted if needed. 

User needs to take the following steps to adjust if base currency is changed:
1. Set default currency
2. Set this new base currency to be 1.00 
3. Update other currency values in respect to new default currency
4. Update prices if needed.

We can to add this to manual if we do not have this yet.

**Comment by BasaraABC** [comment]
Let me explain what problem we have
example 1:
1. User change default currency in the System > Settings > Store Setting
2. This will change default **Display** Currency in SF: prices not changed and base currency with value 1.000 Not changed
This looks logic for me.

example 2
1. User change default currency in the System > Settings > Store Setting
2. User enabled Auto Update currency (login/logout to apply)
3. In this case we have new base currency (Localization > Currencies) set according to the default currency in the System > Settings > Store Setting
This cause next problem:
A. Admin need to change all prices for all products
B. This also affect Multistore because we have only One Base currency in Localization > Currencies

**Comment by abolabo** [comment]
please review this new func https://github.com/abantecart/abantecart-src/commit/bd6886551d248577ad8ff5b6cf494af1b9742f66#diff-e6853fab26fae19f1977239862e22a4dR234

**Comment by BasaraABC** [comment]
Issue is not fixed right. If you have multistore and set for example EUR as base currency in second store it will be applied
<img width="543" alt="2016-12-06_14-41-29" src="https://cloud.githubusercontent.com/assets/2631910/20917101/1cb4ba68-bbc2-11e6-82fb-0cc60d6cf768.png">
How to replicate.
Default store: Auto update ON/ Base currency USD
Second Store: Auto update ON/ Base currency EUR
Select second store in any grid and logout/login

As discussed - only default store setting should work
