### ISSUE TITLE
High CPU usage in abantecart

### ISSUE THREAD

**Issue by adityaab** [abantecart/abantecart-src#67]
Hi! Did any one notice or I am the only one? 
I am using Abantecart for the past 8 months and had added around 1000 products but suddenly my host suspended my account stating High CPU usage. the best thing was I had taken a c-panel backup a few days back. 

 I immediately Changed hosts thinking he may be a sham. and got to hostinger.in made a fresh install and it had zero Products. When I returned after some time hostinger.in also had kicked me out http://www.hostinger.in/cpu_exceeded?aayurvedayoga.com Please help me.

**Comment by BasaraABC** [comment]
Hi. Please move discussion to AbanteCart forum http://forum.abantecart.com/
When create topic post your details - AbanteCart version, installed third party extensions, your have modified core files or not, template, cache enabled?... etc
