### ISSUE TITLE
i found deleteCategory issue in system files

### ISSUE THREAD

**Issue by ktdocker90** [abantecart/abantecart-src#671]
when delete category not unmap resource because i think your code is wrong.
File: admin/model/catalog/category.php

public function deleteCategory($category_id) {
	..
	foreach($resources as $r){
		//should replace 'products' with 'categories' to delete resource after delete category
		$rm->unmapResource(	'categories',	$category_id, $r['resource_id'] );
	}
}

**Comment by abolabo** [comment]
yes. you are right.
thank you!
