### ISSUE TITLE
administrator user password issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#672]
Issue visible for admin side only. If admin User change password to **MH,ep8Ea_@1SqGNvq4'** then on next login **No match Username/Password** occur

<img width="848" alt="2016-09-15_12-20-15" src="https://cloud.githubusercontent.com/assets/2631910/18539142/202ace9e-7b3f-11e6-91d9-f180fc6877db.png">

**Comment by BasaraABC** [comment]
Please fix ASAP and also this related issue #616

**Comment by abantecart** [comment]
This issue is fixed
