### ISSUE TITLE
Backup / Restore functionality is not working

### ISSUE THREAD

**Issue by ghost** [abantecart/abantecart-src#673]
Backup / Restore functionality under System -> Data is not working. Backup is getting stuck and giving errors.

**Comment by BasaraABC** [comment]
Hello. Thank you for attention but this tracker is for bug reporting so you need to provide some more details: AbanteCart version, error you get, the stage you stuck on, errors from AbanteCart log, server OS etc. Please also search abantecart forum and documentation
