### ISSUE TITLE
minimal password issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#676]
password like 123 give error "Password must be between 3 and 20 characters!"
valid for account create and change password form
<img width="854" alt="2016-09-19_18-00-08" src="https://cloud.githubusercontent.com/assets/2631910/18630095/695441a6-7e94-11e6-90be-bf9bc19aeb4f.png">

**Comment by abantecart** [comment]
We always had   3 < pass > 20. It needs to be 4 min. The message it incorrect. 

To add to this issue, should we tighten the password policy? 
Should we create a setting for password policy? 

Let's have a discussion for 1.2.9

**Comment by abolabo** [comment]
minimum 5 maximim 20

**Comment by BasaraABC** [comment]
Issue is not fixed in right way. I able to create account with 4 chars password (error message say min 5).
` `
For the new setting I think it can be simple On/Off. Lets name it Require Stronger Password.
When ON password require minimum 7 chars and at least one number and one letter (or in addition one upper case / lower case letters)

**Comment by abolabo** [comment]
oh..sorry.. of course 4 is minimal

**Comment by BasaraABC** [comment]
Issue fixed

**Comment by BasaraABC** [comment]
Also we need to do something with old registered passwords
