### ISSUE TITLE
setting up product options - no way to save Requirement ON

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#68]
When set Required field to ON and save it is still OFF. To see issue you need to reload page (F5) see screenshot
note: I am sure this issue was fixed during QA 1.2.0 
![optionsissue1](https://cloud.githubusercontent.com/assets/2631910/5935098/b6b6851c-a709-11e4-80e1-907ac176de1b.png)

**Comment by abolabo** [comment]
fix https://github.com/abantecart/abantecart-src/commit/0c28b5bd5975c05339e0aa6b087ac62b86cff736
