### ISSUE TITLE
"go back to the category" improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#684]
http://forum.abantecart.com/index.php/topic,5047.0/topicseen.html

> When working with an entire category it would be nice to go back to the category instead of having to repeat the whole process of choosing categor

**Comment by abantecart** [comment]
This is implemented on product and sales section. We can add more sections later

**Comment by BasaraABC** [comment]
Issue A: please reset filters on every new grid load
<img width="1143" alt="2016-12-07_16-49-03" src="https://cloud.githubusercontent.com/assets/2631910/20963353/9d4c58b0-bc9f-11e6-8b43-8a8c9458990c.png">

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
* Issue B: **Not** fixed
* New issues found please see video. Please enable annotations to see my comments https://www.youtube.com/watch?v=4_8RHpsfiPA

**Comment by abantecart** [comment]
Issue B Is happening only first time. I am looking

**Comment by abantecart** [comment]
Fixed both now.
