### ISSUE TITLE
Pay with Balance is showing negative amount even after logout

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#686]
Admin:
1. Navigate to sales -> customer -> Edit -> Transactions -> Add
2. Add 100 as a credit and click on Save

Storefront:
1. Login with username and password
2. Add one item of $19 to cart
3. Click on checkout

ORDER SUMMARY
1 x BeneFit Girl Meets Pearl
$19.00

Sub-Total:  $19.00
Flat Shipping Rate: $2.00
Total:  $21.00

Under Account Balance click on Pay with Balance

ORDER SUMMARY
1 x BeneFit Girl Meets Pearl
$19.00

Sub-Total:  $19.00
Flat Shipping Rate: $2.00
Account Balance:    -$21.00
Total:  $0.00

Now logout from Account

**After logout still its showing -$21.00**

SUB-TOTAL:  $0.00
ACCOUNT BALANCE:    -$21.00
TOTAL:  $0.00

**Comment by BasaraABC** [comment]
thank you @hb007006 for the detailed bug report. Issue confirmed

**Comment by abantecart** [comment]
This is fixed.
