### ISSUE TITLE
Pay with Balance Before coupon apply  issue

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#687]
Admin:
1. Navigate to sales -> customer -> Edit -> Transactions -> Add
2. Add 100 as a credit and click on Save
3. Navigate to Extensions -> Shipping -> default_flat_rate_shipping -> Edit
4. Cost 199 - save
5. Navigate to sales -> coupons -> coupon (free shipping) -> Edit 
4. status: on, discount: 0, total amount: 0, date end: 02/28/2017 - save

Storefront:
1. Login with username and password
2. Add one item of $19 to cart
3. click on checkout

ORDER SUMMARY
1 x BeneFit Girl Meets Pearl
$19.00

Sub-Total:  $19.00
Flat Shipping Rate: $199.00
Total:  $218.00
1. Click on Pay With Balance (Account Balance: $100.00)

Account Balance: $100.00 ($0.00)    $100.00 applied to order

ORDER SUMMARY
1 x BeneFit Girl Meets Pearl
$19.00

Sub-Total:  $19.00
Flat Shipping Rate: $199.00
Account Balance:    -$100.00
Total:  $118.00
1. Enter coupon code 3333
2. Click on Apply Coupon

Account Balance: $100.00 ($0.00)    $100.00 applied to order

ORDER SUMMARY
1 x BeneFit Girl Meets Pearl
$19.00

Sub-Total:  $19.00
Flat Shipping Rate: $199.00
Coupon (Free Shipping): -$199.00
Account Balance:    -$100.00
Total:  $0.00

**Issue no 1: Account Balance is showing as $0.00 however it should display $81.00**
~~Issue no 2: There is no option for removing coupon~~
~~Issue no 3: Cart is still showing -$81.00 even after logout~~

**Comment by BasaraABC** [comment]
Thank you for bug report. Let me show issue visually
<img width="993" alt="2016-10-07_13-04-59" src="https://cloud.githubusercontent.com/assets/2631910/19180390/90bb8098-8c8f-11e6-9b6f-204f38b29907.png">

For the
issue no 2: new feature request separated from this issue see #688 
issue no 3: you already report it see #686

**Comment by abantecart** [comment]
This issue is fixed. Now balance will be re-applied if coupon is applied. 

Thank you for clarification.

**Comment by BasaraABC** [comment]
Fixes not visible in fresh installation. Please see new screenshot
<img width="607" alt="2016-11-28_13-50-38" src="https://cloud.githubusercontent.com/assets/2631910/20658822/3c1db8ce-b572-11e6-820c-aae6217476b4.png">

**Comment by abolabo** [comment]
probably already fixed. Tried to replicate but unsuccessfully

**Comment by BasaraABC** [comment]
Issue is valid. Replicated easily in todays fresh 129

**Comment by abolabo** [comment]
tried on your installation for 30.11.16. cannot to replicate. Please provide details how to replicate. I used steps from first post.

**Comment by BasaraABC** [comment]
Steps to replicate (same as visible on screenshot)
1. Add any product with paid shipping and start checkout
2. Pay full amount with customer balance (Total: $0.00)
3. go to cart page and apply 3333 coupon (free shipping)
4. Bug: after coupon apply customer should not pay for the shipping so applied balance should be less than applied before
