### ISSUE TITLE
No way to remove coupon after apply

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#688]
Please add Remove Coupon feature after customer apply it to the shopping basket

**Comment by abantecart** [comment]
Ready for QA. Note. If error with applying new code, code removal button will be present. This is OK.

**Comment by BasaraABC** [comment]
Small usability issue: After coupon apply we have 'add coupon' button. I think it should be 'remove coupon' or 'edit coupon'
<img width="874" alt="2016-11-21_14-37-42" src="https://cloud.githubusercontent.com/assets/2631910/20474352/93ce4d1a-aff8-11e6-830d-46ca2bca3fb2.png">

**Comment by abantecart** [comment]
Fixed
