### ISSUE TITLE
Application doesn't logout even after closing browser

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#689]
Storefront:
1. Login with valid user and password
2. Leave your browser for half n hour **or** exit and reopen your browser
3. Its still showing Welcome back username
4. Also it allows to add/remove product in wishlist. May be some more functionality...

Expected behavior
1. After leaving your browser for 10-15 minutes application should log you out
2. After exiting browser application should log you out

**Comment by BasaraABC** [comment]
Hello. This is not an issue. This **Unauthenticated customer** feature behavior - after login session expired it saving basket and wishlist data. When customer try to see account details or checkout AbanteCart will ask for login again so your data is secured.
