### ISSUE TITLE
Back button is not working on Payment page

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#690]
Storefront
1. Login with valid user and password
2. Add product BeneFit Girl Meets Pearl $19.00 into cart
3. Click on view cart then click on checkout
4. It will take you to PAYMENT INFORMATION page
5. Click on Back button 

Issue: Back button is not working

**Comment by BasaraABC** [comment]
Can not replicate in default setup. Make sure your shipping have not Autoselect ON.

**Comment by abantecart** [comment]
Fixed
