### ISSUE TITLE
Error while guest checkout on fresh installation

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#691]
1. Install abantecart v1.2.8 on windows 7 (fresh installation including db creation with demo data)
2. Navigate to storefront
3. Add product BeneFit Girl Meets Pearl to your cart
4. Proceed with Guest checkout
5. Fill your details on GUEST CHECKOUT - STEP 1 and click on Continue
6. You will get below error

There has been a critical error processing your request

Error: Could not load model extension/default_flat_rate_shipping from C:\wamp\www\abantecart\core\engine\controller.php on line 286 in C:\wamp\www\abantecart\core\engine\loader.php on line 109

AbanteCart Troubleshooting Guide

Go to main page

2016-10-09 16:38:27 - load error:  AbanteCart core v.1.2.8 Error: Could not load model extension/default_flat_rate_shipping from C:\wamp\www\abantecart\core\engine\controller.php on line 286 in <b>C:\wamp\www\abantecart\core\engine\loader.php</b> on line <b>109</b>
2016-10-09 16:40:03 - load error:  AbanteCart core v.1.2.8 Error: Could not load model extension/default_flat_rate_shipping from C:\wamp\www\abantecart\core\engine\controller.php on line 286 in <b>C:\wamp\www\abantecart\core\engine\loader.php</b> on line <b>109</b>

This error come only with fresh installation.

To get rid of this error navigate to admin -> system -> cache -> Clear All Cache. Once you will clear cache above issue wont come

**Comment by abantecart** [comment]
Does not look like a reportable issue.
This looks like file is missing in your copy. 
Restore this file:
/extensions/default_flat_rate_shipping/storefront/model/extension/default_flat_rate_shipping.php

**Comment by hb007006** [comment]
You didn't get my point. The issue is coming only once on fresh installation. Application works fine when I perform clear cache from admin. This issue is still reproducible.

**Comment by abantecart** [comment]
How do you install on windows 7? What web server do you use? Is this Apache?

**Comment by hb007006** [comment]
I am using wamp latest version. I have checked, I do have this file with read and execute permission.
This error generally comes on fresh installation and it will come continuously util you perform clear cache. Once clear cache performed, this issue wont come again.

To get rid of this issue, you need to perform clear cache at least once.

**Comment by abantecart** [comment]
As we can not replicate this issue and this is something windows specific, I will as the question again. 
How do you install on windows 7? What web server do you use?

**Comment by hb007006** [comment]
I have used Wampserver 3.0.6 64 bit x64

– Wampserver 3.0.6 64 bit x64 – Apache 2.4.23 – PHP 5.6.25/7.0.10 – MySQL 5.7.14 – PhpMyAdmin 4.6.4 – Adminer 4.2.5 – PhpSysInfo 3.2.5
