### ISSUE TITLE
user group is not working correrctly

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#696]
1. Create a user group e.g. Power Users with Access and Modify permissions ON on below Controllers
	<br/>**36	sale/order_tabs	 ONOFF	 ONOFF
	<br/>37	sale/order_summary	 ONOFF	 ONOFF
	<br/>38	sale/order_history	 ONOFF	 ONOFF
	<br/>39	sale/order	 ONOFF	 ONOFF
	<br/>40	sale/invoice	 ONOFF	 ONOFF
	<br/>41	sale/customer_transaction	 ONOFF	 ONOFF
	<br/>42	sale/customer_group	 ONOFF	 ONOFF
	<br/>43	sale/customer	 ONOFF	 ONOFF
	<br/>44	sale/coupon	 ONOFF	 ONOFF
	<br/>45	sale/contact ONOFF	 ONOFF**
<br/>
2. All above controllers should be in ON status
3. Add a new user e.g. smanager and associate it with newly created group Power Users
4. Now Login with newly created user smanager
5. You will get an error "Permission Denied! You do not have permission to access this page, please refer to your system administrator." while accessing Orders, Customers, Customer Groups, Coupons, or Send Mail Under Sales menu on left pane. 
6. On every link in admin panel it says Permission Denied

Windows 7
Abantecart v1.2.8
WampServer Version 3.0.6 - 64bit
Apache Version: 2.4.23
PHP Version: 5.6.25

**Comment by BasaraABC** [comment]
I think you miss few permission common for the admin
http://docs.abantecart.com/pages/users/user_permissions.html

**Comment by hb007006** [comment]
I did not understand. I have given below permissions and it did not worked. Are there any common / mandatory permissions which should be assigned to every user group?
<br/>36 sale/order_tabs ONOFF ONOFF 
<br/>37 sale/order_summary ONOFF ONOFF 
<br/>38 sale/order_history ONOFF ONOFF 
<br/>39 sale/order ONOFF ONOFF 
<br/>40 sale/invoice ONOFF ONOFF 
<br/>41 sale/customer_transaction ONOFF ONOFF 
<br/>42 sale/customer_group ONOFF ONOFF 
<br/>43 sale/customer ONOFF ONOFF 
<br/>44 sale/coupon ONOFF ONOFF 
<br/>45 sale/contact ONOFF ONOFF

**Comment by BasaraABC** [comment]
Please move discussion to the forum.abantecart.com

**Comment by hb007006** [comment]
Are there any common / mandatory permissions which should be assigned to every user group?
If yes, then what are the common permissions?

**Comment by hb007006** [comment]
ok

**Comment by hb007006** [comment]
![1](https://cloud.githubusercontent.com/assets/22338790/19655520/e653c224-9a39-11e6-92ed-39f071e2e9ec.png)
![2](https://cloud.githubusercontent.com/assets/22338790/19655523/e80be29a-9a39-11e6-8773-75838c432f32.png)
