### ISSUE TITLE
payments with CC validation

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#697]
we need to retest all payment ext that support CC processing

**Comment by BasaraABC** [comment]
Issues found with test number from list https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm
cards which marked as not valid:
Australian BankCard 5610591081018250
Dankort (PBS) 76009244561

**Comment by abantecart** [comment]
We base number validation based on 
https://en.wikipedia.org/wiki/Payment_card_number
Or
http://formvalidation.io/validators/creditCard/

I think we cover all of them. 

Australian BankCard is not active

**Comment by BasaraABC** [comment]
According to the list you provide http://formvalidation.io/validators/creditCard/ we do not support
Solo: 6334580500000000
but in wiki page Solo card marked as inactive https://en.wikipedia.org/wiki/Payment_card_number 
Issue closed
