### ISSUE TITLE
new browser tab without any css

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#698]
Admin front
1. Navigate to System -> Settings -> All Settings
2. Type 'config_shipping_tax_estimate' in Key input field and press enter
3. Click on Edit Action

**It will open a new browser tab without any css. And no action is getting performed for 'config_shipping_tax_estimate'**

Windows 7
Abantecart v1.2.8
WampServer Version 3.0.6 - 64bit
Apache Version: 2.4.23
PHP Version: 5.6.25

**Comment by hb007006** [comment]
![1](https://cloud.githubusercontent.com/assets/22338790/19655538/fe14d1aa-9a39-11e6-9c27-6b62c526834c.png)
![2](https://cloud.githubusercontent.com/assets/22338790/19655540/ff8e81ca-9a39-11e6-80d9-07c92fbe92bb.png)

**Comment by BasaraABC** [comment]
@hb007006  thank you for report.
@abolabo related bugs in this section were fixed before for example #450 .
