### ISSUE TITLE
Better handling for Free shipping set in the product  ISSUES

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#70]
issues for commit https://github.com/abantecart/abantecart-src/commit/97b7f3a0b999efcda8a4c857888358a71e753caa
'Free' text not shown for next shipping extensions:
1. Parcelforce 48 - shipping ignore this setting absolutely
2. Flat shipping rate - setting work but 'Free' text <b>not</b> shown
3. Weight Based Shipping - shipping method not available for product with Free Shipping setting On
4. Royal Mail - ignore Free shipping setting absolutely
5. Price based shipping -  ignore Free shipping setting absolutely
6. UPS, USPS, FEDEX - waiting for fix according to author commit (please fix them too)

**Comment by abantecart** [comment]
Fixed 1, 2 and 3. 

Dima, please check 4 and 6

as for 5. This is not AbanteCart shipping. Please, report it to extension developer

**Comment by abantecart** [comment]
FYI. New method "areAllFreeShipping()" added to Acart class. 

	/**
	 * Check if all products are free shipping 
	 * @return bool
	 */
	public function areAllFreeShipping() {

**Comment by BasaraABC** [comment]
@abantecart <<Fixed 1, 2 and 3.
Parcelforce 48 shown correctly Free on shipping selection page but paid in total see screenshot :scream:
![freeshipping-bug](https://cloud.githubusercontent.com/assets/2631910/6017740/7628857c-abc3-11e4-9e51-5eb2c4fe0e98.png)

**Comment by abantecart** [comment]
Parcelforce 48 is fixed. 

Dima please work on 4 and 6

**Comment by abolabo** [comment]
Royal mail changed. 
USPS changed earlier.
UPS can not to fix because of unable to get access key from ups. 
FEDEX looks like can process products with fixed price shipping

**Comment by BasaraABC** [comment]
<b>issue1:</b> Parcelforce 48 - bug with Fixed Shipping Price (now it summarize Fixed Shipping Price + Parceforce rate)
<b>issue 2:</b> Royal Mail - when Free Shipping enabled for product - royal mail not available
<b>issue 3:</b> Royal Mail - when Fixed shipping price enabled estimated box not work (shipping can not be added to Order Summary box) and Error: Shipping method required! show if select this shipping when checkout
<b>issue 4:</b> USPS - when Fixed shipping price enabled estimated box not work (shipping can not be added to Order Summary box) and Error: Shipping method required! show if select this shipping when checkout
<b>issue 5:</b> USPS - problem with Free shipping enabled - USPS return selected shipping rate for free shipping even if it is not available (let me explain - if Free shipping OFF the USPS return method1 and method2 available for current product shipping but if Free Shipping ON for this product then USPS return method3 selected in USPS settings as Free shipping method - this is wrong, USPS method3 is not available for this product. We can discuss this.)
<b>issue 6:</b> if set Fixed Shipping Price in product then FEDEX not available

**Comment by BasaraABC** [comment]
checking fixes from last post (see above)
issues 2,3,4 - fixed
issue 5 - discussed with abolabo - skipped for now

**Comment by abolabo** [comment]
no chance to check Fedex. Both credentials (from our sandbox-doc and new requested) does not works.

**Comment by BasaraABC** [comment]
* UPS (after fixes) - Fixed Shipping Price not work, like Parcelforce 48 it summarize Fixed Shipping price and regular rate from shippping. Please fix both UPS and Parcelforce
* About Fedex - fedex reset account please see updated info in sandbox doc (they work I checked)

**Comment by abolabo** [comment]
Note: have no idea for case when customer did not set his post code (fedex stops to work).

**Comment by abantecart** [comment]
If zip code is missing, need to show message to customer and not allow to use shipping

**Comment by BasaraABC** [comment]
Note: zip code is <b>required</b> field on new user registration and Guest checkout.
Anyway issue reopened due next issue:
<b>Ship Product Individually issue:</b> If only one product in shopping cart with Ship Product Individually enabled - shipping method show incorrect rates see screenshot. (I think all shipping affected - issue checked with Fedex, Parcelforce48, UPS...)
![fedex](https://cloud.githubusercontent.com/assets/2631910/6243053/c2903e6e-b76c-11e4-8003-f99ba4c3363e.png)

---------------------------------------------------------

**Comment by abolabo** [comment]
1. fedex and other shipping extensions that works by "server-server" approach DO NOT ALLOW individual shipping without fixed shipping price. We talked about it. We can not to afford do loop connections for each product in the cart. It will stuck web-server.
2. i added check for empty post code. Now will show message about in on checkout/shipping page

**Comment by BasaraABC** [comment]
abolabo write: << <em>fedex and other shipping extensions that works by "server-server" approach DO NOT ALLOW individual shipping without fixed shipping price. We talked about it. We can not to afford do loop connections for each product in the cart. It will stuck web-server.</em>

1. Issue related to ALL shipping not only fedex (I check Parcelforce48, UPS.. etc - Parcelforce is not server-server)
2. In case shipping can not support <em>Ship Product Individually</em> setting - <b>DO NOT show FREE</b> - Please calculate shipping rates (see screenshot above - Free Shipping is OFF but shipping return Free if <em>Ship Product Individually</em> enabled) (Merchant lose money!)

**Comment by abantecart** [comment]
This is not issue. Settings are incorrect. 

1. Shipping individually is using fixed shipping price setting. 
2. Fixed shipping price setting set to 0.0. 
this is a reason for free shipping options shown. 

Help tip will be updated.

**Comment by abolabo** [comment]
done
