### ISSUE TITLE
extensions run order

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#700]
Bug with template override with multiple extensions.
 Run order does not work
 looks like it needs to be higher run order number to be more important

**Comment by abantecart** [comment]
To clarify. 

Run order setting in admin is not to control priority of templates or controllers to load. 
Correct way to control this using programmatic value in config.xml "priority"

This is not a bug, but we need to update a dev manual.

**Comment by BasaraABC** [comment]
Can not find the way to check this. Please add test case where this can be checked

**Comment by abantecart** [comment]
No need to test. Just mark that we need to update the manual
