### ISSUE TITLE
embed and 3rd party templates issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#702]
It is not logical to include data-css in embed
data-css-url="http://website/storefront/view/my_template/stylesheet/embed.css" 

Note: firebug report missed css file if you have non default template

**Comment by abantecart** [comment]
Comments to this issue:
This can not be solved on the admin side, as storefront template can change at any time. 

Proposed solutions:
1. Auto detect css file in r/embed/js 
Issue with multi-store usage. If different templates used on different stores, embedded element will look different on the same page. 
Need to keep support for data-css-url attribute to allow custom approach. 

2. Include only default template embed.css. 
data-css-url attribute can be manually changed. 
CSS always can be controlled by parent page that has embed codes.

**Comment by abantecart** [comment]
I like solution 2

**Comment by abolabo** [comment]
added check for existing of css of current template. If not present - use default

**Comment by BasaraABC** [comment]
@abantecart please review.

**Comment by BasaraABC** [comment]
I think we can close it.
