### ISSUE TITLE
tasks: backup - warning in the log

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#704]
Warnings in the error log after backup task completed
`warning: AbanteCart core v.1.2.9 Cannot modify header information - headers already sent by (output started at /htdocs/abc129_m11d14/task.php:148) in <b>//htdocs/abc129_m11d14/task.php</b> on line <b>154</b>`

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue is Not fixed and visible in fresh install
