### ISSUE TITLE
tasks: backup steps counter

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#705]
Steps counter not reset after new task run
<img width="1391" alt="2016-11-14_15-47-31" src="https://cloud.githubusercontent.com/assets/2631910/20258962/d177a2a2-aa84-11e6-9eb4-91ed6d45afb5.png">

**Comment by abolabo** [comment]
bad idea. this counter from database. Need to be equal for debugging

**Comment by abantecart** [comment]
What is bad idea? Steps count should start from 1. Why do we need to know database ID? 
If you want to show database id it should look like this:

Step #1 (step_id: 11)
Step #2 (step_id: 12)
...

**Comment by abolabo** [comment]
There are already presents direct numerations
 "Step 1: Success". 
Look at picture!

**Comment by abantecart** [comment]
If sequential count is there, why it does not start from 1 ?

**Comment by abolabo** [comment]
duplicate of #705
