### ISSUE TITLE
restore field width

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#708]
Restore field is too large in System > Data > Backup/Restore page
<img width="928" alt="2016-11-14_16-59-33" src="https://cloud.githubusercontent.com/assets/2631910/20260388/ff5ffbea-aa8b-11e6-8ace-5c0854423935.png">

**Comment by abolabo** [comment]
how to replicate this? OS? screen width? browser? etc...

**Comment by BasaraABC** [comment]
Firefox browser OS X, Screen width about 1200 px
