### ISSUE TITLE
backup custom files and folders

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#709]
Issue A: custom files included in backup but Not included in the size calculation
Issue B: custom folders not included in the backup
<img width="1097" alt="2016-11-14_17-18-24" src="https://cloud.githubusercontent.com/assets/2631910/20261250/96300e04-aa8f-11e6-8cf1-cc5facc897c7.png">

**Comment by BasaraABC** [comment]
@abantecart : Nothing should be missing in backup. 
Size calculation can be approximate. It should say (Approximately Xxmb)

**Comment by BasaraABC** [comment]
Issue B is not fixed. Please note bug visible only if you **Compress backup**

**Comment by abolabo** [comment]
cannot to replicate issue B. Created folder with name dddd, pasted file into it. Did backup with compression. Checked tar.gz - folder there.

**Comment by BasaraABC** [comment]
Please check on dev server. See screenshot fresh installation
<img width="735" alt="2016-11-25_14-31-10" src="https://cloud.githubusercontent.com/assets/2631910/20619512/85a21ea6-b327-11e6-8f83-1f849eaf8b37.png">

**Comment by abolabo** [comment]
fixed
