### ISSUE TITLE
tasks: Load Missing language data - incorrect status

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#712]
When all translations (Google Translate API) are fail the 'success' status shown in task details
<img width="1417" alt="2016-11-14_18-23-25" src="https://cloud.githubusercontent.com/assets/2631910/20263949/aa5946c8-aa9b-11e6-8bbd-aacaabf0afe7.png">

**Comment by abolabo** [comment]
fixed. Note: now driver of translater respond message that translation for table was skipped, but step execution result is successful.

**Comment by BasaraABC** [comment]
Thank you. In my opinion task details text still disappoints users. Please looks at my view. _We can discuss with all team._
I suggest next changes:
1. add 'execution'. To explain that 'success' status is for step execution, not for transaltion
2. rename Step to 'step id'
3. remove 'Ok'. It is not clear what is ok. Just show result text see screenshot
<img width="1281" alt="2016-11-23_15-06-42" src="https://cloud.githubusercontent.com/assets/2631910/20555064/6f7576b4-b192-11e6-9db8-c1c7acd2c0d0.png">

**Comment by abantecart** [comment]
I have updated the text to be more clear.
