### ISSUE TITLE
Cache issues with installed extensions on fresh Abantecart installation

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#713]
1. download abantecart-src-master-1.2.8
2. Install fresh Abantecart 1.2.8. Use fresh empty DB
3. Login into Admin and Navigate to Extensions -> All Extensions
4. Click twice on Status to sort extension data. It will show you installed extensions first.
5. It will show you 3 extensions installed i.e. banner_manager, neowize_insights, forms_manager
6. Navigate to System -> Cache and Clear All Cache
7. Navigate again to Extensions -> All Extensions
8. Click twice on Status to sort extension data. It will show you installed extensions first.
9. Now it will show you 5 extensions installed i.e. banner_manager, neowize_insights, forms_manager, default_cod, default_flat_rate_shipping

Evidences attached for your reference. 
![1](https://cloud.githubusercontent.com/assets/22338790/20271128/c357341e-aaaf-11e6-8a28-f2ffd1e89419.png)
![2](https://cloud.githubusercontent.com/assets/22338790/20271135/ca65c838-aaaf-11e6-95c4-30a28b8e6a31.png)
![3](https://cloud.githubusercontent.com/assets/22338790/20271138/ccee3482-aaaf-11e6-8ba7-6cb9de87dc17.png)
![4](https://cloud.githubusercontent.com/assets/22338790/20271140/cef378a0-aaaf-11e6-994d-d35622f7fdb2.png)

You can link this issue with #691

[Environment]
Windows 7
Browser Chrome
Wampserver 3.0.6 64 bit x64 – Apache 2.4.23 – PHP 5.6.25/7.0.10 – MySQL 5.7.14 – PhpMyAdmin 4.6.4 – Adminer 4.2.5 – PhpSysInfo 3.2.5

**Comment by BasaraABC** [comment]
Issue confirmed. Some problem with cache in fresh AbanteCart installation
