### ISSUE TITLE
handling fee require logic redesign

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#714]
We have many reports that Handling Fee buggy and hard to understand how it works. We need to redesign it.
http://forum.abantecart.com/index.php/topic,682.0/prev_next,prev.html#new

**Comment by BasaraABC** [comment]
Please fix ASAP

**Comment by abantecart** [comment]
I have added a clarification text to fee handling.

**Comment by abantecart** [comment]
We can consider adding shipping to handling fee as discussed.
