### ISSUE TITLE
Account -> Notifications UI issue

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#718]
[Admin]
1. Install default_textmarketer extension from Admin
2. Navigate to System -> Settings -> IM and and choose SMS Provider as TextMarketer, make it ON for Storefront and click on Save

[Storefront]
1. Register a new user and provide Mobile Phone (SMS Notification) for SMS notifications
2. Login in Storefront with newly created user
3. Navigate to My Account -> Notifications and enable SMS checkboxes for Order Update  and Account Update 
4. Navigate to My Account -> Edit account details and remove Mobile Phone (SMS Notification) field
5. Navigate to My Account -> Notifications. You will see message "SMS notifications are not possible. Mobile number is not saved in your account records." and also SMS column will be disabled

However still SMS checkboxes for Order Update  and Account Update  will get displayed as checked. 

If a user is removing mobile number (for sms notification) from his/her profile. SMS checkboxes should be displayed as unchecked under My Account -> Notifications screen
If a user is adding mobile number (for sms notification) from his/her profile. Original sms settings whatever user was having earlier should get displayed under My Account -> Notifications screen

**Comment by BasaraABC** [comment]
In my opinion this is not an issue. Lets see what others think about

**Comment by hb007006** [comment]
![1](https://cloud.githubusercontent.com/assets/22338790/20351395/a9aa91de-ac38-11e6-87a5-c51c135c979a.png)
![2](https://cloud.githubusercontent.com/assets/22338790/20351398/abc4374a-ac38-11e6-8996-0fa9e09e5324.png)
![3](https://cloud.githubusercontent.com/assets/22338790/20351401/afa82128-ac38-11e6-9174-81fa93c409ed.png)
![4](https://cloud.githubusercontent.com/assets/22338790/20351414/bc01b70e-ac38-11e6-990f-1e067d252a5c.png)
![5](https://cloud.githubusercontent.com/assets/22338790/20351422/c36b304c-ac38-11e6-8e36-fbabe476b979.png)
![6](https://cloud.githubusercontent.com/assets/22338790/20351426/c97bd374-ac38-11e6-9784-2012da3dd14d.png)
![7](https://cloud.githubusercontent.com/assets/22338790/20351480/fc765c40-ac38-11e6-811c-2b0860d2ff9b.png)
![8](https://cloud.githubusercontent.com/assets/22338790/20351490/039ff620-ac39-11e6-953c-88b8ad02b872.png)

**Comment by BasaraABC** [comment]
Let me explain my view. If customer remove mobile this does not mean we should remove/hide his IM notification settings. Where did you see a problem?

**Comment by hb007006** [comment]
If you look at End customer's perspective then it seems its misleading as SMS checkboxes are still checked.

**Comment by abantecart** [comment]
I think, we should not change or remove settings for SMS if customer removes phone number. 

If phone is missing, we could hide customer settings for SMS completely and remove red message. 
If customer puts phone number back, settings will show back as before. 

Any other thoughts?

**Comment by BasaraABC** [comment]
I am not agree. If phone is missing and we remove red message how customer know about SMS feature? In my opinion now it work as it should. No phone in customer account - all SMS setting become inactive and red message about missing phone.

**Comment by hb007006** [comment]
I agree, we should not change or remove settings for SMS if customer removes phone number.

If phone is missing, we could **hide customer settings for SMS completely** and but **we should show red message**.
If customer puts phone number back, settings will show back as before.
