### ISSUE TITLE
Minor align issue with subcategories

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#72]
original post http://forum.abantecart.com/index.php/topic,3238.msg13856.html#msg13856
![issue-align](https://cloud.githubusercontent.com/assets/2631910/6036076/de2b3d6e-ac71-11e4-9d2c-a180717dfc97.png)

see issue in FF, Chrome http://dev06.***********/abc121_m02d02freeshipping/index.php?rt=product/category&path=36&sort=pd.name-ASC&limit=20

**Comment by abantecart** [comment]
I need help matching this issue. I tried may possible sort order and settings. For me categories always align correctly. (tried 3 browsers, FF, Chrome and Safari)

**Comment by BasaraABC** [comment]
I think problem in long subcategory names in 1 row see screenshot above. Also check this link issue visible for me http://dev06.***********/abc121_m02d02freeshipping/index.php?rt=product/category&path=36&sort=pd.name-ASC&limit=20

**Comment by BasaraABC** [comment]
One more report from user http://forum.abantecart.com/index.php/topic,3247.0/topicseen.html

**Comment by abantecart** [comment]
This is one is fixed
https://github.com/abantecart/abantecart-src/commit/ce9156501cdadd7446928bd7ef356325f4ecca28
