### ISSUE TITLE
interrupted task issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#720]
For example during Backup task in process user close accidently browser. 
Currently we have this task in the Scheduled tasks section (System > Logs) - this seems to be right but got next issues:
1. This task kill any previous interrupted backup tasks (we can discuss maybe not an issue)
2. Status of the task is Disabled - this is wrong it was not disabled but _interrupted_
3. No way to remove scheduled task or run it manually (missing buttons)
<img width="983" alt="2016-11-16_14-36-07" src="https://cloud.githubusercontent.com/assets/2631910/20338503/111b3dca-ac0a-11e6-9f8c-161380f2ef1b.png">

**Comment by abolabo** [comment]
probably related to new incomplete status of tasks that we added in 1.2.9. I fixed it in #724.
Please recheck
