### ISSUE TITLE
2checkout order Incomplete

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#721]
Order placed but status is Incomplete 
Note: INS (callback url) and Success page url are set correctly in the 2Checkout sandbox account.
<img width="973" alt="2016-11-18_20-40-13" src="https://cloud.githubusercontent.com/assets/2631910/20432200/a1f81aa8-add0-11e6-96b6-34a246a10e55.png">

**Comment by abolabo** [comment]
not a bug. Please note that return url set in your 2co account. You tried to test on some instance Abc, but redirect goes to another place.

**Comment by BasaraABC** [comment]
Thank you for your comment but you miss note in initial post. I set callback and Success page url in the 2CO account.

**Comment by abolabo** [comment]
not a bug. Issue related to INS call in sandbox mode. To use INS just set demo-setting to Off on this page https://sandbox.2checkout.com/sandbox/acct/detail_company_info

**Comment by BasaraABC** [comment]
Thank you. Now it start work
