### ISSUE TITLE
Newsletter notification while customer registration

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#725]
Abantecart v1.2.8

Storefront:
1. Select radio button Yes for Subscribe Newsletter while registering a new customer.
2. Navigate to My Account -> Notification. Still you will see Newsletter notifications are unchecked.

**Comment by BasaraABC** [comment]
Hello. We check in 1.2.8 demo ( http://demo.abantecart.com ) and 1.2.9 and can not replicate issue.
