### ISSUE TITLE
incorrect product thumbnail url in api call

### ISSUE THREAD

**Issue by ravdeepsingh22** [abantecart/abantecart-src#729]
In api call for product details 
In thumbnail the image url is given in the format as mentioned below
http: is missing from url 

//evilengineerlabs.com/android2/public_html/image/thumbnails/18/76/Fiorella_Purple_Peep_Toes_2_jpg-100206-380x380.jpg

**Comment by abantecart** [comment]
@ravdeepsingh22 can you please provide more explanation. It is not very clear what is incorrect. URL that you have posted is working and looks correct to me. 

I checked API call for product details on 1.2.9 and I get working URL
