### ISSUE TITLE
SMS Notify not working for guest customers

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#732]
Abantecart v1.2.8

[Admin front]

Sales -> Orders -> Status & Comments

Notify Customer functionality is not working for guest customers

**Comment by BasaraABC** [comment]
Make sure when you add comment the Notify Customer is ON

**Comment by hb007006** [comment]
How this defect can be marked as closed?

Notify Customer is ON and working perfectly fine for abantecart customers. **But it is not working for Guest's.**

**Comment by hb007006** [comment]
Please reopen this defect. 

Steps to reproduce
1. do not register yourself as a customer
2. Checkout cart as a Guest
3. Now navigate to Sales -> Orders -> Status & Comments and click on Notify customer. It will show ON status. But SMS notification will not work. Because in Order.php there is check on Customer Id and in case of guest customer id will be 0

**Comment by BasaraABC** [comment]
Hello. You should mention about SMS in initial report. By default SMS is disabled.  What is your SMS provider?

**Comment by BasaraABC** [comment]
check this post https://github.com/abantecart/abantecart-src/issues/637#issuecomment-237803259

**Comment by hb007006** [comment]
Yes, that's my mistake. I have not mentioned about SMS notification.

**Comment by BasaraABC** [comment]
Thank you. This issue is known and in our to-do list.

**Comment by hb007006** [comment]
Ok
