### ISSUE TITLE
Admin - No provision to send Email or SMS to Guest customers

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#733]
We can send Email or SMS to registered customers using Send Email (Sales -> Send Email) functionality. However there is no provision to send Email or SMS to Guest customers

**Comment by hb007006** [comment]
![1](https://cloud.githubusercontent.com/assets/22338790/20802247/7e801026-b811-11e6-89d2-be8bb32f70ba.png)

**Comment by abolabo** [comment]
this issue related to https://github.com/abantecart/abantecart-src/issues/346
just added fix to send IM-notification via sale->orders->history->notify customer

**Comment by hb007006** [comment]
Abantecart already have provision to enter customer name or product name. but there is no support to enter phone number or email address.
Can't we give provision to enter phone number or email address?

Lets say more than 10 customers ordered same products then it will be difficult to decide to whom we need to send email or sms.

**Comment by BasaraABC** [comment]
Guest are not registered customers so you can contact them in via 'Customers who ordered selected products' selection

**Comment by hb007006** [comment]
I do agree with you. But if I would like to send SMS/Email to particular guest regarding his/her recent order, I can't do that. Lets take an example

More than 03 guest customers (Guest James, Guest John and Guest Paul) ordered same products. Now I would like to send SMS and email to Guest James regarding his recent order. Using 'Customers who ordered selected products' I can send sms and email to Guests. However how I will identify Guest James. I did not find any way.

To achieve this, we can give provision to enter phone number (for sms) and email address (for email) for Guest customers.

**Comment by BasaraABC** [comment]
You have an option to disable Guest checkout to force customers create accounts record. 
In my opinion main idea of Guest customers - they _do not want_ to create account and have records in your store or receive anything from you except what they purchased.

**Comment by hb007006** [comment]
This functionality / feature becomes important when Guest Checkout is Enabled and Guest provides his mobile number for SMS notification and email for Email notification.

**Comment by goatlady102** [comment]
I concur with Basara -  the guest check requires an email address for the order.   If customer wanted to receive additional marketing info from you they would make an account.  If you need to contact a customer due to a faulty product or and order issue  the email address is associated with the order. 
In some countries now it is illegal to contact a customer for marketing purposes if they don't signup, and store violators are subject to punitive (monetary) consequences.
