### ISSUE TITLE
No provision to put prefix for Order Id

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#734]
Abantecart v1.2.8

In abantecart, prefix with invoice is allowed. However abantecart doesn't have provision to put prefix along with order id e.g. YDFO-12762871-130701

Most of the carts provides this feature

**Comment by abantecart** [comment]
Order ID is unique in the system. How do you see this working?

**Comment by hb007006** [comment]
I agree, order id is unique in the system. 
But there should be provision in the system to put prefix along with order id as most of the carts provides this feature

There could be multiple ways to implement this. One of the approach could be
YDFO-12762871-11, here 11 is order id and YDFO-12762871- is order fix. May be you can have two columns in DB one for order id (already existing) and another for order prefix (new).

**Comment by abantecart** [comment]
Order ID can not be  alphanumeric unless it is a new field. Why Invoice ID does not work? It generates as unique and Invoice prefix can start with anything custom.

**Comment by hb007006** [comment]
Most of the carts provide this feature. They support order id and invoice id both alpha numeric.
Invoice id comes in picture only when order gets completed.
