### ISSUE TITLE
Sales > Send SMS: incorrect warning message

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#735]
Warning is incorrect. If no customers how it "will be sent to 2 customers"
How to replicate: install latest 1.2.9 with demo data and create one Guest order with mobile number
<img width="819" alt="2016-12-06_15-33-05" src="https://cloud.githubusercontent.com/assets/2631910/20918470/c963b456-bbc9-11e6-8eee-7bd3d534e5dd.png">

**Comment by abolabo** [comment]
top message not needed there.  there ajax-request for recipient count message. Also sql-request for total count of guest orders with mobile-phones will works slow.
