### ISSUE TITLE
Load missing data: dynamic data not copied

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#739]
I check it twice with Spanish language. Install it and copy from English with _Load missing data_ tool. All product have empty spanish descriptions,names etc... a lot of other areas also affected.
In addition step description say "**Translation** skipped" - should be **copy** only there is no installed Google translate API 
<img width="756" alt="2016-12-07_12-55-50" src="https://cloud.githubusercontent.com/assets/2631910/20956670/f2337420-bc7d-11e6-9147-f5eee963b9c7.png">

**Comment by abolabo** [comment]
fixed. Plus found old bug. Description counts was not equal.

**Comment by BasaraABC** [comment]
Cart is crashed. To replicate run Load missing data and visit product at SF
<img width="850" alt="2016-12-08_13-21-54" src="https://cloud.githubusercontent.com/assets/2631910/20999749/6bf66076-bd49-11e6-829d-8feda400f52d.png">
