### ISSUE TITLE
Scenario (No response from payment gateway) is not handled

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#741]
Scenario:
Step 1: Customer selects one of the payment gateway (e.g. paypoint) while checkout process and click on “Confirm” button.
Step 2: The customer is then taken from Abantecart to the transaction page of paypoint where in all the payment related details are entered by the customer
Step 3: Paypoint redirects the customer to Visa, MasterCard or the relevant bank for the next level of authorization.
Step 4: The Bank/Visa/MasterCard authorizes and confirms the transaction.
Step 5: Payment has been deducted and customer is sent back to Paypoint.
Step 6: Due to any technical or network issue, Paypoint is not able to send the consumer back to Abantecart.

As per Abanatecart code, response will always come back in callback method from Payment Gateway website. However as explained above, in Step 6, response will never come. This scenario is not handled in Abantecart.  

Resolution of Step 6 could be:
Generally payment gateway provides the API's to check the transaction status. That could be implemented in Abantecart. This is just a suggestion. I may be wrong. There could be better ways.

**Comment by BasaraABC** [comment]
Try to check for Return/Success url in Paypaint account

**Comment by hb007006** [comment]
We may use Paypoint API to check for Response/Return/Success url in Paypoint account. We can do it manually. But don't you think it should be handled through code itself.

Lets take an example. Suppose the response didn't come to Abantecart due to some technical or network issue. In this case put order status on hold and Abantecart should call Paypoint API from the code itself may be after 5 minutes or 10 minutes and process customer order accordingly. 

 I am just giving a suggestion. There could be better way to handle this. This is not about Paypoint. It can relate to all Payment Gateways.

**Comment by BasaraABC** [comment]
Thank you but I think suggestions and discussion should be moved to AbanteCart forum http://forum.abantecart.com/

**Comment by hb007006** [comment]
Suggestion was for resolving this defect. However if you will see then this particular scenario is not handled so it should be treated as bug.

**Comment by hb007006** [comment]
Please re-open this defect. As you can see this particular scenario is not handled so it should be treated as defect.
