### ISSUE TITLE
Override if source language text was changed and HTML field

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#743]
If you have **Override if source language text was changed** settings On then Not changed field with HTML editor replace child language. You can see issue on product description, store welcome text and other fields with HTML editor.
To replicate:
1. install 2 languages (for ex English and Spanish)
2. Enable **Override if source language text was changed** in store setting and set English as source language
3. Open any product in English, do not change anything and hint bottom SAVE.
Bug: when you switch to spanish - product description replaced with english version

**Comment by abolabo** [comment]
not a bug!. all correct. 
Please read help hint: 
If set, text in all languages will be replaced with new translation if source language text is edited. NOTE: Can cause many translations.

**Comment by BasaraABC** [comment]
Dear @abolabo . Please let me clear this issue. Nothing were changed! So it should not replace child language.

**Comment by abolabo** [comment]
dear @BasaraABC . It's a very special case related to store settings.

**Comment by BasaraABC** [comment]
Unfortunately issue is not resolved. Product description for child language still replaced even if you **did not** change it in source language

**Comment by abolabo** [comment]
cannot to understand how it it. 
i tried to
 - install second language
 - go on any product page and changed description for english language.
- switch content language to spanish and check - spanish variant without  changes

**Comment by BasaraABC** [comment]
It is very easy to replicate please see video tutorial
https://youtu.be/q4yE-ws7h7w

**Comment by abolabo** [comment]
not a bug
