### ISSUE TITLE
submit lock button

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#745]
Please reset submit lock. For example you can not resend Review in case of typo or error.
Issue visible in Chrome, FF in normal and embed modes
<img width="998" alt="2016-12-08_15-58-25" src="https://cloud.githubusercontent.com/assets/2631910/21003736/9065d746-bd5f-11e6-9560-de0a18ff9e17.png">

**Comment by BasaraABC** [comment]
Issue reopened. @abantecart  and me can replicate it

**Comment by abantecart** [comment]
Where was no commit, why it is marked fixed?

**Comment by abantecart** [comment]
Issue is resolved. If other extension use this page, they will need to be updated.
