### ISSUE TITLE
Dashboard: incorrect approval count

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#746]
All customers are approved (1 subscriber) but dashboard display that 1 require approval.
<img width="1262" alt="2016-12-09_14-59-30" src="https://cloud.githubusercontent.com/assets/2631910/21041871/8017e322-be20-11e6-9962-fa91810b5532.png">

**Comment by abolabo** [comment]
changed text

**Comment by BasaraABC** [comment]
it is not a solution because for some reason (you work on this before) all active Newsletter subscribers accounts have status OFF.
