### ISSUE TITLE
Visual editor remove code

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#747]
No way to add styles into HTML block. If select Visual editor  - part of entered code was removed.
ALso issues with inline javascript
`<script type="text/javascript">
document.getElementById('click_me').addEventListener("click", function(event) {
    (function(event) {
        alert(this);
    }).call(document.getElementById('click_me'), event);
});
</script>`

become 
`<script type="text/javascript">// <![CDATA[
n-->document.getElementById('click_me').addEventListener("click", function(event) {
    (function(event) {
        alert(this);
    }).call(document.getElementById('click_me'), event);
});<!--n
// ]]></script>`

Can we improve this?
<img width="843" alt="2016-12-09_15-47-40" src="https://cloud.githubusercontent.com/assets/2631910/21042973/39b30892-be27-11e6-9ae9-ffde1b20b9bf.png">

**Comment by abantecart** [comment]
We need to add ignore to formatting <style> <script> tags to visual editor

**Comment by BasaraABC** [comment]
I am sorry but issue is not fixed.

**Comment by abolabo** [comment]
give me more details. Text as example, screenshots etc...

**Comment by BasaraABC** [comment]
Yes issue is fixed. It was cart autoinstall problem.
