### ISSUE TITLE
Mobile Phone (SMS Notification) issue with Guest Checkout

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#751]
Mobile Phone (SMS Notification) issue with Guest Checkout

1. Add products into cart
2. Use guest checkout and fill all the mandatory details along with Mobile Phone (SMS Notification) i.e. 201555555
3. Select payment method as paypoint or any payment gateway

As per my business need, I am using $this->im->getCustomerURI('sms', (int)$order_info['customer_id'], $orderid) in one of the payment gateway to retrieve Mobile Phone (SMS Notification)

4. $this->im->getCustomerURI('sms', (int)$order_info['customer_id'], $orderid) will return Mobile Phone (SMS Notification) entered by customer i.e. 201555555

Perfectly fine this this point

5. Do not confirm the order
6. Again click on checkout from cart and use guest checkout
7. You will find mandatory and optional data is already filled apart from Mobile Phone (SMS Notification)
8. Mobile Phone (SMS Notification) will come as empty
9. Still $this->im->getCustomerURI('sms', (int)$order_info['customer_id'], $orderid) will return Mobile Phone (SMS Notification) earlier entered by customer i.e. 201555555

Either the Mobile Phone (SMS Notification) field should not come as empty **or** $this->im->getCustomerURI('sms', (int)$order_info['customer_id'], $orderid) should not return any value

**Comment by BasaraABC** [comment]
Hello. Did I understand you correctly: you have custom/modified payment module and somewhere in your code this part return wrong result?
`$this->im->getCustomerURI('sms', (int)$order_info['customer_id'], $orderid)`

**Comment by hb007006** [comment]
I fixed it locally by putting below code in guest_step_1.php
$this->session->data['guest']['sms'] = $this->request->post['sms'];

if (isset($this->request->post[$protocol])) {
        $sms = $this->request->post[$protocol];
} elseif (isset($this->session->data['guest'][$protocol])) {
	$sms = $this->session->data['guest'][$protocol];
} else {
	$sms = '';
}
				
				$fld = $driver_obj->getURIField($form, $sms);

**Comment by BasaraABC** [comment]
I found related issue, mobile number not saved at all. In the invoice displayed current number  saved in customer account. To replicate - create order with one number than go to account and change number. Then if you visit invoice you will see bug.
@abolabo please also review issue reported above by @ hb007006 
<img width="707" alt="2016-12-14_13-06-32" src="https://cloud.githubusercontent.com/assets/2631910/21171486/efbb77f2-c1fe-11e6-9435-734ea81eed05.png">
