### ISSUE TITLE
PayPal connection: connection error handling

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#754]
PayPal pro and Express not work on server with valid SSL certificate installed. Both return connection errors
- App Warning: AbanteCart core v.1.2.9 PayPal Express Checkout Error: . Test mode = 1. in /extensions/default_pp_express/storefront/controller/responses/extension/default_pp_express.php on line 266
 - App Warning: AbanteCart core v.1.2.9 CURL Error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure. Test mode = 1. in /extensions/default_pp_express/admin/controller/responses/extension/default_pp_express.php on line 74
![2016-12-14_12-40-54]
<img width="1035" alt="2016-12-14_12-40-54" src="https://cloud.githubusercontent.com/assets/2631910/21176922/7902992a-c21b-11e6-8853-a555de2ea525.png">

**Comment by abolabo** [comment]
it's a server related issue.

**Comment by abantecart** [comment]
More specific please. What is the issue? Message is not clear

**Comment by abantecart** [comment]
Also, if error it needs to show in red with bootstrap alert standard

**Comment by abolabo** [comment]
1. It's a message of curl. Not sure that we need to explain it.
2. Changed color of growl alert.
