### ISSUE TITLE
Order update sms and email notification

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#760]
Class: storefront/model/checkout/order.php
Method: public function update($order_id, $order_status_id, $comment = '', $notify = FALSE)

**sms** notification is out of **$notify** flag. however send email notification is inside **if ($notify)** flag

I think both of the notifications sms and email should work only if notify flag is true. However as per current code implementation _sms notification will go whether $notify flag is false or true_ and _email notification will go when $notify flag is true_.

It is just an observation...

**Comment by abantecart** [comment]
IM notification settings are handled different way. These notifications have settings that can be managed. This can be a reason for this code to be separated from $notify condition
