### ISSUE TITLE
2Checkout payment: payment successful and incomplete order

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#763]
2Checkout payment: payment successful and incomplete order

1. Login as a customer
2. Add products to cart and use 2Checkout payment method while checkout 
3. Click on confirm. It will redirect you to 2Checkout website for payment. Make successful payment
4. Now network got down for couple of minutes
5. Customer sees page cannot be displayed after successful payment
6. Customer again opens Abantecart and he/she found incomplete order in his/her cart

**Comment by hb007006** [comment]
This can be handled just like Amazon.com

**Scenario:**
User selects Payment Method as 2Checkout or any online payment gateway and clicks on Confirm Order button

**Resolution:**
Order should be created / confirmed as soon as users clicks on Confirm Order button. 

If success / failure response from payment gateway:
Order status should be changed based on failure or success response from payment gateway
Notification should be sent based on failure or success response from payment gateway
This is working as of now.

If no response from payment gateway or user closes the browser after clicking on Confirm Order button:
Payment status should be unpaid
Payment method should be 2Checkout (Awaiting Payment)
Order status should be Order Received / Order Placed or Pending
Notifications should be sent accordingly

Payment method should get converted into Cash on delivery with Pay Now option, if no response from payment gateway even after a specific period of time e.g. 30 minutes. Provide facility to Pay online for Cash on delivery orders.

**Comment by BasaraABC** [comment]
In my opinion after customer click on Confirm Button
1. Place order with default Order status from  payment settings - by default it is Processing
2. No notification/email to customer because order is unpaid and not completed
3. After customer paid order and Payment response to AbanteCart - set order to the payment response status and then send notification/email to customer.
4. Do **Not** convert to Cash On Delivery because only customer should select suitable payment method

To discuss:
one issue here - if customer click cancel on payment side he will have not option to change payment method because basket will be empty. Should start adding products to basket again

**Comment by hb007006** [comment]
1. Place order with default Order status from payment settings - by default it is Processing - _Agree_

2. No notification/email to customer because order is unpaid and not completed 
_>> hb007006: I believe notification should be sent to customer, if order is unpaid. We should notify like below
The status of your recent payment is not known to us at this moment, and hence, we have placed it in "Awaiting Status" state. We are waiting for an update from our payment partner '2Checkout' via whom this payment was processed. It usually takes about 30-45 minutes to resolve the status of the payment. As soon we have an update, we will let you know the status. You can also check the payment status for your order here 

Meanwhile, please do not worry. Your order is placed on Abantecart and will be delivered. If your payment is successful, the payment status on your order will be automatically updated to Paid. However, if your payment fails, we will convert your order to Cash on Delivery. You can still make an online payment for your order using Pay Now functionality or you can choose to pay at the time of delivery._ 

3. After customer paid order and Payment response to AbanteCart - set order to the payment response status and then send notification/email to customer. - _Agree_

4. Do Not convert to Cash On Delivery in any cases because only customer should select suitable payment method
_>> hb007006: I think we should convert the order to COD and also provide online payment option to customer._

To discuss:
one issue here - if customer click cancel on payment side he will have not option to change payment method because basket will be empty. Should start adding products to basket again
_>> hb007006: This wont remain an issue because order will be placed as soon as customer clicks on Confirm Button_
