### ISSUE TITLE
extension upgrade.php issue

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#768]
Hi admins,

I found out that core/lib/package_manager.php on line 680 has a typo.

It should be 
`$file = !file_exists($file) ? DIR_EXT . $extension_id . '/' . (string)$config->upgrade->trigger : $file;`  
instead of 
`$file = !file_exists($file) ? DIR_EXT . $extension_id . '/' . (string)$config->upgrade->sql : $file;`

And that's causing my upgrade script file is not executed. Please confirm if my findings is correct. Thank you.

**Comment by abolabo** [comment]
Yes. it's a stupid typo. Thank you for report!

**Comment by handoyo** [comment]
You're welcome abolabo. :)
