### ISSUE TITLE
UPS add Access Point Economy Service

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#769]
We need update extension to support new services see 
http://forum.abantecart.com/index.php/topic,5325.msg22928.html#msg22928

**Comment by abantecart** [comment]
Needs research.

**Comment by BasaraABC** [comment]
Moved to 2.0
https://www.ups.com/be/en/shipping/time/service/intra/access-point-economy.page?
https://www.upstoday.com/couriers/ups-access-point

With the Locator API and plug-in you'll be able to find locations such as: **UPS Access Point™ locations**  https://www.ups.com/us/en/services/technology-integration/locator-api.page?

list of api https://www.ups.com/us/en/services/technology-integration/developer-api.page?

**Comment by BasaraABC** [comment]
moved to internal tracker
