### ISSUE TITLE
maintenance mode issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#770]
Clear all browser caches and login into admin
(Note: Maintenance mode is ON already!)
http://dev06.******/abc129_newext/index.php?rt=setting/setting/system&s=your_admin
after login click to visit SF 
Bug: you will browse site like customer so only maintenance message shown
please use browserstack to replicate issue. I replicate in IE11 and FF

**Comment by abolabo** [comment]
all correctly. Admin have ability view storefront while it in maintenace mode.

**Comment by BasaraABC** [comment]
this is what we are talking about if clear browser cache "Admin have NOT ability to view storefront"
So in other words admin view storefront as regular customer. Please folow steps and  try to replicate
