### ISSUE TITLE
Password manager of browsers and registration form. 

### ISSUE THREAD

**Issue by abolabo** [abantecart/abantecart-src#771]
All browsers proposes to save post-code (or city) as login name. Need to fix via disabling of autocomplete of form or renaming field loginname to username.

**Comment by abolabo** [comment]
i see two solutions:
1. add autocomplete=off attribute of <form> tag and disable pwd-manager here.
2. move loginname field (or email/ depends on settings) to password section. Need to paste field before password field. Tested on FF. Chrome does not save password in that case. need to investigate.
opinions?

**Comment by BasaraABC** [comment]
can you please apply fix for embed mode?
Also should we rename 'Your password' section?
<img width="790" alt="2017-02-08_16-17-48" src="https://cloud.githubusercontent.com/assets/2631910/22730593/420b96f8-ee1a-11e6-9873-21693ae93ce0.png">

**Comment by abantecart** [comment]
->>>Login details
