### ISSUE TITLE
Load missing data - failed step

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#772]
From time to time  one or two steps failed in Load missing data task.
It is not clear what this step do (what tables copy failed) and if possible add reason of fail
![2017-01-26_17-31-58](https://cloud.githubusercontent.com/assets/2631910/22328221/a52a5ad0-e3ed-11e6-83dd-9151fc845e94.jpg)

**Comment by abolabo** [comment]
added step details into log-file on fault

**Comment by BasaraABC** [comment]
#785
