### ISSUE TITLE
bots cause warnings in log

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#773]
`warning: AbanteCart core v.1.2.9 preg_match(): Compilation failed: nothing to repeat at offset 0 in /core/engine/language.php</b> on line 292`
More info http://forum.abantecart.com/index.php?topic=5383.0#msg23175

**Comment by abolabo** [comment]
you can check if disable accepted-language http-header in your browser (via sniffer plugin). Main idea is in request without this header.
