### ISSUE TITLE
thumbnails stretched if product with option images

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#775]
Issue with thumbnails image proportion if change image settings. Please note it is visible in product with options (option values contain images) like http://demo.abantecart.com/new-ladies-high-wedge-heel-toe-thong-diamante-flip-flop-sandals
more details http://forum.abantecart.com/index.php/topic,5400.msg23257.html#msg23257
<img width="1130" alt="2017-02-07_13-19-30" src="https://cloud.githubusercontent.com/assets/2631910/22679979/3c58fc7e-ed38-11e6-96b7-35e5c01a2d7a.png">

**Comment by BasaraABC** [comment]
original issue fixed however new issue visible when product page load (HI-RES images is enabled) please see screenshot
![2017-02-08_13-31-05](https://cloud.githubusercontent.com/assets/2631910/22726237/f29a5ea2-ee04-11e6-8037-165c29baf46d.png)

**Comment by abolabo** [comment]
cannot fix it. Sizes of this images takes from settings and applies to <img> tag via style attribute.

**Comment by BasaraABC** [comment]
Something is broken now. I see all product images on page before load completed. Looks even worse than before fix.
see screenshot
![2017-02-28_16-26-19](https://cloud.githubusercontent.com/assets/2631910/23399410/b3b088aa-fdd2-11e6-8d5c-da703a23621c.jpg)
