### ISSUE TITLE
Guest Step 1 shipping address error message is not showed

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#779]
Hi admins, 
I found out that both embed and normal Guest Step 1 shipping address error message is not showed if they left empty too.  

    <div class="form-group <?php if (${'error_'.$field_id}) echo 'has-error'; ?>">
	<label class="control-label col-sm-4 col-md-4"><?php echo ${'entry_'.$field_name}; ?></label>
	<div class="input-group col-sm-4 col-md-4">
 	<?php echo $field;	?>
	</div>
	<span class="help-block"><?php echo ${'error_'.$field_id}; ?></span>
    </div>

Should it be: 

    <div class="form-group <?php if (${'error_shipping_'.$field_name}) echo 'has-error'; ?>">
	<label class="control-label col-sm-4 col-md-4"><?php echo ${'entry_'.$field_name}; ?></label>
	<div class="input-group col-sm-4 col-md-4">
 	<?php echo $field;	?>
	</div>
	<span class="help-block"><?php echo ${'error_shipping_'.$field_name}; ?></span>
    </div>

**Comment by BasaraABC** [comment]
Hello. Thank you for report.  We will check
How you replicate missing address? When you register new account address is required and you can not delete default address too

**Comment by handoyo** [comment]
What are the missing address are you referring to Basara? I don't understand.

**Comment by BasaraABC** [comment]
Are you refer to second address form when Guest customer click "Check here if you have a separate shipping address."?
In my setup I got error "Oops, there is an error with information provided!" if left it empty. Can you add some screenshots?
<img width="916" alt="2017-02-08_17-54-12" src="https://cloud.githubusercontent.com/assets/2631910/22734291/b2d4fda4-ee27-11e6-9740-44e94502d927.png">

**Comment by handoyo** [comment]
Hi Basara, 

Yes i'm referring to the second address:

![guest error](https://cloud.githubusercontent.com/assets/225439/22819299/11273d36-efa4-11e6-8780-6b66146f6702.png)

**Comment by BasaraABC** [comment]
Fix is broke something.  If you go to Guest checkout page - it immediately give you errors for all fields. This is wrong. Errors should appear only after form submit like we have before

**Comment by BasaraABC** [comment]
Again wrong fix. Second guest address (Shipping Address) do not return any error if required fields leave empty.

**Comment by abolabo** [comment]
please check it with some old template

**Comment by BasaraABC** [comment]
All fields names are missed for second address (Shipping Address). Please fix
<img width="767" alt="2017-02-20_18-33-48" src="https://cloud.githubusercontent.com/assets/2631910/23123554/6207fa02-f79b-11e6-9e0c-b250558269f9.png">

**Comment by BasaraABC** [comment]
Thank you. To close this bug please apply your changes to Embed mode guest checkout
