### ISSUE TITLE
Multistore coupons - missed feature

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#78]
I think good idea to add Store selection setting for Coupons with next values:
1. <b>All stores</b>
2. Default store
3. Store2
4. Store3.....etc
For example if you have store1 with quality digital electronics and store2 with low cost socks - in case store owner issue coupon 20% for cheap socks and someone apply it for digital electronics (even more  'free shipping'!)

**Comment by abantecart** [comment]
Add to backlog for 1.2.3
