### ISSUE TITLE
Abante cart 129

### ISSUE THREAD

**Issue by dkat101** [abantecart/abantecart-src#781]
Fresh install returning

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/abante_cart_129/system/config.php:2) in /Applications/MAMP/htdocs/abante_cart_129/index.php on line 48

**Comment by BasaraABC** [comment]
Hi. Is it localhost installation? What is your MAMP and PHP versions?

**Comment by BasaraABC** [comment]
I have no issues with MAMP php 7 and AbanteCart 1.2.9 module
try reinstall it https://bitnami.com/stack/mamp

**Comment by dkat101** [comment]
@BasaraABC 
It's a localhost installation.
MAMP: 3.0.7.3
PHP: 5.6.2

**Comment by abolabo** [comment]
You should to install and enable output buffering for your php. 
Please check this https://www.a2hosting.com/kb/developer-corner/php/using-php.ini-directives/php-output_buffering-directive 
Also you can check current php directives in admin of installed AbanteCart (menu System->settings->system->button "phpinfo()" at the heading)
