### ISSUE TITLE
UPS module and 3 letters states

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#784]
No way to save UK province/state in the UPS settings. Only 2 letters state code allowed for save 
http://forum.abantecart.com/index.php/topic,5421.msg23323.html#msg23323

**Comment by BasaraABC** [comment]
Main issue described in this post ignored and not fixed. Also user try with real account and get critical error
http://forum.abantecart.com/index.php/topic,5421.msg23448.html#msg23448

**Comment by abolabo** [comment]
won't fix. UPS API supports only two letter codes of provinces.

**Comment by goatlady102** [comment]
I believe you are incorrect in this -  UPS API does support 2 and 3 letters codes for provinces/states
https://www.ups.com/worldshiphelp/WS14/ENU/AppHelp/Codes/Australia_Province_and_Mexico_State_Codes_for_Air_Ground_Freight.htm
here is one of the UPS pages that show that

Our enhanced UPS integration does.  The state/province is 2/3 digits,  The country origin is only 2.
If you want us to look up our coding for that,  just ask.

Lee (WHY2)

**Comment by BasaraABC** [comment]
### FYI : Address Guidelines

Note: this is **UPS WorldShip** service doc.

According to this doc https://www.ups.com/worldshiphelp/WS14/ENU/AppHelp/SHIPMENT/Country_Territory_Postal_Code_and_State_Prov_Guidelines_Popup.htm
For US 50 and Canada destinations for small package shipments, use the two-letter abbreviation for the state or province.

For Australia and Mexico destinations for Air or Ground Freight shipments, use the 2-to-3-letter abbreviation for the Australia province code or the 2-letter abbreviation for the Mexico state code. 

For other destinations, type **up to five uppercase letters and numbers** (without spaces) to abbreviate the state or province.


In addition see UPS calculator https://wwwapps.ups.com/ctc/request?loc=en_GB
State/Province code is not required. Maybe in API it also not important?
![2017-07-04_15-14-23](https://user-images.githubusercontent.com/2631910/27821175-987e1168-60cb-11e7-9708-aa6c7cc40c94.png)
