### ISSUE TITLE
content language selector: missing icon

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#786]
<img width="490" alt="2017-02-21_16-00-55" src="https://cloud.githubusercontent.com/assets/2631910/23157786/1b692954-f84f-11e6-89f9-3f1674ea3838.png">

**Comment by abolabo** [comment]
is it still present? i cannot to replicate

**Comment by BasaraABC** [comment]
Issue is valid. Not sure why you can not replicate it. 
Try follow screenshot - install British and go to product edit page. And use hi-res display
![2017-03-07_14-30-50](https://cloud.githubusercontent.com/assets/2631910/23646286/bfa5035a-0342-11e7-9056-d3f521b93c0f.jpg)

**Comment by abolabo** [comment]
please be sure that you have correct RewriteBase path in your .htaccess. I checked it on my side - all works correctly.
