### ISSUE TITLE
dev issue: price inc tax

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#790]
1. If no tax total in the basket why we show inc tax? For example see screenshot if product is not taxable at all (in product settings set Tax Class -None-).
![2017-03-02_18-36-41](https://cloud.githubusercontent.com/assets/2631910/23505719/7b32c82a-ff77-11e6-98ad-f8a9d2216042.jpg)

2. In same logic we also have Tax Exempt for customer groups. And here is bug - if set default customer group to _Exempt from all taxes_ the is no Tax total in basket but product display price with tax (in product settings set Tax Class). See screenshot with logged in customer
![2017-03-02_18-49-39](https://cloud.githubusercontent.com/assets/2631910/23506129/3c58e3b2-ff79-11e6-8708-fd2a57acac81.jpg)

**Comment by abantecart** [comment]
Is this with setting ON to show price with the tax?

**Comment by BasaraABC** [comment]
yes, both with setting ON

**Comment by BasaraABC** [comment]
Both issues are not fixed. Checked with Logged in customer
### Issue 1: how price can be with "Inc Tax" sufics if product is _not taxable_? I mean if in the product set Tax class "-none-".
Maybe some users will be confused if in listing some product have not Inc Tax. What do you think? Let's discuss?
<img width="824" alt="tax-1" src="https://cloud.githubusercontent.com/assets/2631910/24292287/4306f8fa-10bf-11e7-8194-21dae5a41127.png">



----------------------


### Issue 2: If set all customer groups to exempt tax. For logged in customer price shown with tax. This is bug - see no tax in the basket
Note: AbanteCart cache was cleared.
<img width="1151" alt="2017-03-24_18-12-51" src="https://cloud.githubusercontent.com/assets/2631910/24292262/27111766-10bf-11e7-8f70-c434678c3ce9.png">

**Comment by goatlady102** [comment]
Hi guys -  I tried to tell you previously on board this was a huge can of worms and there is no easy solution to all the factors that affect trying to add the taxes to each product and still leave the cart functional for site owners in multiple locations selling to customers in multiple locations.  The original solution of was the cleanest for the largest number of site owners.   
Here's an example -  site owner shows pricing with taxes included.  Site owner is located in area that collects taxes on shipping address -  pricing will never be shown correctly until customer logs in and presumed shipping address is fetched to add to the product, There are too many variable of what taxes are applied under what conditions to right the majority of time.

The simplest and most accurate for the buying customer is to show the taxes in the estimate on the cart page,  and with real conditions applied in the checkout page.  Seems that simple solution works for the largest online seller in the world Amazon -  why do we need to complicated site owners management so much?  

Just my opinion,  but the simple solution is the most elegant solution and often the best solution,

Lee

**Comment by abantecart** [comment]
Thank you Lee. I know that it is becoming more complex. 

Buy the way, we have AvaTax integration that was created, but we do not have time to get to it and coordinate with Avalara for publishing.

If your are interested to help. Please send us an email if you are.

**Comment by BasaraABC** [comment]
Please fix issue #817 so I can check this too

**Comment by BasaraABC** [comment]
Bug in listings: if product have not any Tax class on product page shown price without tax like $21.00 but in listing still displays with tax $22.79 Inc tax 
Note: check with Guest customer
<img width="932" alt="2017-03-28_19-02-36" src="https://cloud.githubusercontent.com/assets/2631910/24404017/a17a83c0-13e9-11e7-9155-95335cb92989.png">

**Comment by abolabo** [comment]
was related to cache
