### ISSUE TITLE
dev issue: Load missing data tool broken

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#792]
#### Load missing language data task fail and no error in log

![2017-03-07_15-09-59](https://cloud.githubusercontent.com/assets/2631910/23647447/7a9533ec-0348-11e7-9a31-35a740c30aff.jpg)

related to #785

**Comment by abolabo** [comment]
it's not "broken". Issue was in memory_limit directive. fixed

**Comment by BasaraABC** [comment]
thank you. Now it is run
