### ISSUE TITLE
incomplete translation task - missed language names

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#796]
![2017-03-09_13-45-55](https://cloud.githubusercontent.com/assets/2631910/23744244/0a1b5da4-04e6-11e7-8acf-8b0983f1d402.jpg)

**Comment by abolabo** [comment]
It's not a bug. After language removed we have to show something there. Unknown is correct word.. i think

**Comment by abolabo** [comment]
maybe remove it on check process?
