### ISSUE TITLE
option's value 100+

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#801]
Can not add more than 100 option values.
After save they disappear
http://forum.abantecart.com/index.php/topic,5486.msg23638.html#msg23638
![2017-03-13_16-38-28](https://cloud.githubusercontent.com/assets/2631910/23848921/dfc52840-080b-11e7-972d-362bedf610ce.jpg)

**Comment by easyhostmedia** [comment]
any timeframe to get this fixed as until this is fixed i am unable to continue building my website and it will take me weeks to reconfigure another cart like Opencart.

**Comment by abolabo** [comment]
The cause is in a php restriction, not AbanteCart. You should to increase value max_input_vars in your php.ini file.
We cannot change this value on-the-fly by php security policy.
