### ISSUE TITLE
Broken image [Admin front: Sales -> Send Mail]

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#804]
1. Login into Admin panel
2. Navigate to Sales -> Send Mail
3. Enter necessary details i.e. subject, to etc...
4. Click on Visual
5. Click on Add Media and choose store logo
6. Type your message
7. Click on send
8. Mail delivered successfully 

Open your email. You will see email from Abantecart with icon 
![img](https://cloud.githubusercontent.com/assets/22338790/23999895/b568e016-0a7f-11e7-94ba-9ab067974bca.png)

When you inspect element (right click on image and click on inspect) it will show you 
http://resources/image/18/73/3.png

**Comment by BasaraABC** [comment]
Note: if possible in _Send Email_ please insert image url with Store URL
