### ISSUE TITLE
Removed Footer on Check Out - No CC Validation Javascript

### ISSUE THREAD

**Issue by audas** [abantecart/abantecart-src#805]
AS the title suggests. When removing the footer bar from the bottom of a page - in this case the check out - the page no longer loads in the required Javascript for the body of that page.

Again, check out, removed bottom footer, and the confirm button on the check out for credit card validation throws an error because the javascript was not loaded.

//load creditcard input validation
		$this->document->addScriptBottom($this->view->templateResource('/javascript/credit_card_validation.js'));

No loaded therefore

  $.aCCValidator.validate = function ($form) {

fails.

**Comment by abantecart** [comment]
Thank you for bringing this issue up. Let me work on the solution and move this code to page.tpl instead

**Comment by abantecart** [comment]
This is fixed.
