### ISSUE TITLE
Load missing language data - ignore store multilanguage data

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#807]
After Success **Load missing language data** task completed the Store related data is empty
<img width="958" alt="2017-03-23_13-39-09" src="https://cloud.githubusercontent.com/assets/2631910/24235122/51840586-0fce-11e7-8a4f-f2b1e445e9a5.png">

**Comment by abantecart** [comment]
This has to be entered manually. No issue here. Generally, settings are not suppose to be language specific. 
In V2.0 we will remove these to language section from settings
