### ISSUE TITLE
installation - incorrect error text

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#813]
If connection can not be established during installation error shown ".....Check db setting in configuration file"
installation is not completed so nothing to check in config file
<img width="842" alt="2017-03-24_20-15-50" src="https://cloud.githubusercontent.com/assets/2631910/24295806/0f392074-10cf-11e7-88ab-92f225a33952.png">

**Comment by BasaraABC** [comment]
Issue is not fixed. I check with FTP - config.php is empty so nothing to check in configuration file
<img width="893" alt="2017-03-28_12-37-38" src="https://cloud.githubusercontent.com/assets/2631910/24390522/b008f844-13b3-11e7-8699-9e9f53f0aa50.png">

**Comment by abolabo** [comment]
have no idea how to replicate it
