### ISSUE TITLE
Savings details are missing

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#814]
Savings details are missing from Invoice

**BeneFit Girl Meets Pearl:** $19.00 <strike>$30.00</strike>

1. Add a product "BeneFit Girl Meets Pearl" into cart.
2. Checkout and confirm your order
3. Open your Invoice. Invoice didn't show Total Savings. However most of the carts are displaying Total Savings details.

Savings / Total Savings information should be available on
1. Invoice 
2. Shopping Cart page 
3. Cart dropdown on home page
4. Wherever is applicable

**Comment by hb007006** [comment]
![1](https://cloud.githubusercontent.com/assets/22338790/24332943/17c1a73a-126d-11e7-972f-b1e8f0137a1b.png)
![2](https://cloud.githubusercontent.com/assets/22338790/24332948/27fa7bf4-126d-11e7-8469-a8cf818e7858.png)
![3](https://cloud.githubusercontent.com/assets/22338790/24332951/2e302a8c-126d-11e7-8802-8f720483ff60.png)
![4](https://cloud.githubusercontent.com/assets/22338790/24332954/362dd1da-126d-11e7-9a18-fff336bc5f27.png)

**Comment by abantecart** [comment]
What is  Total Savings? What you show on the screenshot is not part of AbanteCart.

Please do not report custom mods as bugs.
