### ISSUE TITLE
SMS and Email notification issues in case of Request Cancellation of Order

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#815]
1. Add products into cart
2. Click on Checkout 
3. Choose Guest Checkout and click on Continue
3. Provide your mobile number for (SMS Notification)
4. Confirm your order

SMS and Email notifications are coming to Guest and Admin both on order confirmation

5. Open your Invoice
6. Click on Request Cancellation of Order
7. Click on Continue

**Two issues here when you perform Request Cancellation of Order**
1. SMS notification is not going to Guest even after he has provided his number for SMS Notification while checkout. This is happening in case of Guest checkout only. 
2. Email notification is not going to Admin. This is happening in case of Guest checkout and registered customers.

**Comment by abolabo** [comment]
Both bugs are not confirmed. Tested on dev-branch 1.2.10.  Probably fixed earlier.
