### ISSUE TITLE
[ipad mini2] broken listing if product with blurb

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#820]
Visible on Home page in rotated view. Please add blurb to one of the products
![img_0931](https://cloud.githubusercontent.com/assets/2631910/24349071/1de189d2-1308-11e7-80cf-d909540c259d.PNG)

**Comment by abantecart** [comment]
This is normal. Nothing we can do here. Customers will beed to have all the blurbs with similar text length to balance.
