### ISSUE TITLE
missing no-image

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#821]
Column block - missing no image
![2017-03-27_16-17-05](https://cloud.githubusercontent.com/assets/2631910/24349346/eb1c4270-1308-11e7-988d-f1193adc5998.png)

**Comment by abantecart** [comment]
Are you sure your product has an image?

**Comment by BasaraABC** [comment]
Product have not image. In this case should be no-image replacement like on screenshot
<img width="301" alt="screen shot 2017-03-28 at 12 05 32" src="https://cloud.githubusercontent.com/assets/2631910/24389836/e2cb1294-13ae-11e7-9913-08dbbd2105f6.png">
