### ISSUE TITLE
embed: remove bg for rating

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#826]
White bg around rating looks ugly
<img width="586" alt="2017-03-28_14-57-39" src="https://cloud.githubusercontent.com/assets/2631910/24394650/f79585de-13c6-11e7-8426-37943ef898c7.png">

**Comment by abantecart** [comment]
There is not style applied in the include of embed. This is style in the parent template used.

**Comment by BasaraABC** [comment]
Not a bug
