### ISSUE TITLE
Control Panel Session Expiration issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#83]
Control Panel Session Expiration setting work for customer session at SF. I think we need 2 separate settings for Admin and for SF
![admin](https://cloud.githubusercontent.com/assets/2631910/6142695/b74c95ae-b1ed-11e4-96ac-be078b1295bb.png)

**Comment by abantecart** [comment]
This is not an issue. It is improvement please add to dev backlog
