### ISSUE TITLE
Order Statuses Grid js error in non default language

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#830]
Grid is empty and error in console
<img width="1058" alt="2017-03-28_20-55-26" src="https://cloud.githubusercontent.com/assets/2631910/24408988/3ff1d13e-13f9-11e7-9bd4-dc022da84569.png">

**Comment by abantecart** [comment]
We can not replicate this issue on 2 installs. Keep a eye on this i the future

**Comment by BasaraABC** [comment]
I replicate it on upgraded 1.2.9>1.2.10 store in Firefox and Chrome
See screenshot in Chrome
<img width="1022" alt="2017-03-29_13-05-22" src="https://cloud.githubusercontent.com/assets/2631910/24440794/74792eca-1480-11e7-9025-0eac257c29c4.png">
