### ISSUE TITLE
CONTACT US: Duplicate Notification to be sent to customer

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#831]
1. Open home page.
2. Click on Contact Us
3. Fill necessary details and click on Submit
 
Email and SMS notifications are going to admin

**Issue**
Email and SMS notifications are **not** going to user who is submitting the request. At least email notification should be sent on the email address which he / she has provided on contact us form.

**Comment by abantecart** [comment]
This is not actually an issue. This is additional feature that we can consider including as an option.
Customer will have an option to select a copy of message to be send to them. 

Low priority.

**Comment by abantecart** [comment]
I am moving this to 2.0. 
We still need to discuss if this is needed. Do we actually need to send copy to customer? This can be an option with "Send me a copy". In the case, captcha should be required to prevent spamming. 

I think this should be better handled by autoresponder in recipient with receipt acknowledgment.

**Comment by BasaraABC** [comment]
moved to internal tracker
