### ISSUE TITLE
Quick Start Wizard appear on every login

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#837]
Quick Start Wizard appear on every login even if it was completed 
Note for @abolabo : one payment is installed by default. So it is not related
http://forum.abantecart.com/index.php/topic,5557.msg23929.html#msg23929
<img width="673" alt="2017-04-12_13-15-01" src="https://cloud.githubusercontent.com/assets/2631910/24943721/1c11e6de-1f82-11e7-9ad5-f016f8c9484f.png">

**Comment by BasaraABC** [comment]
User also report number of repetitions for "Thank you for installation" message. See if it is related
http://forum.abantecart.com/index.php/topic,5560.msg24171.html#msg24171

**Comment by abantecart** [comment]
Fixed.
