### ISSUE TITLE
API guest checkout

### ISSUE THREAD

**Issue by kontur** [abantecart/abantecart-src#838]
1) I noticed when you use, for example, the API's "Add or update products in cart (basket)" API calls without a token (i.e. no user logged in) it still returns a response with the "added" product - although I assume this is saved nowhere and shouldn't actually be a valid response

2) Is it possible to use the API flow to have a guest checkout, i.e. use the calls listed under "Checkout API" without a user token?

**Comment by abolabo** [comment]
1. it's a bug. fix added
2. No. Guest checkout is not implemented yet
