### ISSUE TITLE
special price 0

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#841]
In some case for example set product to be Free for short period user can set Special price to 0 but SF product page and basket ignore this and show regular price instead
![2017-04-21_16-39-48](https://cloud.githubusercontent.com/assets/2631910/25272325/96131530-26b1-11e7-9ce0-268600318855.png)

**Comment by abantecart** [comment]
I think this is not a bug. You should not set special price of 0. This is not a special to begin with.

**Comment by newforestnick** [comment]
For me I needed to set up a free file download showing the original price crossed out and the SALE icon showing that this was a SPECIAL FREE product. The photo file could be downloaded and buyers would see the quality and be encourage to buy other products from my store. A SPECIAL was the only way that I could do this and encourage them to create an account at the same time.

**Comment by abantecart** [comment]
This sounds like a custom solution that does not fit as common use for eCommerce.
