### ISSUE TITLE
Out of stock status 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#842]
We have to improve one of the Out of stock status. For example Pre-order. 
Better to set Order to new Status Pre-Order (order status) if one the products was out of stock with Pre-Order status (our of stock status). And better display Pre-order message on product page.

**Comment by abantecart** [comment]
Duplicate?

**Comment by BasaraABC** [comment]
No, this is not a duplicate.
#851 is about how AbanteCart show stock message
#842 this issue is about Pre-order process handling

**Comment by BasaraABC** [comment]
### Case: 
System > Settings > Checkout: Stock Checkout OFF
Product quantity 0, Product Track Stock: Yes
Product _Out Of Stock Status_: Pre-Order
<hr>

### Problem: we show customers Pre-order message but do not allow to pre order. 
<hr>


### Solution (discussion): a pre-order button with a title shows up on a product page that is out of stock. 
Allow customers to purchase it and after order is placed set **Order Status** to Pre-Order ?
<hr>

![2017-06-30_13-07-19](https://user-images.githubusercontent.com/2631910/27723095-7a6e8402-5d95-11e7-9d98-bb2e42865342.png)

**Comment by abantecart** [comment]
We should rename "Pre-order" to "Contact us to pre-order"
