### ISSUE TITLE
product image in category listings

### ISSUE THREAD

**Issue by handal59** [abantecart/abantecart-src#843]
In abantecart V1.2.10 images in **some** categories do not upload on the site and i think that this issue might be related to the template [the original template included with abantecart] because if i change the template it works.

**Comment by BasaraABC** [comment]
Hello. Welcome to AbanteCart bug tracker. It is not a forum so please provide step by step how to replicate bug/issue.
Also attach images which one you can not upload and screenshot with problem

**Comment by BasaraABC** [comment]
For dev team to replicate upload image into product
![63770-2](https://cloud.githubusercontent.com/assets/28081496/25472928/05076260-2b36-11e7-9661-3b0254350653.jpg)

**Comment by abolabo** [comment]
Please post memory_limit directive value from phpinfo page.
I mean admin->system->settings->system-> button phpinfo() at the heading

**Comment by BasaraABC** [comment]
it is on our dev server. Please read my note file is very small (dimentions and size)
memory_limit	64M

**Comment by handal59** [comment]
please explain your last comment

php.ino image is below

![memory limit](https://cloud.githubusercontent.com/assets/28081496/25475683/3af3e88a-2b40-11e7-99a1-0003b0f369fa.png)

**Comment by BasaraABC** [comment]
Hell. Possibly this is something wrong with GD php library installed on your server. To investigate and issue could you please send us ftp and AbanteCart administration access to beremenko@abantecart.com

**Comment by handal59** [comment]
i sent it now to your email beremenko@abantecart.com
many thanks for your quick support

**Comment by abolabo** [comment]
fixed

**Comment by handal59** [comment]
Yes I saw it working and many many thanks for your support

 

I would like to learn what was the problem or was it from the cart files, if he problem was from my side I will try to fix in future upgrades if it happens and not bother you

 

Again  I appreciate your support and many many thanks

 

Hani

 

 

BCC-logo-s

Bethlehem Casting Co.

Bethlehem Palestine

TelFax: + 970 (0)2 2749797

Mobile: + 972 (0)54 7742809

Mobile: + 970 (0)59 7887901

Email: info@bethlehemcasting.com
