### ISSUE TITLE
USPS: Ounce based calculation issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#845]
http://forum.abantecart.com/index.php?topic=5609.msg24161#msg24161
2 problems here.

1. There is a bug with ounce based calculations in USPS. We will address this.
For now you can use pound based calculation and it will work correctly.
 
2. 6/16 lb is = 0.37 lb = 5.92 oz,  and exceeds First-Class package limitation of 3.5 oz

**Comment by abantecart** [comment]
Also, looks like we are missing "First Class Package" in the options.

**Comment by abolabo** [comment]
1. added minimal weight size for package 0.001 instead 0.1 pound
2. fixed bug with first-class methods
3. @BasaraABC  please send me text for default weight class of this extension. It must be pounds

**Comment by BasaraABC** [comment]
Hello.
for 2.  Fixed: First-Class delivery options now available.
for 3. If this setting should be always Pound why do we allow to change it? Also I check and after last update no matter what you have selected as Weight class in USPS settings. All the time same result in delivery prices. What is the purpose of this setting?

**Comment by abolabo** [comment]
added warnings for wrong weight and length classes on usps settings page
