### ISSUE TITLE
Resize image errors text improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#846]
Please improve image resource errors. Main idea is now not clear how to find an image in Media Library, to what object (product, category or any) it is assigned.
If possible please add info about resource name (this will allow to use Media Library search) and object mapped to.
- App Error: AbanteCart core v.1.2.11 Image file //resources/image/18/72/e.jpg cannot be resized. Try to decrease original image size 2329x2329px or reduce file size. in /core/lib/image.php on line 258
 - App Error: AbanteCart core v.1.2.11 Resize image error. File: /resources/image/18/72/e.jpg in /core/engine/resources.php on line 345

Please show this error in Error log **only** and do not send Admin Message with App error.

**Comment by abolabo** [comment]
added link to resource manager with automatic popup on page load event
