### ISSUE TITLE
Backup issues part 1

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#85]
Issue A: no way to download backup file from admin
Issue B: do not backup dynamic files (now cache in backup file)
Issue C: do not backup backup file (each time you run backup the backup archive doubled size)
Issue D: please add time-stamp to backup archive filename to save previous backups (now all backups removed)
Issue a screen: ![backup-issue1](https://cloud.githubusercontent.com/assets/2631910/6145052/4f55ce34-b210-11e4-895f-091c643b2f3e.png)
-----------------------------------------------------------------------------------------------------

Issue b screen: ![backup-issue2](https://cloud.githubusercontent.com/assets/2631910/6145053/5316de1e-b210-11e4-96cd-9e038b22b2a5.png)
-----------------------------------------------------------------------------------------------------

**Comment by BasaraABC** [comment]
Issue C and Issue D are not fixed.
new issue E: when backup file removed - download link show empty page. Please add some notice about missed file on server.
![issuee](https://cloud.githubusercontent.com/assets/2631910/6185664/c7bf4c1c-b3a3-11e4-88b2-f1768efbe49c.png)

**Comment by BasaraABC** [comment]
Issue C - still not fixed
about issue E - can not check because now no records in File Uploads section about backup (Please do not remove functionality - fixing doesn't mean features remove, please restore removed functionality and fix Issue E)

**Comment by abolabo** [comment]
what "File Uploads"? NO. 
Upgrade/install history!

**Comment by BasaraABC** [comment]
1. there is no download link in Upgrade/install history - see screen
2. there is no link to Upgrade/install history section after backup complete (it was before)
Please see attached screenshots
![one](https://cloud.githubusercontent.com/assets/2631910/6212849/337298f4-b61c-11e4-979a-31350c5d2175.png)
![two](https://cloud.githubusercontent.com/assets/2631910/6212868/6e7986a6-b61c-11e4-8b89-e96b08e1ffa8.png)
