### ISSUE TITLE
signup up with 2 characters login name which can pass the error check

### ISSUE THREAD

**Issue by afrianviolet** [abantecart/abantecart-src#850]
I find that signup up with 2 characters login name which can pass the error check when press F5 to refresh the screen. Abantecart will create the customer account during this process for login name which is shorter than 5 characters.
For the 1st time verification, the error message occurrs (Login name must be alphanumeric only and between 5 and 64 characters!). But if I ignore it and press F5 to refresh the screen, then it will create an account successfully.
Please fix this problem. (abantecart v1.2.10)
Thank you!

**Comment by BasaraABC** [comment]
Issue is valid. To replicate fill all fields on account registration form and use short login like like "bb", submit form and you will get error message about to short login name.
Next click F5 browser (firefox) will ask you to resend form. Click ok and account will be created

**Comment by BasaraABC** [comment]
Issue is fixed but incorrect error message shown on form resubmit
![2017-05-05_13-00-49](https://cloud.githubusercontent.com/assets/2631910/25735209/e41fdafa-3193-11e7-818a-379bb04d0916.png)
