### ISSUE TITLE
Long first names and menu

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#856]
If customer logged in and have long first name menu misplaced 
<img width="1147" alt="2017-05-02_16-23-35" src="https://cloud.githubusercontent.com/assets/2631910/25612235/151ed83c-2f54-11e7-9e73-508c425259fe.png">

**Comment by abolabo** [comment]
cannot to replicate. see ellipsis instead

**Comment by abantecart** [comment]
It is possible to replicate, if you set the same details.
