### ISSUE TITLE
USPS: multistore (different store weight class)

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#859]
Still different USPS results for stores with different **Store Weight Class** (please do not confuse it with **Base Weight class**)
Test: latest 1.2.11 setup with multi-store. Same product so weight is same, same customer account so address is same too. Only one difference is Store Weight Class.
Default store weight class: Pound
Second store weight class: gramm

For the record, we have following architecture:
1. correlation between all Weight Classes in the Localization > Weight classes. Here we have only _one common for all stores_ **Base Weight class** with value 1.0000. Others have values different from 1.0000
2. Each store have weight class setting. Let's named **Store Weight class** - it should change only Display of weight for customers and of course can Not change any weights
3. Each product have weight value and weight class - **Product Weight Class**. 
4. Some Shipping methods have own weight class setting. Let's name it **Extension Weight Class**
In my opinion **Extension Weight Class** is something about in what weight shipping api want to receive products weight.

![2017-05-10_14-07-44](https://cloud.githubusercontent.com/assets/2631910/25887249/80b3b364-358b-11e7-920c-6371607bbfbe.png)

**Comment by abolabo** [comment]
cannot to replicate

**Comment by abantecart** [comment]
I thought we have discussed this and decided how to fix this issue.

**Comment by BasaraABC** [comment]
Issue is fixed.
