### ISSUE TITLE
Backup 1.2.1  issue?

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#86]
Full backup skip some files see screenshot - in this case install folder and .txt file. Question: why this files skipped? When user run backup he expect that all folders and files archived (especially modified store). 
![backup-isue3](https://cloud.githubusercontent.com/assets/2631910/6147499/d5ebf80a-b22a-11e4-8e5d-dad141ce7664.png)

**Comment by abolabo** [comment]
dir install must be deleted after installation. Abc shows warning in messages about it. 
Another bug fixed.
