### ISSUE TITLE
Resize image errors improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#866]
#### 1. Sometimes two different errors in messages: **App Error** and **Image Resize error 100030**
![2017-05-11_16-17-16](https://cloud.githubusercontent.com/assets/2631910/25942079/f1c54bb4-3665-11e7-885f-fe36ed08f214.png)
<hr>

#### 2. In the App error it is not clear how to find resource
![2017-05-11_16-17-30](https://cloud.githubusercontent.com/assets/2631910/25941991/a1c527a6-3665-11e7-8a25-9a6c9c359cd4.png)

<hr>

#### 3. Need to discuss: messages will be annoying especially for beginners or not tech. We need improve for example:
a. hide error at all - just write error in the log
b. consolidate to one message with 'number of repetitions' count update (if someone can not resize 1000 images now will be 1000 messsages)
c. change message from Critical to Warning?

**Comment by abolabo** [comment]
1. all errors now will be warnings
2. added text about increasing of php memory limit

**Comment by BasaraABC** [comment]
More issues after fix.
to replicate upload big jpg file to product and refresh product edit page in admin:
issue A: one image hint 2 errors and one is critical. As discussed before all resize errors should be warnings
issue B: Missing "resize image" in the warning title
issue C:  Error text in the critical message is incorrect. File is exist and readable (was able to load image path in browser)
issue D: Missing 'how to resolve' text in the resize warning (as discussed before should be not about memory increase or manual image decreasing)

![2017-05-16_17-53-56](https://cloud.githubusercontent.com/assets/2631910/26103135/49336e6c-3a62-11e7-8a5d-2700f35b86dd.png)

**Comment by BasaraABC** [comment]
We need to move all resize warnings to error or system log #878 #877
