### ISSUE TITLE
dev: weight classes insert

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#867]
A. When new weight class inserted please change help note about "Set 1.00000 if this your default weight" to "Set weight conversion factor equivalent to base weight class 1kg"
B. Do not allow to set up two base weight classes (1.00000)

<img width="724" alt="2017-05-12_16-58-24" src="https://cloud.githubusercontent.com/assets/2631910/25993825/995fa4b2-3735-11e7-9f44-622ab7b15ab3.png">

**Comment by abolabo** [comment]
removed help <span> from description of value field.
Value can be 1 for any new custom weight classes
