### ISSUE TITLE
dev: option's value weight class

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#869]
In option value we allow to change weight by percentage or weight value. 
### 1. Only one weight class available - Product Weight class. `Let's discuss`
Problem: if product weight class changed  - in the option value still old weight class.
Solution: do not allow to select weight class in options. Option value should always follow Parent product weight class. 

### 2. Present multi-language issue
![2017-05-12_18-44-10](https://cloud.githubusercontent.com/assets/2631910/25997366/ecd8b394-3745-11e7-8802-fb338ad7ba58.png)

**Comment by BasaraABC** [comment]
Issue is not fixed. More bugs created. After changing Parent weight class the Option's value weight class should follow parent (as we discussed before). But now after parent weight class change:
Issue A: the option's value weight class have no changes
Issue B: one more weight class added for selection in the option's value
![2017-05-15_19-31-07](https://cloud.githubusercontent.com/assets/2631910/26057914/cba8f834-39a5-11e7-8209-2625a63da611.png)

**Comment by BasaraABC** [comment]
#871 related

**Comment by abolabo** [comment]
nothing changed/ we cannot to fix it completely. Bug based on translatable unit name issue. 
Let's return to it in 2.0.

**Comment by abantecart** [comment]
Let me add something here. We do not select weight class in the option. We select absolute or % based calculation for option weight.  
Absolute value is based on parent product weight class set. 

Example:
If product weight class is set to "Kg" in option you should see only % and "Kg" in the weight type selection. 
This is correct behavior.

**Comment by abantecart** [comment]
Let me know if discussion is still needed. I do not see any need as of now.

**Comment by BasaraABC** [comment]
moved to internal tracker
