### ISSUE TITLE
UPS not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#87]
Can not configure UPS to work. I try different UPS and Products settings (weight/lenght classes etc) all the time shown errors or <b>empty rates</b>. (errors like:110602: Missing/Illegal Combination of Package/Dimensions or XML Parsing Error: not well-formed)
![ups-config](https://cloud.githubusercontent.com/assets/2631910/6184114/68bbf8ea-b390-11e4-99c6-0f0cd2d3a5be.png)

Main problem - absent help for this extension and example with worked settings combination

Also warnings in eror log - warning: AbanteCart core v.1.2.1 Invalid argument supplied for foreach() in <b>/xxxxxx/htdocs/abc121_m02d13/extensions/default_ups/admin/view/default/template/pages/extension/default_ups.tpl</b> on line <b>39</b>

**Comment by furqanproductive** [comment]
You need to use Weight Class pound and Length Class Inch
then it will work
