### ISSUE TITLE
product weight and option value weight calculation

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#871]
Issue in weight calculation if product have few options with weight set in values.
What is the best way calculations:
1. Ignore parent weight and sum of all option's values weights?
2. Calculate total of parent weight plus sum of all option's values weights?
Note: issue visible if set option's values weight class (not percentage)
![2017-05-15_19-19-20](https://cloud.githubusercontent.com/assets/2631910/26057907/c198e5c0-39a5-11e7-8a75-eeaa2126695d.png)

**Comment by abolabo** [comment]
no. weight can summarize only when it was set as % by base weight. Static weight will taken from first option. i think all correct here
