### ISSUE TITLE
product size and option value - different sizes and prices for the same product

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#872]
Admin front:
1. Navigate to Catalog -> Products -> Choose One Product -> Edit -> General
2. Configure Price as 50.00. Click on Save
3. Navigate to Promotions -> Specials. Click on Add Special. Configure Price as 40.00 and click on save.
4. Navigate to Options. Click on New Option (+) button.
5. Choose Size from **- Add New Option -** select box. Click on Add
6. Click on Add (+) button under Option Values.
7. Click on default radio box. Choose 30 ml from Option Value. Set Quantity 10. Set Price Modifier 0.00
8. Click on Add (+) button under Option Values.
9. Choose 50 ml from Option Value. Set Quantity 10. Set Price Modifier 2.00
10. Click on Add (+) button under Option Values.
11. Choose 75 ml from Option Value. Set Quantity 10. Set Price Modifier 4.00
12. Click on Save

Navigate to Storefront:
1. You will be able to see Product price as $40.00 <strike>$50.00</strike>. Default select Size as 30ml 10 in Stock. Total Price as $40.00
2. If you choose 50ml from the select box, you will be able to see Product price as $40.00 <strike>$50.00</strike>. Total Price as $42.00
3. If you choose 75ml from the select box, you will be able to see Product price as $40.00 <strike>$50.00</strike>. Total Price as $44.00

**Issue**
I am not able to configure different prices as per their configured sizes 30ml, 50ml and 75ml
_If I will choose 30ml then_ 
Base Price should display as $40 <strike>$50</strike>
Total Price should display as $40
Product description should get changed to BeneFit Girl Meets Pearl, 30ml

_If I will choose 50ml then_
Base Price should display as $68 <strike>$90</strike>
Total Price should display as $68
Product description should get changed to BeneFit Girl Meets Pearl, 50ml

_If I will choose 75ml then_
Base Price should display as $72 <strike>$110</strike>
Total Price should display as $72
Product description should get changed to BeneFit Girl Meets Pearl, 75ml

**Comment by BasaraABC** [comment]
Did we understand you correctly you want to ignore special price if some option value selected?
And how you expect "choose 50ml then" "Total Price should display as $68 ~$90~"? How you calculate this if your 50 ml price modifier $2.00?

**Comment by hb007006** [comment]
No...

I want different price and special price in all three cases 30ml, 50ml and 75ml. In this case price modifier should not be applied. Screenshots attached for your reference

![30ml](https://cloud.githubusercontent.com/assets/22338790/26112739/55798e5e-3a76-11e7-8009-6925a0e3b589.png)

![50ml](https://cloud.githubusercontent.com/assets/22338790/26112752/5dc1cd1a-3a76-11e7-9196-7efb62c4e0dd.png)

![75ml](https://cloud.githubusercontent.com/assets/22338790/26112761/60c00072-3a76-11e7-9681-977ae438eaad.png)

Product description also should get changed to BeneFit Girl Meets Pearl, 30ml, BeneFit Girl Meets Pearl, 50ml, BeneFit Girl Meets Pearl, 75ml respectively.

I am not able to configure different prices as per their configured sizes 30ml, 50ml and 75ml
If I will choose 30ml then
Base Price should display as $40 [s]$50[/s]
Total Price should display as $40 [s]$50[/s]
Product description should get changed to BeneFit Girl Meets Pearl, 30ml

If I will choose 50ml then
Base Price should display as $68 [s]$90[/s]
Total Price should display as $68 [s]$90[/s]
Product description should get changed to BeneFit Girl Meets Pearl, 50ml

If I will choose 75ml then
Base Price should display as $72 [s]$110[/s]
Total Price should display as $72 [s]$110[/s]
Product description should get changed to BeneFit Girl Meets Pearl, 75ml

**Comment by BasaraABC** [comment]
Sorry it is not a bug. Please report only bugs or issues and Don't report feature suggestions or any customs.
Feel free to share your ideas or suggest anything in AbanteCart community forum http://forum.abantecart.com/index.php?board=25.0
