### ISSUE TITLE
cant upload image

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#874]
Please try to upload attached image to the products media on dev06 server.
I see uploading process but when 100% reached nothing happen. No warnings shown.
And if you go to Media library page it is broken.
![2017-05-16_17-23-59](https://cloud.githubusercontent.com/assets/2631910/26102223/55d62afa-3a5e-11e7-821c-0de077c65df8.png)

`error: AbanteCart core v.1.2.11 Allowed memory size of 67108864 bytes exhausted (tried to allocate 24000000 bytes) in <b>/htdocs/abc1211_m05d16nodata/core/lib/image.php`

[300x2000-text.png.zip](https://github.com/abantecart/abantecart-src/files/1004028/300x2000-text.png.zip)

**Comment by BasaraABC** [comment]
Looks like this is same issue http://forum.abantecart.com/index.php/topic,5632.msg24394.html#msg24394
Please reply after fix

**Comment by smggunsstore** [comment]
No one knows what to do with this?  I'm still having the same trouble.

**Comment by abolabo** [comment]
This issue related to GD2 php-library bug. @smggunsstore please prodvide info about your php version and version of gd2 in it.

**Comment by abantecart** [comment]
This issue is related to olde PHP and GD library. Backend process will be added in v2.0 to regenerate thumbnails

**Comment by smggunsstore** [comment]
Added in version2?  so does this mean that until the newer version of Abantecart is released, that this will continue to be an issue?  Can I not fix it on my site now?

**Comment by abantecart** [comment]
This is not an AbanteCart issue.
This problem is  related to server configuration. 
Issue observed on older PHP 5.3.x and older DG library. 
In v 2.0 minimum support for PHP will be increased. 

Additionally, better approach to image resizing will be explored. 

You can upgrade to newer PHP and GD and increase PHP operating memory.
