### ISSUE TITLE
cross origin admin login

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#875]
1. install cart with demo data
2. close all browser windows (FireFox 53)
3. Clear all browser caches
4. Close / Reopen browser
5. Go to admin via **HTTPS** https://dev06*****/abc1211_m05d17login/index.php?s=your_admin
6. enter credentials and login is success
7. change url protocol from https to http. You will be asked to enter admin login credentials again
8. Enter correct credentials and try to login
9. Bug: nothing happen, page reloaded and ask for login again without any warning or errors

**Comment by abolabo** [comment]
In secure mode we use secure flag for session cookie.Cookie with secure flag won't be sent via an unencrypted connection. It will blocked by browser and case is the same as pure first visit of login page.
We cannot to recognize this case. Just do not switch in non-secure mode manually.

**Comment by BasaraABC** [comment]
So we cannot detect Unsuccessful login attempt?

**Comment by abolabo** [comment]
yes, in this case we can't.

**Comment by BasaraABC** [comment]
Issue is not fixed for me.
I use step by step from initial report

**Comment by abolabo** [comment]
Note: before test you should to delete session cookies!

**Comment by BasaraABC** [comment]
Cookies were deleted before test. Read initial step by step guide to replicate issue. 
All browser caches removed before first login

**Comment by abantecart** [comment]
Let's discuss on Monday

**Comment by abantecart** [comment]
Need to add comment to users to clear Cache and Cookies in the browser if login issue occurs.
