### ISSUE TITLE
captcha issue FireFox OS X

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#876]
captcha not work correctly in Firefox 53 os x. Work in other browsers.
<img width="819" alt="2017-05-17_15-00-10" src="https://cloud.githubusercontent.com/assets/2631910/26144467/1f26542a-3b13-11e7-9f55-00ee54e1b9fa.png">

Note: in other browser page loaded with one captcha image and after page load completed loaded updated captcha image. But not in firefox and for this reason it doesnot work

### Chrome
![2017-05-17_15-14-57](https://cloud.githubusercontent.com/assets/2631910/26144640/d035c322-3b13-11e7-8b16-e2f47c8bf340.png)

### FF
![2017-05-17_15-19-53](https://cloud.githubusercontent.com/assets/2631910/26144806/77778166-3b14-11e7-91cb-d231749c7eac.png)

**Comment by abolabo** [comment]
had tried to replicate on browserstack.com.
all 3 issue cannot to replicate on it.
Note: Browser uses request method HEAD (see screenshot) for getting size to compare with captcha image in the it's own cache

**Comment by BasaraABC** [comment]
related #155

**Comment by BasaraABC** [comment]
See if this compare headers screenshot help you.
FF in the top: not work
Chrome in the bottom: work
![2017-06-22_14-20-41](https://user-images.githubusercontent.com/2631910/27421951-b90f7814-5756-11e7-8c7b-1cbcfdb43c6a.png)

**Comment by abolabo** [comment]
we cannot affect on browser caching mechanism

**Comment by BasaraABC** [comment]
Issue with captcha fixed. But because of javascript/retina.min.js removed now retina Logo is not work

**Comment by abantecart** [comment]
Why is it closed?

**Comment by BasaraABC** [comment]
it was closed because captcha issue is fixed.
Retina images in admin now also work but in different way.
