### ISSUE TITLE
Reduce warning in the message system

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#877]
toMessages  56 in 27 files (github search https://github.com/abantecart/abantecart-src/search?utf8=%E2%9C%93&q=toMessages+path%3Apublic_html&type=)

$this->messages 19 (github search https://github.com/abantecart/abantecart-src/search?utf8=%E2%9C%93&q=%22%24this-%3Emessages%22+path%3Apublic_html&type=)

### List of messages for review. I think we can move them to system log. 

1. Admin SendPoint ' . $name . ' cannot be added to the list
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/im_manager.php#L86

2. IM error: Invalid SendPoint ' . $sendpoint . ' was used in IM class.
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/im_manager.php#L118

3. Resize image error. File:
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/storefront/model/tool/image.php#L51

4. Resize image error. File
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/storefront/model/tool/image.php#L60

5. Image Resize Error: file
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/admin/model/tool/image.php#L42

6. Error: Cannot send email. Unknown address or empty message
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/admin/controller/task/sale/contact.php#L210

7. Error: Cannot send sms. Unknown phone number
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/admin/controller/task/sale/contact.php#L261

8. aMySQLi class error: Try to escape non-string value
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/database/apdomysql.php#L112

9. SendPoint ' . $name . ' cannot be added to the list
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/im.php#L228

10. IM error: Unrecognized SendPoint
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/im.php#L271

11. Cannot open " . TRANSACTIONS_LOG_FILE . " file
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/extensions/default_fedex/core/lib/fedex_func.php#L43

12. aMySQLi class error: Try to escape non-string value
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/database/amysqli.php#L123

13. MySQL class error: Try to escape non-string valu
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/database/mysql.php#L133

14 Cache storage driver ' . $cache_driver . ' can not be loaded
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/config.php#L115

15. Warning: Accessing store with non-configured or unknown domain
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/config.php#L210

16. Unable to download file
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/download.php#L347

17. Error: URL: ' . $url . ' Could not load controller
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/dispatcher.php#L229

18. Error: cannot to load config.xml of extension
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/helper/utils.php#L500

19. Not described error
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/language.php#L170

20. Error! Default language with code "' . $lang_code . '" is not available
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/language.php#L353

21. Image file ' . $this->file . ' cannot be resized. Try to decrease original image
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/image.php#L275

22. Resize image error.
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/resources.php#L345

23. Resize image error
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/resources.php#L353

24. Template ' . $template . ' is not found - roll back to default
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/init.php#L469

25. Incorrect character set encoding of file
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/admin/controller/pages/tool/package_installer.php#L754

26. $ext . ' directory is missing
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/extensions.php#L300

27. Not sure about this.
Mailer error!', 'Can\'t send emails.
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/mail.php#L170

28. Check favicon.','Warning: please check favicon in your store 
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/storefront/controller/common/head.php#L67

29. Cannot enable extension
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/lib/extension_manager.php#L274

30. New language definition adding error
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/admin/model/localisation/language_definitions.php#L48

31. Error: Error in data of page with controller
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/layout.php#L190

**Comment by abolabo** [comment]
reduced except https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/layout.php#L190
it's a critical issue.

**Comment by BasaraABC** [comment]
@abantecart can you please review.

**Comment by abantecart** [comment]
I added my comments. Some of removed messages are needed.

**Comment by abantecart** [comment]
Regarding this:
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/core/engine/layout.php#L190
This text is only for technicians. Make sure there is no message and only log
