### ISSUE TITLE
dev: Fedex and store weight class

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#879]
related to #859  
If change Store Weight class then fedex return different delivery prices for same product.

Looks like same bug will be in Parcelforce, Royal mail, UPS, Weight Based Shipping
![2017-05-23_17-01-50](https://cloud.githubusercontent.com/assets/2631910/26349655/91d1f81e-3fda-11e7-9bf8-6496081fef17.png)

**Comment by abolabo** [comment]
no. other shippings works correctly
