### ISSUE TITLE
adding Shared downloads to product

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#88]
No way to add 2 shared downloads to one product. To replicate add shared download to product (product edit page - Files Tab), then reload page and add another shared download. In result only one latest added shared download in list

**Comment by abantecart** [comment]
Fixed.

**Comment by BasaraABC** [comment]
Debug information in error log after <b>Create new download</b> popup appear. Please fix
![shared](https://cloud.githubusercontent.com/assets/2631910/6244135/b7b31f06-b781-11e4-85da-86ea567b3c34.png)

**Comment by abolabo** [comment]
fixed
