### ISSUE TITLE
admin order recalculation issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#880]
Total is incorrect if click recalculate. To replicate please add same products
Note: in screenshot same customer within Wholesale customer group
![2017-05-25_16-15-00](https://cloud.githubusercontent.com/assets/2631910/26444260/e39665ea-4165-11e7-8278-50c189d70ac9.png)

**Comment by abolabo** [comment]
The cause in unavailable products for sale. I excluded these products from selectbox for adding, but some of them can be presents in order. so reviewing after change still required
