### ISSUE TITLE
Unable to donwload file in account/downloads area

### ISSUE THREAD

**Issue by MarbasFR** [abantecart/abantecart-src#882]
If i put a mask like : **test don't work.pdf** i can only get the first 8kb of the file due to an SQL error.

To correct this problem I do the following changes to the file /core/lib/download.php at line 403 :
**'" . addslashes($download_info['mask']) . "',**

**Comment by abantecart** [comment]
Probably this is because of using apostrophe in the text. We will check. 

Thank you for reporting.

**Comment by BasaraABC** [comment]
Still problems here with mask like **Hànyǔ_or_中文;_Zhō_漢語_ngwén.csv**
Download file without  file extension and much less chars in name. 
![2017-06-08_14-54-18](https://user-images.githubusercontent.com/2631910/26918047-94329046-4c5a-11e7-9dfa-b53eaf8821a7.png)

**Comment by abantecart** [comment]
We should not allow files with non-latin characters.

**Comment by abolabo** [comment]
all non-latin chars will be removed from download "mask". In case when mask filename contains only non-latin chars resource name will be taken.

**Comment by BasaraABC** [comment]
Issue is fixed.  Bug closed.
However in my opinion it is not the best solution.
