### ISSUE TITLE
Admin front: Product Name search is not working, if use & keyword in product

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#883]
1. Login into Admin Panel
2. Navigate to Catalog -> Products
3. Click on Add button
4. Type Product Name as **Absolue Eye & Hand Precious Cells**
5. Click on Generate button for SEO Keyword. It won't work properly. Evidence attached
6. Click on Save
7. Navigate to Catalog -> Products and type **Absolue Eye & Hand Precious Cells** in Product Name box or Search for Product input box
8. No result found will appear

![1](https://cloud.githubusercontent.com/assets/22338790/26787235/ea50cafa-4a26-11e7-9295-e5b185e7596e.png)

![2](https://cloud.githubusercontent.com/assets/22338790/26787243/f1d620e0-4a26-11e7-8dcf-0fb69ab0fe1f.png)

![3](https://cloud.githubusercontent.com/assets/22338790/26787256/f9baba00-4a26-11e7-98b9-0bbe40b35c2a.png)

**Comment by abantecart** [comment]
Issue is confirmed. 
Problem with grid lookup and & (ampersand) encoding 
"Absolue Eye & Hand Precious Cells"

**Comment by BasaraABC** [comment]
Can you please add better UTF-8 (or UTF-16) support?
![2017-06-08_15-03-37](https://user-images.githubusercontent.com/2631910/26918343-d32ac880-4c5b-11e7-96f5-74363badc5c5.png)

**Comment by BasaraABC** [comment]
Still problems with french. Try "L'EXTRÊME"
![2017-06-28_13-02-57](https://user-images.githubusercontent.com/2631910/27622597-478eb01e-5c02-11e7-948b-e179820092df.png)

**Comment by BasaraABC** [comment]
Still not work. **L'EXTRÊME** refine key can not find "L'EXTRÊME Instant Extensions Lengthening Mascara" product in grid
