### ISSUE TITLE
Storefront: No option available to subtract item from cart from thumbnail

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#884]
1. Navigate to Storefront home page
2. Click on add to cart button twice and you will find two items in your cart
3. There is no option available to subtract item from cart from thumbnail. It is a basic feature which is not available

![1](https://cloud.githubusercontent.com/assets/22338790/26787688/8f312686-4a28-11e7-9c92-7417fa1642a4.png)
![2](https://cloud.githubusercontent.com/assets/22338790/26787689/9100c8fe-4a28-11e7-814c-ea3480a61514.png)

**Solution should be:**
![3](https://cloud.githubusercontent.com/assets/22338790/26787695/9363d3e8-4a28-11e7-8766-1153f019d85a.png)

**Comment by abantecart** [comment]
Are you sure you do not hame minimum quality of 2 set for this product?

**Comment by hb007006** [comment]
No... minimum quantity is 1 set for this product.

What I am trying to say is we can add items, as many as we want, into cart from thumbnail via clicking on Add to Cart button. For example
If you click Add to Cart button only once then you will have 1 item in your cart.
If you click Add to Cart button 2 times then you will have 2 items in your cart.
If you click Add to Cart button 3 times then you will have 3 items in your cart.
and so on...

However there is no option to subtract / remove item from thumbnail itself. For example I have clicked Add to Cart button 4 times then 4 items will be added to cart. Later I realize and I want to remove 1 item from cart then I can not do it from thumbnail.

**Comment by abantecart** [comment]
This is not a bug. This is a feature that is not offered. We can consider this, but that needs to be put for voting.
