### ISSUE TITLE
Update of cart takes up to 5 mins to take effect

### ISSUE THREAD

**Issue by sicsim** [abantecart/abantecart-src#885]
When I delete an item from the cart or try to change the quantity the cart seems to not work until you come back about 5 minutes later,then everything done earlier appears to have worked.

you can try it here www.scipin.co.za

If anyone knows what's causing this I'd appreciate.

**Comment by BasaraABC** [comment]
Please set your store url in admin setting to http://**www**.scipin.co.za/
Now looks like you have http://scipin.co.za/
Please create topic in http://forum.abantecart.com/ if you need more help with this issue
