### ISSUE TITLE
"null" title and warning in log

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#886]
If in the global search results will be product with name like "Hànyǔ or & 中文; Zhōngwén file  Allegiant by Veronica Roth"
"null" title and warning in log
![2017-06-08_15-25-51](https://user-images.githubusercontent.com/2631910/26926840-6a7346c8-4c79-11e7-8b39-d3b1d52889ca.png)

**Comment by abolabo** [comment]
needs more details how to replicate

**Comment by BasaraABC** [comment]
"null" title issue is fixed but warning in the log
`warning: AbanteCart core v.1.2.11 htmlentities() [<a href='function.htmlentities'>function.htmlentities</a>]: Invalid multibyte sequence in argument in <b>htdocs/abc1211_m06d29/admin/controller/responses/listing_grid/global_search_result.php</b> on line <b>149</b>`
