### ISSUE TITLE
Admin: "Category Name" search is not working for sub-categories

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#887]
1. Login into Admin Panel
2. Navigate to Catalog > Categories
3. Type Cheeks in "Category Name" search box and hit enter
4. No result  found will be displayed

![1](https://user-images.githubusercontent.com/22338790/26940721-67e0b2d6-4c99-11e7-9a6c-dd08cbe712ae.png)
![2](https://user-images.githubusercontent.com/22338790/26940723-68d1975a-4c99-11e7-809a-b75bee8345fd.png)

**Comment by BasaraABC** [comment]
I think this is common grid issue. It was already fixed for Content pages grid #858 
@abolabo  please apply fix for all grids

**Comment by BasaraABC** [comment]
Categories Grid is broken. All subcategories showed as parent
![2017-06-21_16-23-46](https://user-images.githubusercontent.com/2631910/27377061-1598cd74-569e-11e7-8aea-2ef3348420c1.png)

**Comment by BasaraABC** [comment]
Again issue is Not fixed. See new screenshot
![2017-06-22_15-44-37](https://user-images.githubusercontent.com/2631910/27425207-de1249ce-5761-11e7-82bc-2ac14f41392d.png)

**Comment by abolabo** [comment]
it's correct. Shoes is not top-level category. Try to search by all
