### ISSUE TITLE
maintenance mode: success message duplicate

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#894]
After admin save any extension the success message shown all the time on almost any page
![2017-06-20_14-47-01](https://user-images.githubusercontent.com/2631910/27322349-04bd21ac-55c8-11e7-9fb9-b709146e7b77.png)

**Comment by BasaraABC** [comment]
related to Maintenance mode

**Comment by abolabo** [comment]
related to #894 too
