### ISSUE TITLE
Error with no description when installing

### ISSUE THREAD

**Issue by Loggan08** [abantecart/abantecart-src#898]
![namnlos](https://user-images.githubusercontent.com/7104301/27499234-3805fb0e-5863-11e7-81ad-e4c62c99b7c3.png)

Getting this on my site, i've tried 4-5 times without success, installs regularly through softacolous but I dont want the demo data.

my site is https://lolupdater.com

also there seems to be some issues with admin login and https (I can get around them by loading insecure scripts)

**Comment by abantecart** [comment]
How is this a bug? This is an issue with the server configuration or compatibility. 
This is a bug tracker only. 
Please refer to forum for help.
