### ISSUE TITLE
Relative URL link does not work. 

### ISSUE THREAD

**Issue by abantecart** [abantecart/abantecart-src#899]
Try to create a URL link relative to the site. (NO domain) 

Actually link will look like this on SF:
/index.php?rt=/blog/index.php

![screen shot 2017-06-24 at 9 56 00 am](https://user-images.githubusercontent.com/1239995/27509118-a2f8f01e-58c3-11e7-8ee9-ff16685433aa.png)

**Comment by abolabo** [comment]
see help text for details

**Comment by BasaraABC** [comment]
Issue reopened. There is warning in log if add menu item with ../text  url
 `warning: AbanteCart core v.1.2.11 ltrim() [<a href='function.ltrim'>function.ltrim</a>]: Invalid '..'-range, no character to the left of '..' in <b>/htdocs/abc1211_m06d28/storefront/controller/blocks/menu.php</b> on line <b>73</b>`
