### ISSUE TITLE
UI selection

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#90]
for users not clear how to select in new UI (Data Listing Block - custom brands and others..) see http://forum.abantecart.com/index.php/topic,3269.msg13990.html#msg13990
Please add help notice text something like "Type beginning of the name to look up and select"
![ui](https://cloud.githubusercontent.com/assets/2631910/6223854/aae90b6a-b6a4-11e4-9adb-0a4faa6bba05.png)

**Comment by abantecart** [comment]
Text: "Start typing beginning of the name and select matching result(s)"

**Comment by abolabo** [comment]
it is present there. Just some js set width of this input to 25px

**Comment by abolabo** [comment]
fixed
