### ISSUE TITLE
clone product and custom layout

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#901]
There is a problem or misunderstanding. When user clone product the custom layout also cloned. Looks like users do not expect this behavior.
Need to discuss

**Comment by abolabo** [comment]
added note into "success" text in case when original product have custom layout

**Comment by abantecart** [comment]
Can you please post the screenshot what the note looks like?

**Comment by abolabo** [comment]
![2017-07-04 19-13-59](https://user-images.githubusercontent.com/1264239/27837499-4ed91176-60ed-11e7-8ca8-1b666ac1d491.png)
