### ISSUE TITLE
Price-based shipping extension wiping entries

### ISSUE THREAD

**Issue by barry819** [abantecart/abantecart-src#903]
I created a price-based shipping routine in this extension for the US, and it works fine. I am now attempting to create a version for Canada. I have created a location, Canada, which includes all provinces.

When I attempt to edit the additional settings for the shipping name Canada, (img 1). I can enter the rates I want, and turn Canada's status to ON (img 2). However, if I then SAVE the settings, the rates I entered get wiped away and Canada is turned OFF.

Why is the data entered for Canada being wiped? Why is saving it instead deleting it?

This is Price-based Shipping version 1.1 being used with Abantecart 1.2.10.   www.TheresaMatherFantasyShop.com

![abante 1](https://user-images.githubusercontent.com/29803134/27748718-ab6c0c6c-5d8d-11e7-8009-25217c0c0ea6.jpg)
![abante 2](https://user-images.githubusercontent.com/29803134/27748720-ab848eea-5d8d-11e7-9452-de37ded10548.jpg)
![abante 3](https://user-images.githubusercontent.com/29803134/27748719-ab72e85c-5d8d-11e7-8d1b-80af20f3c3fb.jpg)

**Comment by BasaraABC** [comment]
Hello. Price based shipping is 3rd party extension. Please contact extension developer for support
https://marketplace.abantecart.com/index.php?rt=product/vendor_product/support&product_id=157
