### ISSUE TITLE
Language definition "text_sub_total" is missing

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#905]
Missing language definition. I think it is on Order Edit page
`AbanteCart engine cannot find value of language definition with key "text_sub_total" in /abc1211_m07d05/storefront/model/total/sub_total.php line 52 (rt=sale/order/recalc).`

**Comment by BasaraABC** [comment]
Not sure why but in new test 2 missing definitions. To replicate add product to order (in admin)
Language definition "text_description" is missing
`engine cannot find value of language definition with key "text_description" in /abc1211_m07d05v3/extensions/default_flat_rate_shipping/storefront/model/extension/default_flat_rate_shipping.php line 74 (rt=sale/order/recalc). `

Language definition "text_title" is missing
`AbanteCart engine cannot find value of language definition with key "text_title" in /abc1211_m07d05v3/extensions/default_flat_rate_shipping/storefront/model/extension/default_flat_rate_shipping.php line 135 (rt=sale/order/recalc). `

**Comment by abolabo** [comment]
added changes to all shipping extensions models (see commit for details)
