### ISSUE TITLE
Canonical URL issue (SEO issue)

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#908]
URL canonicalization

You can reach product_1 in category_1 both at https://www.example.com/product_1 and https://www.example.com/category_1/product_1 this cause a lot of seo issues in google indexing, it confuses google pretty much. please add a seo friendly category or something or a canonized url option, so i can set preferred URL (shortest version only, or deepest sub-category url).

**Comment by BasaraABC** [comment]
I think we need add canonical tag 
https://moz.com/learn/seo/canonicalization

**Comment by kolynet** [comment]
yes, that is correct!

**Comment by kolynet** [comment]
if you have some temporary source to implement for testing, please paste it.

**Comment by BasaraABC** [comment]
Issue is not fixed. I did not see canonical url tag on product pages. No matter seo urls ON or OFF there is no canonical url on page source

**Comment by BasaraABC** [comment]
There are many urls can be used for products so in my opinion all should have one canonical url.
For example here is the list of one product url (It can be much more)

**Comment by BasaraABC** [comment]
One more note: I think we need separate setting for canonical url

**Comment by abantecart** [comment]
There should be 2 conditions here.
1. SEO ON.
URL to product with SEO domain.com/URL/

2. SEO OFF
URL to product directly  domain.com/index.php?product_id=xxx

**Comment by BasaraABC** [comment]
I did not see canonical tag on product page. Fresh install 1.2.11

**Comment by BasaraABC** [comment]
Issue is not fixed, now we have 2 tags
![2017-09-04_17-35-05](https://user-images.githubusercontent.com/2631910/30022914-9b58baf8-9197-11e7-9643-a867558b7743.png)

**Comment by abolabo** [comment]
what's the problem? 
we need to show canonical url with seo-keyword 
and url with product_id for pages with product_id and some additional parameters such as filters. In that case we need 2 tags.

**Comment by abantecart** [comment]
There should be only 1 canonical tag on all same pages, regardless of entry point (URI). 
Put there direct URL with product_id=[number]

We discussed this on the call, there is a requirement above from me. 

I do not understand what else is not clear here.

**Comment by BasaraABC** [comment]
Bug when SEO Urls enabled in store.
If visit product from category page like
http://localhost/abantecart/cheeks/benefit-girl-meets-pearl
the canonical url will be wrong
![2017-09-06_14-19-46](https://user-images.githubusercontent.com/2631910/30099046-9e3e26b8-930e-11e7-8f0c-9b8712216bbf.png)

**Comment by BasaraABC** [comment]
even worse than before. Now regular url index.php?rt=product/product&product_id=51 in tag when SEO urls enabled. And vise versa see screenshot

![2017-09-06_20-20-59](https://user-images.githubusercontent.com/2631910/30114172-3c358abe-9341-11e7-86b2-751b34533e11.png)

**Comment by abantecart** [comment]
What is going on?

**Comment by BasaraABC** [comment]
After one more round of discussion. Follow next rules:
*if SEO Url enabled in the store = show canonical tag

_next rules is what to show in the tag:_
*the value for canonical tag is: if seo key exist for product tag value 
http://localhost/product-seo-key
if product have not seo key please put in value regular url with ID
http://localhost/index.php?rt=product/product&product_id=136

Hope this is clear

**Comment by kolynet** [comment]
was this fixed lately? if so, please could you quote in the changes or link to mod? thanks:)

**Comment by BasaraABC** [comment]
Canonical urls added in 2017. All changes in commits attached. (search "added a commit" on this page)

**Comment by kolynet** [comment]
i still have double lines of canonical url.

**Comment by BasaraABC** [comment]
what is double lines? Can you report with screenshot and all details (AbanteCart version, prodcut seo key etc)

**Comment by kolynet** [comment]
my fault, i had the wrong common/head view page.
