### ISSUE TITLE
SEO base URLs

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#909]
Please fix these URLs:

/index.php?rt=account/forgotten/password
/index.php?rt=account/login
/index.php?rt=account/create

google not rewarding these, htaccess is a temporary fix anyway, but not a solution!

**Comment by BasaraABC** [comment]
It is not a bug. This pages have not any important content for indexing

**Comment by kolynet** [comment]
Not sure, we might close this as bug, just thinking of seo perspective if it can have negative impact at the shop ranking.

**Comment by BasaraABC** [comment]
In my opinion SEO Urls more for humans than google. Do you think google bot make a big difference between pages like:
/index.php?rt=account/login
/login

Note: this is not a product or category or any other important pages with important content for SEO

**Comment by kolynet** [comment]
Yes, i believe there is a minimal positive upside of using the clean seo URL of /login.

https://www.hobo-web.co.uk/search-engine-friendly-urls/
https://moz.com/blog/15-seo-best-practices-for-structuring-urls

But I don't know to be honest, can ask google experts later, have a contact of a google webmaster partner guy. If it's not a big process, it might worth to change these URLs.

**Comment by abantecart** [comment]
URLs that you listed are account specific URLs. There is no SEO provided for account specific URLs.

**Comment by abantecart** [comment]
I do not think we need to discuss this.
