### ISSUE TITLE
Skrill minor issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#91]
Skrill payment ignore Order status settings see screenshot
![skrill](https://cloud.githubusercontent.com/assets/2631910/6267118/d6b7cdd2-b873-11e4-9bc8-4650b145e46d.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Can not check fixes on new cart installation - Skrill block all new orders see screenshot. Ref# not unique (now used order id) this will cause problems for users when move from test to live store. See screenshot
![skrill-ref](https://cloud.githubusercontent.com/assets/2631910/6287424/f96285f4-b943-11e4-8ff8-6144fc179e81.png)

**Comment by abolabo** [comment]
fixed?

**Comment by BasaraABC** [comment]
issue not fixed http://dev06.xxxxxxxx.net/abc122_m03d30/

**Comment by abolabo** [comment]
can not to replicate on 1.2.2.

**Comment by BasaraABC** [comment]
I replicate it in latest 122 see failed order http://dev06.*********/abc122_m05d19/index.php?rt=sale/order/details&order_id=14&s=your_admin

**Comment by abolabo** [comment]
fixed?

**Comment by BasaraABC** [comment]
fixed in 1.2.2
