### ISSUE TITLE
improve read messages behaviour

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#913]
I think we need to hide already read messages from dropdown. It is annoying
We need to show only new
![2017-07-21_19-22-56](https://user-images.githubusercontent.com/2631910/28463475-c7e45d36-6e4a-11e7-9eee-788df4cff941.png)

**Comment by abantecart** [comment]
Valid point. Let's see how we can do this

**Comment by BasaraABC** [comment]
Issue is not fixed right. If only one message all looks ok - the read message hidden. But when you have new unread message dropdown again show read messages please see screenshot
![2017-08-30_13-32-57](https://user-images.githubusercontent.com/2631910/29858518-f66f4a88-8d87-11e7-8061-037069a60333.png)

**Comment by BasaraABC** [comment]
Again broken. Now **unread** messages not visible too. See screenshot
![screen shot 2017-08-31 at 12 20 00](https://user-images.githubusercontent.com/2631910/29907651-d3e93e28-8e46-11e7-96de-50711a3ea023.png)
