### ISSUE TITLE
unable to generate embed codes

### ISSUE THREAD

**Issue by Aquapyrofan** [abantecart/abantecart-src#915]
The button to generate an embed code to use on a site other than our store page is missing after turning the option to enable embedding on.  Button remains missing even after turning the option off and on repeatedly, and after checking for conflicts and finding none.

**Comment by BasaraABC** [comment]
When you turn option on. Save and reload page. Is it still ON?
What is your cart version?
Do you have related errors in the AbanteCart error log?

**Comment by Aquapyrofan** [comment]
The option remains on after reloading.  we are on version 1.2.10, and there are no relevant errors in the log.

**Comment by BasaraABC** [comment]
First clear AbanteCart cache and see if this help.
If not you need to find **config_embed_status** key value in database

**Comment by Aquapyrofan** [comment]
just to clarify, clearing the cache will not actively harm any items, categories, or other such things that have been created in the store, yes?

**Comment by Aquapyrofan** [comment]
clearing the cache fixed the issue.  thank you for the assistance.
