### ISSUE TITLE
dev: backup step 2 never completed

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#917]
Fresh install 1.2.11 on localhost PHP Version 5.6.30 (Apache/2.4.25 (Unix) )

Backup step 2 running infinitely and never completed see error from log
`AbanteCart core v.1.2.11 FilesystemIterator::__construct(/htdocs/admin/system/backup/manual_backup_20170731_083801/files/admin\system\backup\manual_backup_20170731_083801): failed to open dir: No such file or directory in <b>/htdocs/core/lib/backup.php</b> on line <b>564</b>`

Take a note: **manual_backup_20170731_083801** directory is created.
If script cannot access folder why task not fail?

![2017-07-31_13-43-16](https://user-images.githubusercontent.com/2631910/28765723-65fad98e-75f6-11e7-9afa-21642aa7a123.png)

**Comment by BasaraABC** [comment]
See screenshot - folder exist with files. But filenames looks too long. Is it designed this way?
![2017-07-31_13-51-17](https://user-images.githubusercontent.com/2631910/28766016-cee28068-75f7-11e7-9152-8256ee319dc5.png)

**Comment by abolabo** [comment]
You tried to run it under Windows, not unix! Please check fix

**Comment by BasaraABC** [comment]
it is OS X . I will recheck

**Comment by BasaraABC** [comment]
Issues is not fixed. There are still all files saved with full path in name (see screenshot above) and same error on log.
`2017-08-30 10:43:23 - : AbanteCart core v.1.2.11 FilesystemIterator::__construct(/XAMPP/xamppfiles/apps/abantecart/htdocs/admin/system/backup/manual_backup_20170830_104319/files/admin/controller/api/common): failed to open dir: No such file or directory in <b>/XAMPP/xamppfiles/apps/abantecart/htdocs/core/lib/backup.php</b> on line <b>567</b>`

### For you info:
XAMPP Install on OS X (unix)
All abantecart files and folder set to full read.write for anyone

### PHP info:
PHP Version 5.6.30
System: Darwin local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 
Apache Version : Apache/2.4.25 (**Unix**) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3

**Comment by abolabo** [comment]
macOS related bug

**Comment by BasaraABC** [comment]
You have IS_WINDOWS twice in the code. Thats why last changes not work
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/index.php#L36
and this
https://github.com/abantecart/abantecart-src/blob/1.2.11/public_html/task.php#L33

**Comment by abolabo** [comment]
you right. krasava)
