### ISSUE TITLE
price inc tax and estimate

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#919]
Price inc tax should be visible only when Tax is applied so here example
![2017-08-02_16-24-57](https://user-images.githubusercontent.com/2631910/28867181-67179a1e-779f-11e7-8941-757e1e5cea57.png)

**Comment by BasaraABC** [comment]
It is confuse. For Guests we should apply "Default Store Tax Rate" for store address but as you can see tax not applied because 'Estimate' block disabled. 
So in my opinion we should:
A: according to settings if no address provided yet by customer we use "Default Store Tax Rate" for store address and add this tax to Shopping cart even if estimate block disabled
or
B: hide 'inc Tax' till address will be entered and tax added to cart

**Comment by abantecart** [comment]
As discussed, add additional check if tax actually applied to the price on the product page. If no tax is applied, do not show text "Inc Tax"
