### ISSUE TITLE
dev: import task steps fail

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#926]
49 of 50 steps of the one import task are fail and No error shown.

### Please see example of file and map export hash
[products_import_my.csv.zip](https://github.com/abantecart/abantecart-src/files/1200193/products_import_my.csv.zip)

### hash:

YTo2OntzOjU6InRhYmxlIjtzOjg6InByb2R1Y3RzIjtzOjEwOiJpbXBvcnRfY29sIjthOjU1OntpOjA7czoxMDoiUHJvZHVjdCBJRCI7aToxO3M6MTI6IkFjdGl2ZSAoMC8xKSI7aToyO3M6NjoiTmFtZSAqIjtpOjM7czoyMToiQ2F0ZWdvcmllcyAoeCx5LHouLi4pIjtpOjQ7czo0MDoiUHJpY2UgdGF4IGV4Y2x1ZGVkIG9yIFByaWNlIHRheCBpbmNsdWRlZCI7aTo1O3M6MTI6IlRheCBydWxlcyBJRCI7aTo2O3M6MTU6Ildob2xlc2FsZSBwcmljZSI7aTo3O3M6MTM6Ik9uIHNhbGUgKDAvMSkiO2k6ODtzOjE1OiJEaXNjb3VudCBhbW91bnQiO2k6OTtzOjE2OiJEaXNjb3VudCBwZXJjZW50IjtpOjEwO3M6MjY6IkRpc2NvdW50IGZyb20gKHl5eXktbW0tZGQpIjtpOjExO3M6MjQ6IkRpc2NvdW50IHRvICh5eXl5LW1tLWRkKSI7aToxMjtzOjExOiJSZWZlcmVuY2UgIyI7aToxMztzOjIwOiJTdXBwbGllciByZWZlcmVuY2UgIyI7aToxNDtzOjg6IlN1cHBsaWVyIjtpOjE1O3M6MTI6Ik1hbnVmYWN0dXJlciI7aToxNjtzOjU6IkVBTjEzIjtpOjE3O3M6MzoiVVBDIjtpOjE4O3M6NjoiRWNvdGF4IjtpOjE5O3M6NToiV2lkdGgiO2k6MjA7czo2OiJIZWlnaHQiO2k6MjE7czo1OiJEZXB0aCI7aToyMjtzOjY6IldlaWdodCI7aToyMztzOjg6IlF1YW50aXR5IjtpOjI0O3M6MTY6Ik1pbmltYWwgcXVhbnRpdHkiO2k6MjU7czoxMDoiVmlzaWJpbGl0eSI7aToyNjtzOjI0OiJBZGRpdGlvbmFsIHNoaXBwaW5nIGNvc3QiO2k6Mjc7czo1OiJVbml0eSI7aToyODtzOjEwOiJVbml0IHByaWNlIjtpOjI5O3M6MTc6IlNob3J0IGRlc2NyaXB0aW9uIjtpOjMwO3M6MTE6IkRlc2NyaXB0aW9uIjtpOjMxO3M6MTU6IlRhZ3MgKHgseSx6Li4uKSI7aTozMjtzOjEwOiJNZXRhIHRpdGxlIjtpOjMzO3M6MTM6Ik1ldGEga2V5d29yZHMiO2k6MzQ7czoxNjoiTWV0YSBkZXNjcmlwdGlvbiI7aTozNTtzOjEzOiJVUkwgcmV3cml0dGVuIjtpOjM2O3M6MTg6IlRleHQgd2hlbiBpbiBzdG9jayI7aTozNztzOjI3OiJUZXh0IHdoZW4gYmFja29yZGVyIGFsbG93ZWQiO2k6Mzg7czozNzoiQXZhaWxhYmxlIGZvciBvcmRlciAoMCA9IE5vLCAxID0gWWVzKSI7aTozOTtzOjIyOiJQcm9kdWN0IGF2YWlsYWJsZSBkYXRlIjtpOjQwO3M6MjE6IlByb2R1Y3QgY3JlYXRpb24gZGF0ZSI7aTo0MTtzOjI4OiJTaG93IHByaWNlICgwID0gTm8sIDEgPSBZZXMpIjtpOjQyO3M6MjE6IkltYWdlIFVSTHMgKHgseSx6Li4uKSI7aTo0MztzOjQwOiJEZWxldGUgZXhpc3RpbmcgaW1hZ2VzICgwID0gTm8sIDEgPSBZZXMpIjtpOjQ0O3M6Mjg6IkZlYXR1cmUoTmFtZTpWYWx1ZTpQb3NpdGlvbikiO2k6NDU7czozOToiQXZhaWxhYmxlIG9ubGluZSBvbmx5ICgwID0gTm8sIDEgPSBZZXMpIjtpOjQ2O3M6OToiQ29uZGl0aW9uIjtpOjQ3O3M6MzA6IkN1c3RvbWl6YWJsZSAoMCA9IE5vLCAxID0gWWVzKSI7aTo0ODtzOjM0OiJVcGxvYWRhYmxlIGZpbGVzICgwID0gTm8sIDEgPSBZZXMpIjtpOjQ5O3M6Mjk6IlRleHQgZmllbGRzICgwID0gTm8sIDEgPSBZZXMpIjtpOjUwO3M6MTI6Ik91dCBvZiBzdG9jayI7aTo1MTtzOjE3OiJJRCAvIE5hbWUgb2Ygc2hvcCI7aTo1MjtzOjI1OiJBZHZhbmNlZCBzdG9jayBtYW5hZ2VtZW50IjtpOjUzO3M6MTY6IkRlcGVuZHMgT24gU3RvY2siO2k6NTQ7czo5OiJXYXJlaG91c2UiO31zOjE1OiJwcm9kdWN0c19maWVsZHMiO2E6NTU6e2k6MDtzOjA6IiI7aToxO3M6MTU6InByb2R1Y3RzLnN0YXR1cyI7aToyO3M6MjU6InByb2R1Y3RfZGVzY3JpcHRpb25zLm5hbWUiO2k6MztzOjE5OiJjYXRlZ29yaWVzLmNhdGVnb3J5IjtpOjQ7czoxNDoicHJvZHVjdHMucHJpY2UiO2k6NTtzOjA6IiI7aTo2O3M6MTM6InByb2R1Y3RzLmNvc3QiO2k6NztzOjA6IiI7aTo4O3M6MDoiIjtpOjk7czowOiIiO2k6MTA7czowOiIiO2k6MTE7czowOiIiO2k6MTI7czowOiIiO2k6MTM7czowOiIiO2k6MTQ7czoyNjoibWFudWZhY3R1cmVycy5tYW51ZmFjdHVyZXIiO2k6MTU7czowOiIiO2k6MTY7czoxMjoicHJvZHVjdHMuc2t1IjtpOjE3O3M6MTQ6InByb2R1Y3RzLm1vZGVsIjtpOjE4O3M6MDoiIjtpOjE5O3M6MTU6InByb2R1Y3RzLndlaWdodCI7aToyMDtzOjE1OiJwcm9kdWN0cy5oZWlnaHQiO2k6MjE7czoxNToicHJvZHVjdHMubGVuZ3RoIjtpOjIyO3M6MTU6InByb2R1Y3RzLndlaWdodCI7aToyMztzOjE3OiJwcm9kdWN0cy5xdWFudGl0eSI7aToyNDtzOjE2OiJwcm9kdWN0cy5taW5pbXVtIjtpOjI1O3M6MDoiIjtpOjI2O3M6MjM6InByb2R1Y3RzLnNoaXBwaW5nX3ByaWNlIjtpOjI3O3M6MDoiIjtpOjI4O3M6MDoiIjtpOjI5O3M6MjY6InByb2R1Y3RfZGVzY3JpcHRpb25zLmJsdXJiIjtpOjMwO3M6MzI6InByb2R1Y3RfZGVzY3JpcHRpb25zLmRlc2NyaXB0aW9uIjtpOjMxO3M6MDoiIjtpOjMyO3M6MDoiIjtpOjMzO3M6MzQ6InByb2R1Y3RfZGVzY3JpcHRpb25zLm1ldGFfa2V5d29yZHMiO2k6MzQ7czozNzoicHJvZHVjdF9kZXNjcmlwdGlvbnMubWV0YV9kZXNjcmlwdGlvbiI7aTozNTtzOjE2OiJwcm9kdWN0cy5rZXl3b3JkIjtpOjM2O3M6MDoiIjtpOjM3O3M6MDoiIjtpOjM4O3M6MDoiIjtpOjM5O3M6MDoiIjtpOjQwO3M6MDoiIjtpOjQxO3M6MTc6InByb2R1Y3RzLnN1YnRyYWN0IjtpOjQyO3M6MTI6ImltYWdlcy5pbWFnZSI7aTo0MztzOjA6IiI7aTo0NDtzOjA6IiI7aTo0NTtzOjA6IiI7aTo0NjtzOjA6IiI7aTo0NztzOjA6IiI7aTo0ODtzOjA6IiI7aTo0OTtzOjA6IiI7aTo1MDtzOjA6IiI7aTo1MTtzOjA6IiI7aTo1MjtzOjA6IiI7aTo1MztzOjA6IiI7aTo1NDtzOjE3OiJwcm9kdWN0cy5sb2NhdGlvbiI7fXM6OToic3BsaXRfY29sIjthOjI6e2k6MztzOjE6IiwiO2k6NDI7czoxOiIsIjt9czoxMDoidXBkYXRlX2NvbCI7YToxOntpOjE2O3M6Mjoib24iO31zOjE0OiJzZXJpYWxpemVkX21hcCI7czowOiIiO30=

![2017-08-04_18-28-34](https://user-images.githubusercontent.com/2631910/28967222-60ab9f08-7944-11e7-918f-af46417be1d5.png)

### See latest errors from log

2017-08-04 7:49:27  - warning:  AbanteCart core v.1.2.11 fopen() [<a  href='function.fopen'>function.fopen</a>]: Filename cannot be  empty in  /abc1211_m08d04/admin/controller/task/tool/import_process.php  on line <b>131
--
2017-08-04 7:49:27 - warning:  AbanteCart core  v.1.2.11 fgets() expects parameter 1 to be resource, boolean given in  /abc1211_m08d04/admin/controller/task/tool/import_process.php  on line 135
2017-08-04 7:49:27 - warning:  AbanteCart core  v.1.2.11 fclose() expects parameter 1 to be resource, boolean given in  /abc1211_m08d04/admin/controller/task/tool/import_process.php on line 149
2017-08-04 7:49:27 - Task_id: 5 : step_id: 55 - Failed. 0 rows processed with error. step details:array (  'step_id' => '55',  'task_id' => '5',  'sort_order' => '50',  'status' => '3',  'last_time_run' => '2017-08-04 07:49:27',  'last_result' => '0',  'max_execution_time' => '40',  'controller' => 'task/tool/import_process/processRows',  'settings' =>   array (    'start' => 980,    'stop' => 1000,  ),  'date_added' => '0000-00-00 00:00:00',  'date_modified' => '2017-08-04 07:49:27',)

**Comment by abolabo** [comment]
cannot to replicate. probably fixed by another commits
