### ISSUE TITLE
dev: import load map

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#929]
Issues if try to load map and no way to re-apply another one (if wrong map loaded)
![2017-08-07_17-16-57](https://user-images.githubusercontent.com/2631910/29022767-d6436cbc-7b94-11e7-9c1f-193e53462aad.png)

**Comment by abantecart** [comment]
Implemented differen solution that works faster now

**Comment by BasaraABC** [comment]
Please fix issue B: after map applied the Load Mapping button not work anymore. (You can not apply another map if first was incorrect)

**Comment by abantecart** [comment]
You can not apply map on confirmation page. Slow Javascript we we can not fix. Only solution to remove this feature as it needs to parse HMLT DOM  multiple times.
