### ISSUE TITLE
Missed option types

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#93]
1. We have missed option type FILE on product edit page (Options Tab). 
2. If possible please add DATE type (other carts have Date, Time, Date & Time types )
![options](https://cloud.githubusercontent.com/assets/2631910/6282526/4ff8cdf0-b909-11e4-9caa-22da55ec0c48.png)

**Comment by abolabo** [comment]
1. fixed.
2. goes to roadmap for 1.2.2

**Comment by BasaraABC** [comment]
Issue 1: Old bug came back again - for FILE option type missed important settings (min max size, upload folder, allowed extensions)
![file](https://cloud.githubusercontent.com/assets/2631910/6287664/c554196a-b945-11e4-87a2-c713a635faef.png)

------------------------------
Issue 2: not readable text (on Global Attribute page)
![file2](https://cloud.githubusercontent.com/assets/2631910/6287706/2288de18-b946-11e4-91dd-1fd16a4418e7.png)

**Comment by abantecart** [comment]
I suggest to put this off to 1.2.2

**Comment by abolabo** [comment]
removed GA type FILE for product option.
Added to roadmap.

**Comment by BasaraABC** [comment]
removing feature is not a good approach. Please read this http://forum.abantecart.com/index.php/topic,3318.0/topicseen.html

**Comment by abolabo** [comment]
fixed. need to retest GA+product options at all

**Comment by BasaraABC** [comment]
Testing started see few issues

Issue1: to replicate add default value (input and textarea)
---------------------------------------------------------
![options-issue1](https://cloud.githubusercontent.com/assets/2631910/6555884/0169d044-c69c-11e4-8e43-49f65832db88.png)

Issue2:  warnings in error log
---------------------------------------------------------
![options-issue2](https://cloud.githubusercontent.com/assets/2631910/6555885/016e2964-c69c-11e4-8823-5ccbab165880.png)

Issue3: too short space for option values
---------------------------------------------------------
![options-issue3](https://cloud.githubusercontent.com/assets/2631910/6555886/016e3cc4-c69c-11e4-8539-4c5d01e57068.png)


Issue4: known issue with empty checkbox
---------------------------------------------------------
![options-issue4](https://cloud.githubusercontent.com/assets/2631910/6555887/0171c8c6-c69c-11e4-9169-2ff3fef888d7.png)

**Comment by BasaraABC** [comment]
testing in progress:
Issue 5: cannot save price modifier for File type
-----------------------------------------
![options-issue5](https://cloud.githubusercontent.com/assets/2631910/6576036/af2e1e90-c766-11e4-9d86-0a1c3ed1578b.png)


issue 6 : incorrect view for additional fields for file type added manually (not Global attrib)
------------------------------------------
![options-issue6](https://cloud.githubusercontent.com/assets/2631910/6576037/af8e3564-c766-11e4-9375-7f3f5cb46e64.png)


issue 7 : hidden type is visible in customer order email
-----------------------------------------
![options-issue7](https://cloud.githubusercontent.com/assets/2631910/6576038/af8fabb0-c766-11e4-957e-58471be54a4a.png)

**Comment by abolabo** [comment]
fixed
