### ISSUE TITLE
dev:  import add seo key 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#934]
Please add seo url (seo key) column support to categories and manufacturers import wizard
![2017-08-14_14-23-12](https://user-images.githubusercontent.com/2631910/29263179-f104a4f4-8101-11e7-8acd-0104fa0cfa37.png)

**Comment by abantecart** [comment]
This is old. SEO URL is in there.

**Comment by BasaraABC** [comment]
No it is not. There is no SEO url support for **categories** or **manufacturers** scheme. 
Look at screenshot. Did you see Seo Url in dropdown?
