### ISSUE TITLE
connected store and install with url

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#938]
If store is connected to marketplace and one of extension is installed with url
then duplicated record shown in All Extensions page with 2 install buttons see screen
![2017-08-15_17-09-18](https://user-images.githubusercontent.com/2631910/29312076-26aa9ba4-81de-11e7-8308-33d5e9906579.png)

**Comment by BasaraABC** [comment]
Also in log 
`App Warning: AbanteCart core v.1.2.11 audit log directory is missing in abc1211_m08d15/core/engine/extensions.php on line 301`

**Comment by BasaraABC** [comment]
Issue is not fixed. I see duplicated extension it in fresh install.
![2017-08-29_18-12-25](https://user-images.githubusercontent.com/2631910/29818301-ebf038b2-8ce5-11e7-995d-35bf53348d5f.png)

**Comment by abolabo** [comment]
they are not duplicates!

**Comment by BasaraABC** [comment]
Can you please explain?

**Comment by abolabo** [comment]
see txt_id: "audit_log" vs "audit log"
