### ISSUE TITLE
Sagepay (default_sagepay) not work in Test mode

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#94]
default_sagepay not work in Test mode see screenshot
(Note: worked in Simulator mode)
Just FYI - read this https://our.umbraco.org/projects/website-utilities/ucommerce/ucommerce-support/24107-SagePay-The-Vendor-failed-to-provide-a-RedirectionURL possibly issue caused by "RedirectUrl parameter had not been supplied"

![default_sagepay](https://cloud.githubusercontent.com/assets/2631910/6282892/b33993ea-b90e-11e4-934b-f6108d179026.png)

**Comment by abantecart** [comment]
We have decided to pull Segpay off the release as Segpay API has changed. This will be on the road map for 1.2.2 or separate free extension.

**Comment by abolabo** [comment]
postponed after discussion.
