### ISSUE TITLE
dev: missing log

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#941]
For completed success task log shown but for fail tasks no log
![2017-08-16_19-10-03](https://user-images.githubusercontent.com/2631910/29365893-a4442a46-82c2-11e7-9e3c-8fb1b0b2c07e.png)

**Comment by abolabo** [comment]
link to log-file available only for new import process

**Comment by BasaraABC** [comment]
@abantecart say we need it for old import too.
related #946
