### ISSUE TITLE
dev: import wizard update

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#943]
If update products by unique name almost all fields updated but description and meta keywords are not. (maybe because they are translatable? I have 2 languages installed - initial import and update was run in same language!)

**Comment by abantecart** [comment]
This is related to incorrect (duplicate) columns in the feed. Please recheck

**Comment by BasaraABC** [comment]
Issue is not related to duplicate columns in feed. Please fix
Next fileds ignored in update by product name:
blurb, description, meta keywords, meta description

**Comment by abantecart** [comment]
Good catch. Fixed.
