### ISSUE TITLE
Product- Options- Add Options + missing

### ISSUE THREAD

**Issue by FCWC** [abantecart/abantecart-src#944]
In the 2.1.11 
In products - options . the add (+) button for multiple options is missing
![option-global](https://user-images.githubusercontent.com/31253087/29578730-f61bb38a-8735-11e7-8901-5673c3fdc48d.jpg)

This is in both Global and individual Options

**Comment by BasaraABC** [comment]
Hello. For parent/child attributes please use selectbox. 
You have checkbox type: checkbox is not a multivalue type
