### ISSUE TITLE
dev: import wizard image path

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#945]
Please add support for importing images with path on server.
In test I try full path and path related to /resources/image/ directory (like old import works)
Both cases do not import image with next errors
`Error: Image 18/71/e.jpg does not exists`
`Error: Image /mnt/drive1/home/fullpath/htdocs/abc1211_m08d25/resources/image/18/71/e.jpg does not exists `

**Comment by abantecart** [comment]
Done

**Comment by BasaraABC** [comment]
work with full server path. Thank you.
