### ISSUE TITLE
dev: import wizard counter

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#949]
Counter before and after is not same
![2017-08-29_12-49-13](https://user-images.githubusercontent.com/2631910/29806248-95712d2a-8cb8-11e7-881c-9114edd4c08b.png)

**Comment by BasaraABC** [comment]
Issue come back again. Now **Initial** counter is incorrect
![2017-09-01_13-51-18](https://user-images.githubusercontent.com/2631910/29958407-e5291bbe-8f1c-11e7-8bd4-08fd7dbabbd1.png)

**Comment by BasaraABC** [comment]
You can replicate with this file
[products-with-options-comma.csv.zip](https://github.com/abantecart/abantecart-src/files/1269626/products-with-options-comma.csv.zip)

**Comment by abantecart** [comment]
???? Why

**Comment by BasaraABC** [comment]
It is strange issue if you try to import same file second time - counter will be same (16 initial and 16 proceed). Only on fresh install and first import it is incorrect

**Comment by BasaraABC** [comment]
Issue is not fixed. See screenshot from the fresh installed 1.2.11
![2017-09-04_14-30-17](https://user-images.githubusercontent.com/2631910/30016147-112260c8-917e-11e7-85c4-00afea805fd7.png)

**Comment by BasaraABC** [comment]
Incorrect initial counter for the manufacturers
Try this file [manufacturers.csv.zip](https://github.com/abantecart/abantecart-src/files/1295482/manufacturers.csv.zip)
![2017-09-12_16-43-53](https://user-images.githubusercontent.com/2631910/30319392-ef7cd964-97d9-11e7-82f6-b1bfafc30929.png)
