### ISSUE TITLE
small isssues with banners

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#95]
1. If use graphic banner and html banner (simple div with width height) they are not inline see screenshot
2. No way to use .gif banner with Graphic banner type (issue: AbanteCart resource library kill animation)

http://dev06.xxxxxx.net/abc121_m02d20/

See screenshot for issue 1
![banners](https://cloud.githubusercontent.com/assets/2631910/6285418/314d9a6e-b92e-11e4-9d28-e66dbd0be7d5.png)

**Comment by abantecart** [comment]
This is not an issue as 2 banners have different inner HTML structure. If you need to keep listed banner in balanced, need to put them with the same HTML code.
