### ISSUE TITLE
world pay payment

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#952]
Not work in test mode. 
request sandbox http://www.worldpay.com/us/developers/developer-resources/developer-sandbox-signup
![2017-08-31_15-19-06](https://user-images.githubusercontent.com/2631910/29914053-52b18674-8e61-11e7-8daa-60319af527e0.png)

**Comment by abantecart** [comment]
I propose to discontinue WorldPay.

**Comment by abolabo** [comment]
removed
