### ISSUE TITLE
dev: import wizard - option's value weight class

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#953]
Missing weight type 
![2017-08-31_19-11-18](https://user-images.githubusercontent.com/2631910/29922617-8cf31b6c-8e80-11e7-94f0-1d02a8644aca.png)

**Comment by abantecart** [comment]
This is because of weight id that you picked in the main product. Currently this is linked to main product

**Comment by abantecart** [comment]
Fixed
