### ISSUE TITLE
dev: import wizard - rounded weight value

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#957]
3 digits rounded to 2 digits weight
![2017-09-01_14-35-00](https://user-images.githubusercontent.com/2631910/29959729-e86a8c80-8f22-11e7-8a7b-4368ba3f9173.png)

**Comment by abantecart** [comment]
Yes rounded to 2 decimal. This is not done in the import. 

  **`weight` decimal(5,2) NOT NULL DEFAULT '0.00',**
