### ISSUE TITLE
dynamic data in backup

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#961]
Please do not include **thumbnails** into backup. Thumbnails are dynamic data created on the fly from resources.
Also should be included /download/**temp** folder?
![2017-09-04_15-17-57](https://user-images.githubusercontent.com/2631910/30017720-75d5a100-9184-11e7-90c5-8026aae532a4.png)

**Comment by BasaraABC** [comment]
One more: all temp import/export files also included in backup /admin/system/data
Should we leave it?
![2017-09-04_15-23-09](https://user-images.githubusercontent.com/2631910/30017918-21b6e2fe-9185-11e7-89b0-8e7469c18b67.png)

**Comment by abantecart** [comment]
I think we should leave it.

**Comment by BasaraABC** [comment]
I did not see any commits. Whats is 'ready to QA'?

**Comment by abantecart** [comment]
There is no fix. That is why I set to QA to grab your attention. You can close

**Comment by BasaraABC** [comment]
What about initial request, why we backup dynamic thumbnails?

**Comment by abolabo** [comment]
thumbnails folder has been added to exclusions
