### ISSUE TITLE
dev: incorrect availability

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#962]
Incorrect out of stock status shown for the product with quantity 0 and enabled track stock
![2017-09-04_17-54-13](https://user-images.githubusercontent.com/2631910/30023766-ff4cdcc6-919a-11e7-9663-776e1181f6bf.png)

Note: see if this related to #842 , #851

**Comment by abantecart** [comment]
Why do we need discussion here?

**Comment by BasaraABC** [comment]
@abolabo say this is already discussed with you
