### ISSUE TITLE
dev: test_api.php API js error

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#963]
js error in the browser console after click on buttons
Checked in firefox 55
<img width="604" alt="2017-09-04_18-59-29" src="https://user-images.githubusercontent.com/2631910/30025587-6498704c-91a3-11e7-92d8-35bcc91789a8.png">

**Comment by abantecart** [comment]
I get no JavaScript error. Did you put correct store URL into the script?
