### ISSUE TITLE
Install with HTTPS and CDN Cloudflare service

### ISSUE THREAD

**Issue by BetaStacks** [abantecart/abantecart-src#966]
I had to disable all cloud flare ssl features in order to install. I attempted to simply "load unsafe scripts" but that resulted in the page not moving past the license and agreements when I clicked continue.

**Comment by BasaraABC** [comment]
Did you set up and configure SSL certificate on your server?
What is your AbanteCart version?

**Comment by BetaStacks** [comment]
I’m using Cloudflare’s Flexible SSL and should be on the latest version as I just downloaded it from the official site.

**Comment by abantecart** [comment]
Let me clarify. The issue is, you can not install AbanteCart with enabled SSL. Is this correct?

**Comment by BetaStacks** [comment]
Yes. If I use http:// instead of https:// then it works. 

Once installed, if I use https:// it breaks the published site. See https://www.brandoncorlett.com/shop/ <https://www.brandoncorlett.com/shop/>

**Comment by abantecart** [comment]
Thank you for pointing out this issue. We will investigate. I believe it was not common before to install AbanteCart with SSL on. Most of the time SSL enabled after the app is installed.

**Comment by BetaStacks** [comment]
That makes sense. I am adding the shop to an already existing site that has the SSL. I chose AbanteCart because of the Embed and API solutions it offers.

**Comment by BasaraABC** [comment]
Issue if try to install via HTTPS
![2017-09-07_12-57-25](https://user-images.githubusercontent.com/2631910/30148131-41e29b06-93cc-11e7-925d-25c4d32b706e.png)

**Comment by BasaraABC** [comment]
Issue not fixed, same problems if run install in HTTPS
Notice: Constant HTTPS already defined in /abantecart/htdocs/install/init.php on line 33

**Comment by xystores** [comment]
I'm also facing the same issue. The admin login of Abntecart doesn't allow me to move forward using the correct user id and password. However, if you disable HTTPS from Cloudflare, I'm able to access admin login page and the site too.

I' new to all this, and this is first time, I'm creating a site.

Could you please help?

**Comment by BasaraABC** [comment]
Hello @xystores , cloudflare is know free service as trouble maker. To use it safely enable its CDN features only for the images and css files.
