### ISSUE TITLE
Embed code not working - fresh install

### ISSUE THREAD

**Issue by BetaStacks** [abantecart/abantecart-src#968]
I just did a fresh install with a new database and domain name. http://shop-brandon-corlett.tk 
I cant seem to get the embed code to work with the new or demo products. The widget generator shows a blank spot where the image should be and the code doesn't change with the toggles. 

However, if i use the the main domain on my hostgator account it works. Any addon domain or sub domain does not work. 

![screenshot](http://www.shop-brandon-corlett.tk/Screen%20Shot%202017-09-05%20at%207.48.13%20PM.png)

**Comment by BasaraABC** [comment]
Check what you have in the AbanteCart admin > System > Settings > Store Details in the store url setting

**Comment by abantecart** [comment]
Is this still an issue?

**Comment by BasaraABC** [comment]
Working on my side. Till more details added issue closed

**Comment by BasaraABC** [comment]
To replicate issue visit admin via HTTPS and make sure store url is HTTP.
When Embed code modal opened the browser block it because of mixed content
![2017-09-08_16-54-18](https://user-images.githubusercontent.com/2631910/30206578-b24e46b6-94b6-11e7-85c2-ae9fcfc9d70f.png)

**Comment by BasaraABC** [comment]
Can you please apply same fix in other embed areas (brands, categories)?
![2017-09-18_17-50-50](https://user-images.githubusercontent.com/2631910/30538880-1ce78074-9c9a-11e7-84b8-c25e281db9d3.png)
