### ISSUE TITLE
negative quanity shown

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#969]
If track stock Disabled for the product in my opinion we dont need to show quantity
![2017-09-06_15-26-06](https://user-images.githubusercontent.com/2631910/30101995-6dcaaa92-9318-11e7-9243-ae9213557e72.png)

**Comment by abantecart** [comment]
There is no discussion here. Need to hide QTY if there is no stock and allow to purchase.

**Comment by abolabo** [comment]
try to replicate after commit related to #851. Probably fixed
