### ISSUE TITLE
SF logo not retinized

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#97]
Please retinize SF logo
![retin](https://cloud.githubusercontent.com/assets/2631910/6287928/d7457914-b947-11e4-9dbc-da9564d17a5b.png)

**Comment by abantecart** [comment]
I think this needs to be as a part of template edit section to allow saving 2 files with the same name.
Need to discuss. 
Please keep it in the road map for 1.2.2.

**Comment by abolabo** [comment]
added setting for retina + changes into .htaccess
