### ISSUE TITLE
dev: radio / selectbox option type

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#983]
Product is out of stock (radio and selectbox option type) if one of the value is negative (track stock OFF)
To replicate issue please add 3 option's values with same params as in screenshot
http: //dev06.******.net/abc1211_m09d11/index.php?rt=product/product&product_id=111
![2017-09-11_16-34-03](https://user-images.githubusercontent.com/2631910/30268274-6cf3fe48-970f-11e7-83f0-365edf8d6618.png)

**Comment by abolabo** [comment]
not field type related. Bug is in negative qnt and calculation of total stock
