### ISSUE TITLE
Bad headings in HTML

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#985]
I have found out that the html headings are completely messed up in the source. 

The h1 should be for page title. Then h2, I would personally set for the categories each in category menu.
H3 submenu maybe for the bottom blocks or footer menu.

The random order of headings also bad. It should be in A-Z order, h1, h2..h6. 

Also found some absolutely unneeded stuffs (bad for seo):
Hidden headings are not really good:

<h4 class="hidden">&nbsp;</h4>

I dont know whats its used for, but in my case it seemed to be completely unused.

<div class="sep"></div>

I also found a page about some useful advices 
https://www.hobo-web.co.uk/headers/

**Comment by BasaraABC** [comment]
Hi. For what page you are refer to? 
For example for the product pages
H1 tag is only one and set for product name (same as page title)
H2 is set for blocks titles. You need to set more h2 or h3, h4... in the product description if it is not very short

**Comment by kolynet** [comment]
http://www.abantecart.com/shopping-cart-demo

Home page. I have the same heading structure as on the demo.

H1 is not single, and the order of headings are not really correct, also the hidden headings.

**Comment by kolynet** [comment]
For some reason it removed my pasted code example from source:

`<h4 class="hidden">&nbsp;</h4>`

**Comment by BasaraABC** [comment]
Please move discussion to official forum
