### ISSUE TITLE
dev: stripe missing definition notice

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#987]
![2017-09-14_20-05-53](https://user-images.githubusercontent.com/2631910/30431274-45b0d1d2-9988-11e7-8e73-c5a6566648a4.png)

**Comment by abolabo** [comment]
need more details.
What page?

**Comment by BasaraABC** [comment]
was on this page index.php?rt=extension/default_stripe_settings&s=admin 
but for now can't replicate. I think it is fixed with latest changes
