### ISSUE TITLE
dev: file warning

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#990]
From time to time warning appear in the log
warning: AbanteCart core v.1.2.11 file_get_contents(htdocs/system/cache/settings/29ed0cf11e6bcf385f84dc08ddbe7df4.php): failed to open stream: No such file or directory in <b>/htdocs/core/cache/file.php</b> on line <b>130</b>

**Comment by abolabo** [comment]
what OS? htdocs usually under /var directory 
need more details

**Comment by BasaraABC** [comment]
os x localhost. 
php 7.1.8
It is rare issue hard to replicate. I will update if catch again
