### ISSUE TITLE
dev:  Unknown error - form token issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#995]
To replicate issue first submit _decline_ card number ‎4000000000000002
then try _approve_ cc ‎4242 ‎4242 ‎4242 ‎4242 
![2017-09-15_21-11-39](https://user-images.githubusercontent.com/2631910/30486465-d991251e-9a5a-11e7-8bf2-c3e7b429fee8.png)

**Comment by abolabo** [comment]
was related to csrf

**Comment by BasaraABC** [comment]
Please fix token issue for **all CC payments.** 
For example Autorize.net also have it
![2017-09-18_14-13-30](https://user-images.githubusercontent.com/2631910/30531953-b1c69794-9c7b-11e7-94ff-636e70884de2.png)

**Comment by BasaraABC** [comment]
Realex is not fixed.
![2017-09-18_18-36-16](https://user-images.githubusercontent.com/2631910/30540232-74d091ee-9ca0-11e7-828e-0ff4618895a9.png)

**Comment by BasaraABC** [comment]
realex, autorize fixed.
pp_pro and cashflows can't check

**Comment by BasaraABC** [comment]
fixed in pp pro, waiting for api from cashflows support.  Still no reply
