### ISSUE TITLE
dev: import wizard duplicated products

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#999]
Some products imported twice. Please use attached file
Note: tested on php 5.4.4
[products-with-options-comma.csv.zip](https://github.com/abantecart/abantecart-src/files/1310469/products-with-options-comma.csv.zip)
![2017-09-18_18-16-30](https://user-images.githubusercontent.com/2631910/30539670-c9aa2bba-9c9d-11e7-9554-db220e435ec0.png)

**Comment by abolabo** [comment]
Probably cause is in restarts of steps from js. 
Tried to replicate but unsuccessful. Looks like you have some network glitches.
Anyway we need more details

**Comment by abantecart** [comment]
This can be caused by duplicate run of the same step.

**Comment by BasaraABC** [comment]
I think it was browser or server glitch. Reinstalled cart today on same server and run import in same browser without duplicates. Not sure can we improve this. 
Closed for now
